Adds Smithing
shiptest-ss13/Shiptest pull request #1013
Opened 2022-04-30 03:27 UTC by Vexylius

## About The Pull Request

Forge setup
![image](https://user-images.githubusercontent.com/22380218/166088736-9a39c333-7342-4655-b088-2483667c8e9d.png)

## Why It's Good For The Game

Shiptest goes for some primitive tech and what's morre primivtive than a sord or whatever

## Changelog
:cl:
add: Added Smithing
/:cl:

2022-04-30 03:31 UTC, triplezeta commented
sprites :(

2022-04-30 03:35 UTC, Vexylius commented
it's a draft, gonna change the sprites later or something.
If anyone wants to help with those sprites my DMs are open

2022-04-30 10:10 UTC, Fikou requested changes
first look, i really am not a fan of reagent weapons/armor but ill let someone else decide on that

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/forging_items.dm
> +		return
i'd rather we handle this as a variable than use locate 20 different times.

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/forged_weapons.dm
> +/obj/item/forging/reagent_weapon/staff/attack(mob/living/M, mob/living/user, params)
newline here

2022-04-30 10:10 UTC, Fikou commented on code/game/objects/items/stacks/rods.dm
> +		return
this should be handled on the tongs' afterattack

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/anvil.dm
> +	var/obj/item/forging/incomplete/search_incomplete_src = locate(/obj/item/forging/incomplete) in contents
again, variable, dont look through contents

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/anvil.dm
> +	. = ..()
dont copy parents proc without changing anything

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/anvil.dm
> +			I.icon_state = "tong_full"
this should be handled by update_icon_state on both objects

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/anvil.dm
> +			search_incomplete_src.times_hit -= 3
use defines

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/anvil.dm
> +			to_chat(user, "<span class='notice'>good hit!</span>") //ReplaceWithBalloonAlertLater
should be capitalized if its not a balloon alert

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/forged_weapons.dm
> +			to_chat(user, "<span class='notice'>partially repaired!</span>") //ReplaceWithBalloonAlertLater
same here

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/forging_items.dm
> +	if(istype(attacking_item, /obj/item/forging/coil))
use early returns here

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/forged_weapons.dm
> +	if(istype(attacking_item, /obj/item/forging/hammer))
early return here

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/forge.dm
> +	if(user_smithing_skill >= SKILL_LEVEL_APPRENTICE)
what are these even. why does touching the forge fully upgrade its stuff without you having to do anything

2022-04-30 10:10 UTC, Fikou commented on code/modules/forging/forge.dm
> +		while(forge_temperature < 91)
these should be defines, not magic numbers

2022-04-30 10:11 UTC, Fikou commented on code/modules/forging/forged_weapons.dm
> +			to_chat(user, "<span class='notice'>partially repaired!</span>") //ReplaceWithBalloonAlertLater
and throughout the rest

2022-04-30 10:13 UTC, Fikou commented
Also please credit the original creators as I think this is a port?

2022-04-30 15:17 UTC, triplezeta commented on code/modules/forging/forged_wearables.dm
> +/obj/item/clothing/neck/kink_collar/reagent_clothing
🤨

2022-05-01 01:31 UTC, Apogee-dev commented
ok i strongly suggest looking at vgstation's blacksmithing-related sprites to replace some of these codersprites. there's an assortment of blacksmithing-related equipment as well as a number of smithed weapons you could steal sprites for

2022-05-01 01:43 UTC, ZephyrTFA commented
It's not stealing if you ask and/or credit them correctly

2022-05-25 21:10 UTC, SweetBlueSylveon commented
This would actually be a pretty cool thing for the icecropolis I think.

2022-06-10 01:55 UTC, SweetBlueSylveon commented
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 14 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

-NOOOOOOOOO

2022-06-13 02:19 UTC, Vexylius commented
I honestly forgot about that, damn

2022-07-13 01:20 UTC, closed without merging