Adds the Scav-class Drifter
shiptest-ss13/Shiptest pull request #1050
Opened 2022-05-09 09:01 UTC by someguyjust

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-05-09 09:01 UTC, someguyjust commented
fuck forgot desc

2022-05-09 09:16 UTC, someguyjust commented
any one knows why this is failing?

2022-05-09 09:28 UTC, Fikou requested changes
this needs to use the TGM map format

2022-05-09 12:52 UTC, someguyjust commented
Yes I know the bridge has no wide band

2022-05-09 17:13 UTC, ZephyrTFA commented
Try to avoid having thin diagonal walls or windows

2022-05-09 17:13 UTC, ZephyrTFA commented
![image](https://user-images.githubusercontent.com/12817816/167462329-d321842e-5bc1-4bc5-be3f-8021c9b0a868.png)

2022-05-09 17:14 UTC, someguyjust commented
Literally can't without losing it's shape and keep room

2022-05-09 17:17 UTC, PiperDoots commented
> Literally can't without losing it's shape and keep room

try adding one one in the middle and then another next to it
![image](https://user-images.githubusercontent.com/90694223/167462748-1b5fdab6-8899-4ffb-b1a9-9018597fcf18.png)

2022-05-09 17:19 UTC, someguyjust commented
Then it double on thickness and looks more wonky

2022-05-09 17:26 UTC, someguyjust commented
Guess I can axe that extra seat

2022-05-10 11:24 UTC, someguyjust commented
i have no clue why its failing it seems to work and all the pipes are lined up

2022-05-10 17:12 UTC, Fikou approved these changes

2022-05-10 23:26 UTC, Apogee-dev commented
Config file needs prefix and namelists fields. You also don't have any firelocks on the bridge (though honestly, I'd suggest placing firelocks on all of the dividing windows, considering how easy they are to break)

2022-05-10 23:28 UTC, Apogee-dev requested changes

2022-05-10 23:28 UTC, Apogee-dev commented on _maps/configs/scav.json
> +	"map_short_name": "Scav-class",
"prefix": ISV,
"namelists": insert your namelists of choice here, i'd suggest GENERAL and SPACE at a minimum

2022-05-10 23:29 UTC, someguyjust commented
and i had just closed DMM pain

2022-05-10 23:41 UTC, Apogee-dev commented
You also need to replace all your space tiles with terrain passthrough tiles (and the appropriate area). As a side note, unless they're placed over a floor tile with a ship area, the ship's exterior cameras will simply get deleted.

2022-05-10 23:42 UTC, someguyjust commented
camreas have been removed because they didn't seem to work any ways

2022-05-10 23:43 UTC, someguyjust commented
also where the hell is the file containing ship names, it dosen't seem to exist?

2022-05-10 23:44 UTC, Apogee-dev commented
> also where the hell is the file containing ship names, it dosen't seem to exist?

strings/ship_names.json

2022-05-10 23:45 UTC, someguyjust commented
ah i was on the wrong branch, couldn't find them there lol

2022-05-11 00:22 UTC, Apogee-dev approved these changes

2022-05-13 21:13 UTC, TerraPlanet commented
I very much enjoy this ship. I played a round with it. And looting ruins was very quick and efficient.

2022-05-25 20:58 UTC, SweetBlueSylveon commented
I feel like this ship and the Masinyane serve very similar functions. What makes this one special?

2022-05-26 05:41 UTC, someguyjust commented
> I feel like this ship and the Masinyane serve very similar functions. What makes this one special?

well it is more scavenger focused, and is just more thematic to scavenging, it has room to RP and room for a bit of medical if you know what you are doing, it also has cargo space for what ever you want, and is quite open, and comfy

2022-05-27 11:47 UTC, merged