ISV Riggs
shiptest-ss13/Shiptest pull request #106
Opened 2021-07-30 10:29 UTC by Apogee-dev

## About The Pull Request

Adds a new ship, the Riggs-class Sloop, based on the Rebel Rigger from FTL. 
![rigger](https://user-images.githubusercontent.com/60533805/127640081-cd1c4faa-5484-401c-bd34-c80540fc0b93.png)

Features include:
![riggercargo](https://user-images.githubusercontent.com/60533805/127639663-a65222ff-03f0-48cd-a998-a5b2330b6723.png)
a mech bay, conveniently located at the front of the ship,
![riggercentral](https://user-images.githubusercontent.com/60533805/127639694-7299653c-7fc5-48d2-95d6-0ead06d78f23.png)
 a robotics workshop with a posibrain,
![riggermedsec](https://user-images.githubusercontent.com/60533805/127639740-1202e239-63f5-4330-add4-73aabfe0dfcb.png)
and a dedicated (if empty) armory space.

Notable shortcomings include a poorly-stocked medbay and complete lack of cargo facilities outside of the ore redemption machine. Better get salvaging!

## Why It's Good For The Game

we test ships here

## Changelog
:cl:
add: Added a new ship, the Riggs-class Sloop.
/:cl:

2021-07-31 00:36 UTC, triplezeta commented
looks really good, cant wait to test this ship!

2021-07-31 01:13 UTC, Apogee-dev commented
goofed on the map format, whoops

2021-07-31 23:54 UTC, triplezeta requested changes
![image](https://user-images.githubusercontent.com/51932018/127754951-cee5cd92-fcbc-4784-be97-9102090be275.png)


![image](https://user-images.githubusercontent.com/51932018/127754956-2465cfcf-6363-4453-bfff-815906afa690.png)

2021-08-04 21:53 UTC, MarkSuckerberg commented on _maps/shuttles/shiptest/rigger.dmm
> +	name = "navigation beacon
```suggestion
	name = "navigation beacon"
```

2021-08-05 20:39 UTC, MarkSuckerberg commented on _maps/shuttles/shiptest/rigger.dmm
> +	location = "med"
```suggestion
	codes_txt = "patrol;next_patrol=canteen";
	location = "med"
```

2021-08-05 21:46 UTC, merged