Removes felinids, wraps them into humans
shiptest-ss13/Shiptest pull request #1062
Opened 2022-05-13 03:16 UTC by MarkSuckerberg

## About The Pull Request
***and wraps them into humans. Existing felinids savefiles will be turned into humans with cat ears and a cat tail.**
![image](https://user-images.githubusercontent.com/29362068/168202065-b60d360e-a5b3-4015-baf8-a8d4d07e563a.png)

note- doesn't remove purrbation. **you are not safe.**

## Why It's Good For The Game
Let's face it- felinids were just humans with minor tweaks (that were even so minor as to be disabled by some people resulting in literally just humans). This wraps them into being modified humans, which makes a lot more sense than having them be their own species with all the baggage that entails lore and otherwise. Also allows us to add more variations of tails and whatnot without having to worry about the species being explicitly feline!

## Changelog
:cl:
del: Felinid mutation toxin
del: Weird flavouring of tackles were removed. (E.g. pounce vs. tackle)
del: Felinids
add: Humans can now select ears and tails
fix: All species are now able to wag tails if they get them.
/:cl:

2022-05-26 13:39 UTC, Fikou requested changes

2022-05-26 13:39 UTC, Fikou commented on code/modules/admin/verbs/purrbation.dm
> +	kitty_tail.Insert(H, TRUE, FALSE)
use named args if possible

2022-05-26 13:39 UTC, Fikou commented on code/modules/admin/verbs/purrbation.dm
> +		playsound(get_turf(H), 'sound/effects/meow1.ogg', 50, TRUE, -1)
get turf is not needed here

2022-05-26 13:39 UTC, Fikou commented on code/modules/admin/verbs/purrbation.dm
> +	for(var/M in GLOB.mob_list)
use descript variable names for all these please
also i think we have better global lists for that, like living mobs, or players.

2022-05-26 14:33 UTC, MarkSuckerberg commented on code/modules/admin/verbs/purrbation.dm
> +	for(var/M in GLOB.mob_list)
oh yeah, I just copied it wholesale from the old felinid file, I can get them fixed up when I'm home

2022-05-26 15:35 UTC, Fikou commented on code/modules/admin/verbs/purrbation.dm
> +		playsound(get_turf(H), 'sound/effects/meow1.ogg', 50, TRUE, -1)
also were sure this isnt supposed to be like, SEND_SOUND?

2022-06-06 04:01 UTC, MarkSuckerberg commented
Everything resolved, Purrbation optimisations at 500%

2022-07-03 02:13 UTC, triplezeta commented
oh no you dont

2022-07-05 15:46 UTC, MarkSuckerberg commented
Merge conflicts fixed

2022-07-06 08:24 UTC, Fikou approved these changes

2022-07-06 08:24 UTC, merged