prototype of baytiles
shiptest-ss13/Shiptest pull request #108
Opened 2021-07-31 10:01 UTC by retlaw34

## About The Pull Request

a visual overhaul prototype, the walls and airlocks are so shittily coded and may be taken out. @swifterjack go bug moth about their walls.

the baytiles are the main focus,  they look nice and thats about it
## Why It's Good For The Game
eyecandy

## Changelog
:cl:
add: baytiles
add: baywalls
add: baylocks
add: baystation
soundadd: baysounds
del: swifterjackie
/:cl:

2021-07-31 10:02 UTC, retlaw34 commented
already?

2021-07-31 10:03 UTC, triplezeta commented
i wonder why

2021-07-31 10:11 UTC, swifterjack commented
rude.

2021-07-31 10:12 UTC, swifterjack commented
walls suck give me the cool tiles remove the toblerones

2021-07-31 10:15 UTC, retlaw34 commented
walls will probably not be in the final version, just in so they make the tiles look good

2021-07-31 10:18 UTC, triplezeta commented
walls are based swifter stfu

2021-08-10 00:16 UTC, retlaw34 commented
It is time
i wont touch the new ships

2021-08-29 09:14 UTC, retlaw34 commented
@triplezeta if this gets another conflict its going back to brazil

2021-08-29 14:16 UTC, ZephyrTFA requested changes

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define COLOR_MONOTILE        	"#545c68"
```suggestion
#define COLOR_MONOTILE "#545c68"
```

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define COLOR_TILE_GRAY			"#4c535b"
```suggestion
#define COLOR_TILE_GRAY "#4c535b"
```

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define COLOR_TILE_DARK_GRAY	"#404040"
```suggestion
#define COLOR_TILE_DARK_GRAY "#404040"
```

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define COLOR_WARNING			"#D2D53D"
```suggestion
#define COLOR_WARNING "#D2D53D"
```

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define WOOD_COLOR_YELLOW      "#e3994e"
```suggestion
#define WOOD_COLOR_YELLOW "#e3994e"
```

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define WOOD_COLOR_GENERIC     "#d5a66e"
```suggestion
#define WOOD_COLOR_GENERIC "#d5a66e"
```

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define WOOD_COLOR_RICH        "#792f27"
```suggestion
#define WOOD_COLOR_RICH "#792f27"
```

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define WOOD_COLOR_PALE        "#d2bc9d"
```suggestion
#define WOOD_COLOR_PALE "#d2bc9d"
```

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define WOOD_COLOR_PALE2       "#e6d2ba"
```suggestion
#define WOOD_COLOR_PALE2 "#e6d2ba"
```

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define WOOD_COLOR_BLACK       "#332521"
```suggestion
#define WOOD_COLOR_BLACK "#332521"
```

2021-08-29 14:16 UTC, ZephyrTFA commented on code/__DEFINES/colors.dm
> +#define WOOD_COLOR_CHOCOLATE   "#543c30"
```suggestion
#define WOOD_COLOR_CHOCOLATE "#543c30"
```

2021-08-29 17:08 UTC, ZephyrTFA commented
Atmospherics please stop breaking my CI

2021-08-30 04:53 UTC, shiptest-server commented
#### Test Merge Deployed

##### Server Instance
shiptest

##### Revision
Origin: aabc6f1b144d0c36cf9f9f5d49313c6586ec6706
Pull Request: abd9fd0b092352a4f3b811a7cdc50c3ae98fb2dd
Server: 4a612b6abc77d3aaae270b65dc4c94667e4d6be2

2021-08-30 05:34 UTC, shiptest-server commented
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 293bad3e54aa3f26644d5d871baee9eda36057ca
Pull Request: abd9fd0b092352a4f3b811a7cdc50c3ae98fb2dd
Server: 2c17e761a3dbe846412b0eb5224178d8c7dfc1e4

2021-08-31 21:39 UTC, shiptest-server commented
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: d79659920aec58007df63d3e9b96cb0fe1a16353
Pull Request: abd9fd0b092352a4f3b811a7cdc50c3ae98fb2dd
Server: 72d94bef2620899bd315f660ccb547df14ffc328

2021-08-31 22:40 UTC, shiptest-server commented
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: dd854e7386a7a9a664d6357aab6213b032e1817b
Pull Request: abd9fd0b092352a4f3b811a7cdc50c3ae98fb2dd
Server: d097fa6e32a13458e756307a43c1764f99b243bc

2021-08-31 23:12 UTC, shiptest-server commented
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 4d98cdcea7b4591b94a06237309039f4980217fa
Pull Request: abd9fd0b092352a4f3b811a7cdc50c3ae98fb2dd
Server: 9a29cfa82da92d64f18a8f8bcd69d3ea934be1ac

2021-08-31 23:44 UTC, shiptest-server commented
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: f789e74004b3acb82690d77398848b240a153b6f
Pull Request: abd9fd0b092352a4f3b811a7cdc50c3ae98fb2dd
Server: fec71ade6e716fb63d267abca95b86e22f5eb182

2021-09-01 13:11 UTC, shiptest-server commented
#### Test Merge Removed

2021-09-02 04:59 UTC, shiptest-server commented
#### Test Merge Deployed

##### Server Instance
shiptest

##### Revision
Origin: bf2a3d7daffd8042d3adbe075ec803cd3abd4e03
Pull Request: abd9fd0b092352a4f3b811a7cdc50c3ae98fb2dd
Server: ca0ff8b9f76846976a9d8d2ec5e18cf60ecd28be

2021-09-03 15:42 UTC, MemedHams commented
Okay so- it would be a good idea to make these a separate entity from old walls, and retain them in code, but change construction pathing to the new tiles and walls. Otherwise, you're looking and redoing *every structure, ruin, and ship in the code* which is frankly a reality too terrible to even conceive.

Over time we can shift everything to newtiles, and then kill oldtiles afterwards, but for now I think backwards compat is the way to go.

2021-09-04 03:46 UTC, swifterjack commented
btw, this breaks the syndie S 3x3 decal for some odd reason

2021-09-04 03:47 UTC, retlaw34 commented
this breaks almost every single decal, but i think i can fix some things

2021-09-04 14:49 UTC, shiptest-server commented
#### Test Merge Removed

2021-09-04 14:54 UTC, shiptest-server commented
#### Test Merge Deployed

##### Server Instance
shiptest

##### Revision
Origin: 033ea7d0a6e5ade2feced249d03f7bfcd3eac439
Pull Request: 7361c3ac159212e93184addae2f7f93d77a274a7
Server: 7c123be6a9d9ffcf192aa21466691c922a728b54

2021-09-04 23:21 UTC, shiptest-server commented
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 9693b436ac8eb8d68349b284df72bb252209581f
Pull Request: 7361c3ac159212e93184addae2f7f93d77a274a7
Server: 651bb7bd5250da841cf57899f6ff939ae8b47202

2021-09-07 03:17 UTC, retlaw34 commented
🇧🇷

2021-09-07 05:05 UTC, ZephyrTFA commented
You are failing integration tests.
Invalid components are being attached to parent objects.
`REASON #6: [03:48:33] Runtime in unsorted.dm,1056: Incompatible /datum/component/decal assigned to a /turf/open/floor/plasteel/mono/white`

2021-09-07 05:07 UTC, retlaw34 commented
uhhhhhhhhhh @MarkSuckerberg help

2021-09-07 05:13 UTC, MarkSuckerberg commented
pain, I will look at it tomorrow

2021-09-08 02:04 UTC, shiptest-server commented
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: ca83a63d9154e7bd47271dd9f5ce5d44eb19d7af
Pull Request: b064af1f906d3d5a7928bd1da86beba2cb2a7da3
Server: b9679cc28f47ef4054511559ac3e5f35dd3100bb

2021-09-08 02:36 UTC, shiptest-server commented
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: ca83a63d9154e7bd47271dd9f5ce5d44eb19d7af
Pull Request: b064af1f906d3d5a7928bd1da86beba2cb2a7da3
Server: 52f18b307da9ed9bafb2f173c5db9806fde13a70

2021-09-10 18:37 UTC, ZephyrTFA commented
Check your turf decals. Something has a null icon. 
That is why you are getting this runtime. 
```[03:12:44] Runtime in unsorted.dm,1056: Incompatible /datum/component/decal assigned to a /turf/open/floor/plasteel/mono/white! args: [null,"siding_line",4,0,null,null,null,255]```

2021-09-13 21:43 UTC, ZephyrTFA commented
This is good to merge, you just need to fix your null icons so that integration tests succeed

2021-09-13 21:45 UTC, MarkSuckerberg commented
Fixed that, it's just atmos runtimes now

2021-09-13 21:48 UTC, ZephyrTFA commented
Gonna cry

2021-09-13 21:52 UTC, MarkSuckerberg commented
atmos runtimes my beloathed 😭😭😭

2021-09-19 02:20 UTC, MarkSuckerberg commented
LGTM, YOLO, LMAO, etcetera

2021-09-19 02:20 UTC, merged

2021-09-19 02:20 UTC, retlaw34 commented
YES FDKSJLHOIPBHNA MJK<ALDHIUSHBMNLIU<JHBMNKJ S<LIO>:FSF><LKSJO IPF(*DLPM:<SDPKFJMNODF:PI(JUKDLSUNO