[WIP] Adds new ship spawning verb
shiptest-ss13/Shiptest pull request #1151
Opened 2022-06-02 02:50 UTC by swifterjack

## About The Pull Request
Fixes #1127 by adding a verb that loads any templates you feed into it as a shiptest and generates an overmap token.

Adds new verb, ship_template_load / "Load Template As Ship" which creates an overmap token and ship datum for the selected template and loads it like it was spawned with the shuttle manip. The way I do it is a bit jank, so please tell me if there is a better way.
## Why It's Good For The Game
Fixes bug, lets us spawn out of repo maps. Jobs still dont work, but thats a bit beyond my comprehension right now.

## Changelog
:cl:
add: Added new spawning verb
admin: New verb in debug menu
fix: template spawned ships fly again
/:cl:

2022-06-02 02:53 UTC, swifterjack commented
Note: I have not yet tested the effects of selecting a non-ship template, but i feel like admins can be trusted to not try to spawn lavaland_surface_syndicate_base1.dmm as a shiptest

2022-06-02 17:10 UTC, Cenrus commented
It might be better to add OM token generation to the shuttle manipulator, it's a really useful tool and even lets you preview the shuttle before you spawn it in.

2022-06-02 17:28 UTC, Fikou commented
> Note: I have not yet tested the effects of selecting a non-ship template, but i feel like admins can be trusted to not try to spawn lavaland_surface_syndicate_base1.dmm as a shiptest

test it please

2022-06-25 03:03 UTC, MarkSuckerberg requested changes

2022-06-25 03:03 UTC, MarkSuckerberg commented on code/modules/admin/verbs/map_template_loadverb.dm
> +		var/datum/overmap/ship/controlled/target = new(SSovermap.get_unused_overmap_square(), template)
```suggestion
		new /datum/overmap/ship/controlled(SSovermap.get_unused_overmap_square(), template)
```

2022-06-25 03:03 UTC, MarkSuckerberg commented on code/modules/admin/verbs/map_template_loadverb.dm
> +	template = SSmapping.map_templates[map]
```suggestion
	var/datum/map_template/template = SSmapping.map_templates[input(src, "Choose a Map Template to spawn as a ship.","Place Map Template") as null|anything in sortList(SSmapping.map_templates)]
```
this one's kind of up to choice, just putting it here if you want it to be one line, don't feel forced to do this

2022-07-25 02:10 UTC, ZephyrTFA commented
Sad

2022-08-25 01:41 UTC, closed without merging