Lagoon-class Cruise Ship
shiptest-ss13/Shiptest pull request #1159
Opened 2022-06-03 23:05 UTC by TypeVar

## About The Pull Request

![image](https://user-images.githubusercontent.com/100787466/171964715-1c9ca687-1b09-4a4e-a31b-f457f818c8d9.png)

Adds a roleplay-oriented cruise ship (that does not require mining to function)

## Why It's Good For The Game

Brings more roleplay elements. Engineering contains a TEG so there is no need to mine for fuel and electricity, which (in my opinion) induces LRP behavior. Contains nearly all service department roles, including a chef, botanist, bartender, curator, chaplain, janitor, mime and clown.

## Changelog
:cl:
add: Adds the Lagoon-class Cruise Ship
/:cl:

2022-06-04 15:06 UTC, RuneQuester commented
That's a really cool ship but Im so confused on how mining induces "lrp behavior"
Still, good shit. the competitor to the Echo-class

2022-06-04 16:38 UTC, TypeVar commented
I'm not saying mining is always LRP, though what I am saying is that mining-focused ships, at least from my experience, encourages people to focus more on gameplay than roleplay, which usually results in LRP crewmembers

2022-06-04 20:06 UTC, Apogee-dev commented
Config file needs namelists (I’d suggest GENERAL, SPACE, MERCANTILE, NATURAL) and a prefix, and I’d suggest adding intercoms through much more of the ship, especially work areas like the kitchen, library desk, and engineering section.

2022-06-05 02:18 UTC, TypeVar commented
> Config file needs namelists (I’d suggest GENERAL, SPACE, MERCANTILE, NATURAL) and a prefix, and I’d suggest adding intercoms through much more of the ship, especially work areas like the kitchen, security post, custodial office, library desk, and engineering section. An intercom on the bridge isn’t that useful if there aren’t any elsewhere on the ship after all.

I forgor about intercomms. and what do you mean it needs namelists and a prefix? it already starts off as ISV right? Or does it start off as SV?

2022-06-05 02:26 UTC, Apogee-dev commented
> I forgor about intercomms. and what do you mean it needs namelists and a prefix? it already starts off as ISV right? Or does it start off as SV?

The default prefix is SV. Namelists refers to the names picked for the ship on spawn- Different ships have different pools of names they can pull from (this is why you won't ever find a Colossus named ISV Scrungularity by default, for example)

2022-06-05 02:28 UTC, TypeVar commented
> > I forgor about intercomms. and what do you mean it needs namelists and a prefix? it already starts off as ISV right? Or does it start off as SV?
> 
> The default prefix is SV. Namelists refers to the names picked for the ship on spawn- Different ships have different pools of names they can pull from (this is why you won't ever find a Colossus named ISV Scrungularity by default, for example)

Ahhh I see. can I set up two extra ones that's CONCORDIA and TITANIC or is that too much?

2022-06-05 02:29 UTC, TypeVar commented
> > > I forgor about intercomms. and what do you mean it needs namelists and a prefix? it already starts off as ISV right? Or does it start off as SV?
> > 
> > 
> > The default prefix is SV. Namelists refers to the names picked for the ship on spawn- Different ships have different pools of names they can pull from (this is why you won't ever find a Colossus named ISV Scrungularity by default, for example)
> 
> Ahhh I see. can I set up two extra ones that's CONCORDIA and TITANIC or is that too much?

or is that something I need to set up separately? If that's the case I won't bother

2022-06-05 02:32 UTC, Apogee-dev commented
> > Ahhh I see. can I set up two extra ones that's CONCORDIA and TITANIC or is that too much?
> 
> or is that something I need to set up separately? If that's the case I won't bother

If you want to add new names or namelists you'd have to go into ship_names.json in the strings folder to add them.

2022-06-05 04:48 UTC, Calyxman commented
Holy shit. Yes. Speedmerge

2022-06-06 04:42 UTC, TypeVar commented
Think this is about done. The only error is the mapdiffbot

2022-06-10 23:51 UTC, Apogee-dev commented
Can you make the window and engine shutters start out closed?

2022-06-20 06:05 UTC, SweetBlueSylveon commented
2 Questions
Have any problems arisen since this got Test Merged?
Can you please make the window and engine shutters start out closed?

2022-06-20 22:45 UTC, TypeVar commented
> 2 Questions Have any problems arisen since this got Test Merged? Can you please make the window and engine shutters start out closed?

I can make them start off closed. What kind of problems have come up?

2022-06-22 21:20 UTC, Apogee-dev commented
A few things I missed earlier, make sure all wall buttons and light switches have the correct dir for the wall they're on. The ones on the bridge at the very least are facing the wrong direction.

2022-06-25 00:02 UTC, PrefabQuasar commented
![image](https://user-images.githubusercontent.com/78622038/175749835-be51acd4-32c3-4868-84d8-d40ae954f762.png)
missed a spot

2022-06-25 00:15 UTC, PrefabQuasar commented
also, while in the picture here it seems to be fine, the lower two arcade machines were facing south instead of west when i saw this in-round, unsure why

2022-06-28 23:05 UTC, Sweettoothart commented
North airlock of engineering has access requirements while south one of engineering does not

2022-06-29 03:20 UTC, TypeVar commented
gonna work on this tonight

2022-06-29 19:15 UTC, TypeVar commented
> also, while in the picture here it seems to be fine, the lower two arcade machines were facing south instead of west when i saw this in-round, unsure why

![image](https://user-images.githubusercontent.com/100787466/176517717-c44a84fd-efff-41fb-99dd-c19d3a87219d.png)
not sure why that's the case, it should look like this

2022-06-29 19:16 UTC, TypeVar commented
> North airlock of engineering has access requirements while south one of engineering does not

![image](https://user-images.githubusercontent.com/100787466/176517864-b8da50be-0b1b-4013-8b27-4082fd960aca.png)
South one has the same list() access as the north one

2022-07-02 03:42 UTC, SweetBlueSylveon requested changes
These arcade cabinets are not facing the right direction. If you did a "dir" edit, please use the "get icons from directions" option instead.
![image](https://user-images.githubusercontent.com/55075747/176985329-40f94331-6749-4a03-a176-fc9aea2644e4.png)

2022-07-06 08:14 UTC, SweetBlueSylveon commented
This has been testmerged almost a month now. I'd like to get this closed soon. Please address the pending comments and reviews of this ship. If you're too busy to update this now, I'll look at getting it un-TM'd so we can clear our list.

2022-07-06 15:22 UTC, TypeVar commented
> This has been testmerged almost a month now. I'd like to get this closed soon. Please address the pending comments and reviews of this ship. If you're not ready to finish this, you're free to take your time. However we may have to look at un-TMing this soon.

I'll deal with the direction of the arcade cabinets tonight. Anything else needing changing? I personally think it's good to merge after I fix the arcade

2022-07-06 16:24 UTC, TypeVar commented
> These arcade cabinets are not facing the right direction. If you did a "dir" edit, please use the "get icons from directions" option instead. ![image](https://user-images.githubusercontent.com/55075747/176985329-40f94331-6749-4a03-a176-fc9aea2644e4.png)

Do you mean icon state? If so, what icon state should it be?

2022-07-06 18:36 UTC, TypeVar commented
![image](https://user-images.githubusercontent.com/100787466/177619537-3a374778-a756-47f2-bfd8-67a1b0d07d6e.png)

2022-07-06 18:50 UTC, TypeVar commented
actually hold on gotta fix one more thing

2022-07-06 20:12 UTC, SweetBlueSylveon commented
Mmmmm lookin real marg-able right now.

2022-07-06 20:12 UTC, Latentish approved these changes

2022-07-06 20:12 UTC, merged