Replaces /datum/status_effect/crusher_damage with /datum/component/crusher_damage
shiptest-ss13/Shiptest pull request #1199
Opened 2022-06-11 07:44 UTC by IndusRobot

## About The Pull Request

Replaces status_effect/crusher_damage with component/crusher_damage

## Why It's Good For The Game

Theoretically better performance for the same functionality, although I'm not sure if a component was the right choice considering it's so tiny now. I verified crusher trophies were still dropping correctly afterwards. 

## Changelog
:cl:
fix: Replaced /datum/status_effect/crusher_damage with /datum/component/crusher_damage
/:cl:

2022-06-11 11:05 UTC, tmtmtl30 commented
Yeah, this is more or less what I had in mind. These were clogging up SSfastprocess, since one is created every time an asteroid hostilemob or megafauna spawns, and we have a whole fuckin' lot of those. i suggested it be moved to a component and out of status effects to make the level of modularity roughly the same, and because that was more or less a drop-in change.

the code is still Not Great, though -- crusher damage tracking, along with crusher_loot, could easily be moved to a variable on /mob/living/simple_animal/hostile, since both megafauna and asteroid hostiles are derived from that. that would probably make quite a bit more sense. but this gets the job done at least

2022-06-11 11:05 UTC, tmtmtl30 commented
i switched capitalization modes after the second sentence of that comment. fascinating

2022-06-13 15:57 UTC, Fikou requested changes
GetComponent is not a great solution. i suggest a global associated list of mob = damage

2022-06-13 15:58 UTC, Fikou commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	for(var/obj/item/crusher_trophy/trophy in trophies)
as anything

2022-06-13 15:58 UTC, Fikou commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		for(var/obj/item/crusher_trophy/trophy in trophies)
as anything

2022-06-13 15:58 UTC, Fikou commented on code/modules/mining/equipment/kinetic_crusher.dm
> +	for(var/obj/item/crusher_trophy/trophy in trophies)
as anything

2022-06-13 15:59 UTC, Fikou commented on code/modules/mining/equipment/kinetic_crusher.dm
> +		for(var/obj/item/crusher_trophy/trophy in trophies)
as anything

2022-06-14 12:07 UTC, closed without merging