People with no hunger now regenerate blood
shiptest-ss13/Shiptest pull request #1264
Opened 2022-06-26 05:16 UTC by KittyNoodle

Signed-off-by: KittyNoodle <78111117+KittyNoodle@users.noreply.github.com>

## About The Pull Request

Currently any race that has no hunger doesn't regenerate blood, leading to blood loss being a death sentence for them.
This changes that so they now regenerate blood.

## Why It's Good For The Game

Not being able to regenerate blood (from what i can see on tg is a bug) is both very annoying and made even more annoying on ships, where blood is not easily accessable.

## Changelog
:cl:
tweak: Elzuose now can regenerate blood.
/:cl:

2022-06-26 05:18 UTC, retlaw34 commented
holy shit finally, thank you so much!

2022-07-12 18:23 UTC, triplezeta requested changes
![image](https://user-images.githubusercontent.com/51932018/178566847-572d130f-73c8-4616-823e-e180b1b1643f.png)

2022-07-13 20:27 UTC, KittyNoodle commented
god why

2022-07-13 22:12 UTC, MarkSuckerberg approved these changes

2022-07-13 22:12 UTC, merged