[WIP] Research TCv4
shiptest-ss13/Shiptest pull request #1269
Opened 2022-06-27 01:43 UTC by ZephyrTFA

Research Grid
----
- [ ] Generation
- [ ] Interactions
- [ ] Research Point Usage
- [ ] Completion Checking
- [ ] Completion Handling

Research Nodes
----
- [ ] Node Generation
- [ ] Requirement Checking
- [ ] Unlock Handling

This is planned to be a complete overhaul of the current research system which adds different types of researches, and a dedicated method of unlocking nodes. The old form of research was quite literally click button get gold, which is not only boring but provides little, if not negative, amounts of player interaction.

Changelog
---
todo

2022-07-04 21:04 UTC, SweetBlueSylveon commented
Could we get some pictures or recordings of this new system? I'd appreciate being able to see it!

2022-07-05 12:28 UTC, Fikou requested changes
i'll review the new files later

2022-07-05 12:28 UTC, Fikou commented on code/game/machinery/autolathe.dm
>  					continue
stack these ifs maybe?

2022-07-05 12:28 UTC, Fikou commented on code/game/machinery/computer/Operating.dm
> +		advanced_surgeries.Add(surgery.surgery)
this feels really hacky, can you elaborate why you did it like that?

2022-07-05 12:28 UTC, Fikou commented on code/game/mecha/mech_fabricator.dm
> +				if(set_name in design.category)
stack these?

2022-07-05 12:28 UTC, Fikou commented on code/game/mecha/mech_fabricator.dm
>  	if(set_name in part_sets)
early return

2022-07-05 12:28 UTC, Fikou commented on code/game/mecha/mech_fabricator.dm
> +				if(design.id == T)
stack

2022-07-05 12:28 UTC, Fikou commented on code/game/mecha/mech_fabricator.dm
> +				if(design.id == T)
stack

2022-07-05 12:28 UTC, Fikou commented on code/game/mecha/mech_fabricator.dm
> +				if(design.id == T)
stack

2022-07-05 12:28 UTC, Fikou commented on code/modules/ninja/suit/suit_attackby.dm
> -/obj/item/clothing/suit/space/space_ninja/attackby(obj/item/I, mob/U, params)
why are we deleting this file? refilling ninja suit with radium/smoke powder/replacing power cell is nice

2022-07-05 12:28 UTC, Fikou commented on code/modules/research/bepis.dm
> +	// TODO: BEPIS SHIT
gwa gwa

2022-07-05 12:28 UTC, Fikou commented on code/modules/research/destructive_analyzer.dm
> +	//TODO: ITEMS INTO DEPARTMENTAL POINTS BASED ON COMPLEXITY AND VALUE
gwa gwa

2022-07-05 12:28 UTC, Fikou commented on code/modules/research/nanites/nanite_chamber.dm
> +			say("linked to server")
use visible_message like the cloud controller

2022-07-05 12:28 UTC, Fikou commented on code/modules/research/research_disk.dm
> -/obj/item/disk/tech_disk/major/Initialize()
gwa gwa

2022-07-05 13:38 UTC, ZephyrTFA commented on code/game/machinery/computer/Operating.dm
> +		advanced_surgeries.Add(surgery.surgery)
It's the exact same thing, I just think .Add(X) looks nicer than |= X;
what OOP does to a man

2022-07-05 13:47 UTC, ZephyrTFA commented on code/modules/research/bepis.dm
> +	// TODO: BEPIS SHIT
this is still a draft my boy; WIP

2022-08-03 17:38 UTC, ZephyrTFA commented
Agony

2022-08-16 10:09 UTC, ZephyrTFA commented
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

Yes I know it does, I'm only changing literally everything related to research

2022-09-14 21:52 UTC, ZephyrTFA commented
The only thing stopping me from finishing this is Frontend bullshit. Why is TGUI garbage.

2022-11-21 13:30 UTC, closed without merging

2022-11-21 13:30 UTC, ZephyrTFA commented
maybe one day. But not today

2022-11-21 13:30 UTC, ZephyrTFA commented
Not next week either