shipowners v1
shiptest-ss13/Shiptest pull request #1270
Opened 2022-06-27 11:49 UTC by tmtmtl30

## About The Pull Request

adds ship owners, a system for granting people OOC control of their ship's memo, job slots, and crew. the ship owner is generally the first person to join the ship; the role is transferred if they log out, go AFK, or possess a mob with a mind different than the mind they joined the ship with (like, mindswaps should be fine, but if you ghost, or die and respawn / an admin puts you into a simplemob / you take a ghostrole or something, you won't be the shipowner anymore). functionality for changing the ship's memo, job slots, and join mode have been moved from the cryo console to the ship owner panel that the current ship owner gets.

this PR also adds an application system. the ship owner can set the ship's join mode to "apply". players who attempt to join application-only ships must have an accepted application (organized by ckey) on the ship to join it. if none is found, they are prompted to send an application that includes their ckey, currently-selected character name, and an optional additional message. the ship owner can choose to approve or deny this application.

the ship owner is additionally able to delete applications that have already been accepted or denied, transfer ship owner status to other crewmembers, and toggle their candidacy for automatically inheriting the ship owner role if the current owner goes AFK.

there are also a bunch of misc. fixes to prevent people joining the round when they shouldn't. also the maximum number of job slots for a non-officer job on a ship has been changed to the minimum of 2x the default number of slots and 3 + the default number of slots. also, adjusting the job slots only trips the 2-minute cooldown if you are adjusting above the default slot count, and has a 5 second cooldown otherwise. 

also, admins have a button to open the ship owner panel from the shuttle manipulator panel even if they're not the ship owner, in addition to newly-added buttons to open VV for the ship's docking port and overmap datum. 

borers and split personalities almost certainly fuck with the mind-detection this system uses;  #1259 was made to rectify this but i still haven't tested that PR or tested this PR with borers / split personalities because Fuck, man.

other things:
- [ ] don't merge this fucking PR until i've commented everything because this system is utterly arcane
- [ ] needs to be properly tested with borers and split personalities
- [ ] AFK detection is scuffed -- the place i put the signal is weird, and you don't get a chance to react and stop ship owner control from leaving you if you're afk for long enough (bad if you spend a lot of time without making any inputs at all)
- [ ] the ship owner can't designate a direct successor, only toggle people's eligibility
- [ ] which might be a problem because if nobody is eligible then the ship will enter a state where it's ownerless and will continue checking for an owner every few minutes until either somebody becomes eligible or somebody new joins (who will then become an owner). so you could have a closed ship that ends up permanently ownerless because the last owner turned everybody's eligibility off and logged off or went AFK. ofc you could still ahelp this
- [ ] you don't get told when making an application "this ship doesn't currently have an owner" which seems like nice info to have
- [ ] it turns out that the config settings for AFK detection are fucked because the BYOND reference says that the "inactivity" var on clients counts the number of server ticks, not the number of ds, since the client's last input. so i need to update the config files and change some of the code to reflect that
- [ ] uhhhh 

## Why It's Good For The Game

there are a couple problems with our current system for joining ships. 1: memos are important, but people never use them. 2: some people want finer-grained control over their ship's RP level or crew, but they have no way of doing this. ship owners solve both problems, and the small misc changes i made all seem like common sense to me. 

## Changelog
:cl:
add: Added ship owners, an OOC utility to give players more control over their ships' RP levels. Any crew member can be the ship owner, as long as they are still connected and not AFK. This system is not ckey-based; if you respawn, you are no longer a candidate. Memos and job slot adjustment have been moved from the cryo console to the shipowner panel.
add: Ship applications -- ships can now enter an "application only" mode, where new players must send a ckey-linked application to the ship owner for approval or denial. These applications can be deleted by the owner afterwards; no other interaction is presently possible.
tweak: Ship job slot maximums and job slot change cooldown timers have been adjusted slightly.
refactor: "Latejoin" spawn code has been made more reliable and better able to handle a few edge cases.
admin: Admins can access a ship's ship owner panel from the shuttle manipulator, as well as directly access the docking port and ship overmap datum's VV panels.
/:cl:

2022-06-27 11:49 UTC, tmtmtl30 commented
shut the fuck up

2022-06-27 11:55 UTC, ZephyrTFA commented on code/controllers/subsystem/shuttle.dm
> +			owner_action.Grant(user)
Won't this end up giving admins another action every time, even if they already had it

2022-06-27 11:59 UTC, tmtmtl30 commented on code/controllers/subsystem/shuttle.dm
> +			owner_action.Grant(user)
yeah, but the action automatically deletes itself when they close the window. so i don't think it's a big problem

2022-06-27 11:59 UTC, ZephyrTFA commented on code/controllers/subsystem/shuttle.dm
> +			owner_action.Grant(user)
Huh maybe I should actually read the entire PR before making review comments

2022-06-28 21:09 UTC, tmtmtl30 commented
switched things so that you now get prompted with whether or not you want to send your ckey with your application. i should probably make a more fleshed-out UI for this too but i don't know what the TGUI element for a big old text square is. that's pretty much the only thing stopping me

2022-06-30 06:09 UTC, Kapu1178 commented on code/controllers/subsystem/server_maint.dm
> +	for(var/client/C as anything in currentrun)
you cannot assume clients arent null

2022-06-30 06:20 UTC, Kapu1178 requested changes

2022-06-30 06:20 UTC, Kapu1178 commented on code/controllers/subsystem/shuttle.dm
> +			user.client.debug_variables(port)
cant assume clients arent null

2022-06-30 06:20 UTC, Kapu1178 commented on code/controllers/subsystem/shuttle.dm
> +			user.client.debug_variables(port.current_ship)
cant assume clients arent null

2022-07-07 07:02 UTC, tmtmtl30 commented
ok i figured out what the TGUI element for a big old text square is

2022-07-16 20:41 UTC, RDS88-beeman commented
I'm really having problems with the new application feature. As far as I can tell from my gameplay experience so far, if you want to join a ship with more than two or three people on it, you'll need to fill out an application. And since there's no way to give like a form, you're forced to freehand it.

I cannot freehand an application for the life of me. This mostly results in me sitting on the lobby screen, unwilling to join a ship with no crew but unable to join a ship with a lot of crew, wishing I could just join a ship and play shiptest like I used to.

2022-08-25 02:29 UTC, ZephyrTFA commented
Turns out I accidentally merged this into master in a previous PR, which would be why everything is conflicting

2022-08-25 02:29 UTC, closed without merging