Adds a new Ice Planet ruin, the Hydroponics Lab
shiptest-ss13/Shiptest pull request #1300
Opened 2022-07-05 00:26 UTC by iwishforducks

## About The Pull Request

Adds a new Ice Planet ruin, the Hydroponics Lab. Located deep within a mountain, this old and rusted laboratory focuses on growing experimental and deadly plants.

![2022 07 04-20 21 49](https://user-images.githubusercontent.com/65363339/177227867-5d7d73e8-bedd-4ec2-b90b-b238b2285848.png)

The main loot is as follows:

- Two M1911 handguns + one magazine in total
- One flamethrower
- Security winter coat
- Security jumpsuit
- Jackboots
- A botanical chemical synthesizer
- A variety of botany tools including a botany locker
- Tools + multitool
- Biogenerator, seed extractor, and plant DNA manipulator
- Hydroponic trays
- Bottles of ammonia, diethylamine, ez-nutrient, unstable mutagen, left-4-zed, robust harvest, sodium and ethanol
- Replica pod seeds
- Killer tomatoes
- Death nettle seed
- Kudzu seeds
- A variety of plant seeds and plants
- Biosuit

The katana located in the walls is a replica. I hope some poor sap looks at this PR, sees the katana, and goes "OMG REAL KATANA!!!" and wastes their time trying to tear down the walls.

## Why It's Good For The Game

Ice ruins are lacking and we don't have any hydroponics themed ruins on the ice just yet.

More ruins = good

## Changelog
:cl:
add: Added a new ruin on Ice Planets, the Hydroponics Lab.
/:cl:

2022-07-06 08:50 UTC, Latentish requested changes
This is a fine ruin, but I'm reticent about some of the more dangerous seeds. I'd like to see them included as they can be fun, but kudzu in particular can get out of control easily. So please put some decals or props to indicate its danger. Telegraph the danger.

2022-07-06 18:47 UTC, iwishforducks commented
Revamped the "vault" room a bit more since I kind of hastily whipped that one up, along with making the requested change.

![image](https://user-images.githubusercontent.com/65363339/177621060-a926a73d-ca85-4049-ab9d-2c68ae9a4008.png)

Made things look nicer in general too, updated the main image in the PR to reflect it, but the takeaway is that airlocks telegraph their rooms better and rooms make a little more sense.

2022-07-11 21:46 UTC, SweetBlueSylveon commented
This ruin feels like a lootbox. You have a decent spread of enemies but you fill this ruin to the brim with good shit. You'll need to cut back. I'd recommend removing the weapons and security stuff, as this seems to revolve around the good botany loot more.

2022-07-12 20:45 UTC, iwishforducks commented
I've opted to just remove the plant DNA manipulator and botanical-chemical synthesizer. The security related loot is pretty negligible and only exist to tell a story - ultimately there is nothing more to cut down on.

2022-07-17 07:41 UTC, SweetBlueSylveon approved these changes
Pretty much.
TM?

2022-07-17 16:12 UTC, iwishforducks commented
I think it's fine for a full merge. I got lucky with an ice planet once and it seemed to spawn in just fine. If that's what you're asking, that is, with the whole testmerge question.

2022-07-22 23:26 UTC, merged