The Grand Limbgrower TGUI update, now with its own research node, data disks, snazzy ui I made specifically for this server, and a new feature
shiptest-ss13/Shiptest pull request #1308
Opened 2022-07-06 05:51 UTC by Chubbygummibear

## About The Pull Request
Currently the Limbgrower is turbo garbage and only has a few race options. This is a port of TG's limbgrower update and a lot of shiptest original code written by my own sinful hands. 
The tl;dr is

- Limbgrower has a snazzy new ui
- Limbgrower when first built can print arms and legs for every organic race (snowflake limb races rejoice)
- New Tech node right after advanced biology called Xeno-Organ Biology. unlocks data disks which can be uploaded to the limbgrower to add more printing options in the form of xeno specific organs. costs 2500 research.
- Limbgrower will accept raw meat and grind it into synthflesh for fuel. Bear with me for a second for this one. On Yogstation when I first did this port, I added the hugbox meat processing code because people were used to fueling the cloner with meat for biomass instead of synthflesh. the reason I think it's acceptable here is because sometimes resources are very thin, so the ability to create spare limbs and organs without a chemstation could be the difference of life and death for some crew, and meat is abundant on planets with fauna. Yes this can be used to print synthflesh by grinding meat, disassembling the machine, and taking the full beakers out. Let me know if this is too broken. I think another means of getting a vital reagent is just another boon.

what it looks like on the tech tree
![image](https://user-images.githubusercontent.com/46236974/177475055-dcdd2cb7-85a3-4e21-930d-31bdd7d22377.png)

unupgraded default view
![image](https://user-images.githubusercontent.com/46236974/177459749-145e8332-d05d-44da-85ce-d874e4c2b592.png)

upgraded and with the plasmaman design disk installed
![image](https://user-images.githubusercontent.com/46236974/177475688-31b5e8dc-038d-4d37-92f3-c58556180608.png)

printed from a protolathe with med access, then you just use them on the limbgrower to unlock more organ designs
![image](https://user-images.githubusercontent.com/46236974/177474968-793b839a-c152-43f3-b2ad-c641d712cba3.png)

limbs with mutant colors spawn with a random color. go nuts, make yourself a rainbow if you have the patience to keep rolling limbs
![image](https://user-images.githubusercontent.com/46236974/177478038-f470f96f-f83c-4968-9272-ecbc530e6193.png)

## Why It's Good For The Game

## Changelog
:cl:
add: new Limbgrower tgui interface
add: way more bodypart designs in the limbgrower, such as kepori and vox limbs
add: new research node called Xeno-Organ Biology, which unlocks limbgrower design disks that allow you to print xeno organs in addition to their body parts 
add: Limbgrower accepts raw meat as input and grinds it into synthflesh to use as fuel
del: Limbgrower old ui gone
code: Added some Dwarf stuff (don't worry about it)
code: a lot of snowflake code to make digi legs printable. It is a mess and i'm sorry but it works
/:cl:

2022-07-06 06:02 UTC, triplezeta commented
can you merge the xenoorgan biology node with advanced biotech and add a human limb/organ disk

2022-07-06 06:13 UTC, Chubbygummibear commented
> can you merge the xenoorgan biology node with advanced biotech and add a human limb/organ disk

human organs are available right from the get-go. unless you mean remove them and require a human disk. The advanced biotech merge is a decent idea. i know research can be a pain to get so even 2500 might be a big ask

2022-07-06 06:15 UTC, triplezeta commented
that is what i mean yes

2022-07-06 06:21 UTC, Chubbygummibear commented
> that is what i mean yes

i would like to keep the default organ set available right away because the limbgrower boards can be gotten from the rock planet and for a ship that doesn't immediately have research capabilities than can be a godsend. I've been in a position before where my crew member had died on a sand planet after already receiving a heart bypass. so in order to get a replacement heart i had to hunt a legion for a replacement. these kind of dire straits scenarios are why i want the limbgrower to be able to fill a need immediately. in addition, even if you have a research console and server, you might not have a protolathe to print the disks. meaning you still might not have access to organs.

2022-07-06 06:51 UTC, triplezeta commented
for the sake of lore i want to avoid having there be a "default" set of organs. as an alternative i would suggest just giving the limb grower all roundstart species limb and organ designs by default instead of separating them out into disks

2022-07-06 19:40 UTC, Chubbygummibear commented
> for the sake of lore i want to avoid having there be a "default" set of organs. as an alternative i would suggest just giving the limb grower all roundstart species limb and organ designs by default instead of separating them out into disks

definitely gonna try to talk to some devs about balance. i would like it to be an organ printing option pretty quick, but i'm not sure if it would be too strong having all the designs immediately

2022-07-07 08:26 UTC, Chubbygummibear commented
after talking with a project lead all the roundstart race limbs and organs will immediately be available, and the more exotic races will be design disk locked. working on this now

2022-07-12 04:24 UTC, MarkSuckerberg requested changes
Just realised I didn't actually send these... 😔

2022-07-12 04:24 UTC, MarkSuckerberg commented on code/game/machinery/limbgrower.dm
> +			if(!categories.Find(limb_design_disk.species))
```suggestion
			if(!(limb_design_disk.species in categories))
```

2022-07-12 04:24 UTC, MarkSuckerberg commented on code/game/machinery/limbgrower.dm
> +		for(var/datum/design/found_design in species_categories[category])
```suggestion
		for(var/datum/design/found_design as anything in species_categories[category])
```
Since we know it'll always be a list of purely `/datum/design`s.

2022-07-13 21:47 UTC, MarkSuckerberg approved these changes

2022-07-17 18:46 UTC, merged