Prevent duplicate names for vents and scrubbers
shiptest-ss13/Shiptest pull request #1337
Opened 2022-07-13 04:58 UTC by antropod

Makes scrubbers and vents re-use sequential ids for their names. No longer you will have two vents #9 in the area.

## About The Pull Request

Currently game allocates names for new vents/scrubbers based on how many there are scrubbers in the area. New index for that name will be `names.len + 1`. Assume you have 9 scrubbers in the area. So if you remove, say scrubber #2 and then re-wrench it, it will be named scrubber #9 and have same name as your existing scrubber #9.
On /tg/ this issue was fixed 2 years ago by making scrubbers/vents have random alphanumeric name, which is pain to deal with (original idea was to re-use ids, but then it went south during the conversation in PR)
Here I'm using algorithm for allocating names that was originally proposed in https://github.com/tgstation/tgstation/pull/52398 by myself.

Benefit of this approach is that if you unwrench one vent/scrubber and wrench it back, it will have same name as before.

## Why It's Good For The Game

Makes construction of atmos systems less painful.

## Changelog
:cl:
fix: Prevent duplicate names for vents and scrubbers
/:cl:

2022-07-13 08:09 UTC, tmtmtl30 commented
i'm not a huge fan of this, but that's mostly because i hate areas with a violent, searing passion, and see anything that uses them as an assault on all that is good and just. random IDs would avoid my ire, but i'll have to look at this + the original PR

2022-07-13 11:00 UTC, antropod commented
This is my experience on working with atmos projects:

Random IDs are annoying, because you have to remember each and every one them and look trough lists to find them.

Sequential ids are much easier to remember, for example you made a burn chamber with 4 scrubbers, and now you just remember that scrubbers 1 to 4 are "burn chamber"

Another problem with random ids is ordering, good luck finding scrubber Xy9sd in the list of 20 scrubbers.

This is why I originally proposed to re-use ids, and PR was going this way, but somewhere in the middle of the conversation it all went south and author just made low-effort random naming

2022-07-29 11:58 UTC, antropod commented
@tmtmtl30 can you take a look?

2022-08-07 14:40 UTC, MarkSuckerberg requested changes
Sorry for taking so long, here's just some general small optimizations. Seems good

2022-08-07 14:40 UTC, MarkSuckerberg commented on code/__HELPERS/sequential_id.dm
> +	for (var/i in 1 to names.len)
```suggestion
	for (var/i in 1 to length(names))
```

2022-08-07 14:40 UTC, MarkSuckerberg commented on code/__HELPERS/sequential_id.dm
> +	return names.len
```suggestion
	return length(names)
```

2022-08-19 00:10 UTC, MarkSuckerberg approved these changes

2022-08-19 00:10 UTC, merged