SRM Glaive-Class Hunter Ship
shiptest-ss13/Shiptest pull request #1363
Opened 2022-07-21 09:52 UTC by SweetBlueSylveon

## About The Pull Request
The SRM has no unique ship at the moment. This adds a ship to this very funny almost completely nonpresent PMC faction.
![2022 07 21-02 41 56](https://user-images.githubusercontent.com/55075747/180184328-87d90b1e-6cc1-48b1-9330-ccb9e4670663.png)
![image](https://user-images.githubusercontent.com/55075747/180184484-3a27e9e9-452c-4515-a624-af504b27df7c.png)
![image](https://user-images.githubusercontent.com/55075747/180184582-e1ebe2b6-1feb-4f46-8189-019995ee9d35.png)

This ship also tackles a newish niche! Beasttaming! There's capture pods, a lazarus injector (and planned blueprint), intelligence potions, and docility potions. It's limited, but they have a big hunter tamer culture. They're very well equipped in mining, firearms, and mob taming. They  are very underequipped in medical, they have basically no tech, and it leans heavily into tribal crafting.

## Why It's Good For The Game
Funny SRM PMC heheheehroohroo hahaha 

## Changelog
:cl:phoaly
add: The Glade Class
/:cl:

2022-07-23 08:35 UTC, SweetBlueSylveon commented
![image](https://user-images.githubusercontent.com/55075747/180597427-9908528c-e7b7-44a8-9353-e95e4780065d.png)
bloodborne references

2022-07-23 22:46 UTC, RuneQuester commented
> ![image](https://user-images.githubusercontent.com/55075747/180597427-9908528c-e7b7-44a8-9353-e95e4780065d.png) bloodborne references

Oh dear, what was it? The lag, the griefers, or the horrible maps?

2022-07-24 07:02 UTC, SweetBlueSylveon commented
This should be test merged when the event to introduce the SRM is ready. Once that happens, I'll make the ship purchaseable, and we can get it actually tested enough to merge. So DNM for now.

2022-08-10 03:06 UTC, SweetBlueSylveon commented
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 14 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

IT IS LITERALLY TM'D 
Die

2022-08-15 08:25 UTC, SweetBlueSylveon commented
I'm FUCKING PISSED.

2022-08-15 19:37 UTC, ArdentSpark commented
Haha oh my god that reason for the CI fail is amusing. I had a suggestion, may I propose that these airalarms and APC's bordering the 'secret rooms' are moved? That way the option of opening up the walls and expanded into from the locker room and medical room is there, without having to move machiner
![](https://cdn.discordapp.com/attachments/673107663709798411/1008821608716181555/unknown.png)
y

2022-08-15 22:07 UTC, ArdentSpark commented
The Winchester Mk2 Rifle added by this PR is unprintable, due to requiring Wood, which is not able to be added as a material to Circuit printers, Protolathes, Autolathes, ORMs or Silos due to not containing sufficient materials
![](https://cdn.discordapp.com/attachments/673107663709798411/1008859493012099233/unknown.png)
![](https://cdn.discordapp.com/attachments/673107663709798411/1008859517552959539/unknown.png)

2022-08-20 01:11 UTC, SweetBlueSylveon commented
I'll finish this and mark it ready for review later

2022-09-03 01:43 UTC, PrefabQuasar requested changes
this map doesnt seem to have any major issues, nor have any shown up when it was TM'd, however, i'd reccomend either changing the wardrobe lockers to another sprite or making them not access locked, as the sprite currently used isnt designed to have an access lock, so it looks odd on them, i'm also unsure on the inclusion of sentience potions in here, i feel like too often those can just lead to "animal that acts like a human in every respect", which doesnt feel great for RP

2022-09-03 01:44 UTC, PrefabQuasar commented
> The Winchester Mk2 Rifle added by this PR to the techweb is unprintable, due to requiring Wood, which is not able to be added as a material to Circuit printers, Protolathes, Autolathes, ORMs or Silos due to not containing sufficient materials ![](https://camo.githubusercontent.com/0d279ec6bb0798a8ce0590f992302b29945db9866156350e4a57472f152cfead/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3637333130373636333730393739383431312f313030383835393439333031323039393233332f756e6b6e6f776e2e706e67) ![](https://camo.githubusercontent.com/96a62b22d8b98afa6c2948f2f81a375c85874bd7d756b11c45b54b4af95d5eec/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3637333130373636333730393739383431312f313030383835393531373535323935393533392f756e6b6e6f776e2e706e67)

assuming that this has been addressed

2022-09-03 01:46 UTC, SweetBlueSylveon commented
> assuming that this has been addressed

Yes this has been addressed and the wood has been removed from the requirement.

2022-09-03 01:48 UTC, SweetBlueSylveon commented
> this map doesnt seem to have any major issues, nor have any shown up when it was TM'd, however, i'd reccomend either changing the wardrobe lockers to another sprite or making them not access locked, as the sprite currently used isnt designed to have an access lock, so it looks odd on them, i'm also unsure on the inclusion of sentience potions in here, i feel like too often those can just lead to "animal that acts like a human in every respect", which doesnt feel great for RP

I can swap the locker sprite.

The sentience potion here is for part of the ship's niche of beast taming. I get that players might act like normal people as sentient animals, but I feel that's a reflection on sentience potions as a whole. I am unsure if there's another potion to let players take over simples.

2022-09-03 01:52 UTC, PrefabQuasar commented
> > this map doesnt seem to have any major issues, nor have any shown up when it was TM'd, however, i'd reccomend either changing the wardrobe lockers to another sprite or making them not access locked, as the sprite currently used isnt designed to have an access lock, so it looks odd on them, i'm also unsure on the inclusion of sentience potions in here, i feel like too often those can just lead to "animal that acts like a human in every respect", which doesnt feel great for RP
> 
> I can swap the locker sprite.
> 
> The sentience potion here is for part of the ship's niche of beast taming. I get that players might act like normal people as sentient animals, but I feel that's a reflection on sentience potions as a whole. I am unsure if there's another potion to let players take over simples.

i'm still iffy on them, i'd want a third opinion really

2022-09-03 02:00 UTC, Apogee-dev commented
> i'm still iffy on them, i'd want a third opinion really

Sentience potions are fine imo due to mechanical need. The beast tamer gimmick just plain doesn't work without them, and it gives ghosts more stuff to do.

2022-09-03 02:02 UTC, PrefabQuasar commented
good enough for me, although one day i'd hope to see a potion that gives sentience but not the common language. actually that might not be too hard to add

2022-09-03 02:03 UTC, PrefabQuasar approved these changes
regardless, thats everything i had adressed, and nothing's come up during testing

2022-09-03 17:50 UTC, Fikou commented on code/game/MapData/shuttles/srm_glaive.dm
> +	generate_items_inside(items_inside,src)
```suggestion
	var/static/list/items_inside = list(
		/obj/item/healthanalyzer = 1,
		/obj/item/reagent_containers/food/snacks/grown/ash_flora/puce = 1,
		/obj/item/reagent_containers/glass/mortar = 1,
		/obj/item/reagent_containers/glass/bowl/mushroom_bowl = 1,
		/obj/item/pestle = 1,
		/obj/item/reagent_containers/food/snacks/grown/ash_flora/cactus_fruit = 3,
		/obj/item/reagent_containers/food/snacks/meat/slab/bear = 3,
		/obj/item/reagent_containers/food/snacks/grown/ash_flora/mushroom_leaf = 3,
	)
	generate_items_inside(items_inside, src)
```

2022-09-03 17:56 UTC, merged