Admin verb to spawn planets/ruins
shiptest-ss13/Shiptest pull request #1384
Opened 2022-07-24 18:16 UTC by ZephyrTFA

## About The Pull Request

Adds the ability for an admin with R_FUN to spawn a specific planet with a specific ruin.
Also has the framework to support multiple ruins per planet in the future, when that happens, tmt please

## Why It's Good For The Game

Admin events will be easier

## Changelog

:cl:
admin: Spawn a planet and ruin with a brand new verb!
/:cl:

2022-07-24 20:41 UTC, SweetBlueSylveon commented
YES
YES
YES
YES

2022-07-28 00:09 UTC, Fikou requested changes

2022-07-28 00:09 UTC, Fikou commented on code/controllers/subsystem/overmap.dm
> +	var/list/ruin_turfs = new
would prefer list() here instead of new unless theres some specific reason

2022-07-28 00:09 UTC, Fikou commented on code/modules/admin/verbs/randomverbs.dm
> +	encounter.preserve_level = 1
is this a boolean? if yes make this TRUE

2022-07-28 11:23 UTC, Fikou approved these changes

2022-07-28 11:23 UTC, merged