Adds a Selling Pad to Meta-Class
shiptest-ss13/Shiptest pull request #1418
Opened 2022-08-02 19:22 UTC by TypeVar

## About The Pull Request

Adds a selling pad to the Meta-Class

![image](https://user-images.githubusercontent.com/100787466/182455781-2590cab4-ea52-4320-8a9d-cefc21c7a175.png)

## Why It's Good For The Game

Meta-Class is very underpowered when it comes to whiteships. It being a cargo ship, I think it would be appropriate to add a selling pad, as other cargo ships, such as the Luxembourg have it too. This PR also changes dorms and changes the crew to have 3 cargo techs instead of 3 assistants.

## Changelog

:cl:

tweak: Adds a selling pad to the Meta-Class

/:cl:

2022-08-04 19:32 UTC, TypeVar commented
Can someone review this? I didn't change too much about it and I don't think it will conflict with other PRs

2022-08-08 23:33 UTC, Apogee-dev requested changes

2022-08-08 23:33 UTC, Apogee-dev commented on _maps/shuttles/shiptest/whiteship_meta.dmm
> +/obj/item/storage/backpack/duffelbag/med/surgery,
I'd nix the full set of surgical tools- the Meta doesn't even have an actual medbay after all, just a crate of medical supplies. Use the surgical medkit instead- the one with a partial set of tools and a bit suture/mesh.

2022-08-31 01:57 UTC, closed without merging

2022-08-31 01:59 UTC, Zevotech commented
:thepleadster:

2022-09-06 18:56 UTC, TypeVar commented
Oh this closed. Should I just make a new branch or something?

2022-09-09 20:39 UTC, PrefabQuasar commented
still has a merge conflict to be fixed it seems, but here it is re-opened

2022-09-09 20:40 UTC, PrefabQuasar commented
or.. not? github will not let me re-open this
![image](https://user-images.githubusercontent.com/78622038/189439345-70db7819-dd3c-4d92-bfb8-1c85e621d098.png)

2022-09-09 21:26 UTC, TypeVar commented
:thepleadster:

I'll make a new PR for this then

2022-09-09 21:31 UTC, PrefabQuasar commented
yeah, go ahead