Interdiction
shiptest-ss13/Shiptest pull request #1457
Opened 2022-08-14 05:56 UTC by ZephyrTFA

## About The Pull Request

Adds the ability for ships to create and setup an interdiction console.
This console will allow them to force another ship to dock into an `interdiction point` which is just a reskinned empty event map

After 20 seconds the interdiction will automatically end, so you better be able to get to their ship within that timeframe.
I may consider making the timer longer

## Why It's Good For The Game

Its something people have wanted forever

## Changelog

:cl:
add: Ship Interdiction
/:cl:

2022-08-14 06:07 UTC, MarkSuckerberg requested changes

2022-08-14 06:07 UTC, MarkSuckerberg commented on code/modules/overmap/interdiction.dm
> +					c_x++
```suggestion
		if(dir & NORTH)
			c_y++
		if(dir & SOUTH)
			c_y--
		if(dir & EAST)
			c_x++
		if(dir & WEST)
			c_x--
```

2022-08-14 06:07 UTC, MarkSuckerberg commented on code/modules/overmap/interdiction.dm
> +		throw_ship_contents(current_ship, turn(heading, 180), their_speed * SPEED_THROW_STRENGTH_MULT)
Maybe make this speed differential instead of just raw speed? So if you're both going fast it's easier &c

2022-08-14 06:07 UTC, MarkSuckerberg commented on code/modules/overmap/interdiction.dm
> +		priority_announce("Interdiction is now in effect on target \"[target]\"", "Interdiction Tether Launched", 'sound/misc/announce.ogg', "interdiction", "Interdiction ([current_ship])", zlevel=announce
can't you just use the virtual Zs of the two shuttle ports

2022-08-14 06:07 UTC, MarkSuckerberg commented on code/modules/overmap/interdiction.dm
> +		priority_announce("Interdiction is no longer in effect on target \"[interdicting]\"", "Interdiction Tether Dissipated", 'sound/misc/announce.ogg', "interdiction", "Interdiction ([current_ship])", z
same here

2022-08-14 07:47 UTC, Sylphily commented
pirates but it actual works???? also the time for it seems a bit low, maybe 1 minute is enough?

2022-08-14 13:29 UTC, MemedHams commented
consider adding some kind of gripping mechanic that relies on resources/fine-tuning the interdictor-
if there's a guaranteed short and exact "you will be able to get away" timer you can guarantee that people will respond to being interdicted by sitting on their console and refreshing over and over until the button goes blue

Getting onto someone else's vessel is "doable" (if barely) in 20 sec, but preventing them from jumping in that time is another story

best case scenario you're either 
a: forced to fight a man down as someone stays behind to take your vessel into pursuit
or b: have to fight all in because them jumping out with all your crew onboard _will delete your ship._

2022-08-16 00:21 UTC, RuneQuester commented
only 20 seconds is *really* shit. Like, 5 minutes seems better. Or have it scale off something, like engine count(stupid but, an idea is an idea). Smaller vessels will have longer interdiction times, bigger have shorter. 

Great idea though, and Im glad its being added.

2022-08-17 15:24 UTC, Valorium-RB commented
> only 20 seconds is _really_ shit. Like, 5 minutes seems better. Or have it scale off something, like engine count(stupid but, an idea is an idea). Smaller vessels will have longer interdiction times, bigger have shorter.
> 
> Great idea though, and Im glad its being added.

Seconded. That way it's easier for pirates to prey on small vessels (as they realistically would) and as they get more resources and can locate ships more easily by having more looted hard suits or jetpacks and whatnot, they can take on bigger ships as a form of natural progression.

2022-08-23 00:08 UTC, genessee-forgot-his-password-again commented
whenever i ran pirates and had admin-run interdictions, i usually had a five minute timer

it generally takes some time for attackers to figure out where the other ship actually is (if they're lucky, it takes about a minute) and then it takes another minute or so for everyone to prep up for an attack

20 seconds is, for the most part, nigh impossible unless you're incredibly lucky enough to land directly next to the ship you're attacking - imo, it's one thing to just be disorganized and unable to rally your troops in a timely manner, and it's another where you just get shit rng and are cheated out of a raid because of it

2022-08-23 00:15 UTC, ZephyrTFA commented
There is a giant blue beam from their ship to yours.

2022-08-23 01:55 UTC, MemedHams commented
> There is a giant blue beam from their ship to yours.

this doesn't change the fact that you're effectively forced to fight without support or retreat- since it's guaranteed that they'll be out of there, likely with your fighters offboard, before any meaningful fighting happens

beyond that, even getting on other people's ships in 20 secs is a *big* if- it'd require that they have an easily-accessible point of entry, and aren't actively taking point and defending the outside of their ship.

the meta you're encouraging is one of rapid high-destructiveness, high-lethality attacks, since that's the only way you'd reasonably be expected to take a decently crewed vessel in that timeframe. 

It also completely demolishes the idea of "surrender ye cargo" piracy rp standoffs that don't happen via. comms beforehand, since the time is so absurdly short that wordlessly attacking is pretty much the only option.

2022-08-23 02:05 UTC, Zevotech commented
> It also completely demolishes the idea of "surrender ye cargo" piracy rp standoffs that don't happen via. comms beforehand, since the time is so absurdly short that wordlessly attacking is pretty much the only option.

Pirates SHOULD be doing this, because this is ACTUALLY how pirates work.

2022-08-23 04:43 UTC, ZephyrTFA commented
> > It also completely demolishes the idea of "surrender ye cargo" piracy rp standoffs that don't happen via. comms beforehand, since the time is so absurdly short that wordlessly attacking is pretty much the only option.
> 
> Pirates SHOULD be doing this, because this is ACTUALLY how pirates work.

I'm going to have to ask that you actually read the PR contents.
The time has been changed, along with the entire method interdiction works.

2022-08-23 04:44 UTC, ZephyrTFA commented
Interdiction Start > Minigame where the ship can try to escape > Depending on how well they escape interdiction will last 30 or less seconds with 30 being the baseline.

2022-08-23 04:44 UTC, ZephyrTFA commented
The entire point of this being tested is so that I can adjust it as needed for balance

2022-08-23 04:44 UTC, ZephyrTFA commented
Nothing about this is set in stone.

2022-08-23 05:00 UTC, triplezeta commented
> > It also completely demolishes the idea of "surrender ye cargo" piracy rp standoffs that don't happen via. comms beforehand, since the time is so absurdly short that wordlessly attacking is pretty much the only option.
> 
> Pirates SHOULD be doing this, because this is ACTUALLY how pirates work.

theres plenty of time to make demands when you're interdicting them. in space. when both bridges are going to be fully staffed and able to attend comms.

2022-08-23 05:04 UTC, MemedHams commented
> Nothing about this is set in stone.

Zephyr, we understand that- that's why we're suggesting increasing the timer
having actually looked at the code
here
![image](https://user-images.githubusercontent.com/45698967/186072829-14b3d326-b99b-40ef-9acc-09d266d63326.png)
and here
![image](https://user-images.githubusercontent.com/45698967/186072976-1c07cb87-11fe-43f7-a333-0f8d34f45e3a.png)
and in a few other places
it seems like the max time caps out at 30 seconds with a perfect interdiction, and can be reduced by factors like poor relative vessel speed and higher distance
Is that right?

Because if so it seems like all the stuff being said is still relevant to those conditions, give or take ten seconds of leeway

Might be a good strategy to unbrake it a bit and give vessels overtaking with a speed advantage bonus interdiction time beyond 30
that'd definitely help, but it'd still be mean time to be working in and a half-equipped ghetto tech crew could easily use a variety of methods to stall it out and uncounterably prevent boarding in that period

2022-08-23 05:06 UTC, MemedHams commented
examples:
-RCD your only two airlocks/bolt exits
-drop/throw slipping items between your ships
-metal foam spam the space between vessels
-lube your front entryway
-Just Shoot At The Guys Coming To Your Ship and force them to take evasive action instead of trying to climb on your mobile starbase

any combo of these could make it functionally impossible to besiege a ship that can escape in sub-minute time

2022-09-15 01:50 UTC, closed without merging

2022-09-15 07:41 UTC, Calyxman commented
F

2022-09-15 09:43 UTC, MemedHams commented
stale bot kills again