New Ruin: The Beach Town
shiptest-ss13/Shiptest pull request #1572
Opened 2022-10-11 01:39 UTC by Bjarl

## About The Pull Request
Adds a new beach ruin, the abandoned beachside town
![2022 10 10-18 20 10](https://user-images.githubusercontent.com/94164348/194977185-0f35d08e-64c1-459d-94b2-ec6b66137753.png)
![2022 10 10-18 20 00](https://user-images.githubusercontent.com/94164348/194977192-0b93346e-cea0-4fb2-8b66-5ae7319ec3f1.png)
![dreamseeker_Ht2YcvyQbH](https://user-images.githubusercontent.com/94164348/194977254-d0b25aba-ec6b-4e8b-bad5-949a9961cf07.png)
![dreamseeker_KAB6kPSLrP](https://user-images.githubusercontent.com/94164348/194977259-561f8d97-962e-4545-a4b7-1637ad1a7156.png)

The town is an mostly empty place formerly devoted to tourism and the beloved art of "chilling out". Facets of the life of its inhabitants before their disappearance included drinking, grilling, and swimming off the coast of their fairly large beach. Many interesting things happened on the boardwalk, and a landing pad was present to allow for small ships to dock inside the town. 

The loot list is sparse here. I intend for this to mostly be a setpiece for roleplay instead of a loot pinata. There's a good selection of hydroponics seeds and gear, 2 full bar kits, basic kitchen equipment, an autolathe, a few PDAs, a lotta wood, and a jukebox. Also donuts.

- [x] Ruin spawns, nothing is out of whack that shouldn't be.

## Why It's Good For The Game
Continues the trend of making planets more good by adding more content

## Changelog

:cl:
add: An oddly empty town has been spotted on beach planets in the area. Check it out spacers. 
add: Random donut spawners, never eat the same donut two days in a row!

/:cl:

![dreamseeker_8Xe7Cuq6NH](https://user-images.githubusercontent.com/94164348/194977262-fb125315-2508-4022-9eda-5ed5078442c9.png)
![dreamseeker_SKJXeK9SOt](https://user-images.githubusercontent.com/94164348/194977268-b4efcd99-0896-4209-8b83-c61c086bda65.png)
![dreamseeker_6Ak0bNoVe5](https://user-images.githubusercontent.com/94164348/194977270-367aaf92-5d6d-4cd8-9827-eba99ec92080.png)

2022-10-30 06:22 UTC, SweetBlueSylveon commented
I'd like to see the areas. If you do that, and they aren't fucked, and the checks pass the gas, then we can look at TMing this.

2022-10-30 06:23 UTC, SweetBlueSylveon commented on code/game/area/areas/ruins/beachplanet.dm
> +//Beachside Town
Again try to cut these down.

2022-10-30 06:37 UTC, Bjarl commented
>I'd like to see the areas. If you do that, and they aren't fucked

top screenshot

2023-01-10 22:04 UTC, Latentish requested changes, later dismissed

2023-01-10 22:04 UTC, Latentish commented on _maps/map_catalogue.txt
> +		Tags = "No Combat", "Minor loot"
needs an atmosphere tag

2023-01-25 20:05 UTC, Zevotech commented
round 1272 where this was on a planet the sandstone room with the assistant statue had space tiles

2023-03-15 22:49 UTC, AverageUser67 commented
can you fix the sand and also glass tiles that show space

2023-03-15 23:43 UTC, Bjarl commented
No sorry that'd be too much work

2023-03-23 13:23 UTC, Bjarl commented
@Latentish please lift your requested changes, they've been addressed for a while.

2023-04-07 21:53 UTC, Latentish commented
Marg

2023-04-07 22:02 UTC, merged