5 new crates + new crate category
shiptest-ss13/Shiptest pull request #1576
Opened 2022-10-11 22:04 UTC by Bjarl

## About The Pull Request
Adds 5 new crates for purchase, 4 themed towards planetary gear, and 1 for general exploration use.
The Lava kit contains miniature extinguishers, heat goggles, 2 compact picks, and 60 lavaproof rods.
The Ice kit contains 2 compact picks, cold goggles, winter boots and coats, and cold goggles. 
The Jungle kit contains 2 compact picks, 2 hatchets, and 2 bottles of charcoal pills
The Beach kit contains 6 fake sunglasses, an assortment of shorts, and 2 compact picks. 
The Capsule kit contains 3 bluespace survival capsules. Price is 3000 total

I would love to expand this list, so if you have ideas on what to add to crates and how to balance them, throw em out

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
More things to buy from outposts that have a general purpose. It's hard to get a mining vendor so being able to purchase useful gear from it for a premium is quite useful. You straight up can't get the lavaproof rods without BEPIS and that's just a pain.

## Changelog

:cl:
add: A new category of exploration themed crates. Take a detour to an outpost and see if you'd benefit from buying any.
/:cl:

2022-12-03 18:22 UTC, Fikou commented on code/modules/cargo/packs/exploration.dm
> +					/obj/item/clothing/glasses/cheapsuns)
generalize the formatting of those lists like
contains = list(
	obj1,
	obj2,
	obj3,
)

2022-12-03 18:23 UTC, Fikou submitted a review, later dismissed

2022-12-03 18:23 UTC, Fikou commented on code/modules/cargo/packs/exploration.dm
> +	contains = list(/obj/item/pickaxe/mini,
generalize the formatting of those lists like
```
contains = list(
	obj1,
	obj2,
	obj3,
)
```

2022-12-03 18:47 UTC, ZephyrTFA commented on code/modules/cargo/packs/exploration.dm
> +					)
Don't use more than one tab, trailing comma, dont also indent closing parenthesis

2022-12-14 18:08 UTC, ZephyrTFA requested changes

2022-12-14 18:08 UTC, ZephyrTFA commented on code/modules/cargo/packs/exploration.dm
> +)
```suggestion
	)
```

2022-12-14 18:08 UTC, ZephyrTFA commented on code/modules/cargo/packs/exploration.dm
> +)
```suggestion
	)
```

2022-12-14 18:08 UTC, ZephyrTFA commented on code/modules/cargo/packs/exploration.dm
> +)
```suggestion
	)
```

2022-12-14 18:08 UTC, ZephyrTFA commented on code/modules/cargo/packs/exploration.dm
> +)
```suggestion
	)

```

2022-12-14 18:10 UTC, ZephyrTFA commented on code/modules/cargo/packs/exploration.dm
> +		/obj/item/stack/rods/lava/thirty
```suggestion
		/obj/item/stack/rods/lava/thirty,
```

2022-12-14 18:10 UTC, ZephyrTFA commented on code/modules/cargo/packs/exploration.dm
> +)
```suggestion
	)
```

2022-12-14 18:11 UTC, Bjarl commented
This is why I'm not allowed to code

2022-12-14 18:12 UTC, ZephyrTFA approved these changes

2022-12-14 18:18 UTC, merged