New Beach Ruin: Knight's Rest
shiptest-ss13/Shiptest pull request #1583
Opened 2022-10-21 02:02 UTC by Bjarl

## About The Pull Request
Adds the Knight's Rest Ruin to the beach spawning pool. 
Knight's Rest is a small vaguely castle shaped object with a grave holding a deceased knight inside of it. Those who are not inclined to grave robbing will find basic growing equipment, torches, and some clothing. Those who do rob graves will find the dead knight's KICKASS SWORD. 
It's more of a setpiece than an adventure but having more beach ruins isn't hurting yet.

![2022 10 20-17 38 20](https://user-images.githubusercontent.com/94164348/197092402-29531860-ced3-4285-b3f7-a3c274bfe118.png)
![dreamseeker_7l4t7gggot](https://user-images.githubusercontent.com/94164348/197092564-e868f636-9338-4aaf-aa4e-e8899cfdad3d.png)
![dreamseeker_iEdXdgwqMk](https://user-images.githubusercontent.com/94164348/197092661-c8383c85-4075-4767-8f98-bd571254c620.png)
![dreamseeker_PJJj9xgMrm](https://user-images.githubusercontent.com/94164348/197092672-1e91bb5b-bfde-493c-80e4-c415dd72d178.png)
![dreamseeker_7USXwcSxkc](https://user-images.githubusercontent.com/94164348/197092771-cb4adc0d-f4fe-4393-827b-58dcb75ffd5b.png)

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
More beach ruin variety.

## Changelog

:cl:
add: Roamers of beach worlds have reported a small fortification, surrounded by a serene grass field. Perhaps there's something to investigate there.
/:cl:

2023-01-10 22:00 UTC, Latentish requested changes, later dismissed
This needs a small change to the catalogue entry.
Otherwise this can be tm'd while it is passing.

2023-01-10 22:00 UTC, Latentish commented on _maps/map_catalogue.txt
> +		tags = "No Combat", "Medium Loot"
Needs an atmosphere value

2023-01-15 07:45 UTC, Latentish commented
![image](https://user-images.githubusercontent.com/55075747/212528947-eb899b94-ff8c-4b81-b044-1e95832778bb.png)
Btw you're using a weird grass as well. Ignoring the clowns, they lead to space. You want this one.
![image](https://user-images.githubusercontent.com/55075747/212528962-619909bd-6657-4ebf-bf4f-ca3a1b0df1f8.png)

2023-01-31 15:23 UTC, ZephyrTFA approved these changes

2023-02-01 05:09 UTC, Latentish submitted a review, later dismissed
> ![image](https://user-images.githubusercontent.com/55075747/212528947-eb899b94-ff8c-4b81-b044-1e95832778bb.png) Btw you're using a weird grass as well. Ignoring the clowns, they lead to space. You want this one. ![image](https://user-images.githubusercontent.com/55075747/212528962-619909bd-6657-4ebf-bf4f-ca3a1b0df1f8.png)

This along with every other ruin using these tiles, need to have proper beach planet asteroid tile subtypes.  Or an otherwise properly set up baseturf. I mentioned this in this prior post, but I should have made it as a request change.

2023-02-06 13:28 UTC, spockye approved these changes

2023-02-17 17:15 UTC, merged