CMM Expansion
shiptest-ss13/Shiptest pull request #1602
Opened 2022-11-07 05:06 UTC by retlaw34

## About The Pull Request
Some content to expand the CMM content in the game. It has been lacking, and might still be, but there is more to work with for mappers now.

NOTE: This does not touch any maps, this is more for mappers to mess with.

CM-5, smg that uses 9mm
![image](https://user-images.githubusercontent.com/58402542/200230046-f4b093cd-f9d2-44bc-9866-840efab2fb21.png)

GAL, DMR that uses 308
![image](https://user-images.githubusercontent.com/58402542/200230112-e2050e49-5de8-43b3-8102-5a159219ab2d.png)

CMM Patroller hardsuit, functionally similar to the security hardsuit
![image](https://user-images.githubusercontent.com/58402542/200230273-7d981cd4-824f-4df0-a714-a8d4d98f8076.png)

Sound effects ripped off [TGMC](https://github.com/tgstation/TerraGov-Marine-Corps) as usual

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

More content for mappers, admins, and players for a faction lacking in content.

## Changelog

:cl:
add: CMM weapons CM-GAL-S and CM-5
add: Minutemen now have their own backpack and satchel along with hardsuit
del: Removed old things
tweak: Winchester 308 FMJ is now simply .308
balance: rebalanced something
fix: Fixes the EBR
/:cl:

2022-11-18 22:11 UTC, genessee-forgot-his-password-again commented
immensely based

2022-12-03 18:25 UTC, Fikou requested changes, later dismissed

2022-12-03 18:25 UTC, Fikou commented on code/game/objects/items/storage/belt.dm
> +	new /obj/item/ammo_box/magazine/p16(src)
use a loop

2022-12-03 18:25 UTC, Fikou commented on code/modules/projectiles/boxes_magazines/external/rifle.dm
> +	icon_state = "ebr_mag-[hasammo]"
```suggestion
	icon_state = "ebr_mag-[!!ammo_count()]"
```

2022-12-03 18:25 UTC, Fikou commented on code/modules/projectiles/boxes_magazines/external/rifle.dm
> +	..()
you sure you dont wanna call parent?
also both of those reviews for the other mag too

2022-12-08 06:39 UTC, retlaw34 commented
Sorry for the delay, i'll get to this in a bit

2023-01-06 01:38 UTC, retlaw34 commented
![image](https://user-images.githubusercontent.com/58402542/210912101-b7764ce3-44c9-4a09-b661-63faa574c66b.png)

2023-01-18 01:31 UTC, Latentish commented
marg approved margtest mergery

2023-01-18 01:32 UTC, merged