Porting over Kryson's carpets.
shiptest-ss13/Shiptest pull request #161
Opened 2021-08-14 00:39 UTC by PetMudstone

## About The Pull Request

Ports over Kryson's carpets from https://github.com/tgstation/tgstation/pull/54612. Does not add the spawners nor any way to obtain them at the moment.

## Why It's Good For The Game
Carpets look pretty. Can be used later by mappers or by players. Also, Donk carpets are *integral* to Donk Co. RP.

## Changelog
:cl: Pet Mudstone, Kryson
add: Ported over
/:cl:

2021-08-14 19:18 UTC, martinlyra requested changes

2021-08-14 19:18 UTC, martinlyra commented on code/game/turfs/open/floor/fancy_floor.dm
> +
```suggestion

```

Superflous whitespace here. And that is it.

2021-08-14 19:26 UTC, martinlyra commented on code/game/turfs/open/floor/fancy_floor.dm
> +/turf/open/floor/carpet/executive
```suggestion

/turf/open/floor/carpet/executive
```

Try this

2021-08-14 19:51 UTC, ZephyrTFA commented
Check your line endings. Make sure they're consistent maybe?

2021-08-14 21:23 UTC, martinlyra commented
After #163 gets merged, run the CI again on this to get the green ticks. It is not done automatically whenever a PR has been merged for performance reasons. So just push an empty commit or trigger the CI manually to restart it.

2021-08-15 06:54 UTC, martinlyra approved these changes
Should be fixed! All you need to do now is to push a commit of whatever to restart the CI.

2021-08-15 16:13 UTC, merged