New Ruin: Singularity Research Lab
shiptest-ss13/Shiptest pull request #1612
Opened 2022-11-25 18:49 UTC by Bjarl

## About The Pull Request

Adds the Singularity Research Lab, formerly a cutting edge science station, now overrun with kudzu, it is a space ruin.

![2022 11 25-10 46 03](https://user-images.githubusercontent.com/94164348/204041197-027d9a73-8707-4a00-ad5c-1afcfeff13e0.png)
![2022 11 25-10 46 14](https://user-images.githubusercontent.com/94164348/204041200-98d1a2ac-112c-4c4f-b1ff-d0c1e5a59e81.png)
![2022 11 25-10 46 06](https://user-images.githubusercontent.com/94164348/204041203-4e84a947-8ec9-476d-ae8e-aa9bc17c101a.png)

The two areas of note are the singularity reactor, which is assembled, and would just need a hand if someone were to want to start it, and the research lab. The Research lab contains the fruits of the now deceased science staff's labors, assorted energy weapons. Unfortunately, it also contains the deceased science staff.
![dreamseeker_HFLqhdKLV5](https://user-images.githubusercontent.com/94164348/204038725-1dd396cd-4961-40e1-bd7a-b60b69a33eaf.png)
Other areas of the base were not so lucky, and are thoroughly infested
![image](https://user-images.githubusercontent.com/94164348/204039090-c85eb551-af84-4000-b1d9-14b15c987680.png)
The engineering team attempted to hold back the vines, and quickly discovered that fire was not sufficient.
![dreamseeker_IrJikGDXKw](https://user-images.githubusercontent.com/94164348/204039133-273f0a19-c9b7-467e-a06a-05e0a951e4e6.png)
And what used to be the recreation area is completely gone

Notably, the hangar is empty. I plan on making a patch to put a subshuttle inside it once that rolls around.

Notable loot includes:
3 energy SMGs
3 Flamethrowers
The Ion Projector, a self charging Ion weapon.
An Antique Laser
2 Energy PDWs
2 Accelerator Laser Cannons
4 engineering hardsuits
An engineering lathe and circuit imprinter
A particle accelerator
A singularity generator
6 emitters
1 energy shotgun
Kudzu Seeds
Basically Everything You'd Need For an R&D Set Up
A sense of pride and accomplishment

I feel like this has some rough spots but I've got no idea where to start, so into the review -> testing -> feedback process it goes

- [x] The ruin spawns when the spawn ruin verb doesn't runtime.
## Why It's Good For The Game
More ruin variety. This one spawns in space and does a few things that I haven't seen yet. Mainly a singularity, cool semi-hidden asteroid base that could in theory, be turned into a player lair.

## Changelog

:cl:
add: An abandoned Nanotrasen Asteroid Facility has been spotted in the area. Salvage teams are advised to steer clear, or at least bring a knife.
add: kudzu zombie subtype. 
fix: vent iconstates.
/:cl:

2023-01-12 05:25 UTC, Latentish commented on _maps/map_catalogue.txt
> +		Tags = "Boss Combat Challenge", "Major Loot", "Bad Shelter", "Shelter"
Remove "Bad Shelter". Bad shelter would be like if you have a building with no air on a jungle planet. Reverse of shelter.

2023-01-12 07:37 UTC, Latentish commented on code/game/area/areas/ruins/space.dm
> +//Singularity Lab
Try to cut down on areas.

2023-01-12 07:38 UTC, Latentish commented
I like ruin. I don't have much to say about it really. No complaints other than needing to cut down on areas and fixing the catalogue entry.

2023-01-18 21:46 UTC, Apogee-dev commented
Probably needs some indestructible walls around some loot areas to minimize cheesing with things like jackhammers, plasma cutters, and mechs

2023-01-31 15:24 UTC, ZephyrTFA approved these changes

2023-02-01 05:22 UTC, Latentish approved these changes
I've been waiting for Bjarl to decide they were done with this, and Apogee suggested indestructible areas, but having observed multiple people run this I can say that busting into different places on this is satisfactory and still pretty deadly overall. So I'm going to approve this anyway.
I'd like to merge this, if it's not ready I'd ask you to close or draft it.

2023-02-01 05:51 UTC, Bjarl commented
It has consistently reproducible issues with proper spawning that I'm hoping tmt can give more insight on.

2023-04-07 21:52 UTC, Latentish commented
MERGEMA WHAT IS MERGEMA

2023-04-12 06:56 UTC, spockye requested changes
replace the space cash with the new money, and it's merging'o'clock

2023-04-12 14:13 UTC, spockye approved these changes

2023-04-12 14:19 UTC, merged