Light Onehalf Rework
shiptest-ss13/Shiptest pull request #1613
Opened 2022-11-27 21:17 UTC by Bjarl

## About The Pull Request
![2022 11 27-13 10 05](https://user-images.githubusercontent.com/94164348/204159847-97540351-a40f-4ca9-add2-24b70062d2cd.png)
![2022 11 27-13 09 59](https://user-images.githubusercontent.com/94164348/204159849-f61a6a3c-5a88-4daa-8d4d-c720a97e0151.png)

I saw the Onehalf ruin during uptime and it had broken floor tile sprites. This lead to a small rework and expansion of the ruin. Now it has things like firelocks, more space, no tiles that say "FIX ME", and a few enemies to fight.
Loot has been marginally increased, with two Minebots and a telecomms relay being present on top of what the ruin previously contained. There is also a research paper to be found on top of the terrible pipe setup. Apparently it warranted investigation.

- [x] The ruin will load properly.

## Why It's Good For The Game
It's a little bit more content added onto a ruin that might not have needed it, but did need to not have FIX ME tiles plastered across it.

## Changelog

:cl:
add: DK Excavator 453 has been marginally expanded. It has things to fight now!
/:cl:

2023-01-31 15:33 UTC, ZephyrTFA approved these changes

2023-02-01 05:25 UTC, Latentish commented
![image](https://user-images.githubusercontent.com/55075747/215958505-b35d3502-15e6-4467-b855-c79bc3fc3155.png)
![image](https://user-images.githubusercontent.com/55075747/215958610-23dd1e7a-55c9-4d11-835d-29440a095d35.png)
Fix this please.

![image](https://user-images.githubusercontent.com/55075747/215958768-550ea2a4-68bf-434f-a37f-809189e8f64e.png)
Does this have an area?

2023-02-01 05:26 UTC, Latentish requested changes, later dismissed
![image](https://user-images.githubusercontent.com/55075747/215958505-b35d3502-15e6-4467-b855-c79bc3fc3155.png)
![image](https://user-images.githubusercontent.com/55075747/215958610-23dd1e7a-55c9-4d11-835d-29440a095d35.png)
Fix this please.

![image](https://user-images.githubusercontent.com/55075747/215958768-550ea2a4-68bf-434f-a37f-809189e8f64e.png)
Does this have an area?

2023-02-01 05:45 UTC, Bjarl commented
both fixed

2023-02-17 16:23 UTC, merged