New Space Ruin: Space Mall
shiptest-ss13/Shiptest pull request #1624
Opened 2022-12-11 19:07 UTC by goober3

Adds a Space Mall ruin (for space), an independent space shopping centre (infested with spiders).

Featuring a Fuckton™ of (notable) loot: -9mm ammo box + x2 9mm pistol magazines 
-Commander pistol
-x2 disablers
-Double-barreled shotgun + rubbershots
-Segway
-Condimaster
-Hi-tech janitor appliances
-<3500 credits
-Jukebox
-x1 Advanced medical kit + x2 Toxin kits
-Bluespace bodybag
-Bluespace RPED
-Randomly assorted rare stock parts
-Chem dispenser (board)
-Supercooled water vapor canister (173.15 kelvin)
-x2 Thermomachines
-A cheap phrasebook for visiting Kalixcians
-Autolathe
-Service techfab
-Mining vendor refill
-x2 jaws of life + experimental welder + hand drill
-x1 Comically Large Crowbar

## All the SCREENSHOTS

![smfinalsdmm](https://user-images.githubusercontent.com/118859017/206923291-736b6340-d7ad-410e-b73e-dbf46d8b4f4c.png)

![smfinalareas](https://user-images.githubusercontent.com/118859017/206923302-06db65a8-f066-4426-a8eb-d3330e233d45.png)

![spacemallfinal](https://user-images.githubusercontent.com/118859017/206923318-0c292d22-c086-434d-9153-b526de1c8c1e.png)

- [yes!!!] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

More Ruins ! ! !

## Changelog

:cl:
add: A new space ruin
/:cl:

2022-12-11 19:49 UTC, ZephyrTFA commented
that's a lot of loot, for n relatively little danger

2022-12-11 19:53 UTC, Zevotech commented
add a giant enemy spider

2022-12-11 19:54 UTC, goober3 commented
good point. i'll add more eggs, they spawn a fuckton of spiderlings. and maybe remove the mining vendor.

2022-12-11 19:57 UTC, Zevotech commented
make sure you dont use the ghostrole spider eggs

2022-12-11 20:01 UTC, Sun-Soaked commented
> make sure you dont use the ghostrole spider eggs

honestly? one or two of these might be interesting, we were discussing the possibility of having more player based defenses in ruins a while ago

might lead to funny rp stuff too

2022-12-11 20:03 UTC, goober3 commented
guh. do we even have ghostrole spider eggs here? cause i'd totally add them if we did

2022-12-11 20:08 UTC, MemedHams commented
> guh. do we even have ghostrole spider eggs here? cause i'd totally add them if we did

my intuition says definitely but they might be antag-coded due to being connected to the old spider midround antag

2022-12-11 20:34 UTC, PiperDoots commented
The one thing I feel this could really benefit from is ghost roles. Would fit well within the concept and could bring a lot more life to it.

2022-12-12 02:02 UTC, Valorium-RB commented
At risk of advocating for bloat, it could be neat if there were two variants of this ruin - one infested with spiders and more run-down, and another which is clean, new and staffed with several ghost roles.  Failing that, spiderling spawners would be fun!

2022-12-12 22:57 UTC, goober3 commented
I will consider a Clean™ version when I figure out ghost roles and blacklists (and if the maptainers approve). thank you for the suggestion

2022-12-12 23:35 UTC, Bjarl requested changes
![StrongDMM_JtkYQJCT6T](https://user-images.githubusercontent.com/94164348/207181267-e5934c16-aba1-4c25-a86c-fe226e51f31e.png)
This area needs some visible damage, more webs, generally to be junked up more. 
![StrongDMM_oJ5Hyg8RnX](https://user-images.githubusercontent.com/94164348/207181344-f7dd9fc1-2193-41b8-ad52-d69c94bfe2ac.png)
Ditto for here
![StrongDMM_G64fqjjnTe](https://user-images.githubusercontent.com/94164348/207181377-70d7b07d-4bfc-4b73-89fd-f5c02fde8106.png)
just the damage here.
![StrongDMM_eYAkYrV4FY](https://user-images.githubusercontent.com/94164348/207181496-e318ddf1-f1ae-4ca8-8d1c-84918f08b148.png)
Get a real tile under the SSU. I recommend tech/grid or whatever you feel fits there.
![StrongDMM_o5UFXHv5sB](https://user-images.githubusercontent.com/94164348/207181573-05e8d7c9-9e66-4069-bbb5-73f996f5d249.png)
I recommend putting corpse spawners in here, along with some blood, and spiders. Junk it up if you do that. 
![image](https://user-images.githubusercontent.com/94164348/207181679-bde0e435-d516-4c62-8437-7afbab2fa959.png)
I would put a spider in here too

You should seriously consider swapping out airlocks for airlock assemblies in any area the spiders are supposed to control. Damage helps convey danger. 

![StrongDMM_pQSctMQZBg](https://user-images.githubusercontent.com/94164348/207181846-80360722-d2ed-4b73-8ce9-fc7169a3f2e9.png)
This room needs decal work. 

I'd mark the exact line for these but the diff isn't loading. 
![StrongDMM_TbAEXdbIiK](https://user-images.githubusercontent.com/94164348/207181999-4774f80c-b054-4f25-bd0c-0fe52e00196a.png)
They won't work well. Use one of the subtypes instead.

![StrongDMM_AhtA4OJY9y](https://user-images.githubusercontent.com/94164348/207182109-afcc9a39-b2fe-49dc-8f15-44aa2ebd2f08.png)
I would not put a magical SMES here. They're best hidden away to power whole ruins instead. Swap it out for a normal SMES and varedit it so it starts with a full charge.


I'm gonna load it locally and see if there's anything that catches my eye there.

2022-12-12 23:35 UTC, Bjarl commented on code/game/area/areas/ruins/space.dm
> +/area/ruin/space/has_grav/spacemall/dorms
could you fold this area into the main one?

2022-12-12 23:43 UTC, goober3 commented on code/game/area/areas/ruins/space.dm
> +/area/ruin/space/has_grav/spacemall/dorms
wdym?

2022-12-12 23:46 UTC, Bjarl commented
![dreamseeker_nRE0dCPCOT](https://user-images.githubusercontent.com/94164348/207182950-c0a639d6-8b91-4dee-bf35-e6d89ded7407.png)
Use a visible pipe here so it's not hidden by the floor.

![dreamseeker_jfy8kIni4M](https://user-images.githubusercontent.com/94164348/207183030-15f10821-e5da-45d5-b862-e9809a14c453.png)
The bathrooms are devoid of light. 

![image](https://user-images.githubusercontent.com/94164348/207183563-afc889d9-571e-457c-adae-f92be4e4ebf1.png)
This area just feels fairly empty. What I'd recommend doing is having the "Lounge" area immediately accessible, putting more things in it, and then having the rest of the dorms behind that. Maybe give it a check in counter and make it a space hotel. 

![image](https://user-images.githubusercontent.com/94164348/207183758-09280a9f-55fe-4635-b20d-788f5289c461.png)
You have space tiles under these windows here. 

I'd also recommend adding some girders to maint.

2022-12-12 23:46 UTC, goober3 commented
Oh God Wait I Forgot The Firelocks

2022-12-12 23:47 UTC, Bjarl commented on code/game/area/areas/ruins/space.dm
> +/area/ruin/space/has_grav/spacemall/dorms
Either expand the dorms enough contentwise to need their own area def, or remove the area def and have the dorms be under the /spacemall generic one.

2022-12-12 23:48 UTC, goober3 commented
thank you for the review, will be reviewing your review. and fixing the Ruin. thank you

2022-12-12 23:48 UTC, Bjarl commented
![image](https://user-images.githubusercontent.com/94164348/207184082-9d6d857e-f3ab-4479-93ac-a7b03646d7e3.png)
It seems like the spiders also will eat Bass Pro. Maybe use tinted windows for that store.

2022-12-12 23:49 UTC, goober3 commented
I can't believe they would do that

> ![image](https://user-images.githubusercontent.com/94164348/207184082-9d6d857e-f3ab-4479-93ac-a7b03646d7e3.png) It seems like the spiders also will eat Bass Pro. Maybe use tinted windows for that store.

I can't believe they would do that

2022-12-13 00:25 UTC, SweetBlueSylveon commented
> At risk of advocating for bloat, it could be neat if there were two variants of this ruin - one infested with spiders and more run-down, and another which is clean, new and staffed with several ghost roles. Failing that, spiderling spawners would be fun!

I really don't think we should have ruin alts unless the alts are like, phenomenal

2023-01-17 23:52 UTC, goober3 commented
Oops My Areas

2023-01-17 23:53 UTC, goober3 commented
Okay Nevermind. everything is fine. this merge conflict has been FIXED.

2023-01-26 14:53 UTC, Bjarl approved these changes

2023-01-26 14:54 UTC, merged

2023-02-06 02:22 UTC, ArdentSpark commented
I found something strange with spider behaviour, in that they really really really do not like stepping into or sometimes attacking tiles with windoors or railings. this has a notable effect on one area in particular 
![image](https://user-images.githubusercontent.com/82124989/216868346-dda71a6e-8cb4-4182-854e-f4283cab09c3.png)

The spiders walk up to it, get confused and flee without attacking the windoors.

It can be gamed pretty hard! Just raising in case this is something you'd want edited, as it can be used to flee very effectively from the engineering horde of spiders