fixed the lawnmower and addet it to the outpust
shiptest-ss13/Shiptest pull request #1657
Opened 2022-12-30 17:06 UTC by ritorizo

## About The Pull Request

This PR add a lawnmower to the outpust (not the emaged one altough it could be emaged) to make building more about building and less about clicking grass for 40 minutes.

- [X] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

Colony building is fun but removing the grass is unnecessarily painfull and long.
## Changelog

:cl:
add: The lawn mower is now buyable at the outpust for 800 credits.
fix: Fixed the lawnmower not destroying some flora because of  a typo.
/:cl:

2023-01-18 19:06 UTC, MarkSuckerberg requested changes, later dismissed
Just a minor stylistic change, everything else is good

2023-01-18 19:06 UTC, MarkSuckerberg commented on code/modules/vehicles/pimpin_ride.dm
> +	desc = "Equipped with reliable safeties to prevent <i>accidents</i> in the workplace. The safety light is on"
```suggestion
	desc = "Equipped with reliable safeties to prevent <i>accidents</i> in the workplace. The safety light is <b>on</b>."
```

2023-01-18 19:06 UTC, MarkSuckerberg commented on code/modules/vehicles/pimpin_ride.dm
> +	desc = "Equipped with reliable safeties to prevent <i>accidents</i> in the workplace. The safety light is off"
```suggestion
	desc = "Equipped with reliable safeties to prevent <i>accidents</i> in the workplace. The safety light is <b>off</b>."
```

2023-01-19 17:06 UTC, ritorizo commented
done

2023-01-21 17:55 UTC, merged