Heron- Class!
shiptest-ss13/Shiptest pull request #1670
Opened 2023-01-07 00:13 UTC by spockye

## About The Pull Request

![2023 01 06-03 07 34](https://user-images.githubusercontent.com/79304582/211120227-fdbce9c9-516e-484b-969a-7033582d335c.png)

![image](https://user-images.githubusercontent.com/79304582/211120744-02f54294-6f8b-4bfd-9904-e6f6df9792d8.png)

This PR adds the Heron-Class Star Dreadnaught (ADMINSPAWN ONLY)!!! It's a gigantic Nanotrasen Vessel, containing a Dropship, a Mechbay, and a full Emergency Response Team!

I created this ship as a kind of "opposing force" to the Twinkleshine, though it would probably heavily differ, in use. 
while it has less soldier capacity, less combat gear, and less medical equipment, it makes up for it with its Marauder mech, Functional"tm" Supermatter engine, and its state-of-the-art, totally radical, dropship. 

the crew consists of:
___
- 1x Captain (Centcom Officer)
- 1x First Officer (hop)
- 1x HOS
- 2x Pilots (for the dropship)
- 1x Security Officer (Internal, actual Security work)
- 6x ERT Officers 
- 1x Mech Pilot
- 2x Engine Technicians (Engineers)
- 1x Roboticist
- 2x Medical workers (Paramedic and Medical doctor)
- 1x Atmos tech
- 2x Cargo Crew (quartermaster and cargo tech)
- 1x Cook
- 1x Janitor
____

- [ ] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
More big ships for admins and players to have fun with is good!

## Changelog

:cl:
add: adds the Heron Class Dreadnaught
/:cl:

2023-01-07 00:16 UTC, MemedHams commented
<img width="789" alt="Screen Shot 2023-01-06 at 7 15 17 PM" src="https://user-images.githubusercontent.com/45698967/211120920-b4a9f985-6ce7-480b-93d4-a5a65b773758.png">
criminal behavior detected. Deploying memetic kill agents

2023-01-07 00:18 UTC, spockye commented
> <img alt="Screen Shot 2023-01-06 at 7 15 17 PM" width="789" src="https://user-images.githubusercontent.com/45698967/211120920-b4a9f985-6ce7-480b-93d4-a5a65b773758.png">
> 
> criminal behavior detected. Deploying memetic kill agents

i affirm that im going to find out where you live, and mail you large amounts of packages containing air generating devices, and dust

2023-01-07 00:19 UTC, MemedHams commented
I could be a Dust Mite for all you know. Maybe you'd be feeding me for years. Didn't think about that did you huh???

2023-01-07 05:22 UTC, Bjarl commented
![firefox_7Kgbb4Ookf](https://user-images.githubusercontent.com/94164348/211132572-982c3c39-7595-420a-babf-b8e6d6c59109.png)
Whoever did this is evil


Ping me on the discord for a review tomorrow.

2023-01-13 19:54 UTC, Bjarl requested changes
The ship doesn't always spawn. 
![dreamseeker_t6Ctu3boja](https://user-images.githubusercontent.com/94164348/212397271-b83f0fe3-8f54-4590-aab9-bcc4294a2f20.png)
needs a bypass so people don't feel obligated to pull gasses out, I'd do something like...
![StrongDMM_ncccgB5ozX](https://user-images.githubusercontent.com/94164348/212397465-e32e458d-fefc-4d4e-ad96-509f1fe03bb9.png)
![StrongDMM_1oc0AgM0Ed](https://user-images.githubusercontent.com/94164348/212397530-3d620df6-cb49-4ef9-973a-86eb785a4856.png)
Take the shutters out of the walls
![image](https://user-images.githubusercontent.com/94164348/212397641-fc7de8c5-b5e3-4a00-98d7-71e674695cfb.png)
swap the upper airlock for a glass one, put an air alarm in there, like the screencap.
![image](https://user-images.githubusercontent.com/94164348/212397930-a76e9626-cb6f-4d05-a665-ed34ecda6bb7.png)
the holopad is cute, but any callers will be offset from it.
![StrongDMM_cwOMY1YhMJ](https://user-images.githubusercontent.com/94164348/212398022-d01e2625-bb30-47ae-a701-d80a2fb2262c.png)
toss a button on the inside of the cargo area, so you can't just trap people in there
![dreamseeker_5QdB05PHD3](https://user-images.githubusercontent.com/94164348/212398144-f730dabf-61a4-4787-9226-5e79125cafab.png)
minor decal melding, if you can figure out a way to make it have less of that, that'd be bitchin
![image](https://user-images.githubusercontent.com/94164348/212398278-3fde7266-2080-4cf8-b3e6-9b8c2f06de11.png)
Give them some suit variety, preferably to match the variety in roles (as mentioned in file review).
![dreamseeker_bbIM4nukDg](https://user-images.githubusercontent.com/94164348/212398639-62fa223c-f48b-443e-963b-464854d9bcb0.png)
Decal merging
![StrongDMM_pPcmAw8Im9](https://user-images.githubusercontent.com/94164348/212398822-bf7211cc-2bdb-4ca6-b157-478c68e46b0c.png)
Give the hardsuit it's own name, clean the captain's bathroom.
![dreamseeker_iKe6DYCQQH](https://user-images.githubusercontent.com/94164348/212398913-8fe78700-8926-47ca-9946-390ee05315dc.png)
You should make this a sprite instead of pixelshifting 3 together.
![dreamseeker_HXgU3O80NQ](https://user-images.githubusercontent.com/94164348/212398990-2d16ddba-d930-4555-a26f-e514fa3a7fb0.png)
You can just pull the medals off the wall, I'd recommend using a /structure for that instead of the items.
![dreamseeker_BhfeS2G2fg](https://user-images.githubusercontent.com/94164348/212399050-4f8b3a94-29ec-46c7-ba3d-65fc3a67991f.png)
James (59)
![StrongDMM_bGwmbM2Q6L](https://user-images.githubusercontent.com/94164348/212401459-2aa988e0-8885-4b1f-b423-0f0b15cdc833.png)
I would turn this area into a proper like.. Checkpoint?
![StrongDMM_2T3xlzUYH9](https://user-images.githubusercontent.com/94164348/212401590-c6913db0-39d6-4870-b264-a43275f407dc.png)
For a big ship that I'm sure will be seeing a decent bit of downtime, there's just not enough of a crew area. I'd push it out into the hallway and giving them a bit more of a lounge - chill space.
![StrongDMM_o4WEgmCOPs](https://user-images.githubusercontent.com/94164348/212403423-6015d0d2-df31-4905-b9b0-624c7ee03ed1.png)
You're gonna need another vent here
![StrongDMM_rgI5lzXZ3o](https://user-images.githubusercontent.com/94164348/212403775-1e82fa08-7134-42d4-a19c-6c6dbc37ab51.png)
Add some markings for the orange pipes here.
![StrongDMM_MlDYSIdeGv](https://user-images.githubusercontent.com/94164348/212405873-7aaa4217-74f1-4a9c-a0ad-1fdaa3b8ebd1.png)
Same deal with the cafe, it could stand to eat into the hallway a bit
![StrongDMM_k0TGMBV1ag](https://user-images.githubusercontent.com/94164348/212406019-6f4429d4-58b0-4dd5-805e-bb021564a37c.png)
This airlock needs another vent too
![StrongDMM_DdCOQ0Zgha](https://user-images.githubusercontent.com/94164348/212406140-a0768643-6784-4fdd-bf36-f1092dc4ed46.png)
Give the AI a blast door or shutters tbh ngl
![StrongDMM_4sKaa4EDZF](https://user-images.githubusercontent.com/94164348/212406226-6ad1ec3c-8978-4465-8f18-269577e5caaf.png)
Box reflector in the middle, they need it if all emitters are gonna be firing.

I'm sure there'll be more but I'm feeling map fatigue, so I'll give another go over once you do all this up

2023-01-13 19:54 UTC, Erikafox commented on _maps/configs/heron.json
> +{
this file needs to be renamed to fit into the schema

2023-01-13 19:54 UTC, Erikafox commented on _maps/configs/heron.json
> +			"slots": 6
I'd divide this down into having at least an engineering and medical ert fellow too.

2023-01-13 19:54 UTC, Erikafox commented on code/game/area/ship_areas.dm
> +
commenting here as a reminder, no need to do anything right now

2023-01-13 19:54 UTC, Erikafox commented on code/modules/jobs/job_types/captain.dm
> +	name = "Captain (Nanotrasen)"
Ping a lorehead for a better name here. The centcomm clothes tell me they're a bit above a mere Captain.

2023-01-13 19:54 UTC, Erikafox commented on code/modules/jobs/job_types/cargo_technician.dm
> +
I'm starting to think we need to just wire up a pilot job.

2023-01-13 19:54 UTC, Erikafox commented on _maps/configs/heron.json
> +	"enabled": true
set false for adminspawn.

2023-01-14 02:28 UTC, spockye commented on code/modules/jobs/job_types/captain.dm
> +	name = "Captain (Nanotrasen)"
changed to Fleet Captain!

2023-01-14 02:29 UTC, spockye commented on _maps/configs/heron.json
> +			"slots": 6
it now has one ERT Medical Officer
and one ERT Engineering Officer
both with their respective equipment on spawn

2023-01-19 15:25 UTC, Bjarl commented
![image](https://user-images.githubusercontent.com/94164348/213482295-f3846cbf-c618-481e-96aa-d3bd98bf66fb.png)
If you really wanted the medals to look fancy, you could layer a notice board under them.

2023-01-31 15:34 UTC, ZephyrTFA approved these changes

2023-02-01 06:05 UTC, Latentish commented
I need to be able to see your area layout.

2023-02-01 06:11 UTC, Latentish commented
Does that droppod actually detach?

2023-02-01 08:34 UTC, spockye commented
> Does that droppod actually detach?

not at the moment. waiting for subshuttles to get merged

2023-02-06 01:29 UTC, Bjarl commented
drafted like all other subship reliant prs

2023-03-31 23:00 UTC, goober3 commented
north side cargo windoor is access locked!

2023-04-25 14:49 UTC, Bjarl submitted a review, later dismissed
Needs an exterior subshuttle port

2023-05-09 09:37 UTC, spockye commented
ready for re-review

2023-05-13 16:49 UTC, Addust commented
STINKY nontitanium window, replace or i will send you to god with the hyena horde
<img width="215" alt="image" src="https://github.com/shiptest-ss13/Shiptest/assets/80979251/347c3c78-61e4-4e80-aca3-ac2bccc98c80">

2023-05-21 14:26 UTC, spockye commented
stop failing ;(

2023-05-26 17:16 UTC, Addust commented
voidcrew beat you to it man

2023-05-29 20:20 UTC, Merlin1230 commented
weird error I found loading up this branch for shits and giggles, this ship upon loading immediately deletes itself
![image](https://github.com/shiptest-ss13/Shiptest/assets/76177064/3709d498-2d86-4e4a-832f-0a476367d8b4)
![image](https://github.com/shiptest-ss13/Shiptest/assets/76177064/6a773fb6-dde7-4acc-a94c-8b202486c6c3)
no clue why, doesnt seem to happen with other ships, but thought I would bring it up

2023-05-29 20:44 UTC, spockye commented
yea, happens on my side aswell... i'll see if i can figure out why

2023-05-29 21:48 UTC, spockye commented
seems like it's fixed, unable to reproduce it

2023-06-29 12:24 UTC, spockye commented
Drafted until im back

2023-07-14 19:09 UTC, Imaginos16 commented
they never came back.......................

2023-07-23 19:47 UTC, spockye commented
Erika TRAPPED ME for over a week. I'll get on fixing this now

2023-08-29 22:24 UTC, goober3 requested changes
![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/413aae5c-4483-4f99-abd9-ffb665eb2a56)
![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/7de5e660-6a1d-44df-8ed8-ec280cba30ed)
intercoms need pixel shifting

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/709ce96d-7101-475b-8d28-83aa9d1d37d3)
these walls need to use the new wall sprites or be replaced.

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/493e37d7-8f48-45c5-870f-2dbdb3ef8ade)
unrotated shutters

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/966b75c0-1a11-4a8c-911b-828e98cfff87)
poster light

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/169632b8-659c-4cbf-9e55-68cb556ffdb9)
unconnected wire in the emitter room.

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/06368de5-707e-49f9-aa43-b537375f7809)
none of these emitters will reflect into the SM like this! please replace the reflectors with reflector boxes, or remove the outer emitters.

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/60783f87-af6d-42ad-babb-036c4778a27b)
this radiation closets will get shoved out of place quite easily!! consider securing them, somehow.

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/45c76214-3ddd-4a33-9d40-bb8af539f4fc)
i'd rather these high security doors be replaced with something else, for as long as they lack anywall sprites.

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/0bad5db5-aea6-449f-99f7-08073a347c47)
the inner windoor on the desk here should be access restricted.

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/68fdae3e-7b33-4899-ba16-371bc0c8bf71)
this looks nice but please don't pixelshift holopads!! 

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/117adfc7-b1e1-479b-a552-dd178cced432)
this room needs a vent & scrubber.

this ship still needs tags & a description!
every area needs a light switch. (this applies to the shuttle, too)
please replace the exterior windows with non-spawner versions.

2023-08-29 22:24 UTC, goober3 commented on code/game/area/ship_areas.dm
> +
^^ remove this area! we now have ship/hangar fulfilling the same role.

2023-09-04 20:29 UTC, meemofcourse commented on _maps/shuttles/shiptest/nanotrasen_heron.dmm
in the subshuttle dock, you are using area/hangar, and this causes an immediate sgt

2023-09-05 13:34 UTC, spockye commented on _maps/shuttles/shiptest/nanotrasen_heron.dmm
Ill get that fixed in a day or two

2023-09-14 23:17 UTC, goober3 approved these changes

2023-10-15 15:04 UTC, goober3 commented
good! i'd nitpick this more but this ship been in the oven for long enough.

2023-10-15 16:27 UTC, merged

2023-10-18 02:09 UTC, Doubleumc commented
Emitter reflectors start oriented such that they will reflect back at the emitter, destroying it.

No SM monitor console.