Cepheus-Class Mech Carrier! (CMM)
shiptest-ss13/Shiptest pull request #1685
Opened 2023-01-13 12:36 UTC by spockye

## About The Pull Request
This ship adds the Cepheus-Class Mech Carrier! 

![2023 01 13-13 19 22](https://user-images.githubusercontent.com/79304582/212318856-ffaa2b35-4240-4a5b-8630-73f9b0d38224.png)
____

<details>

<summary>Image Dump</summary>

![image](https://user-images.githubusercontent.com/79304582/212320278-1a3547a6-d81a-4131-a0da-f4d58fc7a458.png)

![image](https://user-images.githubusercontent.com/79304582/212320336-3f42e9aa-6b9c-4926-bb49-2309873a9a60.png)

![image](https://user-images.githubusercontent.com/79304582/212320399-27504bab-17f1-4d86-9551-fffb8143c371.png)

![image](https://user-images.githubusercontent.com/79304582/212320492-681e78d8-2c33-496b-ac1b-8d29f393f579.png)

![image](https://user-images.githubusercontent.com/79304582/212320568-1ae54a7d-c217-4efc-bca6-336892d465ee.png)

![image](https://user-images.githubusercontent.com/79304582/212320613-16d41c2c-421a-45f4-96e5-7849fec4f886.png)

</details>

_____

it was first put into service a few years after the initial Xenomorph hives started cropping up om CMM worlds. While originally being made in response to Mech-equipped pirates, and exploration, it quickly got repurposed to fight the Xeno menace With its Sealed mechs. 

In recent years the need for the ship has declined with the production of specialized ships and better-equipped marines. Due to this, most of the vessels of its kind have fallen into disrepair, and are instead serving as stands in museums, or low-risk patrolling.

The in-game ship, while still in active duty, has fallen into slight disrepair, with Funds from central coming less and less frequently. This has led to the ship becoming mostly self-sufficient, relying on trading with other ships, and exploring/salvaging. 

the main equipment of the ship, would be the mechbay, and the machinery inside. They come equipped with a circuit imprinter, mech fabricator and a Security lathe, for printing weapons, and ammo for the Mechs. The armoury is also quite well stocked.
it does however in turn, lack quite a bit in medical equipment, and mining equipment (outside of mechs)

Crew:
1x Captain
2x Minuteman
2x Mech pilot
1x Roboticist
1x Engineer
3x cadet

Weapons: 3 m1911's / 1 cycler shotgun / captains Revolver (heavily limited on ammo)

- [ ] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
 While cmm's ship rooster has been increasing, the removal of the Carina left a vacant spot for a carrier-esque ship. This ship fills that niche!

## Changelog

:cl:
add: Cepheus class
add: Minutemen Mech pilot job
add: Minutemen Roboticist job
/:cl:

2023-01-13 17:31 UTC, Valorium-RB commented
I signed off on this, lore-wise.

2023-01-17 18:28 UTC, Bjarl reviewed
map review later

2023-01-17 18:28 UTC, Bjarl commented on _maps/shuttles/shiptest/minutemen_cepheus.dmm
> +	desc = "Supposedly a direct line to Nanotrasen Central Command. It's not even plugged in.";
Minutemen ship, Nanotrasen?

2023-01-18 03:59 UTC, Apogee-dev commented
Now that some more CMM content has been merged, could you go ahead and replace relevant items with their new CMM equivalents? examples would be the cycler shotgun -> CM-15, ripley -> CMM ripley, and so on.

2023-01-19 14:49 UTC, Bjarl reviewed
looks good for tm

2023-01-20 18:31 UTC, Bjarl requested changes
Some doors should get names

The ship needs to not fly sideways

2023-01-31 15:34 UTC, ZephyrTFA approved these changes

2023-01-31 16:50 UTC, Bjarl commented
Did you fix it flying sideways

2023-02-06 01:27 UTC, Bjarl commented
once it doesn't fly sideways and has a mech disk it's good to go.

2023-02-06 01:27 UTC, Bjarl approved these changes

2023-02-09 14:44 UTC, Bjarl commented
I vaguely recall seeing it fly the right direction yesterday.

2023-02-09 14:44 UTC, merged