The Crashed Starwalker
shiptest-ss13/Shiptest pull request #1700
Opened 2023-01-16 15:34 UTC by spockye

## About The Pull Request
This PR adds a beach ruin based around a ship I've previously made, called the "Starwalker"

![2023 01 16-16 33 48](https://user-images.githubusercontent.com/79304582/212715120-1234050a-b91c-411c-b792-82d0621cc549.png)

it contains:
some medical supplies ( oinment slurry / herbal pack / crew monitor / health scanner / charcoal bottle / misc pills )
one Swat suit
one shotgun / one energy cutlass
goliath cloak  / military rig
3 abandoned crates
1 gold crate / one silver crate
lizard wine
one baby carp
a radiant dance machine
a sci protolathe
misc salvage

Lore bit:
After a "most excellent robbery that went like, totally as planned", our protagonists aboard the Starwalker fled the crime scene, with heavy damage to the ship's hull. With one of the Engine blocks almost falling off, The valiant crew decided that the best course of action would be a "Totally rad emergency landing". This, of course, ended in disaster, as the pilot was high on LSD. 
The pilot did however manage to steer them towards a nearby lak- sike, it's just some shallow water. Crashing directly onto the ground, the ship split into multiple fragments, Killing the pilot and crewmate, and Impaling the captain. 
The captain knew that he didn't have long until the bloodloss would get to him, and started moving all his treasure into a nearby cavern. _THERE'S NO WAY_ he would die in that godforsaken ship, nor without his treasures. This is where you now find him, rotting in his "100% real Cow skin" throne _(spacemart Brand Comfy chair)_ . 

- [ ] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
currently there's a bit of a lack in beach ruins, something that I'd like to help resolve!

## Changelog

:cl:
add: Adds a new Beach ruin, the beach_crashed_starwalker
/:cl:

2023-01-16 15:38 UTC, spockye commented
uhh, something's weird

2023-01-16 15:45 UTC, spockye commented
I have left your realm, mortals. my PR's exist beyond the limits of your barbaric machines. Look upon my PR's and despair, for you shall never witness their beauty  //edit : Fuck

2023-01-17 18:18 UTC, Bjarl reviewed
map review later

2023-01-17 18:18 UTC, Bjarl commented on _maps/RandomRuins/BeachRuins/beach_crashed_starwalker.dmm
> +	gpstag = "NTREC1";
iirc this is the kilo's tag too. I'd give em a different one

2023-01-17 18:18 UTC, Bjarl commented on _maps/RandomRuins/BeachRuins/beach_crashed_starwalker.dmm
> +/obj/item/circuitboard/machine/protolathe/department/science{
it's just a circuitboard but is the science one appropriate for this ruin? I'd say like... Peacekeeping for ammo (pirate ship) or a cargo one.

2023-01-17 18:18 UTC, Bjarl commented on _maps/RandomRuins/BeachRuins/beach_crashed_starwalker.dmm
> +	name = "Baby carp"
give this guy a desc too

2023-01-17 18:18 UTC, Bjarl commented on _maps/RandomRuins/BeachRuins/beach_crashed_starwalker.dmm
> +	footstep = "wood"
you should subtype the "wood" stairs, maybe get a sprite

2023-01-17 18:18 UTC, Bjarl commented on _maps/RandomRuins/BeachRuins/beach_crashed_starwalker.dmm
> +/obj/effect/decal/cleanable/dirt,
doubled up dirt

2023-01-18 08:06 UTC, spockye commented on _maps/RandomRuins/BeachRuins/beach_crashed_starwalker.dmm
> +/obj/effect/decal/cleanable/dirt,
does that cause issues?

2023-01-18 13:59 UTC, Bjarl commented on _maps/RandomRuins/BeachRuins/beach_crashed_starwalker.dmm
> +/obj/effect/decal/cleanable/dirt,
No

2023-01-19 15:19 UTC, Erikafox requested changes
![image](https://user-images.githubusercontent.com/94164348/213480350-f3bddeb6-fac7-4c31-8c21-a13a650d880b.png)
scatter some broken cables around here

Varedit ALL the APCs to have them start empty.
![StrongDMM_ezxNLnaIQN](https://user-images.githubusercontent.com/94164348/213480592-d1da0e64-ecc0-4719-af01-0933862a0159.png)
I'd give the chair a funny name so people know it's important.

2023-01-21 16:38 UTC, Bjarl requested changes

2023-01-21 16:38 UTC, Bjarl commented on code/datums/ruins/beachplanet.dm
> +	suffix = "beach_crashed_starwalker"
beach_crashed_starwalker.dmm

2023-01-21 16:38 UTC, Bjarl commented
Please do not mark the "I tested this" checkmark if you didn't attempt to spawn it in. That means you didn't test it.

2023-01-31 15:34 UTC, ZephyrTFA approved these changes

2023-02-03 18:16 UTC, Bjarl commented
![image](https://user-images.githubusercontent.com/94164348/216677322-6d70e96d-458f-4dfb-9013-1539d7a30aa1.png)
This uses the cursed sand.

2023-02-28 23:37 UTC, Bjarl approved these changes

2023-02-28 23:47 UTC, merged