beach ruin, The Treasure Cove!
shiptest-ss13/Shiptest pull request #1701
Opened 2023-01-17 10:48 UTC by spockye

## About The Pull Request
This PR adds a new Beach ruin, Treasure Cove. 

![2023 01 17-11 26 30](https://user-images.githubusercontent.com/79304582/212874736-b17917a5-876e-4a7a-a073-1581cc394b8e.png)

![2023 01 17-11 26 58](https://user-images.githubusercontent.com/79304582/212874824-9a161419-b751-41d2-a82d-e50f06981025.png)

![image](https://user-images.githubusercontent.com/79304582/212879021-bcdc2238-b50b-48c2-9cd0-d17cccbd50dc.png)

Loot: 
cm-16 rifle (main loot)
energy gun
pirate sabre
frontiersmen hardsuit
misc combat supplies
secret documents
2x abandoned crates
research note / tesla researcher
basic engineering supplies (smes/tools/autolathe/battery charger)
two boats
silver crate / hidden gold crate
misc junk
______
Threat: 
1x spacesuit ranged pirate
2x sword pirates
1x ranged pirate
punji sticks
_____

Lore tidbit:
This "humble abode" is the home of our 5- now 4 Pirate friends! After a mildly successful raid on a CMM VIP transport, they managed to take a Cargo tech (the VIP), and a CMM guard as hostage. sadly it didn't all go as planned, and the CMM officer managed to free himself and killed one of the pirates. This is where you now find the cave, with both hostages executed, their brother buried, and the pirates grieving his unfortunate passing. 

- [ ] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
more ruins = good.

## Changelog

:cl:
add: Adds a new beach ruin, the beach_treasure_cove
/:cl:

2023-01-17 17:59 UTC, Bjarl reviewed
map review later

2023-01-17 17:59 UTC, Bjarl commented on _maps/RandomRuins/BeachRuins/beach_treasure_cove.dmm
> +	desc = "As you draw near the ancient wall, a sense of foreboding overcomes you. You aren't sure why, but you feel this dusty structure may contain great dangers."
this desc is off the complex iirc. Intentional?

2023-01-17 17:59 UTC, Bjarl commented on code/game/area/areas/ruins/beachplanet.dm
> +	name = "Quirky Cavern"
I feel like quirky cavern isn't the best name for this

2023-01-17 17:59 UTC, Bjarl commented on _maps/RandomRuins/BeachRuins/beach_treasure_cove.dmm
> +	},
you use this a lot, you should make another pr subtyping it and updating your maps to use that subtype.

2023-01-19 15:13 UTC, Bjarl requested changes
![image](https://user-images.githubusercontent.com/94164348/213479034-14734267-6e2a-498a-acae-4a63e681b740.png)
I'd rename - redesc these. Perhaps some sort of "Water Boat"

![StrongDMM_z3OLJRlzpM](https://user-images.githubusercontent.com/94164348/213479464-4682fea3-5335-4c3c-90f0-f1381ecd7b56.png)
Have the fuk off sign out front and make the turret function

2023-01-19 15:13 UTC, Bjarl commented on code/game/objects/items/devices/radio/radio.dm
> +	name = "Old Radio"
old radio, no capitals. Gotta keep things consistent.

2023-01-23 19:28 UTC, goober3 commented
`//seems quite simple to me`
You

2023-01-31 15:34 UTC, ZephyrTFA approved these changes

2023-02-17 15:44 UTC, Bjarl approved these changes

2023-02-17 15:58 UTC, merged