New Rockplanet ruin, Budgetcuts!
shiptest-ss13/Shiptest pull request #1702
Opened 2023-01-17 15:21 UTC by spockye

## About The Pull Request
This PR adds a Nanotrasen Research facility, in a bit of a pickle.

![2023 01 17-15 57 58](https://user-images.githubusercontent.com/79304582/212936680-642aae0c-15d2-48b6-8c75-724d12a2ad13.png)

![2023 01 17-16 16 30](https://user-images.githubusercontent.com/79304582/212936724-c2904f80-5558-49c4-bc2d-c63fd4ad70c5.png)

Loot:
Combat supplies ( 1 m1911 / energy crossbow / security locker / security vendor / hos locker )
Medical supplies ( compact defib / brute,burn,oxy kit ) 
Kitchen supplies
Research supplies ( sci protolathe / circuit imprinter / experimentor / slime cores / research note / nanite supplies )
Fake Death ripley
jackhammer

Threats:
Emergency Retirement Team ( Assault officer / 2x SMG officers / 2x PISTOL officers / 2x FIST officers )
Emergency Treasure Retrieval Team ( RANGED pirate / 2x SWORD pirates / HARDSUIT pirate ) 

Lore grimble!
As you know, Nanotrasen hasn't exactly had the most economically successful season. Due to this, theres a need for some.... Budget cuts _(get it? its the name! im really smart)_. This research station hasn't exactly been productive lately, nor has it been worth having a research station in a place as remote as this. Nanotrasen is now left with two choices. 
Pay the researchers their promised bonus, or... Well, you can guess the second option. 
The Research Director fearing what Nanotrasen would do to him sends out an SOS and kills himself.

Sadly for the rest of the crew, nobody responds to the SOS call, sealing their fate. A certain group of pirates, however, locate the signal and prepare to raid it. 

- [ ] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
More ruins = good! more diversity in ruins is also good!

## Changelog

:cl:
add: Added a new Rock ruin, rockplanet_budgetcuts
/:cl:

2023-01-17 18:07 UTC, Bjarl reviewed
map review later

2023-01-17 18:07 UTC, Bjarl commented on code/datums/ruins/rockplanet.dm
> +	description = "Nanotrasen's gotta lay off some personell, and this facility hasn't been worth the effort so far"
personnel

2023-01-17 18:07 UTC, Bjarl commented on code/game/area/areas/ruins/rockplanet.dm
> +/area/mine/rockplanet
bad ruin area path, check the other ruin area .dms and repath accordingly.

2023-01-17 18:07 UTC, Bjarl commented on _maps/map_catalogue.txt
> +		Tags = "hard combat Challenge", "Medium Loot", "hospitable"
capitalize

2023-01-17 18:07 UTC, Bjarl commented on _maps/RandomRuins/RockRuins/rockplanet_budgetcuts.dmm
> +/obj/item/paper/fluff/awaymissions/moonoutpost19/research/xeno_queen,
read these papers and make sure they don't go into bizarro world, they're old.

2023-01-19 15:08 UTC, Bjarl requested changes
![image](https://user-images.githubusercontent.com/94164348/213476729-b5245eb2-1f8e-46fa-80a7-b588d970c4be.png)
I have the odd feeling that one of these guys will bump the door, they'll see each other, and they'll fight.
![StrongDMM_P5RZzlAnkq](https://user-images.githubusercontent.com/94164348/213477169-7702f774-82ed-49f3-a030-4453b4c94c01.png)
ditch the consuming and industrial extracts. Greys for xenobio is good loot already.
![StrongDMM_UhdhGNJq5O](https://user-images.githubusercontent.com/94164348/213477384-53d12f50-9c31-41d9-9d9e-8e061f3aaa36.png)
swap for a helm console, just have it be broken.
![StrongDMM_ceWQgYIS0q](https://user-images.githubusercontent.com/94164348/213477522-5398c3f6-c8b9-4617-af3f-5cbb7409dcc6.png)
Swap the explosive mine for a (sophisticated) shrapnel mine. Explosives are not really fun to deal with. Shrapnel has a bit more grace.
I also wouldn't be upset if you added more.
![StrongDMM_dItupkaFek](https://user-images.githubusercontent.com/94164348/213477851-1af18ac3-f4bb-4e80-960d-0d8889e5790d.png)
what's up with this?
![StrongDMM_1kAI6Y4Q8N](https://user-images.githubusercontent.com/94164348/213477986-9b19cf26-47c1-41ad-9e19-60728e4b50a3.png)
Decal

2023-01-21 15:45 UTC, Bjarl commented
The pirates outside should be the suited variants, they'll die otherwise.

2023-01-31 15:34 UTC, ZephyrTFA approved these changes

2023-02-17 15:00 UTC, Bjarl commented
![firefox_YSfXdEnTJL](https://user-images.githubusercontent.com/94164348/219689363-8a6488ff-6048-433e-bad1-0c8475a5f749.png)
The real authentic HoS locker needs to go, it has a secfab and enough gear for a small ship.

2023-02-21 17:42 UTC, Bjarl commented
Need to fix the pirates on the outside.

2023-03-13 18:14 UTC, Bjarl commented
fix the pirates

2023-03-23 13:21 UTC, Bjarl commented
re-open when you fix the pirates.

2023-03-24 14:08 UTC, spockye commented
GWA

2023-04-04 13:50 UTC, Bjarl approved these changes

2023-04-04 14:06 UTC, merged