Reworks Power Puzzle
shiptest-ss13/Shiptest pull request #1703
Opened 2023-01-17 23:31 UTC by goober3

Reworks Power Puzzle to (hopefully?) fit modern Testing standards.

## Holy Shit A New Ruin

![new](https://user-images.githubusercontent.com/118859017/213032902-2598e523-83ed-4ff2-b3cb-94dac626e64e.png)

![newareas](https://user-images.githubusercontent.com/118859017/213032919-e7c0d871-ecb5-46ff-a5e9-b251dcf0d4a6.png)

![old](https://user-images.githubusercontent.com/118859017/213032928-24e80c55-f81e-4c4c-99bb-e418efec26b8.png)

Loots: -Hand Teleporter
-Refined Bluespace Crystal
-Bluespace Anomaly Core
-Commander + x2 Surplus Ammo Boxes / magazines
-250 credits
-Insulated Gloves
-Cell Charger Board
-SUPERPACMAN generator
-4 ½ EVA suits
-Engi-Vend
-Big Bess + exosuit drill, hydraulic clamp, ion thruster package (hidden)
-Exotic........Corgi............

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

It's A Ruin, Holy Shit!

## Changelog

:cl:
tweak: Reworked PowerPuzzle, a cargo facility hidden in the outer reaches of space.
/:cl:

2023-01-19 14:56 UTC, Bjarl requested changes
![image](https://user-images.githubusercontent.com/94164348/213475025-644f525a-f78e-4256-8c81-c85ef3762f5c.png)
This room needs a lil bit of decalling
![StrongDMM_RmceMpJYgB](https://user-images.githubusercontent.com/94164348/213475223-d980ee74-24a5-4cbd-a724-3b2d32f01ca7.png)
Ask a lore fellow about the hand teleporter. I think it's fine but they may think otherwise.

2023-01-19 14:56 UTC, Bjarl commented on code/game/area/areas/ruins/space.dm
> +//NUCLEAR DUMP -- this ruin uses an area from power puzzle, for whatever reason. added new areas, for now.
good catch

2023-01-22 23:36 UTC, goober3 commented
> ![image](https://user-images.githubusercontent.com/94164348/213475025-644f525a-f78e-4256-8c81-c85ef3762f5c.png)
This room needs a lil bit of decalling

![image](https://user-images.githubusercontent.com/118859017/213946458-64a72dce-e7b6-4f4e-bc47-ff4a7e78b49a.png)


>Ask a lore fellow about the hand teleporter. I think it's fine but they may think otherwise.

I spoke to Valorium about this, the hand tele should be Fine!

2023-01-31 15:35 UTC, ZephyrTFA approved these changes

2023-02-03 22:54 UTC, Apogee-dev commented
You have a few railings in the middle room blocking part of the main pathway that seem really out of place.

2023-02-03 23:02 UTC, goober3 commented
> You have a few railings in the middle room blocking part of the main pathway that seem really out of place. Also, I'd suggest using Nanotrasen engineer corpses, the ones you have right now are dressed in indie outfits. You might have to make a new object for those if it's not already available.

oops. did not mean for those to be there. Fixing Now.

2023-02-11 06:29 UTC, Bjarl approved these changes

2023-02-11 18:25 UTC, merged