Luxembourg Tweaks
shiptest-ss13/Shiptest pull request #1740
Opened 2023-01-28 22:37 UTC by goober3

## About The Pull Request

Removed the gondola pockets from the Luxembourg, and moved the intercom away from the selling pad (in the same location, but pixelshifted!) 

## Why It's Good For The Game

Gondola pockets were a noob trap, which isn't fun for anyone. The bridge intercom was being sold by the selling pad, whenever the selling pad was used.

## Changelog

:cl:
tweak: The Luxembourg's intercom will no longer be sold by its selling pad.
tweak: Gondola pockets have been ERASED from the Luxembourg's kitchen locker.
/:cl:

2023-01-29 10:32 UTC, Apogee-dev commented
i'll be honest i'd rather see the luxembourg replaced entirely (and in fact, it IS slated for replacement) than just getting minor tweaks like this.

also the gondola pockets are funny as hell

2023-02-03 22:29 UTC, Bjarl approved these changes

2023-02-04 15:48 UTC, ArdentSpark commented
The gondola pockets are really bad actually, they can be used to make insane money which stops the luxembourg from really having to trade with players at all!  Good shout on the intercom move

2023-02-06 01:24 UTC, Bjarl requested changes

2023-02-06 01:24 UTC, Bjarl commented on _maps/shuttles/shiptest/syndicate_luxembourg.dmm
> -/obj/item/storage/box/donkpockets/donkpocketgondola,
replace these 4 with another type of donks.

2023-02-17 14:53 UTC, Bjarl approved these changes

2023-02-17 15:34 UTC, merged