Revamp the shuttle backend
shiptest-ss13/Shiptest pull request #1745
Opened 2023-02-01 19:58 UTC by ZephyrTFA

It does good things

2023-02-03 14:33 UTC, ritorizo reviewed
Disclaimer : I'm not very familiar with the shuttle code.

I looked trough all of it and it's coherent.
Some map object with the property id were changed to base_id which shouldn't have tough (gonna look into it).

2023-02-05 08:56 UTC, ritorizo commented
Made a pr on this branch which should resolve the map issues.

2023-02-05 14:02 UTC, tmtmtl30 commented
i've probably got some substantial thoughts on this, remind me to review it

2023-02-22 01:24 UTC, MarkSuckerberg requested changes
Definitely a few things need looking over and some testing of some cases

2023-02-22 01:24 UTC, MarkSuckerberg commented on code/game/objects/structures/morgue.dm
>  	id = "[REF(port)][id]"
Think you meant to remove this

2023-02-22 01:24 UTC, MarkSuckerberg commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +/datum/gas_mixture/proc/__auxtools_parse_gas_string()
almost certain this should be atomised into a different PR

2023-02-22 01:24 UTC, MarkSuckerberg commented on code/modules/mapping/map_template.dm
> +					return list(xcrd, ycrd)
Pretty sure BYOND lists of numbers need to have a key or else there's weirdness with the ordering (e.g. list("x" = x, "y" = y) might be needed)

2023-02-22 01:24 UTC, MarkSuckerberg commented on code/datums/shuttles.dm
> -			port.load(src)
Sure this won't break the change from https://github.com/shiptest-ss13/Shiptest/pull/42?

2023-02-22 01:24 UTC, MarkSuckerberg commented on code/modules/shuttle/shuttle.dm
> -		load()
See comment about https://github.com/shiptest-ss13/Shiptest/pull/42

2023-03-10 21:56 UTC, ZephyrTFA commented
me when all the maps conflict

2023-03-10 21:56 UTC, closed without merging