Outposts v0.2: Test PR
shiptest-ss13/Shiptest pull request #1789
Opened 2023-02-24 15:46 UTC by tmtmtl30

## About The Pull Request

ships spawn in (non-exclusive, so don't get too comfortable) hangars at the outpost sized to them, connected to a new "main level" of the outpost via an elevator. new hangars are generated as necessary as ships spawn / dock. let me know if radio works across hangars or not

this is mega-unfinished and not fit for merge, but it IS fit for test, and that's what we do around here isn't it???

## Why It's Good For The Game

it's cool

## Changelog

:cl:
add: Ships now spawn at the outpost, in hangars. Take the elevator in the top-right down to the main level.
add: 100% guaranteed most realistic ss13 elevator experience if you ignore all the things that aren't realistic
/:cl:

2023-02-24 16:08 UTC, tmtmtl30 commented
unit tests are angry but it works locally. my solution for getting ships to spawn on the outpost was a quick hack and i'll think of a better one when i'm not dead tired

2023-02-24 19:04 UTC, UltraBigRat commented
overall pretty good, some feedback:
Maybe add ship names (and maybe classes) to the  elevator floor buttons since all floors other then the first one are a hangar for a single ship.
The elevator button on the outside should probably just call instead of moving it up or down, and maybe the elevator should only close upon it beginning to move not when people enter. 
overall pretty good though, just needs polish.

2023-03-05 13:59 UTC, tmtmtl30 commented
minor update: admins can now spawn ships in locations other than the outpost

2023-03-08 15:49 UTC, spockye submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/79304582/223762489-efa009d2-cff4-435c-864d-50afa86304d1.png)
small decal error here. Try changing the layers around!

![image](https://user-images.githubusercontent.com/79304582/223758772-5561a698-ec55-4c8c-87b6-ceffc1f464dd.png)
did you mean for them to be this faded?

![image](https://user-images.githubusercontent.com/79304582/223759183-a9a012a0-ed0d-4095-9d1e-b898a47c0686.png)
WOAH HIGH TECH HOLOGRAPHIC COMPUTER SCREEN

![image](https://user-images.githubusercontent.com/79304582/223759403-550af2d4-5356-4399-9955-222ccfa7799a.png)
use the table version of the wideband!

![image](https://user-images.githubusercontent.com/79304582/223760204-6fb2e6b8-ffd9-41e2-acb9-34a70b843cd7.png)
Button doesn't work

![image](https://user-images.githubusercontent.com/79304582/223760476-2bcf148e-3c6b-462e-8a39-987d8d5152a5.png)
This button doesn't work

![image](https://user-images.githubusercontent.com/79304582/223760790-9dfef936-e681-4474-bca7-1d0fb7c36e9d.png)
This button doesn't work

2023-03-08 17:55 UTC, goober3 commented
I don't know if this is a Mapping Issue or what but. a lot of Air Supply Pipes in the outpost are invisible in-game. odd!

2023-03-09 16:46 UTC, goober3 commented
will there bean option for ships to spawn in Space on ship configs? might be useful for more hazardous ships, like the Metis.

2023-03-10 00:09 UTC, tmtmtl30 commented
i don't have that planned but it'd definitely be doable code-wise

2023-03-12 11:36 UTC, tmtmtl30 commented
spockye has graced the PR with a second map for testing -- the map will be picked randomly at roundstart

2023-03-18 21:32 UTC, BarteG44 commented
the requirement for a kitchen was a chef holopad. the holopad is here but kitchen is not. i will resort to violence

2023-04-21 08:40 UTC, BarteG44 commented
Add moar holopadd got daym

2023-07-05 16:25 UTC, thgvr commented
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

2023-07-25 00:58 UTC, MarkSuckerberg requested changes
just two small non-functional things, otherwise it's legit from what I can tell

2023-07-25 00:58 UTC, MarkSuckerberg commented on code/modules/overmap/objects/outpost/elevator/elevator_master.dm
> +	/// The index into the floor list at which the
the

2023-07-25 00:58 UTC, MarkSuckerberg commented on html/changelogs/AutoChangeLog-pr-1812.yml
> +  - bugfix: The rigger-c json is now correctly pathed to a .dmm file
oop

2023-07-25 09:02 UTC, thgvr approved these changes

2023-07-28 00:52 UTC, MarkSuckerberg approved these changes
lgtm

2023-07-28 01:20 UTC, merged

2023-07-28 01:23 UTC, goober3 commented
no freakin way lois

2023-07-28 01:23 UTC, BarteG44 commented
At last