Update Define Spacing
shiptest-ss13/Shiptest pull request #179
Opened 2021-08-21 02:32 UTC by ZephyrTFA

UPDATES A LOT OF SPACING FOR DEFINES TO BE IN LINE WITH CODING GUIDELINES.
THIS WAS DONE VIA REGEX AND WILL REQUIRE AT LEAST A WEEK OF BEING TM'D BEFORE FULL MERGING

2021-08-23 14:28 UTC, martinlyra requested changes

2021-08-23 14:28 UTC, martinlyra commented on code/__DEFINES/flags.dm
> +////////////////Area flags\\\\\\\\\\\\\ \
```suggestion
////////////////Area flags\\\\\\\\\\\\\\
```

The CI is complaining about this

2021-08-23 16:17 UTC, ZephyrTFA commented on code/__DEFINES/flags.dm
> +////////////////Area flags\\\\\\\\\\\\\ \
My savior

2021-08-23 16:29 UTC, martinlyra approved these changes

2021-08-29 10:55 UTC, martinlyra requested changes

2021-08-29 10:55 UTC, martinlyra commented on code/game/machinery/scan_gate.dm
> +#define SCANGATE_lizard "lizard"
```suggestion
#define SCANGATE_LIZARD "lizard"
```

2021-09-01 17:53 UTC, martinlyra commented
Just discard your changes on the `check_regex.py`, reflect your new target(s) to the `check_regex.yaml` file. That should be good to go!

2021-09-02 04:59 UTC, shiptest-server commented
#### Test Merge Deployed

##### Server Instance
shiptest

##### Revision
Origin: bf2a3d7daffd8042d3adbe075ec803cd3abd4e03
Pull Request: 289cc24feb05cc64ea8e9b2427e42845e60eed8c
Server: ca0ff8b9f76846976a9d8d2ec5e18cf60ecd28be

2021-09-04 14:49 UTC, shiptest-server commented
#### Test Merge Removed

2021-09-06 20:13 UTC, MarkSuckerberg commented
LGTM

2021-09-06 20:14 UTC, merged

2021-09-07 10:35 UTC, martinlyra commented
:tada: