NTSV Tegus-class Mining Carrier
shiptest-ss13/Shiptest pull request #1880
Opened 2023-04-09 01:52 UTC by goober3

## About The Pull Request
![tegusB](https://user-images.githubusercontent.com/118859017/230747921-3d856b37-552b-4ac5-8635-ef6ff1047758.png)

![image](https://user-images.githubusercontent.com/118859017/230747599-9d942440-1594-46aa-97ec-f833d48375f6.png)

![areategusB](https://user-images.githubusercontent.com/118859017/230747924-b283f146-3606-41e8-a195-29ff80bc8824.png)

![shuttletegusA](https://user-images.githubusercontent.com/118859017/230747765-675e6385-ef80-4e0e-ae8f-3e3d817612ef.png)

![areashuttletegusA](https://user-images.githubusercontent.com/118859017/230747767-eecb9116-0ae4-47f9-89f1-f0746bbe92af.png)

Adds a Nanotrasen mining carrier with a large shuttle for performing mining operations and transporting crew. 

A full telecomms setup, a relay linking the shuttle with the mothership, and a spyglass kit facilities Miner to Mothership communication, allowing expedition teams to travel long distances whilst still remaining connected to the Tegus.

This PR also ports Fikou's spyglass rework from TG (this was included in the original Columba PR, which is closed now!)

## Why It's Good For The Game

Columba But Better

## Changelog

:cl:
add: The Tegus-class Mining Carrier, a Nanotrasen mining ship with a large subshuttle.
tweak: Spyglasses use actions now
/:cl:

2023-04-09 18:57 UTC, retlaw34 approved these changes
i fucking love tegus you jsut dont understand

2023-04-09 23:06 UTC, spockye requested changes
![image](https://user-images.githubusercontent.com/79304582/230800396-5f1c8fe3-df9c-48ba-95ec-503c0d37f2b0.png)

unconnected vent and scrupper


![image](https://user-images.githubusercontent.com/79304582/230800421-d24c96d7-d330-472a-8a14-a1df4767824f.png)

no need for the manifold to go into the wall

![image](https://user-images.githubusercontent.com/79304582/230800488-7926bd6b-2182-421e-95aa-c82f22ceee4c.png)

please replace it with "tegus_shield_port"! 

the ship looks rad. Good work!

2023-04-13 18:11 UTC, goober3 commented
the checks have somehow fixed themselves. Good.

2023-04-14 17:32 UTC, goober3 commented
the checks have somehow unfixed themselves. Bad.

2023-04-19 23:12 UTC, Bjarl commented on code/datums/shuttles.dm
> +	name = "Tegus Transport Shuttle"
Please give it a different name than the ship

2023-04-22 14:13 UTC, Bjarl requested changes
![image](https://user-images.githubusercontent.com/94164348/233788600-88f61d1d-9336-423e-bca5-7c291aa28687.png)
The shutters on the subshuttle need to start closed. You get weird space wind and trouble with freespawning it otherwise.
I'd also like it one of the holofields was replaced with a cycling airlock. 
![StrongDMM_h1SqbcNbbB](https://user-images.githubusercontent.com/94164348/233788679-8d1f84a4-9456-489d-afb3-93ceef407461.png)
lockers go on 28/-28
![StrongDMM_q3PToBHOOH](https://user-images.githubusercontent.com/94164348/233788712-1bb736c3-d141-41c6-81dc-9c4cbc42a1da.png)
There needs to be a cable under the terminal for it to work
![image](https://user-images.githubusercontent.com/94164348/233788763-07d3b1a2-8729-4801-87dc-c1ec5261b1e1.png)
Use /three_quarters to reduce file size. 
![StrongDMM_XKF1HRWOJq](https://user-images.githubusercontent.com/94164348/233788794-f668cd26-fa69-478c-84a0-cef359bf94c3.png)
Give this room more of a tech bend. Try having some techfloor under the machines. To my eye it blends together with the rest of the ship far too much
![StrongDMM_m7M2YXw4aq](https://user-images.githubusercontent.com/94164348/233788854-ad9fb12a-3f13-4f2c-8ce0-e6fc45d26999.png)
Ditto down here
![image](https://user-images.githubusercontent.com/94164348/233788901-6cc75d80-cbc1-40bc-9ce6-e236eaeefa73.png)
Where is THEIR BED
Also lockers
![image](https://user-images.githubusercontent.com/94164348/233788928-36df0da9-c7ba-4723-8af0-721fdaa541b1.png)
Don't mix catwalks and pumps. It looks like shit.
![StrongDMM_LQ3tRvCGkF](https://user-images.githubusercontent.com/94164348/233788948-9dfd16e6-a719-417e-803e-8cd415d26317.png)
Set the density on the booze-o to 0 and pixelshift it onto a wall. 
![StrongDMM_ywAI8RXSNy](https://user-images.githubusercontent.com/94164348/233789394-d4930c1e-7066-479d-81ec-818d9d671671.png)
Firelocks on stairs can ruin the vertical effect. Consider moving it back
![StrongDMM_Qw3nDCki29](https://user-images.githubusercontent.com/94164348/233789420-ea22d2b0-9847-4f65-9e1b-98463b0edbc4.png)
Run the supply pipe with the scrubber pipe so you don't have atmos machine - pipe overlap
![image](https://user-images.githubusercontent.com/94164348/233789460-6e3568a8-c2be-48a6-93be-2002aeab046f.png)
Either or. If you want them to have the choice give them the boards and make it so they have to construct them.
![StrongDMM_k8bs1svMGD](https://user-images.githubusercontent.com/94164348/233789539-110c1463-2eeb-4966-8fc0-73ae2c0638d6.png)
MAKE IT SYMMETRICAL 
![StrongDMM_GK3iNgy5Y7](https://user-images.githubusercontent.com/94164348/233789586-a3a756f2-890e-4772-9112-3f23f1b277ad.png)
I'd have airlocks leading into this room. Also ditch the stairs and the catwalks. Make it seem more like an office - ready room. 


Right now the entire ship feels very _flat_ I think this is because you only used 3-4 types of tiles, some stairs, and decalling. Flat isn't bad, but it can make things less interesting. I'd experiment with stronger decal colors, different tile types, and establishing theming to areas, because some of the placement feels flat out random to me. The mining room and bar are probably the most stand out offenders to this. 
![StrongDMM_P9ZuzjL3SB](https://user-images.githubusercontent.com/94164348/233789757-8e90520d-9631-4029-a65c-0ae2b609dcbe.png)
Also consider using some interior reinforced hull tiles here.

![image](https://user-images.githubusercontent.com/94164348/233789778-cf2b38e3-f57c-473e-9931-68bc21bcebba.png)
Honestly the nose could be expanded to give it some proper cargo areas. It really feels like a shape first design second ship, leading to things like the semi-random filing cabinets, or the mining room.
![StrongDMM_ce88xk58lV](https://user-images.githubusercontent.com/94164348/233789829-41fd3652-291c-449d-b596-4ec9b454c4e6.png)
Airlocks this size should have 2 vents for quick cycling.

Consider making a subtype of Ions that are less efficient to encourage usage of the subshuttle. You can't really force it but it should be the preferable alternative.

2023-04-22 18:33 UTC, goober3 commented
review jumpscare

2023-04-25 14:51 UTC, Erikafox requested changes
Needs a docking point for subshuttles on the outside.

2023-05-25 10:48 UTC, spockye reviewed
![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/8c806e93-525a-43d5-b809-86803769b7e3)

missing pipes

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/7e4c5b95-df49-4316-8589-6d2648a6a45c)

the canteen feels really secluded. mabye add some windows here?

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/9bb99e50-b685-4264-bd5a-a43cf03ad136)

give the poor dude a bed :(


![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/711d44b5-3f51-4d42-a3d3-09a91f35f9cd)

this apc isnt wired


-----------

mabye add a locker with spare clothes? not seeing any

2023-06-11 02:26 UTC, Latentish requested changes, later dismissed
To start you have two atmos piping errors and a subshuttle related runtime that need to be fixed before this can be merged.
This airlock on the subshuttle is not set up properly
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/c7e61eaf-b633-4f99-86e3-ac2f4ea47d86)

Cryopod wakeups should be separate from crew quarters, or at least have some more separation.
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/ae03f060-c31d-4389-abc9-0f5f5154b307)

You need to add lightswitches

Not mechanically supported, but I definitely prefer telecomms be stored in a vacuum or cold temperature.
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/5d50d400-4448-4515-8829-3b7ed8a0820a)

You need mroe emergency lockers.
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/7d6ec91d-1d1b-4465-9d61-cb17c44b67a0)


Cryopod areas also need handheld radios and lights somewhere reachable.
Also this are looks more like a front desk office than crewquarters.
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/d535f8ad-6a68-4fb1-9691-e10c70d0a455)

The subshuttle could definitely use a pair of emergency lockers.

2023-06-11 02:29 UTC, Latentish commented
Ship's pretty good overall.

2023-06-12 20:39 UTC, goober3 commented
this ready for TM / review, aside from the funky integration check fail. i'm not quite sure how to fix that

2023-06-13 01:28 UTC, Bjarl reviewed
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/dc1ae890-7ee5-482c-91c8-621b7c44c976)
I think this room needs a lil more decalling

Maybe go a bit heavier on the metal interior, instead of titanium.

2023-06-13 20:20 UTC, PrefabQuasar commented
already thoroughly reviewed, so i wont pile on much, but it's worth considering reducing the range of that subshuttle by cutting out the pacman, and maybe the SMES too, otherwise it really can just go Wherever

2023-06-14 10:21 UTC, spockye approved these changes
Massive improvements all around. I'm liking where this is going!

2023-06-14 11:09 UTC, Latentish commented
I have to say that I really preferred the overall shape of your last iteration more.

2023-06-14 18:00 UTC, goober3 commented
> I have to say that I really preferred the overall shape of your last iteration more.

perhaps. i think this shape still works aesthetically. and the layout has improved moreso, i hope


> ![image](https://user-images.githubusercontent.com/94164348/245324982-dc1ae890-7ee5-482c-91c8-621b7c44c976.png) I think this room needs a lil more decalling
> 
> Maybe go a bit heavier on the metal interior, instead of titanium.

i'll Experiment

2023-06-24 21:51 UTC, goober3 commented
OUGH

2023-06-24 23:06 UTC, Apogee-dev requested changes
Lock the subshuttle cockpit's airlock to the pilot job, please. It makes sense to keep the other crew members from running off with it, and if somebody desperately needs in they can always hack the door.

2023-06-24 23:24 UTC, Bjarl commented
No cryopod computer in the cryopod room

2023-06-24 23:25 UTC, goober3 commented
> No cryopod computer in the cryopod room

this is being fixed!

2023-07-06 20:11 UTC, Bjarl requested changes
descending from the heavens to inform you that I like the ship, except engineering
The atmospherics machinery needs to be better marked, and it could use an atmospheric siphon set up (as well as air pressure tank, but that's less essential)

2023-07-06 21:57 UTC, goober3 commented
Ough

2023-07-11 06:02 UTC, Bjarl approved these changes
it'll probably be fine

2023-07-13 20:19 UTC, Latentish submitted a review, later dismissed
Pass your checks.

2023-07-14 03:53 UTC, Apogee-dev approved these changes

2023-07-30 23:01 UTC, Bjarl commented
waiting for the harddel fixes to go in because that fixes the CL failure this has.

2023-07-30 23:02 UTC, goober3 commented
oh no way!!! cool!!!

2023-10-20 18:05 UTC, spockye requested changes
![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/c72223c8-c9c6-45cd-b743-aed268589cd8)

Poster light

also add lightswitches

2024-01-04 05:50 UTC, Zevotech commented
## Please for the love of god add lightswitches to the ship and subshuttle
Replace these with the new good rations
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/7ec5647f-dfa8-408c-a22b-528fd659bd74)

Give the other plasma pacman 5 sheets as well, or maybe replace it with some other kind of pacman for diversity. A bad roll on the solars might cause power issues. Also see if you can put the fuel in a crate or something. Having it sat on top of the generator looks weird.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/aa818f43-eb6e-43aa-b795-f9cf9c69a48e)

Gngineering in general looks kind of empty, maybe add a locker or a desk for whoever works back here, a power monitoring console would also be appreciated. Also, replace the air canister with a high pressure airtank. You'll get maybe five uses out of the airlocks before the canister runs out and they stop working. The airlocks also straight up dont work until the canister is wrenched down.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/37d3f7b8-aaf3-4286-ae7c-da1cff00a21f)

Give the empty crates some junk or spare mining gear maybe. Add more trash around, maybe a crate shelf, make it FEEL like a cargo bay. Also, probably move that pipe dispenser to engineering. Not sure why its just sitting there.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/9340d8ef-58a2-4cc6-a91a-a4db679ef55c)

Did you copy this disk from the vela/cepheus? see if you can get rid of those CMM designs on there.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/98b474c1-8783-4f87-a8e8-eb1e6a9de6cd)

Feels like there could be more in here. Maybe toss in a few cleaner grenades, a maid outfit or some maintenance loot. 
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/f2dcb4af-3d35-4493-b38a-59df5c8f6882)

Maybe make the mining camera a small item so it fits into pockets. Also the captains locker has independent captains gloves in it. I like the emergency signaler, nice touch. You can change the ships starting funds in the JSON, maybe give it a bit more than 2000 considering its dedicated to logistics?
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/49200986-04b1-4539-9023-0775580c6b0e)

Throw a crate at the end for the refined materials to be put into. Otherwise, very nice smelting setup! Functions well.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/af2da96c-4782-4a27-82dd-8025ae18d2c6)

This computer doesn't seem to work. Also, why is it here? I'd replace it with something else.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/6507a98d-52fe-4a84-a2c6-f26da1ccae86)

I'd recommend throwing on some exterior defenses similar to the ones on the Vela to block potential debris or meteors. Good way to use this empty space.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/3cd11daa-1511-4367-bf2d-bb2544ba3ad9)

1. The subshuttle starts with no fuel. 2. The prechargers are from the fucking PILL CLASS. they have 0 DENSITY. Please use normal prechargers. 3. The airlock on the subshuttle does not work. Might be related to how the layer adapters are placed, look at other ships airlocks to see how they do it. 4. Either add access buttons to the outside of the subshuttle or move them to where they can be pressed from both inside and outside. 5. Give the pilot a proximity crew pinpointer instead of a normal one.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/76251301-ab92-4431-8030-3917b114b678)
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/8c1a64ba-5040-4f9b-abe7-df74413bc5ee)

2024-01-04 22:48 UTC, goober3 commented
yeah. i think i'm going to shelve this for a remap in the future. this ship could be much, much better.

2024-01-04 22:48 UTC, closed without merging