Ports displacement filters for height/dwarfism
shiptest-ss13/Shiptest pull request #1916
Opened 2023-04-20 03:12 UTC by thgvr

## About The Pull Request
![image](https://user-images.githubusercontent.com/81882910/233248662-123464f6-fa78-440a-8b6b-71fbfa9c2e5f.png)
Need to add to prefs (prefcode augh)
Works for dwarves.

## Why It's Good For The Game
Better looking height filters

## Changelog

🆑 Thgvr, Melbert, That REALLY Good Soda Flavor, FatFat, AndreyGusev
add: Height should now look better.
add: Dwarves should look less horrible.
/🆑

2023-04-21 00:21 UTC, Ms-Mee commented
Should probably have a more descriptive changelog if I'll be honest, clarify that dna body_size was replaced with the height filters at the very least

2023-04-21 00:28 UTC, thgvr commented
ok, reasonable

2023-05-03 19:46 UTC, MarkSuckerberg requested changes

2023-05-03 19:46 UTC, MarkSuckerberg commented on code/modules/mob/living/carbon/human/update_icons.dm
> -			worn_overlays = new_overlays
kepori & vox may break without this, check just in case for me

2023-05-03 19:46 UTC, MarkSuckerberg commented on code/datums/datum.dm
> +	for(var/filter_raw in filter_data)
```suggestion
	filter_data = sortTim(filter_data, GLOBAL_PROC_REF(cmp_filter_data_priority), TRUE)
	CHECK_TICK
	for(var/filter_raw in filter_data)
```
humour me and slot this in for a bit, this might cause some visual weirdness or eat the world, or it might help with overtime a bit, dunno

2023-05-03 20:55 UTC, thgvr commented on code/modules/mob/living/carbon/human/update_icons.dm
> -			worn_overlays = new_overlays
They seem to work fine during test merge with this.

2023-05-03 21:00 UTC, thgvr commented on code/datums/datum.dm
> +	for(var/filter_raw in filter_data)
okay, I'll commit this and see how it fares in test merge

2023-05-03 21:07 UTC, thgvr commented
what the hell is that linter fail

2023-06-02 01:20 UTC, thgvr commented
It's over.

2023-06-02 01:27 UTC, Ms-Mee commented
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

2023-10-14 00:31 UTC, thgvr commented
This is gonna sit until a solution is found which might be forever

2023-12-04 11:48 UTC, thgvr commented
One day

2023-12-04 11:48 UTC, closed without merging