Aegis update + patient clothing
shiptest-ss13/Shiptest pull request #2150
Opened 2023-07-09 14:58 UTC by Draggeru

## About The Pull Request
The Aegis:
![2023-07-09 06 32 40](https://github.com/shiptest-ss13/Shiptest/assets/81540056/cf262257-1699-40e0-bcb1-6dc60f1e98a6)
I've touched up the central hallway's decals, they always bothered me but at the time of the Aegis' creation, I wasn't as well versed with map making as I am now. They're small tweaks that look better to me. The smart fridge was removed and turned into a board, originally you could access the smart fridge from outside of the ship, which wasn't intended. Added some new posters. Compressed the number of red lockers down and cleaned up the main hallway. I gave the psychologist a dart gun because honestly, it sounded really funny.

![dart riffle](https://github.com/shiptest-ss13/Shiptest/assets/81540056/eb10154a-1e28-4a5d-b41b-9b20f92b71a9)

The Patient set:

![patient](https://github.com/shiptest-ss13/Shiptest/assets/81540056/65066ea3-92d1-4233-9bf6-a6448d43b11f)

Kepori and Vox versions are available. Long-term patients now spawn with the white gown and slippers. The previous clothes they spawned with were always intended to be replaced.

Hopefully, this PR also fixes long-term patients spawning with borked ID's. 

## Why It's Good For The Game

Fixing stuff, making stuff look better, and adding new RP opportunities with clothes are good.

## Changelog

:cl: Drag
add: Adds a bunch of shit to the Aegis, nothing earth shattering
add: Added the patient set, along with Vox and Kepori compatible sprites
tweak: tweaked with the Aegis' decals
fix: (Hopefully) Fixes the Aegis' patient Id's
:cl:

2023-07-09 21:57 UTC, Imaginos16 approved these changes
Good sprites. Cre is cool!

2023-07-11 05:37 UTC, Bjarl requested changes
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/d9daf101-04d8-42c9-b2bd-eee823fb1715)
I don't think it's the smartest thing to put the weapons in the cryo room. Maybe in a safe on the bridge?
![StrongDMM_wRMAGTuroy](https://github.com/shiptest-ss13/Shiptest/assets/94164348/010d7bf2-0d3f-42bb-90fc-bbeabd8d4fd2)
Ditch the codespeak, or make it 1 use (captain only)
![StrongDMM_3laX9v7Ikj](https://github.com/shiptest-ss13/Shiptest/assets/94164348/b93543fc-1721-40f9-bdf0-7c478a19c5c8)
ditch the guerillas
![StrongDMM_dgixa74FQe](https://github.com/shiptest-ss13/Shiptest/assets/94164348/36bd53a5-70c1-44df-a14d-ae39e634faaa)
you can fit the fridge here, you just need to put it on a tile adjacent to the wall, pixelshift it, and set it's density to zero
![StrongDMM_RD4NvA5Qky](https://github.com/shiptest-ss13/Shiptest/assets/94164348/814b7558-13bd-4319-a748-12f1dbd4046f)
Give this door a button on the interior (for the psychologist) that has the special functions var set to three. It will bolt the door, and allow for some privacy. The door's id_tag var will need to match the button's id var.
The bridge could use a bolt button too.
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/055f5fb3-d16e-40d2-97ef-824f6d03b96f)
cute but you can force pacifism on someone with this. If you want it _because_ it's cute, you need to make a safe subtype.
![StrongDMM_xZvIB4w8TV](https://github.com/shiptest-ss13/Shiptest/assets/94164348/0bfd696e-5a72-4da4-bfd9-195f41741ce8)
don't run this wire under the SSU
![StrongDMM_yDfgkwZmHR](https://github.com/shiptest-ss13/Shiptest/assets/94164348/171f7c38-47e4-43a3-b216-b1315936b020)
given that the ship's focus isn't botany. Biogenerator *or* nutrivend.
![StrongDMM_Ri9swx64uO](https://github.com/shiptest-ss13/Shiptest/assets/94164348/66400215-5302-4926-b237-99981e54a32d)
adjust the layering on this railing so it doesn't look like this.
![StrongDMM_TUzH2f88KC](https://github.com/shiptest-ss13/Shiptest/assets/94164348/b69a3ecc-227d-42f6-845d-46b190a08ea4)
the catwalk will go over this decal, making this tile look stupidly busy
![StrongDMM_S4DeT50Olq](https://github.com/shiptest-ss13/Shiptest/assets/94164348/c2189c28-a016-4078-b724-e65b42dce7ec)
use the /ship variant of grass

2023-07-11 07:11 UTC, Draggeru commented
>[StrongDMM_wRMAGTuroy](https://user-images.githubusercontent.com/94164348/252559931-010d7bf2-0d3f-42bb-90fc-bbeabd8d4fd2.png) Ditch the codespeak, or make it 1 use (captain only)

The codespeak manual has been available and approved from day one, is there a reason why we no longer want the entire crew with codespeak?

2023-07-11 18:15 UTC, Erikafox commented
> The codespeak manual has been available and approved from day one, is there a reason why we no longer want the entire crew with codespeak?

for clarity - 
![Discord_hpcj4Ne8md](https://github.com/shiptest-ss13/Shiptest/assets/94164348/3fcdf838-d94c-426d-903f-3440fb04865c)

> Give this door a button on the interior (for the psychologist) that has the special functions var set to three. It will bolt the door, and allow for some privacy. The door's id_tag var will need to match the button's id var.
The bridge could use a bolt button too.

I was informed that this is actually function 4, and requires the normaldoorfunction var to be set to 1

2023-07-12 05:13 UTC, Draggeru commented
Everything but the grass was changed, applying the ship version of the grass breaks.

2023-07-13 22:34 UTC, Bjarl requested changes
You've got some tables that are just. greyscaled to be green in botany

And I think this should be config limited to 1 ship per round. It can take up a good amount of crew.

2023-07-19 02:30 UTC, Draggeru commented
> You've got some tables that are just. greyscaled to be green in botany
> 
> And I think this should be config limited to 1 ship per round. It can take up a good amount of crew.

Is there an issue with the tables being green? There are tables that are greyscaled orange in engineering, why is there no apparent problem with them?

2023-07-19 02:42 UTC, Bjarl commented
> > You've got some tables that are just. greyscaled to be green in botany
> > And I think this should be config limited to 1 ship per round. It can take up a good amount of crew.
> 
> Is there an issue with the tables being green? There are tables that are greyscaled orange in engineering, why is there no apparent problem with them?

I thought they were wooden tables.

2023-07-19 05:35 UTC, Draggeru commented
> > > You've got some tables that are just. greyscaled to be green in botany
> > > And I think this should be config limited to 1 ship per round. It can take up a good amount of crew.
> > 
> > 
> > Is there an issue with the tables being green? There are tables that are greyscaled orange in engineering, why is there no apparent problem with them?
> 
> I thought they were wooden tables.

So just change all the tabled to wooden tables and its good to go?

2023-07-19 05:36 UTC, Bjarl commented
> > > > You've got some tables that are just. greyscaled to be green in botany
> > > > And I think this should be config limited to 1 ship per round. It can take up a good amount of crew.
> > > 
> > > 
> > > Is there an issue with the tables being green? There are tables that are greyscaled orange in engineering, why is there no apparent problem with them?
> > 
> > 
> > I thought they were wooden tables.
> 
> So just change all the tabled to wooden tables and its good to go?

Ungreen the green tables and swap the back tables out for wood ones I suppose.

2023-07-19 05:40 UTC, Draggeru commented
> And I think this should be config limited to 1 ship per round. It can take up a good amount of crew.

Are we going forward with limiting all ships to one at some point since we are seeing active new ship projects? (Including the Eventide)

2023-07-19 05:41 UTC, Bjarl commented
> > And I think this should be config limited to 1 ship per round. It can take up a good amount of crew.
> 
> Are we going forward with limiting all ships to one at some point since we are seeing active new ship projects? (Including the Eventide)

The default is going to become 1 Soonish.

2023-07-19 05:45 UTC, Draggeru commented
> > > And I think this should be config limited to 1 ship per round. It can take up a good amount of crew.
> > 
> > 
> > Are we going forward with limiting all ships to one at some point since we are seeing active new ship projects? (Including the Eventide)
> 
> The default is going to become 1 Soonish.

While I have your attention, should the hardline logo be swapped out with the ISF logo? Hardline makes industrial ships and the Aegis is not intended as one. What is the determining factor for manufacturing logos?

2023-07-19 05:46 UTC, Bjarl commented
> > > > And I think this should be config limited to 1 ship per round. It can take up a good amount of crew.
> > > 
> > > 
> > > Are we going forward with limiting all ships to one at some point since we are seeing active new ship projects? (Including the Eventide)
> > 
> > 
> > The default is going to become 1 Soonish.
> 
> While I have your attention, should the hardline logo be swapped out with the ISF logo? Hardline makes industrial ships and the Aegis is not intended as one. What is the determining factor for manufacturing logos?

I would ask the lore team

2023-07-19 05:52 UTC, Draggeru commented
What Var should be added to the json to limit the Aegis to one ship, Im officially having a certified Drag moment

2023-07-19 06:04 UTC, Draggeru commented
This is where we are at so far appearance wise
![2023-07-18 23 50 30](https://github.com/shiptest-ss13/Shiptest/assets/81540056/c7542947-2e2b-4e5f-950e-d96f23071746)

2023-07-19 23:55 UTC, thgvr commented on code/modules/clothing/under/miscellaneous.dm
> +	supports_variations = VOX_VARIATION | KEPORI_VARIATION
```suggestion
	supports_variations = DIGITIGRADE_VARIATION_NO_NEW_ICON | VOX_VARIATION | KEPORI_VARIATION
```

2023-07-20 02:27 UTC, Apogee-dev submitted a review, later dismissed
Add access restrictions, in general. Workspaces and critical areas like engineering, the medical labs, the kitchen, and ESPECIALLY the bridge should have appropriate access restrictions on their doors.

2023-07-20 03:31 UTC, Draggeru commented
> Add access restrictions, in general. Workspaces and critical areas like engineering, the medical labs, the kitchen, and ESPECIALLY the bridge should have appropriate access restrictions on their doors.

Ill put access restrictions on engineering, but the bridge has a door lock, medical should not have ANY restrictions due to its nature with the long term patient (and the fact you must walk through medical to get to the janitorial supplies), the kitchen and botany are intended as public access. The bridge has no windows, and there have been no issues with people invading the space in my playtesting on the live server. If it is a problem there is a lock that can be applied.

2023-07-26 15:31 UTC, Bjarl approved these changes

2023-07-26 15:41 UTC, merged