Nerfs Block Chance + Cooldown
shiptest-ss13/Shiptest pull request #2172
Opened 2023-07-16 04:05 UTC by Bjarl

## About The Pull Request
Weapons with blockchance are mildly degenerate, due to how you can carry multiple, and they allow near nullification of ranged weapons if stacked enough. Thus I am nerfing their chances to fire and adding a cooldown. Shields are exempt from the cooldown because they're shields. 

## Why It's Good For The Game
Combat should be *more* lethal. Harder to cheese. That sort of thing. Wear armor and carry a shield if you want to avoid damage. Or buy a gun.

## Changelog

:cl:
add: blocking something now starts a short timer before you can block something again.
balance: Block Chances have been reduced across the board
/:cl:

2023-07-16 06:14 UTC, MemedHams commented
I'd leave the officer sabres at 50, if only because their whole gimmick is having pitiable damage and low block

also, it might be a good idea to implement a check if the item is in the active hand before blocking (add a flag to shields and exempt them)

2023-07-16 07:41 UTC, Bjarl commented
I'll take a look at the sabres. Not sure how I'd implement a flag since I haven't done it before, but I'll take a looksie too.
If I can get that set up I'll adjust the balance some more.

2023-07-16 21:07 UTC, Bjarl commented
Alright, shields now block consistently, weapons only block if you're actively using them

2023-07-16 23:41 UTC, Valorium-RB commented
This enables a fun design space for parrying daggers and the like when we add more mechanics for SUNS duelist stuff, really cool.

2023-07-20 02:36 UTC, Apogee-dev commented
You know, regarding block chance, you could make stacking multiple sources have rapidly diminishing returns or just make it so the object with the highest block chance applies and all the others are ignored.

2023-08-01 20:55 UTC, MarkSuckerberg requested changes
just this

2023-08-01 20:55 UTC, MarkSuckerberg commented on code/modules/mob/living/carbon/human/human_defense.dm
> +		if(!istype(I, /obj/item/clothing) || get_active_held_item(I) || istype(I ,/obj/item/shield))
```suggestion
		if(!istype(I, /obj/item/clothing) || I == get_active_held_item() || istype(I ,/obj/item/shield))
```

2023-08-03 17:28 UTC, MarkSuckerberg approved these changes
forgot i have to clear my change request to make this merge

2023-08-03 17:43 UTC, merged