Jungle Botany Redo 2 Electric Boogaloo
shiptest-ss13/Shiptest pull request #2188
Opened 2023-07-21 18:47 UTC by Addust

## About The Pull Request

redesigns jungle botany to be Good
will write more later

## Why It's Good For The Game

old jungle botany was LITERALLY A KILO-CLASS SHIP _**WHAT THE FUCK**_

## Changelog

:cl:
add: new jungle botany! try not to FUCKING DIE!
/:cl:

2023-07-21 20:30 UTC, goober3 commented
![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/9d551ce8-3759-4bdd-8f95-7bad133a8222)
thank u mapdiffbot, very helpful

2023-07-23 19:43 UTC, spockye reviewed
![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/5cc8d322-862e-4acc-a318-8042faf22f62)

For being a botany ruin, the Botany element of it does feel kind of... minor to me. think you could make it a bit more central to the ruin, or atleast expand on it a bit more?

2023-07-24 00:11 UTC, PrefabQuasar commented
please include a picture of the ruin in both your mapping software and ingame

2023-08-08 17:33 UTC, Bjarl requested changes
https://github.com/shiptest-ss13/Shiptest/pull/1972#pullrequestreview-1461432521
I'm not gonna copy paste my entire review but this needs to be addressed

2023-08-08 17:33 UTC, Bjarl commented on _maps/map_catalogue.txt
> +		Tags = "Medium Combat Challenge", "High Loot", "Liveable"
```suggestion
		Tags = "Medium Combat Challenge", "Major Loot", "Liveable"
```

2023-08-08 17:33 UTC, Bjarl commented on code/game/area/areas/ruins/jungle.dm
> +/area/ruin/jungle/botanicalresearch/caves
use /area/overmap_encounter/planetoid/cave/explored.

2023-08-20 21:25 UTC, spockye commented
Creator does not intend on working on it

2023-08-20 21:25 UTC, closed without merging