Adds elf ears for humans.
shiptest-ss13/Shiptest pull request #2204
Opened 2023-07-27 02:18 UTC by Higgin

## About The Pull Request

Adds a small cosmetic genemod for humans - elf ears.

## Why It's Good For The Game

Lore-friendly customization options... good? This also includes a new define to make future recolorable sprite accessories for humans mirror their skin-tones, code help thanks to @MarkSuckerberg 

Original ears from [Skyrat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/675).

## Changelog

:cl:
add: Adds elf ears.
/:cl:

![image](https://github.com/shiptest-ss13/Shiptest/assets/3894717/8edc89ae-acc7-40ac-a8e6-03c19293d84e)
![image](https://github.com/shiptest-ss13/Shiptest/assets/3894717/dd5db8ff-6c80-4dcf-a409-ab4c4236dd6e)
![image](https://github.com/shiptest-ss13/Shiptest/assets/3894717/4bf7baae-ee54-4577-991d-bc7c2659014f)

2023-07-28 01:51 UTC, MarkSuckerberg requested changes
just this, pretty much!

2023-07-28 01:51 UTC, MarkSuckerberg commented on code/modules/surgery/organs/ears.dm
> +		color = ear_owner.skin_tone
```suggestion
		color = skintone2hex(ear_owner.skin_tone)
```

2023-07-30 09:15 UTC, thgvr commented
Any chance you could make these use the same greyscale pallette as human parts?

2023-08-01 20:45 UTC, MarkSuckerberg approved these changes
code is good, though I do think it would be nice if you could re-palette the ears. Shouldn't be too difficult!

2023-08-02 07:56 UTC, Higgin commented
![image](https://github.com/shiptest-ss13/Shiptest/assets/3894717/4ebe7d2b-ac69-44c1-8ca2-0024c5c9824f)
![image](https://github.com/shiptest-ss13/Shiptest/assets/3894717/8e87ae38-0fb7-454b-a8cd-2532966d7037)
![image](https://github.com/shiptest-ss13/Shiptest/assets/3894717/328ffce2-63f3-4a79-918c-8ea95195c8b0)
@thgvr @MarkSuckerberg applied the greyscale human palette, how's this look?

2023-08-02 18:48 UTC, thgvr approved these changes

2023-08-03 05:08 UTC, merged