IRMG Vaquero-class Light Frigate
shiptest-ss13/Shiptest pull request #2214
Opened 2023-07-30 06:44 UTC by Apogee-dev

## About The Pull Request

![vaquero](https://github.com/shiptest-ss13/Shiptest/assets/60533805/06518b7c-911f-499c-88a1-45157a78c0a5)
![vaquero_areas](https://github.com/shiptest-ss13/Shiptest/assets/60533805/6adc1014-cf92-4dac-9458-d4c6efdd31c1)

Adds the Vaquero-class Light Frigate, a small (7 players) Inteq generalist to fill the frankly terrible shoes the Hound left behind. While the Vaquero has all the features expected of an Inteq ship (meeting room, armory, large cargo bay, boombox), it actually has average engineering gear in combination with a full set of surgical tools and table, making it much more well-rounded than the other Inteq ships, even if it pays for this by only being lightly armed, with 3 pistols, and having a small footprint and crew capacity.

The Vaquero has a crew capacity of 7:
- one Vanguard
- one Master-At-Arms to run the armory and function as second-in-command
- one Enforcer
- one Artificer
- one Corpsman
- two Recruits

## Why It's Good For The Game

A generalist rounds out the Inteq catalogue nicely, and helps balance out the fact that all of the Inteq specialists are positively enormous.

## Changelog

:cl:
add: Added the IRMG Vaquero
/:cl:

2023-07-30 23:00 UTC, Bjarl requested changes
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/b49d103c-5414-4931-b38a-161e69114091)
I am firmly against terminals over catwalks.
![dreamseeker_GDIU0mylTM](https://github.com/shiptest-ss13/Shiptest/assets/94164348/ed83ec58-fa58-4ac5-a429-63ce62ce4fe6)
speaking of, the fuel crate needs to be subtyped, not var-edited.
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/f2ea241c-cf6c-45b9-9e40-33a95cb45872)
the SSU is eating the intercom. This is an intercom as items problem, but. For now just move the intercom.
![dreamseeker_fCQlaNLUHI](https://github.com/shiptest-ss13/Shiptest/assets/94164348/22520630-9098-4c33-adfc-644a221ef498)
A third light would not hurt
![StrongDMM_LcF21kaCBl](https://github.com/shiptest-ss13/Shiptest/assets/94164348/24b34a5c-bfd3-4cac-9595-b57e1fa6da3d)
the order of objects here should be table - fridge - plant - table
![StrongDMM_vrzSxPfiFR](https://github.com/shiptest-ss13/Shiptest/assets/94164348/e21f8b67-3708-4c86-bf40-573f08f83305)
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/c7e65c31-2d7a-400a-8960-816585ee2530)
no wallmounts adjacent to stairs (think of how it'd look irl), no stacked wallmounts
![StrongDMM_eNe0sSuPIY](https://github.com/shiptest-ss13/Shiptest/assets/94164348/6afc3354-9038-4d62-a450-88347e4b6dad)
the DOCKS are GOING TO STACK
The mobile dock should be facing in towards the ship anyways. I recommend putting it up front. You can just set the dheight var on it to the distance to the edge, and the template will be happy.
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/57d79197-caf6-4b1a-ba05-b2b3213ab8f7)
Now I know the template says /lethal but it doesn't work right now. I'd just use the normal one.
![dreamseeker_cHw1sFUDAL](https://github.com/shiptest-ss13/Shiptest/assets/94164348/d6655566-f816-431f-88bd-ff23bc4b6996)
I would put the fax on the rear table, and toss a table wideband down in it's place.
![StrongDMM_VokSkf7CT0](https://github.com/shiptest-ss13/Shiptest/assets/94164348/ddb51cd1-ac8b-4671-b089-b173d34a7f3f)
this layout does not work consistently. Mainly because eventually contaminants will get into the loop.
![StrongDMM_gzYdQFZQ4U](https://github.com/shiptest-ss13/Shiptest/assets/94164348/ee0fa9af-e86f-4df9-a96a-25f6cadc1bd8)
Move the blast doors in a tile so they don't cover the engines. It's a style thing I've been trying to enforce for a bit
![StrongDMM_3RIOKhR3Gl](https://github.com/shiptest-ss13/Shiptest/assets/94164348/2aff3543-6516-4692-92d5-6dbf53d0a986)
using the burnt no smoking sign might be funny here

2023-07-30 23:00 UTC, Erikafox commented on _maps/configs/inteq_vaquero.json
> +		"INTEQ"
```suggestion
		"BEASTS",
		"INTEQ"
```

2023-07-30 23:00 UTC, Bjarl commented on _maps/configs/inteq_vaquero.json
> +	"map_name": "Vaquero-Class Light Frigate",
not sold on the name honestly. Very Solar flavoring. The lorbs might have some animal (perhaps a kalixian draft beast) that fits better.

2023-07-30 23:20 UTC, Apogee-dev commented
>fax machine
I want to leave the fax machine at the front just so it's next to all the "functional" parts of the bridge. Don't really want to have to switch that table and the one with the cigars and sundries that's all next to the vanguard's living space.

>namelist changes
No problem with doing this, I'm just curious why you want them trimmed down.

>ship name
It's a reference to this ship's design inspiration, the Cowboy-class frigate, from a Starsector mod, just like the Talos was a sideways reference to the Tarsus (and that name's also explicitly terran in origin, too). I don't want to get too far away from that.

2023-07-30 23:22 UTC, Bjarl commented
>No problem with doing this, I'm just curious why you want them trimmed down.

It lets the inteq namelist roll more often, which is good Solid Faction Flavoring

2023-08-03 10:05 UTC, spockye reviewed
![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/22e3a0c0-3ca7-4145-ae76-c2289526065d)
make these the interior type. the tiles under the holofans start without air.

2023-08-18 02:40 UTC, Bjarl approved these changes

2023-08-19 18:12 UTC, spockye approved these changes

2023-08-20 06:27 UTC, merged