Mudskipper-class Salvage Runner
shiptest-ss13/Shiptest pull request #2224
Opened 2023-08-01 01:54 UTC by goober3

## About The Pull Request
![mudskipper](https://github.com/shiptest-ss13/Shiptest/assets/118859017/037ab2bd-adb5-417c-8e75-20f2f239e87f)
![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/725f610d-a5c4-4cfd-bdd4-29f8bf4a1969)
![mudskipper-area](https://github.com/shiptest-ss13/Shiptest/assets/118859017/3f943276-2c11-4386-bf49-6711620d6b4d)

adds the mudskipper-class salvage runner, an independent replacement to the scav-class. the mudskipper is a small, budget scavenger vessel, housing only 4 crewmembers, it specializes heavily in ruin-raiding & salvage, at the cost of lacking in every other department. it also boasts a much lower depressurize-ability compared to the original scav-class. yippee

## Why It's Good For The Game

the scav-class was an egregious excuse of a ship. this PR will banish it to The Pit.

## Changelog

:cl:
add: the mudskipper-class salvage runner, the scavenging successor to the scav.
balance: the scav-class has been disabled. 
/:cl:

2023-08-01 02:34 UTC, Bjarl requested changes, later dismissed
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/c31d3a28-93fa-4331-80ad-c009f91db9f6)
chemical lasers 2030
![StrongDMM_jVZ5aLIyj6](https://github.com/shiptest-ss13/Shiptest/assets/94164348/27556f4d-9af9-4620-919f-59ca0b2b5c92)
use some shitty retro consoles
![StrongDMM_gIlduc7Zgi](https://github.com/shiptest-ss13/Shiptest/assets/94164348/582ed0d8-49e3-40cf-84cb-e5433a07a650)
enshitten it with ration packs
![StrongDMM_ZchHtF2h2m](https://github.com/shiptest-ss13/Shiptest/assets/94164348/12bafac4-d490-4c76-8188-41fcc25cafe3)
give them the burnt no smoking thing 
![StrongDMM_cnfeaeRGxC](https://github.com/shiptest-ss13/Shiptest/assets/94164348/730e637e-89c9-439a-a9b1-f4b5e5b78a76)
This should be a potted plant
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/efa67905-d6d0-407e-8449-cd71a52f51c7)
this sprite only has 1 dir just so you know
@Imaginos16 come hither cruft boy
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/dfc3c8e4-d759-4c7b-8256-041d06d1aaae)
I would give them a connector and a can or two, honestly.

2023-08-01 02:34 UTC, Bjarl commented on _maps/configs/independent_scav.json
just remove it

2023-08-01 02:42 UTC, goober3 commented
> use some shitty retro consoles

when they add connected retro consoles!!

> enshitten it with ration packs

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/98d0216b-ffda-4b38-80a9-3d8304d8db3d)
i already threw this in here. so the lizard players wouldnt starve

thank yuo for reviewing my PR erika shiptest i will now address your review bye bye

2023-08-01 03:34 UTC, Bjarl commented on _maps/configs/independent_mudskipper.json
please make their starting funds lower. there should be a few examples in ship configs.

2023-08-01 13:56 UTC, spockye reviewed
![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/34238a2b-ff34-4ca7-a978-ec224dd2c672)

unconnected Scrubber

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/8d7e9681-2272-4df9-ada9-dff4940907b2)

i'd say rotate these. mabye put some radios on the table aswell?

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/ab3e1fbc-e878-4620-81bb-efad8014976e)

dont use that one. it wont store the suit inside automatically. use the Inherit subtype

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/18d32d9f-8c05-46fd-8ea8-33b4f1a3c6ea)

i would say give them a normal energy gun. Scatter is a bit stronk

2023-08-01 13:58 UTC, spockye commented
nevermind, im blind

2023-08-01 17:46 UTC, goober3 commented
> i'd say rotate these. mabye put some radios on the table aswell?

i rotated the cryo pods in a way that someone could crawl out of them easily & unobstructed. sideways is best, i think.

> i would say give them a normal energy gun. Scatter is a bit stronk

i've tested this and i would call it a sidegrade. the scatter gun deals more damage at the cost of draining faster. and the captain gets it cause they're special-er than everyone else.

2023-08-02 21:53 UTC, Xylarr commented
Cryo room has no cryo overseer thing and as a salvage ship it could use a pickaxe or two

2023-08-03 23:26 UTC, goober3 commented
whdhsadufdfhghf

2023-08-18 17:55 UTC, merged