Revamps wasteplanet_unhonorable
shiptest-ss13/Shiptest pull request #2256
Opened 2023-08-07 03:54 UTC by Dethstorm

## About The Pull Request
Revamps all of wasteplanet_unhonorable to not be a mess of a ruin. (screenshots pending)

## Why It's Good For The Game
Because bad ruins are bad.

## Changelog

:cl:
add: new stuff to wasteplanet_unhonorable
add: new areas for wasteplanet_unhonorable
/:cl:

2023-08-07 04:04 UTC, Dethstorm commented
Made a PR for the sole reason of knowing what's causing conflicts.

2023-08-07 18:04 UTC, Bjarl requested changes
Please remember to update the map catalog (_Maps/map_catalog.txt) to reflect the changes you've made here

The exterior of the area could use more fluff. I recommend putting down dirty decals, maybe some warning signs, a few light mobs (abandoned bots and maybe a hivebot or two), OR. Trim down what you have to just the ruin, and use turf passthrough + area passthrough to let the game set the ruin's surroundings up for you.

The area surrounding the ruin should be /overmap_encounter/planetoid/wasteplanet/explored, It'll let the area have weather.

![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/af00506f-6574-4ad9-8730-9dba6a6266ee)
replace these tiles with the wasteplanet variants. That should fix your main airlock not working
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/7a1504b0-ce5a-49da-ac53-a1cbbc5b5ebf)
no need for cycle link helpers here or at the other airlock, the AAC handles it automatically.

Speaking of, the internal one is bugged, but I think that's alright here. It keeps players from going into radiation hell quickly.
![StrongDMM_yLmwdjas28](https://github.com/shiptest-ss13/Shiptest/assets/94164348/ae4d2b9d-fdd9-4b0c-89e7-924480945e1c)
Some more decalling would be bitchin, plus maybe some firelocks sprinkled under the doors.

It is certainly an improvement on the previous iteration, so congrats.

2023-08-07 18:04 UTC, Bjarl commented on code/game/area/areas/ruins/wasteplanet.dm
> +	requires_power = TRUE
```suggestion
```

2023-08-07 18:04 UTC, Bjarl commented on code/game/area/areas/ruins/wasteplanet.dm
> +	requires_power = TRUE
```suggestion
```

2023-08-07 18:04 UTC, Bjarl commented on code/game/area/areas/ruins/wasteplanet.dm
> +	requires_power = TRUE
```suggestion
```

2023-08-07 22:34 UTC, Dethstorm commented
Cycle link helpers were removed and tiles were changed, but I can't get the cycling airlock to work. Screenshots Soon TM?

2023-08-08 03:59 UTC, Bjarl submitted a review, later dismissed
unless you intend for the outdoors to be unlit, use the /lit tile variants there
![StrongDMM_XEEYwmDiAf](https://github.com/shiptest-ss13/Shiptest/assets/94164348/d27f51c9-d53f-403e-aa6f-8cdd38c2a65c)
replace the tiles in here with good atmos tiles (the ones you use inside), may solve the issue with the AAC

How'd you swap the areas? I tested it on my local like such
![2023-08-07 20 59 04](https://github.com/shiptest-ss13/Shiptest/assets/94164348/00e70109-bb29-4cb8-bb28-f9ebd40f2dac)
and I didn't see any issues with it

2023-08-08 19:01 UTC, Dethstorm commented
> unless you intend for the outdoors to be unlit, use the /lit tile variants there ![StrongDMM_XEEYwmDiAf](https://user-images.githubusercontent.com/94164348/258979552-d27f51c9-d53f-403e-aa6f-8cdd38c2a65c.png) replace the tiles in here with good atmos tiles (the ones you use inside), may solve the issue with the AAC
> 
That bit of the ruin doesn't really need lighting; it's abandoned and the light bulb's broken, don't see a reason to use /lit variants. Switched the tiles around, I think the AAC works now but there's one issue left; the pressure doesn't really rise:
<img width="214" alt="Screenshot_2375" src="https://github.com/shiptest-ss13/Shiptest/assets/88121917/27c71629-8a0d-43e9-b77e-ee4c506c1236">

> How'd you swap the areas? I tested it on my local like such ![2023-08-07 20 59 04](https://user-images.githubusercontent.com/94164348/258980656-00e70109-bb29-4cb8-bb28-f9ebd40f2dac.png) and I didn't see any issues with it
> 
Areas were switched to "/area/ruin/wasteplanet/wasteplanet_radiation" from "area/overmap_encounter/planetoid/wasteplanet/explored". The latter caused any turfs marked with that area to be replaced with planet generation.
The only possible issue this might cause is the lack of weather in the area, but I don't think that's too big of a problem.

2023-08-08 19:04 UTC, Bjarl commented
> > unless you intend for the outdoors to be unlit, use the /lit tile variants there ![StrongDMM_XEEYwmDiAf](https://user-images.githubusercontent.com/94164348/258979552-d27f51c9-d53f-403e-aa6f-8cdd38c2a65c.png) replace the tiles in here with good atmos tiles (the ones you use inside), may solve the issue with the AAC
> 
> That bit of the ruin doesn't really need lighting; it's abandoned and the light bulb's broken, don't see a reason to use /lit variants. Switched the tiles around, I think the AAC works now but there's one issue left; the pressure doesn't really rise: <img alt="Screenshot_2375" width="214" src="https://user-images.githubusercontent.com/88121917/259201985-27c71629-8a0d-43e9-b77e-ee4c506c1236.png">


That area is fine, I said the outdoors (so everything surrounding the ruin)

2023-08-08 19:06 UTC, Dethstorm commented
Ah I think the outdoors should be fine as unlit

2023-08-18 02:32 UTC, Bjarl approved these changes

2023-09-04 20:16 UTC, spockye approved these changes
a 100% improvement, good work!

2023-09-04 20:22 UTC, spockye commented
I'll Merge this once checks pass. 
Send me a message in ruinyard if you need any help!

2023-09-05 13:01 UTC, Dethstorm commented
> I'll Merge this once checks pass. Send me a message in ruinyard if you need any help!

Oh I has forgotten about this. I'll check it once I get home. May or may not need help

2023-09-09 15:22 UTC, Dethstorm commented
Ready for merging.

2023-09-10 11:33 UTC, merged