Fuck you
shiptest-ss13/Shiptest pull request #2257
Opened 2023-08-07 06:06 UTC by Bjarl

## About The Pull Request
![2023-08-06 20 34 27](https://github.com/shiptest-ss13/Shiptest/assets/94164348/e22adb54-414b-4604-947e-b4553948c4e4)
![2023-08-06 20 34 30](https://github.com/shiptest-ss13/Shiptest/assets/94164348/9c72a85e-364b-4cde-8ec2-4ce2b8ed3ee6)
![2023-08-06 20 36 48](https://github.com/shiptest-ss13/Shiptest/assets/94164348/8bf719d0-2dfa-450d-a94a-c746913c1e77)
remaps the shitty fucking wasteplanet ruin

adds concrete caves to wasteplanets.

https://github.com/shiptest-ss13/Shiptest/assets/94164348/815e4b59-d562-48f3-aa50-ca45f7e25315

## Why It's Good For The Game
i am the content slave and this shit is fucking awesome.

## Changelog

:cl:
add: wasteplanets now spawn concrete caves
add: Patrician-Class Trader Shuttle
add: wasteplanet_tradepost has been remade
add: acid proof marker beacons. it's self explanatory.

/:cl:

2023-08-07 06:21 UTC, meemofcourse commented
fuck you baltimore!

2023-08-07 08:07 UTC, Latentish commented
Poggers?

2023-08-07 12:36 UTC, ZephyrTFA commented
Really do not appreciate getting an email titled "Fuck You" from github.
![image](https://github.com/shiptest-ss13/Shiptest/assets/12817816/58251db8-5936-47da-be70-16c7d361e8ba)

2023-08-07 12:57 UTC, goober3 commented
![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/46cf1124-f35e-40f8-a43e-6ca685282986)

2023-08-07 18:22 UTC, spockye requested changes
![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/4762a588-6785-4c7e-81b3-5170fa4f277a)

atmos fuckies


![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/d829a75f-e066-4fb0-b8fe-e0854cd7e462)

cable fuckies

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/d812b331-ffda-4e4b-bdeb-a255e2d436bf)

both doors and buttons use the same ID. 

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/8e3009c4-099f-42d2-baf0-9f358efff358)

no button for the engine shutters

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/ab69df69-a98c-4c07-a8d3-53b6af64cedb)

powered holofans might be good to add here. 

could use some more decalling inside the building, could also use some kind of canteen/recreational room? Since its seems like a long term deployment

mabye add some extra threats in the main room, seeing that the loot is pretty good?
big hivebot.....


this is a massive improvement (and i like the setting)

2023-08-07 19:02 UTC, Bjarl commented
>could use some more decalling inside the building, could also use some kind of canteen/recreational room? Since its seems like a long term deployment

It's intentionally pretty spartan, but I did add some mild "people ate here" greebling to a few spots. Review otherwise addressed

2023-10-28 02:38 UTC, Latentish requested changes

2023-10-28 02:38 UTC, Latentish commented on _maps/map_catalogue.txt
> +		Size = (x = 57(y = 51(z = 1)
It should be like (x = 57)(y = 51)(z = 1)

2023-11-19 14:54 UTC, closed without merging