Pill Press
shiptest-ss13/Shiptest pull request #2275
Opened 2023-08-11 07:09 UTC by GenericDM

## Pill Press!
This will add a lacking feature in ghettochem, the ability to produce pills.

### todo

- [ ] Sprites!
- [x] Make it work!
- [ ] Figure out how to select what pill type you want to use, when altclick, screwdriver, and wrench are all taken!
- [ ] Get yelled at by coders probably!
- [ ] Fix my shitcode!
- [ ] Learn how overlays work!
- [ ] Re-path it to be more in-line with other chem devices
---
As of now, you can insert a beaker, with optional pill bottle, to produce pills up to 30u.
You can adjust the size of the pills produced with a screwdriver.
The machine can be placed onto tables, or dragged around.

:cl:
add: Adds a hand-powered pill press for ghetto chemistry.
/:cl:

2023-08-11 07:10 UTC, GenericDM commented
i should learn how to squash commits, that would be a good idea

2023-08-16 22:10 UTC, Imaginos16 approved these changes
Sprotes are fine for now, good hackjob honestly.

2023-08-18 06:24 UTC, MarkSuckerberg approved these changes
seems good!

2023-08-22 04:04 UTC, thgvr requested changes

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +		to_chat(user, "<span class='warning'>There's no container in [src]!.</span>")
```suggestion
		balloon_alert(user, "no container!")
```

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +		to_chat(user, "<span class='warning'>[beaker] is empty!")
```suggestion
		balloon_alert(user, "[beaker] empty!")
```

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +		to_chat(user, "<span class='notice'>You finish pressing a pill.</span>")
```suggestion
		balloon_alert(user, "finished pressing")
```

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +/obj/machinery/chem_press/attackby(obj/item/I, mob/living/user, params)
Descriptive vars, no `I` please

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +		to_chat(user, "<span class='notice'>You add [I] to the input slot [src].</span>")
```suggestion
		balloon_alert(user, "[I] added to input")
```

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +		to_chat(user, "<span class='notice'>You add [I] into the output slot of [src].</span>")
```suggestion
		balloon_alert(user, "[I] added to output")
```

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +					to_chat(user, "<span class='notice'>You adjust the press to produce [current_volume]u pills.</span>")
```suggestion
		balloon_alert(user, "making [current_volume]u pills")
```

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +					to_chat(user, "<span class='notice'>You adjust the press to produce [style_colors["[pill_style]"]] pills.</span>")
```suggestion
		balloon_alert(user, "making [style_colors["[pill_style]"]] pills")
```

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +				update_icon()
```suggestion
				update_appearance()
```

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +				update_icon()
```suggestion
				update_appearance()
```

2023-08-22 04:04 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +	update_icon()
```suggestion
	update_appearance()
```

2023-08-22 04:06 UTC, thgvr commented
Also, do you think you could add a construction recipe for this? It'd be useful even with outpost ordering. Stock part support optional.

2023-08-22 04:08 UTC, thgvr commented on code/modules/reagents/chemistry/machinery/chem_press.dm
> +		var/obj/item/reagent_containers/pill/P
Descriptive var names

2023-08-22 04:18 UTC, GenericDM commented
> Also, do you think you could add a construction recipe for this? It'd be useful even with outpost ordering. Stock part support optional.

What would you suggest for this? I had intended on making a recipe, but couldn't come up with any ideas for it.

2023-08-25 17:00 UTC, thgvr approved these changes

2023-08-27 00:07 UTC, Imaginos16 commented
im merging this lmao

2023-08-27 00:22 UTC, merged