Make IPC able to recharge/repair at borg station
shiptest-ss13/Shiptest pull request #2284
Opened 2023-08-13 14:54 UTC by ritorizo

## About The Pull Request

IPC will now recharge/repair like borg when they get into a borg recharger.

## Why It's Good For The Game

Robort <3

## Changelog

:cl:
add: IPC can now recharge/repair at borg recharge station.
/:cl:

2023-08-13 20:22 UTC, thgvr requested changes

2023-08-13 20:22 UTC, thgvr commented on code/modules/mob/living/carbon/human/species_types/IPC.dm
> +	if(repairs)
Please do not add repairing into these, IPCs are already incredibly easy to fix.

2023-08-14 13:25 UTC, ritorizo commented on code/modules/mob/living/carbon/human/species_types/IPC.dm
> +	if(repairs)
Done

2023-08-18 06:50 UTC, MarkSuckerberg requested changes

2023-08-18 06:50 UTC, MarkSuckerberg commented on code/modules/mob/living/carbon/human/species_types/IPC.dm
> +		C.RegisterSignal(C, COMSIG_PROCESS_BORGCHARGER_OCCUPANT, /mob/living/carbon/proc/charge)
```suggestion
		C.RegisterSignal(C, COMSIG_PROCESS_BORGCHARGER_OCCUPANT, TYPE_PROC_REF(/mob/living/carbon, charge))
```

2023-08-18 22:27 UTC, thgvr approved these changes

2023-08-20 15:26 UTC, MarkSuckerberg approved these changes

2023-08-20 15:58 UTC, merged