New Sand Planet Ruin: Alien Facility
shiptest-ss13/Shiptest pull request #2353
Opened 2023-09-14 03:16 UTC by Draggeru

## About The Pull Request

Adds a completely new ruin to the game, an alien facility on sand planets.
SDNM View:
![2023-09-13 20 25 31](https://github.com/shiptest-ss13/Shiptest/assets/81540056/59f1ec93-4bb5-43dc-8d98-812f1bc9e18a)

In Game View:
![ruin 1](https://github.com/shiptest-ss13/Shiptest/assets/81540056/bd02b8a2-a59f-4c8b-a0fc-a97d7e258ba3)

My intent was to redo a map in the deprecated files, but the one I picked had abductor stuff. Which abductors no longer exist in the lore, so I swapped it out for xenos instead.

## Why It's Good For The Game

New ruins = good. New ruins with more than 2 braincells worth of effort = good. New Ruins also means I can bribe the maptainers into letting me PR a ship. :)

## Changelog

:cl:
add: Alien Facility ruin for sand planets
del: At least half of my braincells
/:cl:

2023-09-14 03:21 UTC, meemofcourse commented
> del: At least half of my braincells

don't keep this in ok thanks

2023-09-14 03:24 UTC, Draggeru commented
> > del: At least half of my braincells
> 
> don't keep this in ok thanks

:(

2023-09-19 10:27 UTC, spockye requested changes
![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/16cc1595-078c-45f9-bcdd-73479f3854f1)

missing cable

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/279d2b91-fa4d-498d-8e98-06b32a102732)

Resin walls dont count as turf walls. you need to put floors under them!

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/9dff14d7-82e6-49da-b718-265bfe023ccd)

please try to include some premade external areas around the two opening points. Pregen might cover them up fully, either making the exhaust, or entrance not end up well, functioning as intended. 

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/5cc4b7dd-bba3-427e-a1f2-f4a8ae5a8a26)

unconnected scrubber

![image](https://github.com/shiptest-ss13/Shiptest/assets/79304582/7ef67d34-a4ee-42d3-b5fe-df329bf35763)

please make your id's a bit more unique. include the name of the ruin or something!
helps with bugtesting later on

2023-09-19 11:26 UTC, Draggeru commented
> ![image](https://user-images.githubusercontent.com/79304582/268922406-16cc1595-078c-45f9-bcdd-73479f3854f1.png)
> 
> missing cable
> 
> ![image](https://user-images.githubusercontent.com/79304582/268922589-279d2b91-fa4d-498d-8e98-06b32a102732.png)
> 
> Resin walls dont count as turf walls. you need to put floors under them!
> 
> ![image](https://user-images.githubusercontent.com/79304582/268922847-9dff14d7-82e6-49da-b718-265bfe023ccd.png)
> 
> please try to include some premade external areas around the two opening points. Pregen might cover them up fully, either making the exhaust, or entrance not end up well, functioning as intended.
> 
> ![image](https://user-images.githubusercontent.com/79304582/268923525-5cc4b7dd-bba3-427e-a1f2-f4a8ae5a8a26.png)
> 
> unconnected scrubber
> 
> ![image](https://user-images.githubusercontent.com/79304582/268923758-7ef67d34-a4ee-42d3-b5fe-df329bf35763.png)
> 
> please make your id's a bit more unique. include the name of the ruin or something! helps with bugtesting later on

![2023-09-19 05 17 57](https://github.com/shiptest-ss13/Shiptest/assets/81540056/92d74762-9eb4-4897-8b07-4a7a861670d5)
Done

2023-09-22 19:45 UTC, thgvr requested changes
Remove the shrapnel mines.

2023-09-23 02:21 UTC, Draggeru commented
I have no idea why the integration test is failing

2023-09-23 03:00 UTC, immortalartisan commented
Check the details on the integration test seems to be something related to rad types

2023-09-23 03:34 UTC, MarkSuckerberg commented
Sorry, it's a random fail that's fixed in #2364, I'll just re-run them for you

2023-09-23 04:16 UTC, Draggeru commented
Oh I think I forgot a couple mines, don't TM this until I can get home to double check

2023-09-23 14:46 UTC, Draggeru commented
We're good now, I forgor about the mine at the top. All good for a test merge again.

2023-09-23 20:43 UTC, thgvr approved these changes

2023-09-30 14:58 UTC, goober3 requested changes
please add more exterior! even if it's just, like. an empty field -- symmetrical lines of terrain will look odd, especially if this ruin spawns inside a mountain.

2023-10-02 10:54 UTC, Draggeru commented
> please add more exterior! even if it's just, like. an empty field -- symmetrical lines of terrain will look odd, especially if this ruin spawns inside a mountain.

![Uploading 2023-10-02 04.51.58.png…]()
Done

2023-10-16 15:32 UTC, spockye commented
do you intend for those sandbags to be deployed? if that case use the sturcture version. not the Item

2023-10-21 23:56 UTC, Draggeru commented
> do you intend for those sandbags to be deployed? if that case use the sturcture version. not the Item

Oh, nah. I think I'll just axe em

2023-10-28 02:39 UTC, Latentish requested changes
You need to make a map catalogue entry.

2023-10-28 02:40 UTC, Latentish requested changes

2023-10-28 02:40 UTC, Latentish commented on config/sandruinblacklist.txt
> +#_maps/RandomRuins/SandRuins/whitesands_alien_facility.dmm
This is a deprecated file that we do not upkeep. You should not make changes to it.

2023-10-29 10:43 UTC, Draggeru commented
> You need to make a map catalogue entry.

Where is that in the code?

2023-10-30 07:50 UTC, Latentish commented
> Where is that in the code?

You updated a file called the sandruinblacklist.txt. It's listed in the changes you made. As for the mapcatalogue, it's a txt in the maps folder. There's another txt that's a key for adding new entries.

2023-11-07 22:23 UTC, meemofcourse requested changes
is this thing on? ok cool

i have a couple of issues with this ruin:
* the hive is very symmetrical and organized. i would not imagine a xenomorph hive as a giant cube
* there is a lot of engineering gear in what should be a medical ruin, notably the inclusion of an atmospherics setup, multiple canisters and generators, making the ruin be a strange atmos-chemical-medical mix. change this!

2023-11-07 22:26 UTC, meemofcourse commented
some other minor stuff:
* for what i imagine is a ruin raided by Unspecified Syndicate Force, it doesn't look very damaged. add some casings, broken glass, grilles and unsecured girders
* maybe try and make it less of a Square

2023-11-08 14:32 UTC, Bjarl requested changes
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/8d9c113d-a5a6-4522-8de8-bffd8b59f4cf)
All of your exterior plating are going to be active turfs because they start as airless.

![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/aa7a05cc-075d-4c7a-9142-794480d087cf)
Don't do this
Do this
![StrongDMM_uETgYtbZlJ](https://github.com/shiptest-ss13/Shiptest/assets/94164348/7c8a6ea0-ae98-459e-8e98-e0823babab25)

![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/5803c3dc-a5b7-4c1f-9427-27245ace1287)
Put dir on button

![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/7296b3d0-30c4-4c35-8715-19a9d7db6921)
Turn this into a proper laundering / cleaning area. It's spartan and the maint stuff sitting around hurts the image.

![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/0f51471e-d838-4601-a5bf-c55d7449ce8d)
Lockers should be on +-28
![StrongDMM_WA31ACVW5E](https://github.com/shiptest-ss13/Shiptest/assets/94164348/ef901629-5ce0-4008-b363-a7ea92b472f9)
no virology content
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/d4a3ebc4-eed1-4539-825a-27d5c1c2f664)
No brainrot please clean it *all* out

![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/3a5fce65-f642-458b-b8c8-ce84fa5a8e26)
This is a lot of food for a base that's in the middle of Shit Being Fucked. I would have some empty donk boxes and cut out an ingredient box.
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/806c8d4b-d44a-4839-a8e6-a79801ebd73d)
This is very boxy. Please make it more organic / overgrown. It should seem like a hive. Intentional, but in an alien way
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/003a340b-cab0-4b60-b1bd-b8a03c77a041)
All turfs on the inside ring should have a new subtype made with planetary atmos disabled (to show that they're closed air)
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/77a46c77-a3e4-449b-adbc-3a67a8a1da87)
Make this into a proper little shitty engineering locker room.
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/f267a516-7139-4adc-8f0b-b21044787395)
It would be cool if the threat was telegraphed by having the aliens starting to grow out of / against one of the walls
Needs a proper office (not a lobby), perhaps with some fluff reports and a fax machine.
Complete absence of light switches, the more civilian areas could use them.
![image](https://github.com/shiptest-ss13/Shiptest/assets/94164348/063671e2-ce62-4ebb-b101-84384a8dc537)
What is the story supposed to be with this plasma anyways. Is someone supposed to rush in and ignite it? Set up a vent that's been clearly jammed up to show that it's a countermeasure that's been circumvented.

2023-11-12 19:51 UTC, Draggeru commented
I've lost motivation to keep contributing to shiptest at current. Maybe I will revive this at some point down the line.

2023-11-12 19:51 UTC, closed without merging