Plasteel Combat Helmet - Shitty Civvie Hats, Because Why Not
shiptest-ss13/Shiptest pull request #2366
Opened 2023-09-20 19:37 UTC by Addust

## About The Pull Request

Adds the stamped plasteel combat helmet, a cheap (2 plasteel) helmet that is not good at staying on your head (can't fall off on its own, but can be stripped nearly instantly), and, if combined with leather, a lined stamped plasteel combat helmet, which is basically that but with lengthened strip time. Needs a welder for the unlined version.

i need spriting advice

## Why It's Good For The Game

Ghetto helmets, gentlemen? Gives people unique solutions for headgear while on planets.

## Changelog

:cl:
add: A new craftable helmet has been added! Costs 2 plasteel, you can also craft a lined version with some leather.
/:cl:

2023-09-20 22:30 UTC, BarteG44 commented
i applaud the soul

2023-09-20 23:38 UTC, retlaw34 requested changes
Repeating what I said on discord:

To be honest,  if you're going to make a makeshift helmet, make it look makeshift instead of making it look like a ww1 helmet.

The Eris makeshift helmet should give some ideas

The sprite's is a bit flat but I'd just make up a new design instead of touching it up 
For the obj, check how the other helmets are drawn, 3/4 to the side


![image](https://github.com/shiptest-ss13/Shiptest/assets/58402542/4fda3d90-2470-4c9c-b6e0-8a3098e07b2f)

2023-09-21 00:02 UTC, goober3 requested changes

2023-09-21 00:02 UTC, goober3 commented on _maps/outpost/outpost_test_2.dmm
> +	},
do not add a helmet to the outpost. thanks

2023-09-21 06:37 UTC, Bimbly commented
Plasteel is nigh impossible to get without an ORM which I feel kinda goes against the spirit of it being makeshift thrown together. I personally would have it made out of normal metal like the scrap armor. (also strip time isnt much of a downside if you want it to have a real one maybe have it make you nearsighted or something?)

2023-10-20 06:32 UTC, thgvr commented
Not a huge fan of the sprite, or the reliance on crafting menu stuff. I am also not convinced this has a place.

2023-10-25 19:21 UTC, Imaginos16 commented
Not particularly impressed by the PR, and Mark shared much of the same sentiments as I and the other reviewers. As such, I'll be closing the PR.

2023-10-25 19:21 UTC, closed without merging