ERT Minor Refactor, more ERTs, ERTs can now spawn on subshuttles
shiptest-ss13/Shiptest pull request #2395
Opened 2023-10-04 22:43 UTC by meemofcourse

## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/71348 and https://github.com/tgstation/tgstation/pull/56345, with code adapted for Shiptest. 

Also adds the following ERTs:
* NT Loss Prevention
* Frontiersmen
* Inteq
* Minutemen
  * Riot Control
  * BARD
  * GOLD Collector
* Syndicate
  * Gorlex Maruders
  * Cybersun Commando
  * Cybersun Paramedic
* SolGov
  * Sonnensoldner
  * Solarian Inspector

## Why It's Good For The Game

adminbus funny

## Changelog

:cl: Zonespace27, Ryll-Ryll, MeeMOfCourse
tweak: Admins can now spawn an unarmed horde of interns in addition to the old armed horde
tweak: Admins can toggle name randomization for ERT's, as well as if they'd like to be spawned in the briefing room at the time of creation
tweak: Admins can now force ERT's to pick the leader role from the most experienced candidates in terms of playtime
tweak: Menus like Create Response Team and Create Portal Storm now toggle boolean options when clicked, rather than open a popup window to select one of the two options
refactor: Centcom Officials are now a full subtype of ERT, rather than being a separate antagonist type with duplicated functionality
admin: ERTs can now have a custom shuttle that they can spawn on, on a toggle while creating said ERT.
admin: Shiptest-Specific ERTs, and respective files.
/:cl:

2023-11-08 15:39 UTC, Bjarl reviewed
assorted just balance thoughts.

2023-11-08 15:39 UTC, Bjarl commented on code/modules/clothing/outfits/ert/frontiersmen_ert.dm
> +	id_role = "Buccaneer"
Buccaneer is a really pirate brained name, not frontiersman. Give them something more strikingly militaristic.

2023-11-08 15:39 UTC, Bjarl commented on code/modules/clothing/outfits/ert/frontiersmen_ert.dm
> +	gloves = /obj/item/clothing/gloves/combat
basic guys don't need insulated gloves

2023-11-08 15:39 UTC, Bjarl commented on code/modules/clothing/outfits/ert/frontiersmen_ert.dm
> +	id_role = "Carpenter"
I curse spockye for adding the ember before I finished the Tobermoon. Militarism please.

2023-11-08 15:39 UTC, Bjarl commented on code/modules/clothing/outfits/ert/frontiersmen_ert.dm
> +	backpack_contents = list(/obj/item/ammo_box/n762_clip=3, /obj/item/binoculars=1, /obj/item/melee/classic_baton/telescopic)
I do not care for stun combat. Give them like... a nice knife.

2023-11-08 15:39 UTC, Bjarl commented on code/modules/clothing/outfits/ert/inteq_ert.dm
I'd add Inteq to all the id_roles here.

2023-11-08 15:39 UTC, Bjarl commented on code/modules/clothing/outfits/ert/inteq_ert.dm
> +	suit_store = /obj/item/gun/ballistic/automatic/assault/ak47/inteq
the ak is pretty powerful. It'd be nice to have a semi auto rifle of some flavor that isn't a DMR.

2023-11-08 15:39 UTC, Bjarl commented on code/modules/clothing/outfits/ert/inteq_ert.dm
> +	suit_store = /obj/item/gun/ballistic/shotgun/bulldog/inteq
give them a combat shotgun imo.

2023-11-08 19:08 UTC, meemofcourse commented on code/modules/clothing/outfits/ert/inteq_ert.dm
whar. shouldn't there be distinction between each other

2023-11-09 02:53 UTC, MarkSuckerberg requested changes
just some minor things

2023-11-09 02:53 UTC, MarkSuckerberg commented on code/modules/admin/verbs/one_click_antag.dm
> +			return FALSE
```suggestion
		if(!length(candidates))
			to_chat(usr, span_warning("No applicants for ERT. Aborting spawn."))
			return FALSE
```

2023-11-09 02:53 UTC, MarkSuckerberg commented on code/modules/admin/verbs/one_click_antag.dm
> +				to_chat(usr, "<span class='warning'>Could not spawn you in as briefing officer as you are not a ghost!</spawn>")
```suggestion
				to_chat(usr, span_warning("Could not spawn you in as briefing officer as you are not a ghost!"))
```

2023-11-18 20:21 UTC, thgvr requested changes

2023-11-18 20:21 UTC, thgvr commented on code/modules/clothing/outfits/ert/nanotrasen_ert.dm
> +		/obj/item/gun/energy/e_gun/stun=1,\
```suggestion
		/obj/item/gun/energy/e_gun/hades=1,\
```

2023-11-18 20:22 UTC, thgvr approved these changes

2023-11-19 08:53 UTC, Admiral-Gigaton commented
cant wait for an event where the admins just spawn like 8 pills total, load them with syndie/NT ERTs, and send them out to battle to the death

2023-11-22 08:01 UTC, thgvr commented
It seems fine in TMs but there's still some issues I believe with erts spawning at centcom. I'll take a thorough look this weekend.

2023-12-06 04:37 UTC, MarkSuckerberg commented on code/modules/clothing/outfits/ert/nanotrasen_ert.dm
> +		/obj/item/gun/energy/pulse/carbine/loyalpin=1)
```suggestion
		/obj/item/melee/baton/loaded=1)
		suit_store = /obj/item/gun/energy/pulse/carbine/loyalpin
```
it don't fit

2023-12-12 00:46 UTC, MarkSuckerberg approved these changes
very good pr

2023-12-12 01:00 UTC, merged