Ranger Class fixes
shiptest-ss13/Shiptest pull request #2410
Opened 2023-10-16 16:30 UTC by spockye

## About The Pull Request
adds:
cell charger
weapon charger
two flashes and a cell (so you can actually make a shell for the AI)

## Why It's Good For The Game
errors requested to be fixed by Latency

## Changelog

:cl:
add: Added a couple missing things to the Ranger Class
/:cl:

2023-10-30 08:03 UTC, Latentish commented
please fix your merge conflict so we can tm and marg

2023-11-02 21:23 UTC, Latentish requested changes
Please change the flashes to the box of flashbulbs. The ones you used don't actually work with the shell.
Please add a camera setup in the northern maintenance room like there is in the southern one.
Please add an NT comms channel to the comms setup.

2023-11-08 15:09 UTC, Bjarl approved these changes

2023-11-11 05:13 UTC, Latentish commented
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/f6f57a88-b4c8-4a02-b76d-975e2016539f)
Wall laptap please fix.

2023-11-21 20:09 UTC, closed without merging