SUNS sprites wave 1. Clothing
shiptest-ss13/Shiptest pull request #2439
Opened 2023-10-29 10:51 UTC by Draggeru

## About The Pull Request

Adds a bunch of faction sprites for SUNS. This PR ONLY has clothing.

![suns sprites](https://github.com/shiptest-ss13/Shiptest/assets/81540056/bde939c3-534a-4d05-b0a0-a782d611d4dd)
Not pictured: The CMO coat and SUNS soft spacesuits since they're being bastards.

This PR does NOT introduce these sprites anywhere in the game, it simply adds them to the code.

## Why It's Good For The Game

Factions having their sprites is good.

Current todo:
- [ ] Fix the SUNS soft suit helmet and suit
- [ ] Fix the CMO coat
- [ ] Fix the XO beret's type path so that it's not confusing
- [ ] Add a bulletproof vest for SUNS peacekeepers
- [ ] Fix the scientist labcoat so that it works as a toggleable hood
- [ ] Add the captains mask because I forgor

:cl:
add: Adds all of the clothing intended for SUNS. Including uniforms for the captain, xo, cmo, scientists, miners, engineers, and doctors
/:cl:

2023-10-29 11:05 UTC, retlaw34 commented
✨

2023-10-30 11:29 UTC, Draggeru commented
Why is run linters failing gwuh

2023-10-30 15:18 UTC, GenericDM commented on code/modules/clothing/under/accessories.dm
You missed a bunch of leading slashes in this, meaning the type paths are defined relatively instead of absolutely.

2023-11-01 11:50 UTC, Draggeru commented
Ready for review but I also have no idea why Integration is failing

2023-11-04 22:18 UTC, GenericDM requested changes
Lots of minor stylistic/spelling errors. Feel free to tweak the suggestions as you see fit.

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/gloves/color.dm
> +	name = "Academic staff gloves"
```suggestion
	name = "academic staff gloves"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/armor.dm
> +	name = "Peacekeeper Plating"
```suggestion
	name = "peacekeeper plating"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/armor.dm
> +	name = "Gilded Peacekeeper Plating"
```suggestion
	name = "gilded peacekeeper plating"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/armor.dm
> +	desc = "A funky armored coat worn by essentric peacekeepers. Closing the coat is socially impropper."
```suggestion
	desc = "A funky armored coat worn by eccentric peacekeepers. Closing the coat is socially improper."
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/armor.dm
> +	name = "\improper Decorated academic coat"
```suggestion
	name = "decorated academic coat"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/armor.dm
> +	desc = "A funky armored coat worn by essentric peacekeepers. Closing the coat is socially impropper."
```suggestion
	desc = "A funky armored coat worn by eccentric peacekeepers. Closing the coat is socially improper."
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/armor.dm
> +	name = "\improper Peacekeeper Greatcoat"
```suggestion
	name = "peacekeeper greatcoat"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/gloves/color.dm
> +	name = "SUNS captain's gloves"
```suggestion
	name = "\improper SUNS captain's gloves"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/head/berets.dm
> +	desc = "A soft beret sporting a discontinued inkwell quill feather. If only it could hold ink once more"
```suggestion
	desc = "A soft beret sporting a discontinued inkwell quill feather. If only it could hold ink once more."
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/head/jobs.dm
> +	desc = "A black cap worn by the more essentric peacekeepers."
```suggestion
	desc = "A black cap worn by the more eccentric peacekeepers."
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/head/misc.dm
> +	name = "Suns surgery cap"
```suggestion
	name = "\improper SUNS surgery cap"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/head/misc.dm
> +	desc = "A hat worn by the more essentric medical staff."
```suggestion
	desc = "A hat worn by the more eccentric medical staff."
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/head/misc_special.dm
> +	name = "Peackeeper Visor"
```suggestion
	name = "peacekeeper visor"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/head/misc_special.dm
> +	name = "Gilded Peackeeper Visor"
```suggestion
	name = "gilded peacekeeper visor"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/masks/breath.dm
> +	name = "SUNS half face mask"
```suggestion
	name = "\improper SUNS half face mask"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "\improper SUNS Peacekeeper hardsuit helmet"
```suggestion
	name = "\improper SUNS peacekeeper hardsuit helmet"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "\improper SUNS Peacekeeper hardsuit"
```suggestion
	name = "\improper SUNS peacekeeper hardsuit"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "\improper SUNS Industrial hardsuit helmet"
```suggestion
	name = "\improper SUNS industrial hardsuit helmet"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "\improper SUNS Industrial hardsuit"
```suggestion
	name = "\improper SUNS industrial hardsuit"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "\improper SUNS Captains helmet"
```suggestion
	name = "\improper SUNS captain's hardsuit helmet"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "\improper SUNS Captains hardsuit"
```suggestion
	name = "\improper SUNS captain's hardsuit"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/armor.dm
> +	desc = "An armored coat intended for SUNS Captains on the frontier. Go forth, and spread the message of the academy."
```suggestion
	desc = "An armored coat intended for SUNS captains on the frontier. Go forth, and spread the message of the academy."
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/armor.dm
> +	desc = "A white coat used by Suns acedemic staff. It designates the second in command on the ship."
```suggestion
	desc = "A white coat used by SUNS academic staff. It designates the second in command on the ship."
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/cloaks.dm
> +	name = "SUNS short cloak"
```suggestion
	name = "\improper SUNS short cloak"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/cloaks.dm
> +	name = "SUNS academic staff cloak"
```suggestion
	name = "\improper SUNS academic staff cloak"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/cloaks.dm
> +	name = "SUNS captain's cloak"
```suggestion
	name = "\improper SUNS captain's cloak"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/hoodies.dm
> +	name = "SUNS labcoat"
```suggestion
	name = "\improper SUNS labcoat"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/hoodies.dm
> +	name = "SUNS labcoat hood"
```suggestion
	name = "\improper SUNS labcoat hood"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/jobs.dm
> +	name = "\improper black school jacket"
```suggestion
	name = "black school jacket"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/jobs.dm
> +	name = "\improper Peacekeeper Coat"
```suggestion
	name = "peacekeeper coat"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/suits/labcoat.dm
> +	desc = "A labcoat often worn by the more essentric medical instructors."
```suggestion
	desc = "A labcoat often worn by the more eccentric medical instructors."
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/under/accessories.dm
> +	name = "suns waistcoat"
```suggestion
	name = "\improper SUNS waistcoat"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/under/accessories.dm
> +	name = "suns ribbon"
```suggestion
	name = "\improper SUNS ribbon"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/under/accessories.dm
> +	name = "suns gembow"
```suggestion
	name = "\improper SUNS gem bow"
```

2023-11-04 22:18 UTC, GenericDM commented on code/modules/clothing/under/accessories.dm
> +	name = "suns chest poof"
```suggestion
	name = "\improper SUNS chest poof"
```

2023-11-08 06:25 UTC, Draggeru commented
This PR is irrecoverably fucked, it keeps undoing other sprite PRs and I can't fix it. If someone else who knows what to do to fix this they're welcome to take a crack at it. I don't have the time or knowledge to do this in a way that's not overtly difficult.

2023-11-08 06:25 UTC, closed without merging