The Evolution of Bar RP
shiptest-ss13/Shiptest pull request #2470
Opened 2023-11-10 14:45 UTC by thgvr

## About The Pull Request
Ports Saunas & Towels from Skyrat. Some edits to the code to fit here, and to make it work a little more sane. Ports some improvements to radial menus from TG.
![image](https://github.com/shiptest-ss13/Shiptest/assets/81882910/23386cc1-d4d7-4312-af41-10b207ea15ce)

## Changelog

:cl:
add: Saunas, craftable with wooden planks. Uses wood for fuel, and requires water splashed on the sauna.
add: Towels. You can use them in-hand to change it from waist, chest, or head.
/:cl:

2023-11-10 14:47 UTC, Martinpachu commented
YEAAA YEAAH

2023-11-10 15:18 UTC, Norletic commented
love dieing of liver issues while drinking pure ethanol in a sauna

2023-11-10 21:22 UTC, Martinpachu commented
the ''on'' and ''off'' messages are reversed. turning it on says it turns off etc

2023-11-11 04:02 UTC, thgvr commented
I already fixed that

2023-11-14 18:17 UTC, MarkSuckerberg requested changes, later dismissed

2023-11-14 18:17 UTC, MarkSuckerberg commented on code/game/objects/structures/sauna.dm
> +		water_amount -= used_amount
```suggestion
		var/used_amount = min(water_amount / 10, 20)
		water_amount -= used_amount
```

2023-11-14 22:11 UTC, merged