Updates default TGUI background, overhauls autolathe tgui theme
shiptest-ss13/Shiptest pull request #2515
Opened 2023-11-22 02:34 UTC by thgvr

## About The Pull Request
Adds shiptest SVG as a replacement for the NT one in default tgui theme
Overhauls `ntos_terminal` theme, giving it an orange hue and adding it to autolathes.
![image](https://github.com/shiptest-ss13/Shiptest/assets/81882910/1786295b-adc7-49fb-b353-a1036c98c211)
 

## Changelog

:cl:
add: Autolathe has a new TGUI theme.
imageadd: New TGUI background, the Shiptest logo.
/:cl:

2023-11-28 22:56 UTC, MarkSuckerberg requested changes
pog

2023-11-28 22:56 UTC, MarkSuckerberg commented on tgui/packages/tgui/interfaces/Autolathe.js
> +                            design.buildable ? '#0000000' : 'default'
```suggestion
                            design.buildable ? '#00000000' : 'default'
```

2023-12-04 11:49 UTC, thgvr commented
Not sure if I'm sold on the orange, might take it back to green. If anyone has thoughts pls comment

2023-12-07 13:44 UTC, thgvr commented
@MarkSuckerberg what do you think of the orange vs green

2023-12-12 00:17 UTC, MarkSuckerberg commented
> @MarkSuckerberg what do you think of the orange vs green

I really do like the amber, I'd say increase the contrast on the text a bit though if you could. 

honestly the classic amber display would be amber text on a black background, even if that's a bit less colourful and distinct from normal UIs

2023-12-30 08:29 UTC, thgvr commented
im gonna make it green

2024-01-07 16:14 UTC, MarkSuckerberg approved these changes

2024-01-07 16:28 UTC, merged