Total golem death
shiptest-ss13/Shiptest pull request #2537
Opened 2023-11-29 00:57 UTC by thgvr

## About The Pull Request
Removes golems

## Why It's Good For The Game
Removes golems

## Changelog

:cl:
del: Removes golems
/:cl:

2023-11-29 01:26 UTC, tiramisuapimancer commented
major L for all cloth golem boywives

2023-11-29 01:27 UTC, ritorizo commented
Golem ? more like go lame.

2023-11-29 01:33 UTC, tmtmtl30 commented
> major L for all cloth golem boywives

im going to have to get a divorce IG

2023-11-29 05:06 UTC, Imaginos16 commented
W

2023-11-29 06:32 UTC, Latentish requested changes
Please just remove lavaland_surface_golem instead of upkeeping it. And kill the entry in the ruin catalogue as well.

2023-11-29 16:27 UTC, ChesterTheCheesy commented
> major L for all cloth golem boywives


https://github.com/shiptest-ss13/Shiptest/assets/71487903/418f2d29-4010-4d80-b79f-1767f9f9e832

2023-11-30 00:19 UTC, Latentish approved these changes
good

2023-12-03 00:02 UTC, MarkSuckerberg requested changes
looks good other than this, I'd prefer you either remove the slimes entirely or give them some other effect if you could

2023-12-03 00:02 UTC, MarkSuckerberg commented on code/modules/mining/equipment/wormhole_jaunter.dm
> +	desc = "A single use device harnessing outdated wormhole technology, Nanotrasen has since turned its eyes to bluespace for more accurate teleportation. The wormholes it creates are unpleasant to tra
```suggestion
	desc = "A single use device harnessing outdated wormhole technology, Nanotrasen has since turned its eyes to bluespace for more accurate teleportation. The wormholes it creates are unpleasant to travel through, to say the least.\nThis jaunter has been modified to fit on your belt, providing you protection from chasms."
```

2023-12-03 00:02 UTC, MarkSuckerberg commented on code/modules/research/xenobiology/crossbreeding/charged.dm
> +	effect_desc = "Does nothing. Sorry :)"
🥺

2023-12-03 00:02 UTC, MarkSuckerberg commented on code/modules/research/xenobiology/crossbreeding/chilling.dm
> +	effect_desc = "Does nothing. :)"
🥺

2023-12-03 00:26 UTC, thgvr commented on code/modules/research/xenobiology/crossbreeding/chilling.dm
> +	effect_desc = "Does nothing. :)"
Mark I'm not adding a new effect to xenobio extracts

2023-12-06 03:35 UTC, MarkSuckerberg approved these changes
rip, won't be missed

2023-12-06 03:37 UTC, merged