RILENA 2
shiptest-ss13/Shiptest pull request #2574
Opened 2023-12-08 02:00 UTC by MoonTheBird

## About The Pull Request

Added a bunch more RILENA stuff!
FOOD:
![image](https://github.com/shiptest-ss13/Shiptest/assets/64121399/789a9c78-c177-488e-bf1f-f4a3cd044a52)
PLUSHIES:
![image](https://github.com/shiptest-ss13/Shiptest/assets/64121399/bd3885a4-28b9-4060-bace-d22759f5b865)
POSTERS:
![image](https://github.com/shiptest-ss13/Shiptest/assets/64121399/c2295d54-6f45-4296-8828-900d0baf26c5)

## Why It's Good For The Game

MORE RILENA

## Changelog

:cl:
add: Added a bunch more RILENA stuff! Five more posters, three more plushies, a popsicle, some macaroni and cheese, and, of course, the elusive RILENA MRE.
/:cl:

2023-12-28 17:01 UTC, MarkSuckerberg requested changes

2023-12-28 17:01 UTC, MarkSuckerberg commented on code/modules/food_and_drinks/food/ration.dm
> +	name = "/improper RILENA flavored cereal"
```suggestion
	name = "\improper RILENA flavored cereal"
```

2024-01-29 22:27 UTC, meemofcourse commented
fix ur conflicts and address review pls

2024-02-04 16:26 UTC, thgvr commented
I think we should probably go a little less hard on this stuff

2024-03-12 02:32 UTC, thgvr commented
No activity in a while, ping me if you'd like to work on this again

2024-03-12 02:32 UTC, closed without merging