Heating rations now provides their bonus vitamin/nutriment reagents
shiptest-ss13/Shiptest pull request #2586
Opened 2023-12-14 18:42 UTC by SomeguyManperson

## About The Pull Request

Ration packs now use bonus_reagents properly, prior they would set the list when being heated and not use it

![image](https://github.com/shiptest-ss13/Shiptest/assets/24857008/1bf14f40-5140-410f-a228-e07599ae83ac)

## Why It's Good For The Game

Cooking rations now makes them better

## Changelog

:cl:
fix: heating rations increases their nutritional value as intended
/:cl:

2023-12-20 14:10 UTC, FalloutFalcon commented
I wrongly assumed that bonus reagents were spawned on init

2023-12-22 07:59 UTC, MarkSuckerberg requested changes
just some minor tweaks!

2023-12-22 07:59 UTC, MarkSuckerberg commented on code/modules/food_and_drinks/food/ration.dm
> +				if(r_id == /datum/reagent/consumable/nutriment || r_id == /datum/reagent/consumable/nutriment/vitamin)
```suggestion
				if(ispath(r_id, /datum/reagent/consumable/nutriment))
``` This is basically istype() for paths

2023-12-22 07:59 UTC, MarkSuckerberg commented on code/modules/food_and_drinks/food/ration.dm
> +		if(bonus_reagents && bonus_reagents.len)
```suggestion
		if(length(bonus_reagents))
```

2023-12-28 16:47 UTC, MarkSuckerberg approved these changes

2023-12-28 18:01 UTC, merged