The Scrapper
shiptest-ss13/Shiptest pull request #263
Opened 2021-09-15 17:58 UTC by Omppusolttu

## About The Pull Request

Adds the Scrapper as a new ship.

## Why It's Good For The Game

New ship 👍 

## Changelog
:cl:
add: Ship
/:cl:

2021-09-15 18:50 UTC, swifterjack commented
picture please

2021-09-19 22:19 UTC, triplezeta requested changes

2021-09-19 22:19 UTC, triplezeta commented on _maps/configs/scrapper.json
> +	"map_short_name": "Scrapper",
```suggestion
	"map_short_name": "Scrapper-class",
```

2021-09-21 12:37 UTC, closed without merging

2021-09-21 12:37 UTC, Omppusolttu commented
doing jank shit