Adds a lava canyon as a new lava planet ruin
shiptest-ss13/Shiptest pull request #2642
Opened 2024-01-15 03:33 UTC by MemeSnorfer

## About The Pull Request

Adds a lava canyon ruin, with the remains of a scorched ashwalker village nestled between the crags. Comes with an associated area for this ruin.

## Why It's Good For The Game

Lava planets need ruins.

## Changelog

:cl:
add: New lava canyon ruin
/:cl:

2024-01-25 02:39 UTC, Zevotech requested changes, later dismissed
Alright, a lavaland ruin! Finally!
Starting off strong, you did an excellent job blending the area of the ruin with the natural environment. The fact that I can't see where the planetgen ends and the ruin begins is a huge win for this ruin. This is a positive comment, no need to change anything about the ruin in terms of environment as far as I can tell.

This may surprise you, but the BDM is actually passive and minds their business until you attack them! People can just walk up and yoink that chest with no risk. I'd either remove the chest, or put it behind a locked gate with a setup similar to the ashdrake ruin (Boss drops a key to the gate) to prevent people from just snatching it. Remember that the boss itself is a pretty big reward for anyone competent enough to beat it.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/25a17fd1-ad56-4a08-99fb-1422d7f642f9)
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/18bde81d-2dae-4104-90e1-665d9c0468bd)

Two things. One, the ashwalker corpses will get husked by the first storm that comes in which may mess with the vibes you were going for. Second, mixing these two types of walls is weird. I'd either stick with just using sandstone or necropolis walls to really send the ashie vibes home.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/edaa1d48-439d-40c5-ac02-a7e708f053cf)

Interesting setup here. I'm not sure if this is a reference to something so I'm going to suggest changing the dusty shard to something more rewarding or removing it altogether and replacing it with a shield or something.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/b593cffc-ccd2-4cd9-86e5-73af31770cd1)

This is silly and great. I had no idea these tiles dropped out and rose back up like a platformer game. No change requested here.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/63f8215c-d4c9-457a-bedf-62769ae8dd4e)

The scrap metal/titanium feels out of place in this ruin, I'd just replace it with ore. Also having bone weapons everywhere on the floor feels weird. Maybe have them in a dedicated armory hut or just on/next to corpses.
![image](https://github.com/shiptest-ss13/Shiptest/assets/95449138/b299db1b-ebf7-45c4-8c34-c30eae5120a6)

Anyways this is a pretty great ruin. Hope to see it merged quickly because its in a pretty good state as-is.

2024-01-29 09:08 UTC, Zevotech commented on code/game/objects/items/puzzle_pieces.dm
> +/obj/item/keycard/gatedrop/lavacanyon
Add the key to the blood drunk's crusher loot pool as well. Megafauna drop different things when killed with a crusher.

2024-02-17 18:39 UTC, Latentish commented
Tming this gonna test it live =)

2024-02-25 10:47 UTC, Latentish commented
I want to test this in game one more time. But otherwise I think this is rad as fuck.

2024-02-29 00:10 UTC, Latentish requested changes, later dismissed
Absolutely beautiful map. Swap out the narsien armor in the chest for something else and we can merge this.

2024-02-29 00:16 UTC, Latentish approved these changes
beautiful map

2024-02-29 00:40 UTC, merged