Removes firing pins and clumsy checks on guns
shiptest-ss13/Shiptest pull request #2702
Opened 2024-02-06 00:07 UTC by FalloutFalcon

## About The Pull Request

Removes firing pins and clumsy checks from guns

## Why It's Good For The Game

Firing pins and clumsy checks are huge cruft.
Both are designed to limit around things we don't care about anymore

## Changelog

:cl:
del: Removed firing pins
del: Removed clumsy checks on guns
/:cl:

2024-02-06 13:08 UTC, Cadunkus commented
Does this mean you can't have guns without firing pins (that are therefore useless)?

2024-02-20 14:52 UTC, FalloutFalcon commented
> Does this mean you can't have guns without firing pins (that are therefore useless)?

No its a in depth removal of every pin and and check for it. This means every gun will fire regardless. Also simplifies paths for many weapons which were just gun/normalfiringpin basically 

currently it crashes the game. Haven't had time to look into it

2024-04-20 03:40 UTC, thgvr requested changes
Get the sprites as well please

2024-04-20 03:40 UTC, thgvr commented on code/game/machinery/computer/arcade.dm
> -		if(prob(0.0001)) //1 in a million
Keep this

2024-04-20 15:40 UTC, thgvr approved these changes

2024-04-20 15:51 UTC, merged