Tortuga-class Converted Cargo Freighter
shiptest-ss13/Shiptest pull request #2765
Opened 2024-02-25 03:45 UTC by meemofcourse

## About The Pull Request

![tortuga](https://github.com/shiptest-ss13/Shiptest/assets/75212565/981781e4-d57c-4f21-93ad-496e3ed5f883)
![imagen](https://github.com/shiptest-ss13/Shiptest/assets/75212565/252de101-ee3d-4e3b-a0e4-6475f8fadec7)
![imagen](https://github.com/shiptest-ss13/Shiptest/assets/75212565/151c1302-9e32-42db-83af-97db27d8dc87)
![imagen](https://github.com/shiptest-ss13/Shiptest/assets/75212565/d4b82622-406c-45a0-9c1e-1781b2802cf4)

Originally a cargo transport vessel, the Tortuga class is an improvised combat vessel under the ranks of the Frontiersmen fleet. Clever field modifications include the conversion of the cargo bay to a hangar, and additional padding around the ship in the form of asteroid rocks. It serves a dual purpose, both as a capable ship for establishing a military enclave in a sector, and as a sturdy vessel for reconnaissance. The nimble Brawler-class subshuttle of the Tortuga is offset by its very low overall mobility and loss of operation if the subshuttle were to be lost.

It is staffed by:
* 1 Captain
* 1 Shipswain (Head of Security)
* 1 Aidman
* 1 Sapper
* 2 Boarders
* 2 Rookies

## Why It's Good For The Game

The Ember is a pseudo-dreadnaught, and unfortunately, it kind of sucks. Pirates need a subshuttle to effectively raid.

## Changelog

:cl:
add: Tortuga-class.
add: Brawler-class.
del: Ember-class.
del: Scar suit.
tweak: Frontiersmen outfits start with less stuff.
/:cl:

2024-02-25 04:39 UTC, Apogee-dev requested changes, later dismissed

2024-02-25 04:39 UTC, Apogee-dev commented on _maps/configs/pirate_tortuga.json
> +	"description": "Originally a cargo transport vessel, the Tortuga class is an improvised combat vessel under the ranks of the Frontiersmen fleet. Clever field modifications include the conversion of
"Originally a cargo transport vessel, the Tortuga is an improvised combat vessel used by the Frontiersmen fleet. Civilian transports are modified with shuttle handling facilities, and asteroid rubble is belted to the exterior of the hull as a form of cheap improvised armor and concealment. The Tortuga serves a dual purpose as a reconnaissance element and a vessel capable of establishing forward bases within a sector. While the Brawler-class shuttle carried by the Tortuga offers a surprising degree of speed and range to its boarding parties, the Tortuga itself is sluggish and nearly helpless without its shuttle."

Several edits for clarity and grammar.

2024-02-25 04:39 UTC, Apogee-dev commented on _maps/configs/pirate_tortuga.json
> +		"Aidman": {
I feel like we could probably come up with a better name for this, "Aidman" is ridiculously clunky. Ship's Surgeon? Medic? It doesn't need to be completely unique to the faction.

2024-02-25 04:39 UTC, Apogee-dev commented on _maps/configs/pirate_tortuga.json
> +		"Shipswain": {
Why not just use the more common "Bosun" or "Boatswain" here? Both roll off the tongue quite a bit better. You could even use Deck Boss or something if you want to keep it from being too age of sail-y.

2024-02-25 04:39 UTC, Apogee-dev commented on _maps/configs/pirate_tortuga.json
> +		"Sapper": {
Another awkard job name, given the sapper's primary job is actually going to be maintaining the ship, with occasional assistance for breaches. I'd just go with Mechanic or something similar. As with the doctor slot above, you don't need to use completely faction-unique names for every role, as long as they fit the faction's flavor and suit the job. You also might want to give them a second engineer if you intend for one to join the boarders on the shuttle.

2024-04-07 00:56 UTC, Latentish submitted a review, later dismissed
Subshuttle has a few issues. It doesn't dock in the ship correctly, the doors have problems opening, and shield gens are fucky.

2024-05-04 18:24 UTC, Latentish commented
This has that abandoned warehouse barren "you live like this" dollar store meth lab type feel.  Pretty good. Wanna tm this again to  make sure it's all working properly.

2024-05-20 11:24 UTC, merged