[DNM] Bobnames, or: Guestbook, from Mojave Sun
shiptest-ss13/Shiptest pull request #2770
Opened 2024-02-26 08:10 UTC by meemofcourse

## About The Pull Request

This thing sucks to port, I'm going to be real with you.

TODO:
* [x] Make it sort of work
* [ ] Fix an error where adding a guest name doesn't work
* [ ] Make it so you automatically know your ship's crewmates, and captains know other faction members
* [ ] Something with ERTs
* [ ] Make the guestbook save across rounds

![imagen](https://github.com/shiptest-ss13/Shiptest/assets/75212565/8943246e-145d-44b2-8284-3539fb09b565)
![imagen](https://github.com/shiptest-ss13/Shiptest/assets/75212565/8966bff4-8688-466e-88fa-2d73f71d2572)
![imagen](https://github.com/shiptest-ss13/Shiptest/assets/75212565/24e680be-e994-4aed-af3e-f4333d9b4a8d)

This pull request ports the following:
* https://github.com/Mojave-Sun/mojave-sun-13/pull/2415
* https://github.com/Mojave-Sun/mojave-sun-13/pull/2433

These PRs change how examining someone works. You have to walk up to someone and remember their face in order to recognize their voice. Names will still be displayed with people's IDs

## Why It's Good For The Game
* The current anonymity system sucks for stealthy shit. You immediately know someone's real name. An improved system allows for more roleplay possibilities.
* Kansatsu is more reliable.
* You can rob people with a knife and a balaclava at the outpost, and they won't know who you are!

## Changelog
:cl:
refactor: Anonymous mechanics. Characters no longer instantly recognize each other, and need to properly memorize each other in order. You can recognize an unmasked person by ctrl-shift-clicking them.
/:cl:

2024-02-29 01:45 UTC, ZephyrTFA requested changes, later dismissed
no persistence

2024-02-29 15:26 UTC, XxNinMario64xX commented
Is there a reason why persistence is getting removed? Feels weird given familiarity should build between shifts, even if people end up on different ships and whatnot. Plus it would just kinda feel like an artificial memory-wipe every shift.

2024-02-29 15:31 UTC, meemofcourse commented
I can think of two reasons why.
* Storage space concerns. Twenty character slots, each with a list of two names. It's just strings, but the list can be infinitely long, and will stack over time as people stop playing.
* Actually keeping anonymity effective - people are only unknown once, and even if you have a balaclava on all day, you'll eventually be known by other people joining your crew.

2024-02-29 15:41 UTC, Martinpachu commented
not a fan of the idea of having to set names again every round

2024-02-29 15:43 UTC, thgvr commented
If it's persistent it does not mesh with any of our server's design, as well as making the anonymity feature apply only once.

2024-02-29 15:59 UTC, Martinpachu commented
aren't people able to recognize voices and ways of speaking? it doesn't really make sense that you forget all of that after the round ends

2024-02-29 16:44 UTC, XxNinMario64xX commented
I can understand the storage space issue, but I feel like there should be a poll or something about whether or not this should be reimplemented without persistence given it's going to change expected RP experiences, especially with constantly seeing "new" faces when they're characters that have already met each other before. If assuming the character's identity is allowed, then the lack of persistence becomes more of an annoyance than anything else since people will have to keep re-remembering each other despite wanting to build a solid memory and relationship with another character. 

I'd rather not have the system in place if it's not going to have persistence, as it's going to get real annoying really quickly if I have to keep re-remembering everyone every shift, and it'll be even more of an annoyance to have to keep remembering characters my character has had interactions with, especially if I _forget_ to _remember_ someone that my character would definitely remember.

2024-02-29 18:15 UTC, thgvr commented
We're not doing persistence, period.

2024-03-01 17:26 UTC, Absolucy commented
![2024-03-01 (1709313753) ~ dreamseeker](https://github.com/shiptest-ss13/Shiptest/assets/65794972/35060063-479b-46ac-a26b-038f2938caa8)

Emotes and LOOC only show the generic names - these are crewmates I all have in my guestbook.

2024-03-01 17:50 UTC, meemofcourse commented
LOOC would be tricky because it outright uses the mob name instead of handling it per player but i can probably fix emotes

2024-03-01 17:57 UTC, meemofcourse commented
![imagen](https://github.com/shiptest-ss13/Shiptest/assets/75212565/0d678f05-5da9-4075-b353-3ec2b55af87a)
i don't know dude it works on my machine

2024-03-01 18:27 UTC, Skies-Of-Blue commented
![image](https://github.com/shiptest-ss13/Shiptest/assets/86762641/1422fcbe-3bcf-44bd-a5f3-686c0f6fa680)

Orbit menu appears overinflated due to ghosts being unable to add any characters to guestbook. Also means it's significantly harder to tell who's who and what's what while observertesting, as all characters show up with their Adjectives rather than their Names.

2024-03-01 18:38 UTC, meemofcourse commented
if you are seeing people with their generic names outside of the orbit menu that is an issue with mind datums that i have zero idea why it is happening. reobserve to fix it

2024-03-01 18:57 UTC, Skies-Of-Blue commented
> if you are seeing people with their generic names outside of the orbit menu that is an issue with mind datums that i have zero idea why it is happening. reobserve to fix it

Reobserving, and relogging, did not fix it.

2024-03-01 19:13 UTC, BarteG44 commented
You should add it to the right click pop up menu so people who don't know the esoteric key combination aren't left out.

Also maybe make the key bind display in the chat after you try and memorize names this way so those people can learn it properly

![image](https://github.com/shiptest-ss13/Shiptest/assets/105491762/ee68012d-a278-4ae2-8a3f-9f346756d9d1)

2024-03-01 19:13 UTC, thgvr commented
it's not esoteric and it tells you on examine

2024-03-01 19:34 UTC, MarkSuckerberg commented
honestly I assumed it would be on examine more too

2024-03-01 22:36 UTC, RikuTheKiller commented
I'll be honest this is kind of boring, I'd much rather know people's names by default.
I haven't played much with this (same goes for shiptest overall) but it's really off-putting IMO.

2024-03-02 01:31 UTC, RikuTheKiller commented
Or, well, actually, it's fine, or it would be if we could examine people closer to see the name on their ID, if it's visible. (within like a 1 tile range)

2024-03-03 00:16 UTC, goober3 commented
wideband logs bypass the guestbook. they probably shouldnt do that.

2024-03-03 00:20 UTC, MitztheKat commented
I hate this

2024-03-03 14:49 UTC, Sweettoothart commented
Recommending to add these adjectives

Energetic 
Hyper
Friendly (for friend shaped blorbos)
Stylish
Dignified
Stout
Hawkish
Sleepy
Exasperated
Gap-toothed
Pugnacious
Zealous 
Zesty
Feisty
Jaded
Hobbling
Chaotic

2024-03-03 15:37 UTC, goober3 commented on strings/preference_adjectives.txt
> +Wrinkly
hey. you can put these in a code suggestion to make meem's life easier.
```suggestion
Wrinkly
Energetic
Hyper
Friendly
Stylish
Dignified
Stout
Hawkish
Sleepy
Exasperated
Gap-toothed
Pugnacious
Zealous
Zesty
Feisty
Jaded
Hobbling
Chaotic
```

2024-03-03 15:39 UTC, goober3 commented on strings/ipc_preference_adjectives.txt
> +Worn-Out
```suggestion
Worn-Out
Energetic
Hyper
Friendly
Stylish
Dignified
Hawkish
Exasperated
Pugnacious
Zealous
Zesty
Feisty
Jaded
Hobbling
Chaotic
```

2024-03-03 16:58 UTC, MidnightLunarCat commented
Adding Skittish to IPC adjectives could be nice, since it feels strange thats present for organic being but not positronics when there isn't really anything stopping an IPC from being skittish.

Other then that i can't think of anything and the server isn't up for me to compare more adjectives right now to see if any other adjectives are like that.

2024-03-07 09:28 UTC, Cadunkus commented
> Kansatsu is more reliable.

Ironically this system doesn't work with the agent IDs because no matter what you rename the agent ID to now it will always say "agent ID" despite successfully changing voice when paired with a chameleon mask. Might want to look into that.

2024-03-09 04:47 UTC, MitztheKat commented
please, PLEASE un-TM this for the colony round. this **will** break and cause Tgui to bluescreen.

2024-03-09 20:22 UTC, thgvr commented
With https://github.com/meemofcourse/Shiptest/commit/409f2054fceafd8151a19bf1212f64ac846d6a5e , any mob dying results in the orbit menu breaking and isn't reproducible on local. Not really sure *why* exactly, but I may be leaning towards 515's fault

2024-03-21 01:16 UTC, FalloutFalcon commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +			return "" //not necessary because this is basically the most common age range
Need to add something to not display the age examine text because currently it spits out something like "they appear to be ."

2024-03-21 01:17 UTC, FalloutFalcon commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +		if(60 to 70)
should prob be 60 to 69, 50 to 59 ya know

2024-04-01 14:39 UTC, FalloutFalcon commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +		if(60 to 70)
I realize this would mess up if age has a decimal value so nvm

2024-04-16 01:56 UTC, thgvr commented
This all works and code quality is fine, we'll figure out something to clean up orbit menu later. LGTM

2024-04-16 03:12 UTC, merged