Remaps the Shetland
shiptest-ss13/Shiptest pull request #2774
Opened 2024-02-27 20:07 UTC by Apogee-dev

## About The Pull Request
![faroe](https://github.com/shiptest-ss13/Shiptest/assets/60533805/182e8201-7279-4617-8690-ae7dc5f9e8a7)
![faroe_areas](https://github.com/shiptest-ss13/Shiptest/assets/60533805/f4f9bf56-dd4d-4ff9-8219-753221b5804e)

Brings the Shetland up to modern mapping standards, makes the layout less garbage, adds some amenities and RP facilities, and rebalances the ship's mechanical features.

- RnD and ORM removed
- TEG added
- Weapons and armor rebalanced
- Massive aesthetic improvements

## Why It's Good For The Game

Shetland is the oldest ship we have left in the game and despite getting a couple updates along the way it really shows. It was either update it or kill it, and I think the Shetland still has good potential and is worth saving.

## Changelog

:cl:
tweak: Remapped the Shetland
balance: Removed RnD and ORM from Shetland
/:cl:

2024-02-27 20:11 UTC, meemofcourse commented
sus

2024-02-28 19:20 UTC, Cadunkus commented
Aw now there's no empty space to do engineering projects.

2024-03-06 12:19 UTC, Latentish commented on code/modules/clothing/outfits/factions/independent.dm
> +	gloves = /obj/item/clothing/gloves/color/white //poverty gloves
Hilarious.

2024-03-06 12:21 UTC, Latentish requested changes, later dismissed

2024-03-06 12:21 UTC, Latentish commented on shiptest.dme
> +#include "code\datums\weather\weather.dm"
This is an irrelevant change. Swap this back so we don't have a DME edit tag here.

2024-03-06 12:22 UTC, Latentish commented
Finally some good fucking remap. I'll test this on live as soon as you aren't PRing a DME change (rip all other tm's that add a new file)

2024-03-06 17:51 UTC, Cadunkus commented
I don't see a fax machine in the .dmm file with ctrl+f.

2024-03-07 19:24 UTC, Apogee-dev commented
> I don't see a fax machine in the .dmm file with ctrl+f.

Indie ships don’t get faxes.

2024-03-24 02:42 UTC, Latentish commented
Tested this on live, seems to be pretty much good? So because I don't have much to say I'm going to pass this review off to the other mapties.

2024-04-04 23:17 UTC, meemofcourse approved these changes
yeah

2024-04-05 05:28 UTC, tiramisuapimancer commented
this is a good remap, but the fact that it isnt the skeld anymore kind of defeats the point doesnt it

2024-04-07 00:54 UTC, Latentish commented
> this is a good remap, but the fact that it isnt the skeld anymore kind of defeats the point doesnt it

No. We don't need a n among us reference. Also the old layout was the thing that sparked the ship cute.



This ship is good for a merge smile.

2024-04-07 01:08 UTC, merged