Cybersun's blacksite ruin
shiptest-ss13/Shiptest pull request #2835
Opened 2024-03-11 23:05 UTC by Marabout2

## About The Pull Request

Apparently, there is a need for more ruin so here it is, one additional ruin to the rooster.

## Why It's Good For The Game

More ruins mean more things to be explored ?

## Changelog

:cl:
add: Added a new Cybersun related ruin
code: Modified the map_catalogue.txt file; the icemoon.dm areas ruin file; modified the icemoon.dm datum to add said ruin.
:cl:

2024-03-11 23:10 UTC, thgvr commented on code/datums/ruins/icemoon.dm
> +
one too many newlines at end of file

2024-03-11 23:11 UTC, thgvr commented on code/game/area/areas/ruins/icemoon.dm
> +	sound_environment = SOUND_AREA_TUNNEL_ENCLOSED
```suggestion
	sound_environment = SOUND_AREA_TUNNEL_ENCLOSED
	
```

2024-03-11 23:11 UTC, thgvr commented on code/datums/ruins/icemoon.dm
> +
```suggestion
```

2024-03-12 04:38 UTC, tiramisuapimancer commented
chicken typo

2024-03-13 05:08 UTC, Latentish commented
Add 3 pictures to show your ruin in your description. 1 in game screenshot (Use the command "Change View Range" to get one while ghosted), and two SDMM screenshots (one with areas on, one with only area borders on) (make sure to use the screenshot button in sdmm).

2024-03-13 14:42 UTC, Marabout2 commented
Alright, should be done with the images too !

2024-03-22 07:12 UTC, Latentish commented
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/c86c7dd0-edbe-4bb0-b46a-e4ecf6980ce4)
Don't copy paste content from another ruin for this please.

2024-03-22 07:29 UTC, Latentish requested changes
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/a3e0d454-2b8f-429a-a83d-a373d9077dcd)
Don't run pipes through walls unless it is for an the singular exhaust pipe of a ship or compound.

![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/e699e73a-c28c-4043-bca5-98e2d0228926)
Add a dangerous mob here =)

Add some fluff incriminating the syndies here as fringe ex members, or deserters.

Change your shuttle here, it's lifted straight from the bombed out airbase.

I think this is a strong ruin, fix your stuff up and we can look at TMing it.

2024-04-01 11:10 UTC, Latentish commented
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/c63a388a-8d3b-422d-8f1c-8b2bec7c6238)
This door is facing the wrong direction. you have a diagonal wall here (don't do that), you missed one underwall pipe, and these lights need to have a wire node under them to turn on.
Aside from this I'm very very impressed.

2024-04-01 11:13 UTC, Latentish commented
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/e71623ae-b2d4-4d00-98a0-2e07466a7a83)
this rainbow area is certainly concerning . I would recommend looking at the li-tieguai and using the red decals that it uses if these ones are being a bit too 70's.

2024-04-01 11:16 UTC, meemofcourse commented
happy april fools lat

2024-04-11 02:44 UTC, Latentish requested changes
![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/bd167b52-01a9-4a14-ab82-8801bee86b13)
Hi!!!! This is going to cause an atmosphere difference. I'd recommend closing it up and adding an airlock, or making icemoon outside subytpes for cement and stairs.

![image](https://github.com/shiptest-ss13/Shiptest/assets/55075747/2cb2c019-fd7a-4dda-af03-548be1798e57)
Open plating actually already has an icemoon subtype. Use that instead.

Other than that this looks pretty good. Get those tiles fixed and we can TM this.

2024-05-17 19:50 UTC, goober3 requested changes
please swap out the snow turfs outside for the /lit variant. also, fix your unrotated airlocks.

2024-06-20 13:20 UTC, Latentish commented
I want this merged already. Get this passing checks, and I will give it a lookover on local, and I'll merge it.

2024-07-04 15:37 UTC, SomeguyManperson commented
syndie mobs in this need to be swapped to the new hostile human paths

2024-07-17 02:48 UTC, SomeguyManperson reviewed
should fix present issues

2024-07-17 02:48 UTC, SomeguyManperson commented on _maps/RandomRuins/IceRuins/icemoon_cybersun_blacksite.dmm
> +/mob/living/simple_animal/hostile/syndicate/melee/space,
```suggestion
/mob/living/simple_animal/hostile/human/syndicate/melee/space,
```

2024-07-17 02:48 UTC, SomeguyManperson commented on _maps/RandomRuins/IceRuins/icemoon_cybersun_blacksite.dmm
> +/mob/living/simple_animal/hostile/syndicate/ranged/space,
```suggestion
/mob/living/simple_animal/hostile/human/syndicate/ranged/space,
```

2024-07-17 02:48 UTC, SomeguyManperson commented on _maps/RandomRuins/IceRuins/icemoon_cybersun_blacksite.dmm
> +/mob/living/simple_animal/hostile/syndicate/melee/sword,
```suggestion
/mob/living/simple_animal/hostile/human/syndicate/melee/sword,
```

2024-07-17 02:48 UTC, SomeguyManperson commented on _maps/RandomRuins/IceRuins/icemoon_cybersun_blacksite.dmm
> +/mob/living/simple_animal/hostile/syndicate/ranged/space/stormtrooper{
```suggestion
/mob/living/simple_animal/hostile/human/syndicate/ranged/space/stormtrooper{
```

2024-07-17 02:48 UTC, SomeguyManperson commented on _maps/RandomRuins/IceRuins/icemoon_cybersun_blacksite.dmm
> +/mob/living/simple_animal/hostile/syndicate/ranged/smg/pilot{
```suggestion
/mob/living/simple_animal/hostile/human/syndicate/ranged/smg{
```
pilot subtype was killed brutally in ruincut

2024-07-17 02:48 UTC, SomeguyManperson commented on _maps/RandomRuins/IceRuins/icemoon_cybersun_blacksite.dmm
> +/mob/living/simple_animal/hostile/syndicate/ranged/smg/orion,
```suggestion
/mob/living/simple_animal/hostile/human/syndicate/ranged/smg/orion,
```

2024-07-17 02:48 UTC, SomeguyManperson commented on _maps/RandomRuins/IceRuins/icemoon_cybersun_blacksite.dmm
> +/mob/living/simple_animal/hostile/syndicate/melee,
```suggestion
/mob/living/simple_animal/hostile/human/syndicate/melee,
```

2024-08-06 08:11 UTC, rye-rice commented
sowwy, nwo prwogwess iwn a mwonth, rweopwen wwen wrorking on iwt agwian

2024-08-06 08:11 UTC, closed without merging