Constructable exercise equipment
shiptest-ss13/Shiptest pull request #2839
Opened 2024-03-16 04:15 UTC by Gristlebee

## About The Pull Request

- Punching bags can now be constructed from 5 cloth and deconstructed with a wirecutter.
- Bench presses and chest presses can be constructed from 5 metal and deconstructed with a wrench.
## Why It's Good For The Game

You no longer need to smash apart the exercise equipment like a caveman, and offers players some more freedom in how they want to decorate or arrange their ships.

## Changelog

:cl:
add: Punching bags can be built with 5 cloth.
add: Bench press and chest press can be built with 5 metal.
add: Exercise equipment can be deconstructed.
/:cl:

2024-03-16 20:15 UTC, Apogee-dev commented
I’d actually prefer if exercise equipment could be unanchored and dragged in addition to deconstructed. Maybe allow for unanchoring weight benches with wrench and deconstructing with a screwdriver?

2024-03-17 23:22 UTC, Gristlebee commented
> I’d actually prefer if exercise equipment could be unanchored and dragged in addition to deconstructed. Maybe allow for unanchoring weight benches with a wrench and deconstructing with a screwdriver?

It's been added, and the punching bag can also be unwrenched.

2024-03-20 14:48 UTC, west3436 commented on code/modules/mining/lavaland/ruins/gym.dm
> +	var/uraction = anchored ? "unsbolt [src] from" : "bolt [src] to"
typo "unsbolt"

2024-03-20 14:52 UTC, west3436 commented on code/modules/mining/lavaland/ruins/gym.dm
> +		return TRUE
Ensure you want to return TRUE here; if not, remove the "else" statement entirely

2024-03-20 14:53 UTC, west3436 commented on code/modules/mining/lavaland/ruins/gym.dm
> +		return TRUE
Verify that TRUE should be returned here even if the action is not completed.

2024-03-20 14:54 UTC, west3436 commented on code/modules/mining/lavaland/ruins/gym.dm
> +	var/uraction = anchored ? "unsbolt [src] from" : "bolt [src] to"
Same typo as above

2024-03-20 14:54 UTC, west3436 commented on code/modules/mining/lavaland/ruins/gym.dm
> +		return TRUE
Same note regarding TRUE returns.

2024-03-20 18:39 UTC, Gristlebee commented on code/modules/mining/lavaland/ruins/gym.dm
> +	var/uraction = anchored ? "unsbolt [src] from" : "bolt [src] to"
Typo fixed.

2024-03-20 18:40 UTC, Gristlebee commented
Typos have been fixed, the extraneous TRUE returns are removed. Also fixed a typo I noticed. Bolt and unbolt messages were backwards.

2024-03-20 19:11 UTC, Gristlebee commented on code/modules/mining/lavaland/ruins/gym.dm
> +		return TRUE
Not having the TRUE present causes the mob to attack the bench after the action.

2024-03-20 19:12 UTC, Gristlebee commented
Seems like the TRUEs are necessary, but now Rust is failing. Agh.

2024-03-25 08:46 UTC, Gristlebee commented
Typos are fixed, the the TRUEs are necessary to prevent the tools from hitting the benches or the bag after the action. Everything should hopefully be good now.

2024-03-27 01:11 UTC, MarkSuckerberg requested changes, later dismissed
just a few tiny things

2024-03-27 01:11 UTC, MarkSuckerberg commented on code/modules/mining/lavaland/ruins/gym.dm
> +		return TRUE
```suggestion
	return TRUE
```

2024-03-27 01:11 UTC, MarkSuckerberg commented on code/modules/mining/lavaland/ruins/gym.dm
> +	..()
```suggestion
	return ..()
```

2024-03-27 01:11 UTC, MarkSuckerberg commented on code/modules/mining/lavaland/ruins/gym.dm
> +		return TRUE
```suggestion
	return TRUE
```

2024-03-27 01:11 UTC, MarkSuckerberg commented on code/modules/mining/lavaland/ruins/gym.dm
> +	return TRUE
```suggestion
	return anchored == check_anchored
```

2024-03-27 02:35 UTC, Gristlebee commented
Suggested changes have been added, and it looks like everything works

2024-03-30 14:33 UTC, thgvr requested changes

2024-03-30 14:33 UTC, thgvr commented on code/modules/mining/lavaland/ruins/gym.dm
> +		. += "<span class='notice'>[src] is <b>bolted</b> to the floor.</span>"
Can you please convert all of these to span macros?
Example:
```suggestion
		. += span_notice("[src] is <b>bolted</b> to the floor.")
```

2024-03-30 20:27 UTC, Gristlebee commented
Spans have all been converted to macros as requested

2024-04-11 19:37 UTC, thgvr approved these changes

2024-04-11 20:44 UTC, merged