Frontiersman Distillery Ruin
shiptest-ss13/Shiptest pull request #2907
Opened 2024-04-16 17:03 UTC by goober3

## hey look it's a new ruin
<details><summary>The Ruin</summary>

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/e9b43902-945a-4090-9be9-a0da753ebcff)

![2c5f52abe42891f0bfc41d57205f0e86](https://github.com/shiptest-ss13/Shiptest/assets/118859017/4697ec2b-a78b-46ad-930e-d1ce491295dc)

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/d05d6996-47da-46ea-8f35-ef35ac5578ca)

</details>

## and another <s>pill</s> subshuttle
![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/39eb60d5-1244-4cc1-9524-96f31438d689)

## About The Pull Request
This PR adds a new ruin to rockplanets featuring a group of New Frontiersman bootleggers based out of a pre-ICW era Nanotrasen research facility.
A new type of bottle crate for moonshine bottles has been added, as well as a new subtype of Frontiersmen, without need for air.
Moonshine now requires a fermenting barrel or distillery to be produced. Thank you to @FalloutFalcon for providing the code that makes this work, as well as refactoring bottle crates to make them work with variables.

<details><summary>Threats</summary>

```
- Melee Frontiersman (x3)
- Revolver Frontiersman (x4)
- Rifle Frontiersman Trooper (x4)
- Rifle Frontiersman
- Frontiersman Officer
- Mi-go (Dog)
- Explosive Mines (x5)
```

</details>

<details><summary>Major Loot</summary>

```
- Moonshine Jugs (x31)
- Moonshine Keg
- Moonshine Vat
- Regular Medkit
- Bicaridine Bottles (x2)
- Common Machine Boards (x2)
- Common Computer Board
- Drink Dispenser
- Booze Dispenser
- SRM Distiller
- Autolathe
- Uranium PACMAN Generator
- ~4000 credits
- Hydroponics Trays (x2)
- .357 Revolver (x2)
- HP Shadow
- .45 Speedloader
- .357 Speedloader (x2)
- Commander
- Stetchkin Pistol
- Empty Commander Magazine (x2)
- AP 9mm Ammo Box
- Stetchkin Magazine (x2)
- Mosin Rifle (x3)
- Mosin Clip (x2)
- Armor Vest (x3)
- SWAT helmet (x2)
```

</details>

## Changelog

🆑 goober3, FalloutFalcon
add: A new Frontiersman-themed rockplanet ruin.
add: Frontiersmen now have subtypes with oxygen masks.
tweak: Moonshine can now only be brewed via fermenting barrels & distillers.
code: Drinks recipes can now have multiple required containers.
/🆑

2024-04-16 17:27 UTC, goober3 commented
![3e315ec0253ef2041bbf559a939571d1](https://github.com/shiptest-ss13/Shiptest/assets/118859017/f97202a3-81c9-41f5-beb2-912c78360018)
![7d3bdc581cb7faef78beea2a9f5be7e9](https://github.com/shiptest-ss13/Shiptest/assets/118859017/533e55cd-b7b3-4941-b819-2bee12d9671c)
whar

2024-04-24 14:01 UTC, FalloutFalcon requested changes

2024-04-24 14:01 UTC, FalloutFalcon commented on code/modules/reagents/chemistry/holder.dm
> +						if(typesof(C.required_container))
This currently just returns a list of types but has the (unwanted?) side effect of allowing sub types. buttt since your not comparing it against your cached item it returns true if anything is in required_container. Change this to (cached_my_atom.type in C.required_container) This compares the type against the types in your list

but also required_container is not yet a list
var/obj/item/reagent_containers/required_container = null // the exact container path required for the reaction to happen

ORRRR if you want to be lazy
just do 
(cached_my_atom.type in typesof(C.required_container))
this means that any subtypes of an item works (this is currently fine but strict types are probally better here
and your moonshine react goes from
	required_container = list(/obj/structure/fermenting_barrel,
	/obj/structure/fermenting_barrel/distiller)
to
	required_container = /obj/structure/fermenting_barrel
since distiller is a subtype of barrel and typesof grabs  the "main" type and any subtypes it works

2024-04-24 14:01 UTC, FalloutFalcon commented on code/modules/reagents/chemistry/holder.dm
> +						if(typesof(C.required_container))
Sorry if i got something wrong when i first explained this to you

2024-04-24 14:01 UTC, FalloutFalcon commented on code/modules/reagents/chemistry/holder.dm
> +						if(typesof(C.required_container))
is this how you do this?
```suggestion
						if(cached_my_atom.type in typesof(C.required_container))
```

2024-04-24 14:01 UTC, FalloutFalcon commented on code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +	required_container = list(/obj/structure/fermenting_barrel,
I dont know how to grab multiple lines here but. this is all you need
```suggestion
	required_container = /obj/structure/fermenting_barrel
```

2024-04-24 14:01 UTC, FalloutFalcon commented on code/modules/food_and_drinks/drinks/drinks/bottle.dm
Perfect

2024-05-04 18:12 UTC, Latentish commented
I should remove window spawners. Please don't use them in your maps =)

2024-06-22 17:00 UTC, SomeguyManperson commented on _maps/map_catalogue.txt
> +
```suggestion
```
p sure these are all removed

2024-06-22 22:44 UTC, goober3 commented on _maps/map_catalogue.txt
> +
i'm the sufferer

2024-06-26 16:05 UTC, FalloutFalcon approved these changes

2024-07-11 23:07 UTC, rye-rice requested changes
_maps/RandomRuins/RockRuins/rockplanet_distillery.dmm:2210:error: undefined type: /obj/structure/guncase
_maps/RandomRuins/RockRuins/rockplanet_distillery.dmm:2213:error: unknown type

This is why it won't merge

2024-07-16 08:37 UTC, rye-rice commented
Bump

2024-07-17 02:35 UTC, SomeguyManperson commented on _maps/RandomRuins/RockRuins/rockplanet_distillery.dmm
> +/obj/structure/guncase,
```suggestion
/obj/structure/guncloset,
```

2024-07-20 13:09 UTC, goober3 commented
hi, this PR is fixed now. sorry for the delay. could someone like and hit the merge button please.

2024-07-23 17:11 UTC, rye-rice approved these changes

2024-07-23 17:48 UTC, merged