Ports Bodycameras from Fulp
shiptest-ss13/Shiptest pull request #2982
Opened 2024-05-11 22:50 UTC by Zevotech

## About The Pull Request
Ports a player-attachable camera that can be viewed on security camera consoles from fulpstation with some adjustments and fixes to make it work on our codebase. 
Also ports most of https://github.com/tgstation/tgstation/pull/52767 to fix movable cameras being a black screen.

The body camera is attached to a jumpsuit, and enabled using an ID. The jumpsuit must be worn for the camera to be active. The body camera can be used on a security camera console to connect it to the network of the console.

TODO:

- [ ] Make modcomps connectable to security camera console networks and maybe start with the security camera network of the area they spawn in
- [ ] Possibly get better sprites for the body cameras
- [ ] Add body cameras to maps that would have them

## Why It's Good For The Game
You can now monitor individuals from afar using a security camera console! Good for mining vessels and military vessels, as well as any vessel with a dedicated, well-stocked security force. Great for coordination!

## Changelog

:cl:
add: adds Bodycameras, ported from fulpstation
fix: Ports a fix from tg that fixed movable cameras being a black screen
/:cl:

2024-05-12 01:00 UTC, Sun-Soaked commented
aegis security turn off bodycam macro

2024-06-15 05:58 UTC, FalloutFalcon requested changes

2024-06-15 05:58 UTC, FalloutFalcon commented on code/modules/clothing/body_camera.dm
> +	AddComponent(/datum/component/bodycamera_holder)
I dont like this being here, it should be in the real Init.

2024-06-15 05:58 UTC, FalloutFalcon commented on code/game/machinery/computer/camera.dm
> +
This runtime if you attack it with something that isent a body-cam and prevents you from attacking it
```suggestion
/obj/machinery/computer/security/attackby(obj/item/I, mob/user, params)
	if(istype(I, obj/item/bodycam))
		var/obj/item/bodycam/bodycam = I
		bodycam.cameranetwork = network
		user.balloon_alert(user, "body camera linked to network.")
	else
		return ..()
```

2024-08-06 07:57 UTC, rye-rice commented
sowwy, nwo prwogwess iwn mwonths, rweopwen wwen wrorking on iwt agwian

2024-08-06 07:57 UTC, closed without merging