Adds Gun Cases. For guns.
shiptest-ss13/Shiptest pull request #2998
Opened 2024-05-17 23:08 UTC by Martinpachu

## About The Pull Request

Adds in gun cases that can hold a variety of guns and magazines, intended for use in cargo and certain ships and ruins. Sprites by retlaw are a work in progress.

## Why It's Good For The Game

Adds in a cool way to store firearms safely, and also its realistic i think. Also requested by apogee.

## Changelog

:cl:
add: Cargo guns and certain guns in ships now come inside cases alongside some magazines, the ammo now comes separately for safety reasons.
/:cl:

2024-05-17 23:10 UTC, SomeguyManperson commented on code/modules/projectiles/guns/ballistic.dm
> +	if (!spawnwithmagazine && !istype(magazine, /obj/item/ammo_box/magazine/internal))
```suggestion
	if (!spawnwithmagazine && !ispath(mag_type, /obj/item/ammo_box/magazine/internal))
```
I goofed here

2024-05-18 20:44 UTC, Martinpachu commented
Should be **ready.** A **test-merge** would be good.

2024-06-02 03:42 UTC, retlaw34 commented
fix your merge conflict!!

2024-06-04 23:49 UTC, FalloutFalcon requested changes, later dismissed

2024-06-04 23:49 UTC, FalloutFalcon commented on code/modules/cargo/packs/gun.dm
> +	cost = 300
"sold for less then 200cr." 300cr

2024-06-24 02:13 UTC, merged