Tegu-class Communications Freighter
shiptest-ss13/Shiptest pull request #3016
Opened 2024-05-22 18:50 UTC by goober3

## About The Pull Request
This PR adds a brand new ship to Nanotrasen's post-rework roster.

<details><summary>Images</summary>

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/6a41eddd-fcbe-4630-b1b9-814d3f966671)

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/6c1ca5ac-0b24-4086-b9b9-a9a5cb4eb3b5)

![image](https://github.com/shiptest-ss13/Shiptest/assets/118859017/39594bbe-7837-4d49-a21f-442e42af5e2d)

</details>

The Tegu-class is an engineering freighter equipped with a full telecommunications setup and a subshuttle. It is built to not only facilitate communications between Nanotrasen-aligned vessels in the sector, but also foster several smaller networks for other vessels with a small array of relays. The ship also comes equipped with a small cargo department, an engineering department, a small communications room, and a supply office for the QM.

This PR also adds a new design disk for printing telecommunications parts. 

## Why It's Good For The Game
more ship

## Changelog

:cl:
add: The Tegu-class Communications Freighter, a Nanotrasen comms ship.
add: A new subshuttle, the Skink-class Cargo Runner.
/:cl:

2024-06-01 17:01 UTC, EEASAS commented
okkk.... but isnt there like.... new ship restrictions.... like you cant make new nanotrasen/independent/syndicate/srm/solgov ships......

2024-06-01 17:02 UTC, meemofcourse commented
do they know chat

2024-06-01 17:04 UTC, goober3 commented
> okkk.... but isnt there like.... new ship restrictions.... like you cant make new nanotrasen/independent/syndicate/srm/solgov ships......

i'm doing this in defiance of the maptainers because i hate them

2024-06-01 17:04 UTC, thgvr commented
> okkk.... but isnt there like.... new ship restrictions.... like you cant make new nanotrasen/independent/syndicate/srm/solgov ships......

This restriction is for contributors outside of the main team.

2024-07-12 21:40 UTC, rye-rice commented
sowwy, nwo prwogwess iwn mwonths, rweopwen wwen wrorking on iwt agwian

2024-08-24 20:41 UTC, goober3 commented
we're so back

2024-08-27 21:22 UTC, thgvr commented
I am begging you to finish this

2024-08-27 21:27 UTC, goober3 commented
> I am begging you to finish this

this is technically already finished. it just needs a review and a description.

2024-09-03 04:10 UTC, meemofcourse requested changes
![imagen](https://github.com/user-attachments/assets/ac9c11fa-a89b-477d-9cc9-d6c52f89567f)
i do not like that the lightswitch in the officer's lounge controls the lights in the officers' quarters. there are also three light switches in the cargo office
![imagen](https://github.com/user-attachments/assets/82bf8cdc-0b34-4c78-a904-c6be7c3f9083)
this restroom needs better lighting
![imagen](https://github.com/user-attachments/assets/bd704628-5fe9-4a45-a4b6-94f190ee3cba)
i believe the pda painter is a centcom utility and it lets you have SUNS pdas so it would be best to remove it
![imagen](https://github.com/user-attachments/assets/7db5319e-ee04-405f-9de9-4ac53599a318)
the only set of tools i could find in this ship are hidden below two welding helmets. consider adding toolboxes and toolbelts to the engineer and engi director lockers - they should not start with them
![imagen](https://github.com/user-attachments/assets/b260f892-62dc-4247-9ec6-7e67d95c87b3)
maybe have an emergency suit here
![imagen](https://github.com/user-attachments/assets/2dd53e5b-72bc-4b9f-ae05-2eec90b9cb2f)
while i'm not an engi player i don't think this is right

maybe a ship like this could use a power monitor. i'd ask a maptainer/other person who is more experienced with telecommunications to test things out but cool ship

2024-09-03 17:27 UTC, goober3 commented
> i do not like that the lightswitch in the officer's lounge controls the lights in the officers' quarters. there are also three light switches in the cargo office

this was done so i wouldn't have to make more areas and add APCs to the officer's quarters but in hindsight i probably should just do that. also the multiple lightswitches exist for the same reason you'd have two light switches on both ends of a hallway. it's more convenient like that.

> i believe the pda painter is a centcom utility and it lets you have SUNS pdas so it would be best to remove it

i might add a generic sanitised version of the PDA painter later in a seperate PR. for now they can live without.

thak yuo

2024-09-07 06:22 UTC, fighterslam commented
The "/turf/open/floor/plasteel/telecomms_floor" (north floor) starts with the normal, default airmix, 101.3 KPA, etc. The circuit floors (south floor) "turf/open/floor/circuit/telecomms" constantly produce a colder airmix, causing these two adjacent turfs to have atmos differences and process once they spawn in, so I think this might be a small performance concern. It was something I had to deal with on the Ranger too - you probably either want to set the circuit floors to normal circuit floors so there's no atmos differences, or make a new telecomms_floor type that has the same initial airmix. 
![image](https://github.com/user-attachments/assets/a56a1362-29a7-4ba3-8c34-394d34aab938)

2024-09-10 04:21 UTC, meemofcourse approved these changes
this ship rocks dude

2024-09-23 05:29 UTC, rye-rice commented
@shiptest-ss13/maptainers

2024-09-23 05:54 UTC, Sadhorizon commented on _maps/configs/nanotrasen_tegu.json
> +{
Add `"faction": "/datum/faction/nt"`, somewhere, or it's gonna show as indie on the spawning menu.

2024-11-03 10:23 UTC, thgvr commented
@shiptest-ss13/maptainers ancient pr, please decide if its being merged or not

2024-11-04 19:28 UTC, goober3 commented
> @shiptest-ss13/maptainers ancient pr, please decide if its being merged or not

this still has yet to be tested substantially in-game actually. some day...

2024-11-07 00:00 UTC, DorfGuy1 commented
Where's the guide?
 TO the comms

2024-11-16 22:58 UTC, tzui5020 commented
It needs a chair or a few railings in the Cargobay please. I beg you

2024-12-03 13:18 UTC, thgvr commented
purgatory

2024-12-07 14:57 UTC, meemofcourse approved these changes
BWAAH SCARY TELECOMMS

2024-12-07 15:10 UTC, merged