Granularizes mech equipment
shiptest-ss13/Shiptest pull request #3039
Opened 2024-05-29 21:55 UTC by Gristlebee

## About The Pull Request

Granularizes mech equipment in the outpost catalogue and adjusts some of the descs.

## Why It's Good For The Game

More fine control how much you need to order at the outpost is good. And honestly? Who needs three drills?

## Changelog

:cl:
tweak: Granularizes mech equipment
tweak: mech cargo pack descs
/:cl:

2024-05-29 22:31 UTC, Martinpachu commented
i drink mech equipment for lunch. you worm.

2024-05-31 06:26 UTC, FalloutFalcon requested changes, later dismissed

2024-05-31 06:26 UTC, FalloutFalcon commented on code/modules/cargo/packs/mechs.dm
>  /datum/supply_pack/mech/equipment/scanners
```suggestion
/datum/supply_pack/mech/equipment/scanner
```

2024-05-31 06:26 UTC, FalloutFalcon commented on code/modules/cargo/packs/mechs.dm
> +	desc = "A trio of electronic mining scanners, graded to interface with a mech."
```suggestion
	desc = "An electronic mining scanner, graded to interface with a mech."
```

2024-06-02 09:12 UTC, merged