Saint Roumain Militia Content Expansion Part 2: New Jobs!
shiptest-ss13/Shiptest pull request #3119
Opened 2024-06-17 11:58 UTC by Imaginos16

## About The Pull Request
THE LONG AWAITED SEQUEL!

This PR adds a ton of things, but let's start with the most important changes:

![image](https://github.com/shiptest-ss13/Shiptest/assets/77556824/a835e27d-81d4-47ae-a32d-de3573779800)

Not only has every job has been tweaked and resprited visually, but you might've noticed at least three unfamiliar faces to the roster of the Saint Roumain's Militia! This is because now, there are new jobs for people to enjoy!

These include:

- The Flamebearer, a member of the ecclesiastical sect of the Church of Saint Roumain, focused on preaching the word of Saint Roumain, the Ashen Huntsman, through the holy text of the Liber Incendium!

- The Machinist, a dedicated hunter focused on engineering prowess. Most workers of Hunter's Pride incidentally are Machinists by trade back in Illestren!

- The Hunter Colligne, effectively a secondary rank to the Montagne. They are trainee Hunter Montagnes effectively, learning the art of hunting and commandeering to eventually lead their own cadre of Hunters as a Montagne.

All jobs within the SRM also have unique job icons exclusive to them. Hope you enjoy it!

This PR tweaks some minor stuff aboard the Elder-class, specifically to accomodate the new jobs. A Shadow slot has been killed in exchange for one Colligne, one Machinist and one Flamebearer slot.

And finally, this PR does the absolutely random thing of updating the ID-less icon and its background for no other reason other than I could.
![image](https://github.com/shiptest-ss13/Shiptest/assets/77556824/586919c7-3472-4b0e-9abd-d35fdfe72215)

## Why It's Good For The Game
Pleade join my shipse I begge...

## Changelog

:cl: PositiveEntropy
add: The Hunters of Illestren have now allowed for Hunter Collignes, Machinists and Flamebearers to now roam the Frontier aboard their humble fleet!
imageadd: The Saint Roumain's Militia has been fully resprited!
imageadd: All SRM jobs now have unique HUD icons!
imageadd: The Unknown Job HUD icon has been resprited!
/:cl:

2024-06-17 18:30 UTC, generalthrax commented
The Fire Within

2024-06-17 21:55 UTC, SomeguyManperson commented on code/modules/clothing/spacesuits/hardsuit.dm
> -//Hardliner Syndie suit
?

2024-06-17 22:56 UTC, Imaginos16 commented on code/modules/clothing/spacesuits/hardsuit.dm
> -//Hardliner Syndie suit
Duplicate path I killed.

2024-06-18 07:46 UTC, thgvr commented on code/modules/clothing/factions/srm.dm
> +	name = "saint-roumain flambearer robes"
```suggestion
	name = "saint-roumain flamebearer robes"
```

2024-06-18 07:54 UTC, Apogee-dev requested changes, later dismissed

2024-06-18 07:54 UTC, Apogee-dev commented on code/modules/clothing/factions/srm.dm
> +	name = "saint-roumain flambearer robes"
Typo here ("flambearer"). Should be "flamebearer"

2024-06-18 07:54 UTC, Apogee-dev commented on code/modules/clothing/factions/srm.dm
> +	desc = "A set of ashy-grey robes made from hard leather, adorned with gold trims. Its rough finish after a near-char and application of aromatics is heavily favored for the ecclesiastical sect of th
"A set of ash-grey robes made from hard leather and adorned with gold trim and impregnated with aromatic oils. The rough, nearly-charred finish is a favorite of the ecclesiastical sect of the Church of Saint Roumain, a constant reminder of the Ashen Huntsman himself."

2024-06-18 07:54 UTC, Apogee-dev commented on code/modules/clothing/factions/srm.dm
> +	desc = "A well-maintained hard leather coat typically worn to denote the rank of Colligne, a trainee Hunter Montagne. It is treated with bullet-resistant materials, and lined with the dark fur of Il
Typo here ("Illestrenin"). Should be "Illestrian"

2024-06-18 07:54 UTC, Apogee-dev commented on code/modules/clothing/factions/srm.dm
> +	desc = "An armor-plated knight's helmet, the pointed design of it reminiscent of iconography depicting the great Ashen Huntsman."
"An armored helmet with an unusual design that recalls both pre-industrial Solarian armor and iconography depicting the Ashen Huntsman. Though hand-made, it is surprisingly quite spaceworthy."

2024-06-18 07:54 UTC, Apogee-dev commented on code/modules/clothing/factions/srm.dm
> +	desc = "A modified knight's plate armor turned into a space-worthy hardsuit. A powered exoskeleton hidden behind the plates help grant it slight maneuverability."
Suggested rewrite to drive home the artisanal nature of most SRM gear and make Hunter's Pride more than a little more explicitly badass: 
"A hand-crafted suit of armor either modified from a set of normal plate armor or designed to resemble one. A powered exoskeleton has been cleverly integrated into the design and, surprisingly, it is completely vacuum-proof. Suits like this are a testament to what the master craftsmen of Hunter's Pride are capable of."

2024-06-18 08:57 UTC, merged