Hazardous Gases (Cl and HCl)
shiptest-ss13/Shiptest pull request #3180
Opened 2024-07-05 08:10 UTC by Thera-Pissed

## About The Pull Request
Adds chlorine gas and hydrogen chloride gas
These gases hurt to be exposed to in high concentration if not in EVA
Plasma, Trit, Cl, and HCl now damage eyes if not wearing goggles (welding, heat, or cold goggles currently)
Chlorine reacts with hydrogen to make HCl and makes heat while doing so. HCl burns into H2O and Cl.
![image](https://github.com/shiptest-ss13/Shiptest/assets/90987989/e0263c74-0958-475f-b956-4024b32ed237)

The life code changes likely aren't the best. Mostly drafting this so I feel obligated to keep working on it and can get some input.

## Why It's Good For The Game
Hazardous planetary gases! (not actually implemented in this PR, but opens up the possibility)
More gases that are actually relevant to Normal shiptest rounds is good, since there's few station gases that can be reasonably seen or made (freon has been made like once. stimulum and nitryl are dumb. likely could be removed)

## Changelog

:cl:
add: Chlorine and Hydrogen Chloride gases! Wear your goggles!
/:cl:

2024-07-05 08:12 UTC, Thera-Pissed commented
woohoo 164 commits because I started before hydrogen got in!

2024-07-10 19:24 UTC, rye-rice reviewed
Push a new commit, seems checks failed for some unrelated reason

2024-07-10 19:24 UTC, rye-rice commented on code/modules/atmospherics/machinery/portable/canister.dm
>  	)
o,
```suggestion
		"fuel mix" = /obj/machinery/portable_atmospherics/canister/fuel,
		"chlorine" = /obj/machinery/portable_atmospherics/canister/chlorine,
		"hydrogen chloride" =/obj/machinery/portable_atmospherics/canister/hydrogen_chloride,
	)
```

2024-07-10 19:52 UTC, rye-rice commented
oh wow that fixed the checks

2024-07-25 18:30 UTC, SomeguyManperson commented on code/modules/mob/living/carbon/human/life.dm
> +	return FALSE
```suggestion
	var/obj/item/clothing/CS = wear_suit
	var/obj/item/clothing/CH = head
	if(istype(CS) && istype(CH))
		if (CS.clothing_flags & CH.clothing_flags & STOPSPRESSUREDAMAGE)
			return TRUE
	return FALSE
```

2024-08-03 10:10 UTC, rye-rice commented
Tell me if this still isn't finished, I'll merge in like 2 days after skimming the code if a review isn't given

2024-08-05 04:36 UTC, firebudgy commented
Spilled a bottle of chlorine on a local and it runtimed.
![image](https://github.com/user-attachments/assets/5ba96ccd-b6a7-4ff9-a8d1-2d659d916abb)
![image](https://github.com/user-attachments/assets/77a41d83-69ef-44ee-8cad-d82f9b491ad2)

2024-08-05 23:43 UTC, rye-rice requested changes

2024-08-05 23:43 UTC, rye-rice commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	if(istype(T))
Avoid single letter vars, changing obj/O to obj/exposed_object shouldn't mess anything up i think, same with turf/open/T

2024-08-05 23:43 UTC, rye-rice commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +
Same here with M

2024-08-06 07:39 UTC, rye-rice approved these changes

2024-08-06 07:48 UTC, merged