Custom Drinks Patch (it will break)
shiptest-ss13/Shiptest pull request #321
Opened 2021-10-06 16:53 UTC by zestybastard

## About The Pull Request

Adds Terg's custom drink sprites. This patch will break. I guarantee it.

## Why It's Good For The Game

edward....

## Changelog
:cl:
add: new drinks
/:cl:

2021-10-06 16:56 UTC, Ms-Mee commented
add: New drinks

2021-10-06 17:15 UTC, Ms-Mee requested changes
One last tiny thing missing, but other than that seems all good.

2021-10-06 17:15 UTC, Ms-Mee commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +
```suggestion
	var/obj/effect/light_holder
	
```

2021-10-06 17:24 UTC, Ms-Mee approved these changes
Good first PR indeed, if something else I missed breaks that's on me

2021-10-06 17:26 UTC, zestybastard commented
> 
> 
> Good first PR indeed, if something else I missed breaks that's on me

thanks! i stole all of it

2021-10-06 17:29 UTC, Ms-Mee commented
> 
> 
> > Good first PR indeed, if something else I missed breaks that's on me
> 
> thanks! i stole all of it


Better than trying to make something new and just breaking everything including configs.txt somehow.

2021-10-06 20:56 UTC, Nobelium-XVIII commented
> > 
> > 
> > Good first PR indeed, if something else I missed breaks that's on me
> 
> thanks! i stole all of it

The wonders of open source

2021-10-06 21:06 UTC, Bokkiewokkie commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/out_of_lime/expose_mob(mob/living/M, method=INGEST, reac_volume)
should be /datum/reagent/consumable/ethanol/out_of_lime in these paths

2021-10-06 21:08 UTC, zestybastard commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/out_of_lime/expose_mob(mob/living/M, method=INGEST, reac_volume)
noted, tyty

2021-10-06 21:27 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	color = pick(potential_colors)
```suggestion
/datum/reagent/consumable/ethanol/out_of_lime/proc/update_color()
	color = pick(potential_colors)

```

2021-10-06 21:29 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +			H.update_hair()
```suggestion
/datum/reagent/consumable/ethanol/out_of_lime/expose_mob(mob/living/carbon/human/consumer, method=INGEST, reac_volume)
	if(method == INGEST || method == TOUCH)
		if(istype(consumer))
			consumer.hair_color = pick(potential_colors)
			consumer.facial_hair_color = pick(potential_colors)
			consumer.update_hair()
```

2021-10-06 21:29 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	SSticker.OnRoundstart(CALLBACK(src,.proc/UpdateColor))
```suggestion
	SSticker.OnRoundstart(CALLBACK(src,.proc/update_color))
```

2021-10-08 13:46 UTC, zestybastard commented
New update: adds several changes suggested by Unutrius (big thanks) and also attempts to simplify the Out Of Lime Code

2021-10-08 18:10 UTC, ZephyrTFA commented on whitesands/code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +	required_reagents = list(/datum/reagent/consumable/ethanol/screwdrivecocktail = 2, /datum/reagent/consumable/ethanol/margarita = 1)
This line is throwing errors because the screwdriver cocktail path is invalid. Make sure this is the correct path

2021-10-10 20:09 UTC, zestybastard commented on whitesands/code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +	required_reagents = list(/datum/reagent/consumable/ethanol/screwdrivecocktail = 2, /datum/reagent/consumable/ethanol/margarita = 1)
fixed possibly let me double check

2021-10-12 17:24 UTC, zestybastard commented
updated some stuff thanks to advice from unutrius, the real MVP

2021-10-14 03:39 UTC, ZephyrTFA requested changes

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +
```suggestion

```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +
```suggestion

```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +
```suggestion

```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +		M.use(reac_volume)
```suggestion
		M.use(reac_volume)

```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/darkest_chocolate/on_mob_metabolize(mob/living/M)
```suggestion

/datum/reagent/consumable/ethanol/darkest_chocolate/on_mob_metabolize(mob/living/M)
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/darkest_chocolate/on_mob_life(mob/living/carbon/M)
```suggestion

/datum/reagent/consumable/ethanol/darkest_chocolate/on_mob_life(mob/living/carbon/M)
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/darkest_chocolate/on_mob_end_metabolize(mob/living/M)
```suggestion

/datum/reagent/consumable/ethanol/darkest_chocolate/on_mob_end_metabolize(mob/living/M)
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/archmagus_brew
```suggestion

/datum/reagent/consumable/ethanol/archmagus_brew
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/archmagus_brew/on_mob_life(mob/living/carbon/human/M)
```suggestion

/datum/reagent/consumable/ethanol/archmagus_brew/on_mob_life(mob/living/carbon/human/M)
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/out_of_lime
```suggestion

/datum/reagent/consumable/ethanol/out_of_lime
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/out_of_lime/expose_mob(mob/living/carbon/human/consumer, method=INGEST, reac_volume)
```suggestion

/datum/reagent/consumable/ethanol/out_of_lime/expose_mob(mob/living/carbon/human/consumer, method=INGEST, reac_volume)
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +/datum/chemical_reaction/freezer_burn
```suggestion

/datum/chemical_reaction/freezer_burn
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +/datum/chemical_reaction/out_of_touch
```suggestion

/datum/chemical_reaction/out_of_touch
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +/datum/chemical_reaction/darkest_chocolate
```suggestion

/datum/chemical_reaction/darkest_chocolate
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +/datum/chemical_reaction/out_of_lime
```suggestion

/datum/chemical_reaction/out_of_lime
```

2021-10-14 03:39 UTC, ZephyrTFA commented on whitesands/code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +/datum/chemical_reaction/archmagus_brew
```suggestion

/datum/chemical_reaction/archmagus_brew
```

2021-10-19 04:19 UTC, ZephyrTFA commented
See #363

2021-10-19 04:19 UTC, closed without merging