Adds Clockwork Sect and Ratvarian Language
shiptest-ss13/Shiptest pull request #322
Opened 2021-10-06 22:08 UTC by untrius

## About The Pull Request

Adds the Clockwork religious sect, and gives them a little bit to do.

My intent here was to make a new set of things to do for the chaplain on the Shepard-class.  As I have written it, this is mostly RP fuel.

Features added:
1) Clockwork sect is now selectable from the Altar of the Gods.
-Using red alter sprite while a new one is being sprited
2) Metal/iron sheets can be sacrificed for 1 favor each.
-Could be extended to accept other metals
3) 60 favor can be traded for 30 brass via brass transmutation rite.
-Allows Shepard's crew to refit the ship in brass if they want
-Could add new rites to create more things from brass
4) Chaplain in clockwork sect knows the Ratvarian language and can teach it by blessing with their bible.
![image](https://user-images.githubusercontent.com/7697956/136289716-e342cdeb-892a-4428-834a-e832dad71a58.png)
![image](https://user-images.githubusercontent.com/7697956/136289734-c392520a-7c52-4c1d-a5d4-3838f759a649.png)

## Why It's Good For The Game

More stuff for people on the Shepard-class to do.

## Changelog
:cl:
add: Add Clockwork Sect
add: Re-add Ratvarian language
/:cl:

2021-10-06 22:09 UTC, untrius commented
It's probably ready now, but I'm drafting it so I can stare at the code a little longer.

2021-10-07 14:49 UTC, ZephyrTFA commented on code/__HELPERS/ratvarian_language.dm
> +/proc/text2ratvar(text) //Takes english and applies ratvarian styling rules (and rot13) to it.
Move the comment above and turn it into an autodoc comment

2021-10-07 14:50 UTC, ZephyrTFA commented on code/modules/religion/religion_sects.dm
> +/datum/religion_sect/clockwork/on_conversion(mob/living/L)
```suggestion
/datum/religion_sect/clockwork/on_conversion(mob/living/acolyte)
```

2021-10-07 14:51 UTC, ZephyrTFA requested changes
Just a few minor things. 
Change your one letter var names to be more descriptive and move your comments above the thing they are commenting and turn them into autodoc comments

2021-10-08 03:38 UTC, merged