Mapping hazards and types
shiptest-ss13/Shiptest pull request #3233
Opened 2024-07-21 09:52 UTC by Thera-Pissed

## STILL A WIP! DRAFTED BECAUSE I KEEP SHOWING STUFF OFF IN THE DISCORD
## About The Pull Request

Adds several mapping hazard base types that can be used to make new hazards.
Implements some baseline hazards using this.
I'll write more about this soon, just getting the draft up quick here.
basically, new obj/structure/hazard implemented
also
hazard/electrical (sparks zaps stuns)
hazard/floor (caltrops, slips, launchers)
hazard/smoke (smoke)
hazard/radioactive (old radiation barrels use this, need to tweak these still.)
hazard/slowdown (overhead, sticky, clamber over)

all of these are easily subtyped and can be customized with just variable changes, making it easy to implement for maps.

implemented electrical hazard example:
https://youtu.be/4P-67V_US6Q

## Why It's Good For The Game
Ruins could stand to have more hazards, and making it simpler for mappers to tweak hazards to their liking will make maps gooder I think.

## Changelog

:cl:
add: ruin hazards
/:cl:

2024-07-21 10:20 UTC, thgvr reviewed
https://github.com/shiptest-ss13/Shiptest/blob/master/.github/AUTODOC_GUIDE.md

2024-08-11 05:02 UTC, thgvr commented
Still being worked on? Let me know when you want a review

2024-08-11 05:21 UTC, Thera-Pissed commented
still being worked on, been busy this week, mostly drafted because I want more implemented hazards before its sent

2024-10-16 22:10 UTC, Thera-Pissed commented
if the electric hazards are wanted let me know, I'm not finishing the rest of this however.

2024-11-03 10:25 UTC, thgvr commented
Let us know when you want a review on this

2024-12-10 04:06 UTC, Thera-Pissed commented
My goal of having several hazards finished for this before review has made me stall on it for a while, if I could get a review now that'd be great. If anything seems wonky I'll cut it for a future PR.

2024-12-29 22:20 UTC, FalloutFalcon requested changes

2024-12-29 22:20 UTC, FalloutFalcon commented on code/modules/ruins/objects_and_mobs/generic_hazards/hazards/electrical_conduit.dm
This file is not ticked

2024-12-29 22:20 UTC, FalloutFalcon commented on code/modules/ruins/objects_and_mobs/generic_hazards/hazard_code/floor.dm
> +	sleep(10)
Try and avoid using sleep as its prone to causing overtime, I would swap this to an addtimer with a callback instead
something like 
```
addtimer(CALLBACK(src, PROC_REF(acctually_launch)), 0.5 SECONDS)
```

2025-01-06 13:49 UTC, FalloutFalcon commented
ehh this has been open for 2 long.. just remeber in future that sleeps are evil..

2025-01-06 13:49 UTC, FalloutFalcon approved these changes

2025-01-06 13:59 UTC, merged