The Particlening
shiptest-ss13/Shiptest pull request #3239
Opened 2024-07-23 20:06 UTC by rye-rice

## About The Pull Request

Fixes #1793

This adds a fuck ton of particles to the game. These are almost entirely ported from tgstation, specifically:
https://github.com/tgstation/tgstation/pull/71110 (I was unable to get the editor to work, so this is just the backend fancy stuff)
https://github.com/tgstation/tgstation/pull/59869 (particles)
https://github.com/tgstation/tgstation/pull/60515  (particles)
https://github.com/tgstation/tgstation/pull/74555 (particles)

And because atomization is not in my name, I have also done added my own spin on this, and that is making blood show up as a particle effect, instead of mysteriously showing up on the floor. I also made the mysteriously showing up on the floor bit more clearer if you are spilling a lot of blood.

Because of the above, I went further and ported https://github.com/DaedalusDock/daedalusdock/pull/79 (blood squirts only) as well for being shot, and some additions I made myself. I am aware using sleep() is bad practice, but I'm not sure how I would avoid using it here outside of rearranging how a lot of things work, so ill just say its "fine"

Also gibbing doesn't destroy your body anymore, however it STILL will be very hard to fix you reguardless, since you still fall apart like a lego character, it's just you no longer need to stuff them into a legion corpse.

And during testing since it annoyed me, bloodloss effects are more pronounced and harder to ignore, taken mostly from https://github.com/tgstation/TerraGov-Marine-Corps 's bloodloss effects but less severe in a way. 

And one last thing, bone breaking has sound effects, from Terragov above. Cronch.

## Why It's Good For The Game

While i'm not convinced over using particles over hand drawn sprite effects, I cannot deny i see the potential in them, especially here!

![Screenshot_15726](https://github.com/user-attachments/assets/714b60d7-46f0-429f-a94a-8b13220fb39e)

![Screenshot_15727](https://github.com/user-attachments/assets/8b00ad2b-13ba-4971-b2b4-dbf1975dce57)

![Screenshot_15728](https://github.com/user-attachments/assets/b78f91bf-0462-41a9-88aa-5f7b76c222ac)

![Screenshot_15729](https://github.com/user-attachments/assets/32e05c97-457c-4c11-a7c1-fe6f1aa6235f)

![Screenshot_15730](https://github.com/user-attachments/assets/27a6b03a-ca73-41e1-bfee-9a3cc8a25404)

## Changelog

:cl: Baystation12, Kapu1178, rye-rice
add: Particles!
add: Bleeding has better feedback
add: Bone breaking now has sound effects
add: Getting shot now throws blood squirts! Live through the somme for REAL this time!
balance: gibbing no longer destroys your chest, no more legion transfers!
fix: Lava particles should no longer destroy your FPS

/:cl:

2024-07-23 21:30 UTC, Apogee-dev commented
I already gave my opinion about the gibbing changes on discord but I’ll repeat them here: I think it’s a move in the wrong direction. All the sources of gibbing in the game are rare, predictable, or player-initiated. If implanting brains into legion corpses is unbelievable and jank, I’d rather remove brain implanting entirely. Not all round removal is a bad thing, and some failure states- especially ones that are predictable or triggered by another player’s direct choice- should not be recoverable.

2024-07-23 21:34 UTC, thgvr commented
Particle updates are great. This has no reason to be bundled with the gibbing change though

2024-07-25 06:36 UTC, Leon9621 commented
As a note, I believe the bone breaking sounds here cause people to crash when they play, depending on the version of BYOND they have installed. Not sure why- wish I could be more helpful here, sorry. 

https://i.imgur.com/c9zeSqP.png pic of it happening to me, cloudbreak mentioned it happening a few times as well

2024-07-25 07:47 UTC, thgvr commented on code/datums/looping_sounds/weather.dm
> +		'sound/ambience/storm_outdoors.ogg' = 1
```suggestion
		'sound/ambience/storm_outdoors.ogg' = 1,
```

2024-07-25 07:47 UTC, thgvr commented on code/modules/mob/living/blood.dm
> +/* how bleeding works has changed, this is now useless
Then delete it

2024-07-25 07:47 UTC, thgvr commented on code/modules/surgery/bodyparts/bodyparts.dm
> +	owner.visible_message("<span class='danger'>You hear a cracking sound coming from [owner]'s [name].</span>", "<span class='userdanger'>You feel something crack in your [name]!</span>", "<span class=
Span macros please

2024-07-25 07:47 UTC, thgvr commented on code/modules/surgery/bodyparts/bodyparts.dm
> +	playsound(owner, list('sound/health/bone/bone_break1.ogg','sound/health/bone/bone_break2.ogg','sound/health/bone/bone_break3.ogg','sound/health/bone/bone_break4.ogg','sound/health/bone/bone_break5.o
This is probably what is causing issues, maybe something about file access idk

2024-07-26 21:10 UTC, thgvr requested changes, later dismissed
Leave the non-visual gibbing changes (leaving a torso behind) for a different pr and discussion

2024-08-01 06:52 UTC, Thera-Pissed commented
Lava particles can be grabbed by gravitational anomalies and flung around, which looks quite silly.

2024-08-10 00:14 UTC, thgvr commented
We can merge this once you take out the gibbing change that leaves a torso behind

2024-08-26 20:44 UTC, rye-rice commented
apologies for the delay in removing the anti-salt measure, got distracted by a fucking butterfly; lgtm, etc

2024-08-26 21:45 UTC, merged