High-Class Corporate Luxury Ship
shiptest-ss13/Shiptest pull request #328
Opened 2021-10-10 04:26 UTC by Mannybrado

## About The Pull Request
Adds in a brand new ship, the High-Class. First(probably) in the new line of Corporate Luxury ships. Includes a boardroom and stuff. Also, a sec-tec vendor.

## Why It's Good For The Game
ceo of shiptest,
more roleplay ships are good i think

## Changelog
:cl:
add: new ship, high-class
/:cl:

2021-10-10 04:46 UTC, ValoTheValo commented
Could you post a picture of the ship?

2021-10-10 04:46 UTC, Mannybrado commented
![corpship](https://user-images.githubusercontent.com/54787585/136682563-3c80e5c6-16cb-4c5f-9ca6-fddc25ace5dd.png)
here. you can also look at the mapdiff bot, but, guh

2021-10-10 04:48 UTC, ValoTheValo commented
Oooh very nice

2021-10-11 00:02 UTC, Mannybrado commented
buhh trying to fix linters

2021-10-11 19:14 UTC, Mannybrado commented
videogames

2021-10-15 19:43 UTC, Anderson-Cooper requested changes

2021-10-15 19:43 UTC, Anderson-Cooper commented on _maps/configs/corphigh.json
> +		"Station Engineer": 1,
```suggestion
		"Station Engineer": 2,
```

2021-10-15 19:43 UTC, Anderson-Cooper commented on _maps/configs/corphigh.json
> +		"Station Engineer": 1,
we need more engineers.

2021-10-15 19:58 UTC, Mannybrado commented on _maps/configs/corphigh.json
> +		"Station Engineer": 1,
done

2021-10-17 03:35 UTC, triplezeta commented
classy indeed :+1:

2021-10-17 03:36 UTC, triplezeta approved these changes
looks solid

2021-10-17 04:18 UTC, merged