New Cargo Missions (Pirate Bounties, Salvage)
shiptest-ss13/Shiptest pull request #3327
Opened 2024-09-03 16:02 UTC by generalthrax

## About The Pull Request

A few more missions to cargo. Should make them more varied, with some financial incentive for combat ships or scrappers to search for certain things

- [ ] Add dogtags to Frontiersmen corpses
- [ ] Add dogtags to Ramzi drops
- [ ] Missions for both
- [ ] Turn in Protolathe Mission
- [ ] Turn in RND Console Mission
- [ ] Turn in Circuit Imprinter Mission
- [ ] Decrease weight of Fishing Missions

(prices subject to change)

## Why It's Good For The Game

More financial incentives to go hunt down the Pirate ruins for combat ships. A reason to stash up the rare machinery you find from ruins to sell them instead of Grinding RND And Getting Those Sweet Research Points

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-09-03 16:03 UTC, Martinpachu commented
who would EVER sell their RND? other than me

2024-09-03 16:48 UTC, generalthrax commented
Plenty would. Its also weighed to be Quite Rare so you're not stocking up like 8 RND boards for a shiptillion credits

2024-09-03 17:16 UTC, Madtankdriver commented
The dog tags on corpses sounds like a pretty cool idea. I like it!

2024-09-03 22:11 UTC, Martinpachu commented
> Plenty would. Its also weighed to be Quite Rare so you're not stocking up like 8 RND boards for a shiptillion credits
its less that you can get a bunch of them and more so that it's so rare and absurdly powerful that nobody would ever do it. i like it, though.

2024-09-03 22:13 UTC, generalthrax commented
I think you underestimate just how many people dislike interacting with RND. Outside of Gamers, at least. It'll be very low-weighted anyways, so w/e.

2024-09-03 22:15 UTC, Martinpachu commented
> I think you underestimate just how many people dislike interacting with RND. Outside of Gamers, at least. It'll be very low-weighted anyways, so w/e.

i dont think the weighing matters a lot since rnd is sooo rare either way. not really a problem i just thought it was a little funny.

2024-09-04 12:57 UTC, Aquidu commented
Thoughts on a potential mission where you have to turn in a canister of a certain gas?

2024-09-06 05:22 UTC, Apogee-dev commented
> > I think you underestimate just how many people dislike interacting with RND. Outside of Gamers, at least. It'll be very low-weighted anyways, so w/e.
> 
> i dont think the weighing matters a lot since rnd is sooo rare either way. not really a problem i just thought it was a little funny.

Don't worry! it's going to get rarer.

2024-09-16 01:45 UTC, thgvr commented
...are ramzi/frontiersmen mobs common enough for this?

2024-09-16 05:57 UTC, generalthrax commented
> ...are ramzi/frontiersmen mobs common enough for this?

Yes.

2024-10-14 22:21 UTC, generalthrax commented
This should be ready. I'm aware about Fallcon's dynamic mission stuff but I figured I'd get this out of the way to see if its compatible rather than just close this outright

2024-11-09 02:16 UTC, MarkSuckerberg approved these changes
still seems good for merge if you can manage to get a sprite for the dogtags and resolve the conflict since I think dynamic missions are still a little ways off

2024-11-09 23:39 UTC, generalthrax commented
Sounds good. I'll try and get it done once this uptime is over.

2024-11-12 06:39 UTC, generalthrax commented
Conflicts are fixed and I now have a sprite courtesy of @rye-rice. This should be good to go.

2024-11-14 15:25 UTC, Sun-Soaked commented
fix checks and conflicts and I'll get it in

2024-11-21 03:49 UTC, MarkSuckerberg requested changes
also you gotta add a worn state for the dogtags too

2024-11-21 03:49 UTC, MarkSuckerberg commented on code/modules/research/designs/comp_board_designs.dm
> -
you gotta remove this from the base research node to get it to pass checks. or just readd this

2024-11-27 17:48 UTC, MarkSuckerberg approved these changes

2024-11-27 18:00 UTC, merged