Adds the fireaxe to the black market
shiptest-ss13/Shiptest pull request #3364
Opened 2024-09-15 11:38 UTC by MassiveMen

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-09-20 13:15 UTC, FalloutFalcon commented
Way 2 cheap. Change the description to be something silly like 1 of a kind fireaxe stolen from nt and make it the same price as a high tier gun

2024-09-20 13:28 UTC, FalloutFalcon requested changes
What i said above or- make it rusty and nerf the damage

2024-09-20 13:45 UTC, generalthrax commented
> Way 2 cheap. Change the description to be something silly like 1 of a kind fireaxe stolen from nt and make it the same price as a high tier gun

Consider: Shiptest's combat scene is dominated by guns. You can buy a shotgun for the same price and deal like 6x times more damage in a quarter of the time. Melee's not quite have the kick it used to.

2024-09-20 13:48 UTC, FalloutFalcon commented
> > Way 2 cheap. Change the description to be something silly like 1 of a kind fireaxe stolen from nt and make it the same price as a high tier gun
> 
> 
> 
> Consider: Shiptest's combat scene is dominated by guns. You can buy a shotgun for the same price and deal like 6x times more damage in a quarter of the time. Melee's not quite have the kick it used to.

yes i agree but fireaxes should stay kinda rare and cool. this is way to cheap.
im already working on more melee.

2024-09-20 13:51 UTC, MassiveMen commented
> > > Way 2 cheap. Change the description to be something silly like 1 of a kind fireaxe stolen from nt and make it the same price as a high tier gun
> > 
> > 
> > Consider: Shiptest's combat scene is dominated by guns. You can buy a shotgun for the same price and deal like 6x times more damage in a quarter of the time. Melee's not quite have the kick it used to.
> 
> yes i agree but fireaxes should stay kinda rare and cool. this is way to cheap. im already working on more melee.

A price bump of that size would put it at the level of the SUNS saber (actually rare) or the magnetic cleaver (just better). In what universe are fire axes rare.

2024-09-20 13:53 UTC, generalthrax commented
Agreed. This is a glorified shipbreaking tool for destroying windows, at best.

2024-09-20 13:58 UTC, MassiveMen commented
> Way 2 cheap. Change the description to be something silly like 1 of a kind fireaxe stolen from nt and make it the same price as a high tier gun

As for the joke, sure I could try again, I threw that together at 4am and went to sleep

2024-09-26 22:15 UTC, FalloutFalcon approved these changes

2024-09-26 22:15 UTC, FalloutFalcon commented on code/modules/cargo/blackmarket/blackmarket_items/weapons.dm
> +	price_max = 2000
```suggestion
	price_max = 4500
```

2024-09-27 02:13 UTC, MassiveMen commented
I have no idea what that does I hit it on accident. I'm praying.

2024-09-27 22:48 UTC, FalloutFalcon submitted a review, later dismissed

2024-09-27 22:48 UTC, FalloutFalcon commented on code/modules/cargo/blackmarket/blackmarket_items/weapons.dm
> +	item = /obj/item/fireaxe
```suggestion
	item = /obj/item/melee/axe/fire
```

2024-09-29 13:58 UTC, merged