Cabinet Refactor
shiptest-ss13/Shiptest pull request #3378
Opened 2024-09-16 20:07 UTC by Bjarl

## About The Pull Request
Mildly refactors fireaxe cabinets to allow them to be subtyped with different items. Also adds an is_wielded proc to most weapons that can be wielded to prevent potential weirdness with this down the line.

## Why It's Good For The Game
Cabinets are soulful

## Changelog

:cl: Erika Fox
code: Fireaxe cabinets have been repathed, and now function as a more general cabinet object. please report any inconsistencies with behavior
/:cl:

2024-09-20 01:27 UTC, FalloutFalcon requested changes

2024-09-20 01:27 UTC, FalloutFalcon commented on code/game/objects/structures/cabinet.dm
> +	var/empty = FALSE
this var is useless

2024-09-20 01:27 UTC, FalloutFalcon commented on code/game/objects/structures/cabinet.dm
> +	var/our_object
```suggestion
	var/allowed_type
```

2024-09-20 01:27 UTC, FalloutFalcon commented on code/game/objects/structures/cabinet.dm
> +			stored = new stored(src)
```suggestion
	if(allowed_type && !spawn_empty)
		stored = new allowed_type(src)
```

2024-09-20 01:27 UTC, FalloutFalcon commented on code/game/objects/structures/cabinet.dm
> +			stored = new stored(src)
you'll need to make spawn_empty

2024-09-20 01:27 UTC, FalloutFalcon commented on code/game/objects/structures/cabinet.dm
> +	if(stored)
```suggestion
	if(istype(stored))
```

2024-09-20 12:52 UTC, FalloutFalcon requested changes
Good work so far!

2024-09-20 12:52 UTC, FalloutFalcon commented on code/game/objects/items/spear.dm
> +
This doesn't anything
```suggestion

```

2024-09-20 12:52 UTC, FalloutFalcon commented on code/game/objects/items/spear.dm
> +	if(HAS_TRAIT(REF(src), TRAIT_WIELDED))
dont know why this would need to be ref
```suggestion
	if(HAS_TRAIT(src, TRAIT_WIELDED))
```

2024-09-20 12:52 UTC, FalloutFalcon commented on code/modules/projectiles/gun.dm
> +
I forget how much guncode snowflakes its wielding but i would also refactor  this as well to use the trait. you can even just put a HAS_TRAIT in the return of that is_wielded if gun uses it alot for now

2024-09-20 13:57 UTC, Bjarl commented on code/game/objects/items/spear.dm
> +	if(HAS_TRAIT(REF(src), TRAIT_WIELDED))
misread a linter last night

2024-09-26 16:59 UTC, FalloutFalcon requested changes

2024-09-26 16:59 UTC, FalloutFalcon commented on code/datums/components/twohanded.dm
> +#define TRAIT_WIELDED "wielded"
This should be in the traits file.

2024-09-26 16:59 UTC, FalloutFalcon commented on code/datums/components/twohanded.dm
> +#define TRAIT_WIELDED "wielded"
though its horribly organized and could use some file separation...

2024-09-26 16:59 UTC, FalloutFalcon commented on code/game/objects/structures/cabinet.dm
> +		qdel(stored)
```suggestion
		qdel(stored)
		stored = null
```

2024-09-26 16:59 UTC, FalloutFalcon commented on code/game/objects/structures/cabinet_types.dm
> +	stored = /obj/item/melee/axe/fire
```suggestion
	allowed_type = /obj/item/melee/axe/fire
```

2024-09-26 16:59 UTC, FalloutFalcon commented on code/game/objects/structures/cabinet_types.dm
> +	stored = /obj/item/melee/axe/fire
This would be storing a path in a variable that's type is an object!

2024-09-30 16:06 UTC, FalloutFalcon approved these changes

2024-09-30 16:55 UTC, merged