Planetary Lighting Colors
shiptest-ss13/Shiptest pull request #3419
Opened 2024-09-23 22:31 UTC by Bjarl

## About The Pull Request
<details><summary>screencaps</summary>
<p>

![dreamseeker_4Gp6mnCDNE](https://github.com/user-attachments/assets/3eab1069-e47f-4a09-8c6d-20c26d4d16dd)
![dreamseeker_ESzoX9zGLQ](https://github.com/user-attachments/assets/0ded8c90-a417-40b7-aaeb-22f09b3d0aec)
![dreamseeker_0ew77loMC0](https://github.com/user-attachments/assets/c2da8723-ddd3-4239-bd5a-1086aa8bde75)
![dreamseeker_bZA16gvMeA](https://github.com/user-attachments/assets/6fc1ca33-fffc-4191-a6e5-f6278fb8e5fc)
![dreamseeker_V7WYCRWN4v](https://github.com/user-attachments/assets/7fdd1da3-ad20-437f-9ef8-917c5f6cf6db)
![dreamseeker_iTCBsMqMuL](https://github.com/user-attachments/assets/c07ff65c-65d7-49ad-ad56-212f85105123)
![dreamseeker_FGH6nwSdCk](https://github.com/user-attachments/assets/52fcdcfd-e0cf-4265-a8d5-d04e9e11e00e)

</p>
</details> 

Adds some planetary lighting defines and applies them to relevant planets. I had noticed I had an old pr that did this (among other things) so I ripped this out.
Values are entirely subject to change I don't remember where I got them from and I'm not a so called 'colour theorist'

As a coincidence planetary turf files are cleaned up a little by this.

## Why It's Good For The Game
A little bit of atmosphere fluff.

## Changelog

:cl:
add: Some planets now have new lighting values. Please report back on if they are "Pleasant"
/:cl:

2024-09-23 22:31 UTC, Bjarl commented
guh??

2024-10-05 04:20 UTC, FalloutFalcon approved these changes

2024-10-07 20:52 UTC, FalloutFalcon requested changes
looks very pretty but has some linters to sort out

2024-10-18 08:38 UTC, FalloutFalcon reviewed
otherwise looks good

2024-10-18 08:38 UTC, FalloutFalcon commented on code/game/objects/effects/glowshroom.dm
> +	/turf/open/lava,))
```suggestion
		/turf/open/lava
	))
```

2024-10-22 19:47 UTC, FalloutFalcon approved these changes

2024-10-26 13:35 UTC, Sun-Soaked submitted a review, later dismissed
code looks fine. I'd ask spriters about doing this, though.

2024-10-28 01:09 UTC, Erikafox commented
fuck it

2024-10-28 01:09 UTC, Erikafox commented
ill fix it later.

2024-10-28 18:46 UTC, Sun-Soaked approved these changes
we'll give it a try!

2024-10-29 21:03 UTC, merged