Gives simple humans armor
shiptest-ss13/Shiptest pull request #3489
Opened 2024-10-07 08:11 UTC by rye-rice

## About The Pull Request

Give simple humans armor by grabbing the behavior from asteroid mobs and giving them to simple mobs

## Why It's Good For The Game
@Apogee-dev and I have discussed this before, simple humans, even with armor are very weak to low calibers, its "balanced" out with more health, which isn't ideal. By doing this we encourage people to use higher calibers with simplemobs, otherwise they would be reserved for pvp

Seeing as the next gun expansion is exclusively 22 lr, and 22lr is disproportinately good against simplemobs vs actual players, this is better to do now
## Changelog

:cl:
add: Gives simple humans armor!
/:cl:

2024-10-07 19:34 UTC, thgvr commented
Should be fine, this is pretty much how I balanced fauna

2024-10-07 21:00 UTC, FalloutFalcon requested changes
i think it would make sense to define the values of amour vests and use them here to ensure they aren't as arbitrary..

2024-10-07 21:01 UTC, rye-rice commented
Out of scope, these values were taken from the armor values the sprites the simplemobs use

2024-10-07 21:32 UTC, FalloutFalcon commented
> Out of scope, these values were taken from the armor values the sprites the simplemobs use
Me and theubernyan both consider this in scope.

2024-10-07 21:37 UTC, FalloutFalcon requested changes
please define the amour values...
also clarify in the pr that you drop the max health to compensate
and also you could just remove the maxHealth and health from most of these assuming its 100 for the types above it but i wont force you to....

2024-10-07 21:37 UTC, FalloutFalcon commented on code/modules/mob/living/simple_animal/hostile/human/frontiersman.dm
> +	rapid_fire_delay = 1
Undocumented

2024-10-07 23:38 UTC, SomeguyManperson reviewed
All of these are inherited from the default hostile human type so they can be removed

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/nanotrasen.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/frontiersman.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/frontiersman.dm
> +	health = 100
```suggestion
```

2024-10-07 23:38 UTC, SomeguyManperson commented on code/modules/mob/living/simple_animal/hostile/human/frontiersman.dm
> +	health = 100
```suggestion
```

2024-10-18 07:36 UTC, rye-rice commented
@Apogee-dev , i delegate YOU

2024-10-18 07:36 UTC, closed without merging