Adds Sords For PGF
shiptest-ss13/Shiptest pull request #3571
Opened 2024-10-16 02:37 UTC by Bjarl

## About The Pull Request
As title

## Why It's Good For The Game
It's fluff stuff for the PGF.

## Changelog

:cl: Imaginos, Erika
add: The Pan Gezenan Federation has sent out shipments of boarding cutlasses to the Frontier. Expect cool doohickeys on your friendly neighborhood PGF Vessel
imageadd: Imaginos: PGF sord sprites
code: sabres now take up less space in code
/:cl:

2024-10-17 20:58 UTC, rye-rice approved these changes

2024-10-18 09:00 UTC, FalloutFalcon requested changes
I would honestly drop the block chance on these in favor for a minor damage buff.
I think it fits the vibe of a pgf cutlass better.

2024-10-18 09:02 UTC, FalloutFalcon commented
also god bless the brave coders of every single storage item for never learning how to make reusable code.

2024-10-21 23:30 UTC, FalloutFalcon approved these changes

2024-10-21 23:49 UTC, merged