Icemoon Ruin - Server Array
shiptest-ss13/Shiptest pull request #3595
Opened 2024-10-19 01:03 UTC by NoeSilent

## About The Pull Request

Adds a **Server Array** ruin to Ice moons.

The ruin offers an engineering challenge to be fully explored, but in case a team is lacking the tools, they can scrounge around for everything they need to get past the obstacles.

The available loot is wide in variety, allowing any job to hopefully gain something from the time spent to explore it.

There are plenty of spiders, but their venom is replaced with **Mindbreaker Toxin**, not posing a threat to the body but instead the victims mind. Spiders already have many ice variants, so these new ones are the ice variant of the viper spider.

## Why It's Good For The Game

There need to be more ice ruins! The variety is lacking, and if I had to invest in a structure on an ice moon it would definitely be a bunch of machinery being cooled down by the chilly air.

## Changelog

:cl:
add: server array ice ruin
add: ice vipers
/:cl:

2024-10-19 01:20 UTC, Imaginos16 commented
Please include a picture of your ruin into the PR please.

2024-10-19 01:25 UTC, NoeSilent commented
> Please include a picture of your ruin into the PR body, please.

your wish is my command

2024-10-19 01:51 UTC, NoeSilent commented
just remembered that robco toolmaker is just a mountain of entirely free things, so I've replaced it with a broken circuit imprinter

2024-10-23 23:08 UTC, Gristlebee requested changes
Hey there, for screenshots you're expected to provide an image of it in strongdmm, one with the areas, and without, along with a picture of the ruin spawned ingame. Add those please when you get the chance.

- These egg spawners release a large amount of random spiders. Was that intended when you mapped it in? That's fine if intended, but I'd recommend adding some extra loot in that area due to the extra challenge as there's currently not much reason to go in there.
![image](https://github.com/user-attachments/assets/e99b33a8-cda4-462f-a8d6-37a7ac11ab5c)

- Please remove the suicide implication. Have them be killed by something else.
![image](https://github.com/user-attachments/assets/118eab9a-015e-462c-b27c-8973bca1b732)
![image](https://github.com/user-attachments/assets/ddf37129-4d3f-4100-9c54-2a4e79913e7e)
- Use full tile windows and grilles instead of spawners here please.
![image](https://github.com/user-attachments/assets/c44a1ff1-4b01-4ba3-b3e7-4ecc869cf1f2)
- This room could use some lighting or at least a broken light.
![image](https://github.com/user-attachments/assets/4a68b5c9-e771-4b78-b870-ed587aab9889)
- A powered SMES would be good, in the event players take too long to find the ruin and the turret runs out of power.
![image](https://github.com/user-attachments/assets/1b01dff7-1809-4624-9075-33d258f2a3b2)
- Turfs that are exposed to planetary atmos on the ruin spawn should be made a subtype with the planet's atmos set. Otherwise the pressure differences can slow down loading or cause unintended effects during spawning like tearing up tiles or decals.. Go to ```code\game\turfs\open\icemoon``` and follow the format there to make any necessary tile subtypes you need.
![image](https://github.com/user-attachments/assets/8fdcb970-d904-402e-ae84-854a4f3ba42c)

- Pipes shouldn't be mapped under walls. They can go under windows, doors or false walls.  Also a similar issue as above with having passive vents exposing it to planetary atmos. I'd suggest running the pipes through maint and using heat exchange pipes.
![image](https://github.com/user-attachments/assets/bb7bd08d-a17e-4635-83a0-f1ac5cd81b17)
- A basic atmos system would be a good addition for the ruin. Ventilation would help explain how the spiders got around the server farm.
- This is good, making the ruin seem like it was actually lived in with living quarters and amenities. I'd recommend adding a some eating space somewhere like tables or an extra room.
![image](https://github.com/user-attachments/assets/0bdbf0bb-fd96-4164-bdf9-2ac7b1749bef)
- This seems to be a Nanotrasen ruin from the signage, but it doesn't particularly feel like one style wise. 
![image](https://github.com/user-attachments/assets/cdbc42f6-5db4-40ab-82d1-018950a1eb0a)
A 44 Shadow is a Hunters Pride weapon, when it'd be more typical for NT hired Vigilitas security to use weapons like Commanders or energy.
- The dorms, the main hallway, and the engineering workshop look plain and could use more decaling. I'd suggest looking at other NT ships like the Harrier or Ranger to get inspiration for the NT decal palate.
![image](https://github.com/user-attachments/assets/e855ce35-f0ae-4231-8622-0cc09721c34c)
![image](https://github.com/user-attachments/assets/eda66041-6fc4-4fe9-8045-924b3a9b3cb5)

2024-12-03 13:21 UTC, thgvr commented
@NoeSilent Please address reviews

2025-01-10 06:33 UTC, Gristlebee commented
Thanks for PRing this map. I'll be closing this for now. When you're able to work on this and address the reviews, feel to reopen the PR.

2025-01-10 06:33 UTC, closed without merging