Serene Sporting
shiptest-ss13/Shiptest pull request #3604
Opened 2024-10-20 20:47 UTC by Erikafox

## About The Pull Request
Adds new guns
M17 pistol - .22lr - 10rd mag
M12 rifle - .22lr - 25rd mag
m13 rifle - .22lr - 25rd mag - 3rd burst
m15 rifle - 5.56 clip - 20rd mag
m11 shotgun - 12g - 8rd tube

[Watch the video here](https://youtu.be/O1TrkZ_FHFU?si=-dAk-dlTSsug8X0R)

## Why It's Good For The Game
project content into the world

## Changelog

:cl: Apogeesys, Ryerice, Erikafox 
add: Serene Outdoors has begun a new production run of its classics - the Model 17, Model 12, Model 15, and Model 11
del: old combat shotgun
/:cl:

2024-10-20 20:57 UTC, rye-rice approved these changes

2024-10-21 00:09 UTC, Apogee-dev commented
Would you mind putting an image of the sprites in the PR body? just a screenshot of the project file if need be, it's just that the resolution on the video isn't perfect and factors like lighting can make things hard to see.

2024-10-21 00:18 UTC, Erikafox commented
done

2024-10-21 00:27 UTC, Apogee-dev requested changes
Mostly just some proofreading, there were a couple grammar errors on the descs and a note on the super sporter crate that's entirely optional.

2024-10-21 00:27 UTC, Apogee-dev commented on code/modules/cargo/packs/gun.dm
> +	desc = "An cheap target shooting pistol manufactured by Serene Interstellar. Chambered in .22lr"
"A cheap target (...)"
small grammar error

2024-10-21 00:27 UTC, Apogee-dev commented on code/modules/cargo/packs/gun.dm
> +	desc = "Contains a recently manufactured Model 12 \"Sporter\", Serene Outdoor's premier small game rifle."
small grammar error: should be Serene Outdoors' rather than Serene Outdoor's

2024-10-21 00:27 UTC, Apogee-dev commented on code/modules/cargo/packs/gun.dm
> +	desc = "Contains a recently manufactured Model 15 \"Super Sporter\", Serene Outdoor's premier big game rifle."
Same as with the Sporter. Calling a 5.56 a big game rifle might also be a little confusing, even if deer are technically big game- maybe just calling it a hunting rifle would work better. You probably shouldn't try hunting bear or moose with this thing!

2024-10-21 00:27 UTC, Apogee-dev commented on code/modules/projectiles/guns/manufacturer/serene_sporting/ballistics.dm
> +	desc = "A 25-round, magazine for the Model 12 \"Sporter\". These rounds do okay damage with awful performance against armor."
"A 25-round magazine (...)
small grammar error, misplaced comma

2024-10-21 00:27 UTC, Apogee-dev commented on code/modules/projectiles/guns/manufacturer/serene_sporting/ballistics.dm
> +	desc = "A 10-round, magazine for the Model 17 \"Micro Target\". These rounds do okay damage with awful performance against armor."
"A 10-round magazine (...)
Small grammar error, misplaced comma

2024-10-21 00:27 UTC, Apogee-dev commented on code/modules/projectiles/guns/manufacturer/serene_sporting/ballistics.dm
> +	desc = "A 20-round, magazine for the Model 15 \"Super Sporter\". These rounds do average damage and perform moderately against armor."
Same as the other magazines, misplaced comma.

2024-10-21 01:43 UTC, MemeSnorfer commented
One major ~~complaint~~ thing I wanted to point out; The sporter and super sporter hunting rifles would apply penalties to characters with the gunslinger quirk, since these rifles are _technically_ automatic weapons with a burst size of 1.

2024-10-21 01:52 UTC, Apogee-dev commented
> One major ~complaint~ thing I wanted to point out; The sporter and super sporter hunting rifles would apply penalties to characters with the gunslinger quirk, since these rifles are _technically_ automatic weapons with a burst size of 1.

Isn't this already the case with other semi-automatic weapons? I thought gunslinger also applied penalties to other self-loaders like the Candor too.

2024-10-21 02:01 UTC, MemeSnorfer commented
> > One major ~complaint~ thing I wanted to point out; The sporter and super sporter hunting rifles would apply penalties to characters with the gunslinger quirk, since these rifles are _technically_ automatic weapons with a burst size of 1.
> 
> Isn't this already the case with other semi-automatic weapons? I thought gunslinger also applied penalties to other self-loaders like the Candor too. EDIT: It doesn't, I misread. Gunslinger penalties are applied to assault rifles, LMGs, and SMGs as classes. Technically it doesn't even apply to machine pistols. This ALSO means it doesn't actually apply to the Sporter or Super Sporter either, because they're just under the base ballistic/automatic type instead of the smg or assault subtypes.

Huh. I misremembered gunslinger's subtype penalties, then (I thought it was *every* weapon typed under automatic.

The machine pistols being unaffected seems like a bit of an oversight though :P

2024-10-21 02:35 UTC, Erikafox commented
> > One major ~complaint~ thing I wanted to point out; The sporter and super sporter hunting rifles would apply penalties to characters with the gunslinger quirk, since these rifles are _technically_ automatic weapons with a burst size of 1.
> 
> Isn't this already the case with other semi-automatic weapons? I thought gunslinger also applied penalties to other self-loaders like the Candor too. EDIT: It doesn't, I misread. Gunslinger penalties are applied to assault rifles, LMGs, and SMGs as classes. Technically it doesn't even apply to machine pistols. This ALSO means it doesn't actually apply to the Sporter or Super Sporter either, because they're just under the base ballistic/automatic type instead of the smg or assault subtypes. So yeah, none of these guns get gunslinger penalties or bonuses (except for the Buckmaster, which gets -1 gunslinger recoil like all shotguns). You might want to slap a gunslinger penalty on the Larker, but otherwise it can be ignored.

tbh I'm of the opinion that we should remove gunslinger. It's too far into the side of gameplay altering quirk

2024-10-21 03:17 UTC, FalloutFalcon commented
> > > One major ~complaint~ thing I wanted to point out; The sporter and super sporter hunting rifles would apply penalties to characters with the gunslinger quirk, since these rifles are _technically_ automatic weapons with a burst size of 1.
> > 
> > 
> > Isn't this already the case with other semi-automatic weapons? I thought gunslinger also applied penalties to other self-loaders like the Candor too. EDIT: It doesn't, I misread. Gunslinger penalties are applied to assault rifles, LMGs, and SMGs as classes. Technically it doesn't even apply to machine pistols. This ALSO means it doesn't actually apply to the Sporter or Super Sporter either, because they're just under the base ballistic/automatic type instead of the smg or assault subtypes. So yeah, none of these guns get gunslinger penalties or bonuses (except for the Buckmaster, which gets -1 gunslinger recoil like all shotguns). You might want to slap a gunslinger penalty on the Larker, but otherwise it can be ignored.
> 
> tbh I'm of the opinion that we should remove gunslinger. It's too far into the side of gameplay altering quirk

I think it could probably stay but it should be a positive quirk that adds the few cool tricks like fanning and minor visuals like spin-cocking. Remove all the number tweaking cause its only really for powergaming

2024-10-21 11:52 UTC, Apogee-dev requested changes
Oops, one last desc error. Sorry I missed that one.

2024-10-21 11:52 UTC, Apogee-dev commented on code/modules/cargo/packs/gun.dm
> +	desc = "A cheap target shooting pistol manufactured by Serene Interstellar. Chambered in .22lr"
manufactured by Serene Outdoors

2024-10-23 00:08 UTC, Apogee-dev approved these changes

2024-10-23 23:28 UTC, generalthrax commented
Should probably show what cartridge the weapon takes in the cargo menu. Sporter and Super Sporter do not rn

2024-10-23 23:35 UTC, Erikafox commented
mags are gonna be in a future pr. I'm going to organize- oh come on what'd i push

2024-10-23 23:35 UTC, Erikafox commented
nothing it just edits ships okay anyways - They're going to be in my next code PR - im gonna make a new category for magazines and check that you can purchase like - all of them

2024-10-23 23:44 UTC, thearbiber commented
Super sporters medium sized. Not sure thats intended since its a rifle

2024-10-23 23:46 UTC, generalthrax commented
The M17 is bulky, too

2024-10-23 23:47 UTC, Erikafox commented
m17 should be fixed in latest. im fine with the m12/m15 being medium atm

2024-10-23 23:50 UTC, generalthrax commented
I unno. I just noticed the M12 being bulky while the M15 was normal. Seemed mixed up

2024-10-23 23:51 UTC, Erikafox commented
Ah. actual weights instead of 'weapon' weights

2024-10-23 23:51 UTC, thgvr commented
All these but the pistol should be unable to fit in a bag, probably.

2024-10-23 23:52 UTC, Erikafox commented
weapon weight and actual item weight are two different systems.
Weapon weight is "can you fire while double-wielding/without wielding"
item weight is you know what it is.

either way fixed

2024-10-26 04:21 UTC, Sun-Soaked approved these changes
looks good

2024-10-26 04:21 UTC, Sun-Soaked commented on code/modules/projectiles/guns/manufacturer/serene_sporting/ballistics.dm
> +		name = "Model 11 \"Cuckmaster\""
![image](https://github.com/user-attachments/assets/75f1ef1c-de64-4fa0-b1ff-4897bbdb9937)

2024-10-26 04:21 UTC, Sun-Soaked commented on code/modules/projectiles/guns/manufacturer/serene_sporting/ballistics.dm
> +		name = "Model 11 \"Cuckmaster\""
remove this, please.

2024-10-26 06:06 UTC, merged