New Ship: Woeful Cthonian-class Patrol Cutter
shiptest-ss13/Shiptest pull request #3624
Opened 2024-10-23 02:01 UTC by Erikafox

## About The Pull Request
<details><summary>Screenshots</summary>
<p>

![StrongDMM-2024-10-22 21 48 24](https://github.com/user-attachments/assets/4af2be10-6802-4f3a-a91b-bd8f882dbc8e)
![StrongDMM-2024-10-22 21 48 26](https://github.com/user-attachments/assets/7b7c40cd-82af-431e-9ace-9c7dddda2947)
![image](https://github.com/user-attachments/assets/39dc3e77-a58f-4f42-8bd6-1b28d8377a9d)

</p>
</details> 

Adds a new ship to the PGF Roster - the Woeful Cthonian. The Cthonian is a small ship designed for generalist usage, with a particularly functional medbay and high levels of style. The crew of a Cthonian is:

- 1 Captain
- 1 Engineer
- 1 Doctor
- 3 Crewmen

You will likely notice that they are all navy - this is to give this ship a slightly higher focus by taking away the internal dynamic marines and navy are supposed to have. It also made it way easier to map.

## Why It's Good For The Game
Expands the PGF roster with a small generalist to play in rounds that don't have the pop nor need for a 10+ person ship

## Changelog

:cl:
add: A new PGF ship is in the neighborhood - Woeful Cthonians have been deployed in the frontier!
/:cl:

2024-10-23 19:15 UTC, Sadhorizon commented
Heyo. I promise it'lll be better this time!

- ![obraz](https://github.com/user-attachments/assets/c70a47f6-a176-489c-9181-0a4d2b52055f)
Shouldn't those be stacked the other way around? Looks kinda weird.
- I think you forgot the defib
- Is the empty "janitorial closet" in med... meant to be empty?
- ![obraz](https://github.com/user-attachments/assets/5b9ec4f3-653f-42ec-8a45-72610cf5d6c2)
The stalker.
- ![obraz](https://github.com/user-attachments/assets/a3cec239-304d-4862-ab13-c102ffab1c81)
Ho boy. Why are there tools in here and not in engi? Seems like a strange choice tbh; Does a non-marine ship really need three boxes of flares?; I don't think hunting knives really fit PGF?
- Noting that the beam pistols don't have any spare cells. Might be intended, idk.
- Angle grinder doesn't come with hearing protection. Would probably be nice.
- ![obraz](https://github.com/user-attachments/assets/910a5174-bea4-483f-88ad-cf68e38b5193)
You forgot to wire the engines.
- ![obraz](https://github.com/user-attachments/assets/4adaf7ba-4579-49cc-855e-0d5de08527fd)
I don't think you should be able to open this from both sides at once. Feels weird.
- ![obraz](https://github.com/user-attachments/assets/8c962e53-8118-4c2c-939e-a1b2884577a9)
This feels kinda random ngl. You do you though.
- ![obraz](https://github.com/user-attachments/assets/7f4c3cb7-4277-4064-8f77-e97984aaf5b8)
Other PGF ships don't use cabinets. I don't see why this one should?
- Captain's pistol should be in a guncase. It's the standard rn iirc.
- There is a significant lack of wall flags, compared to the Crying Sun.
- ![obraz](https://github.com/user-attachments/assets/bd6c131f-a6c5-430b-aba3-629f300fd395)
I think you should put something inside. Maybe move the recorders from Lockers to here? I find empty cabinets sad :(
- There is two outpost comm consoles.

2024-10-23 21:10 UTC, Gristlebee requested changes
- The ship appears to be missing a gravity generator
- Not entirely sure about the mortar here flavour-wise in terms of the PGF as a faction. I'd suggest swapping it out for another blender or put something else there.
![image](https://github.com/user-attachments/assets/724a87bc-34a6-4465-8f43-98ad8cbd8c01)
- Stimulants in the SSU here seems odd to me. I'd rather you have it somewhere in the medbay.
![image](https://github.com/user-attachments/assets/c824443b-9348-438c-8a5c-58f0b5fddc1e)

- Some extra power cells for the beam pistols would be good in the armory, and I noticed there's no weapons rechargers aboard for the guns. You could either add one, or swap out one of the cell charger boards in engineering for a weapon charger board.
- There are no fire lockers/extinguishers on the ship. I'd suggest adding a couple.
- In a similar vein, there's no oxygen emergency closets, or internal tanks in general on the ship, which may make things tricky for anyone intending to EVA.

2024-11-04 02:19 UTC, Gristlebee requested changes
Ship looked good on live during testing, and no major issues came up as far as I'm aware.

Cut one of the cell charger boards from the crate in engineering here, I don't think the ship needs three cell chargers.
![image](https://github.com/user-attachments/assets/3c263ce1-a55e-491a-9f0a-ed2c796f5d45)

I'll get this merged once that's done.

2024-11-04 05:52 UTC, Gristlebee approved these changes

2024-11-04 08:01 UTC, merged