Ammo Antics
shiptest-ss13/Shiptest pull request #3694
Opened 2024-11-02 03:46 UTC by Erikafox

## About The Pull Request

Subtypes AP/HP/Rubber ammo for several calibres that didn't have it. adds it to the market in relevant cases.
adds tracker rounds to a few places. makes them work differently.
removes incendiary ammo from everything except shotguns

- [ ] I tested my pr

## Why It's Good For The Game

makes the ammo gameplay stuff available to more weapons. entertainment value

## Changelog

:cl:
add: rifle calibre and pdw calibre rubbershot/armor piercing/hollow point. check da outpost
add: tracker rounds for a few guns. check the black market :3
del: most forms of incendiary ammo

/:cl:

2024-11-03 19:37 UTC, Apogee-dev commented
I wonder how viable it would be to make the speed values you defined here modifiers on the cartridge’s base speed value rather than fixed values? I was looking over the code and noticed a few weird things here and there like match revolver bullets being faster than standard DMR bullets. it’d be nice if we could make certain guns in general have slightly faster or slower bullets than others.

2024-11-03 19:38 UTC, Erikafox commented
> I wonder how viable it would be to make the speed values you defined here modifiers on the cartridge’s base speed value rather than fixed values? I was looking over the code and noticed a few weird things here and there like match revolver bullets being faster than standard DMR bullets. it’d be nice if we could make certain guns in general have slightly faster or slower bullets than others.

we'd have to tie it to a modifier like how bullet skins work. not opposed to doing it like such, though.

2024-11-08 21:33 UTC, generalthrax commented
A few select bullet types like .22lr hollow / rubber and .300 are half and half normal. Probably a quick fix but something you might wanna look at before We Become Real

2024-11-14 02:50 UTC, generalthrax commented
6.5x57mm only has half the ammo and its the wrong ammo type for both normal and trackers.

2024-11-14 02:57 UTC, Erikafox commented on code/modules/projectiles/boxes_magazines/ammo_stacks/prefab_stacks/premade_sniper_stacks.dm
> +/obj/item/storage/box/ammo/a65clip/PopulateContents()
```suggestion
/obj/item/storage/box/ammo/a65clip/trac/PopulateContents()
```

2024-11-14 14:25 UTC, Sun-Soaked requested changes
document cruft removals in changelog

2024-11-15 17:21 UTC, generalthrax commented on code/modules/projectiles/boxes_magazines/ammo_stacks/prefab_stacks/premade_smg_stacks.dm
> +/obj/item/storage/box/ammo/c46x30mm/ap/PopulateContents()
This should be hp instead of ap

2024-11-20 17:56 UTC, Sun-Soaked approved these changes
looks good

2024-11-20 17:56 UTC, Erikafox commented
yaaaaay

2024-11-21 00:26 UTC, merged