Chironhermes2
shiptest-ss13/Shiptest pull request #3710
Opened 2024-11-06 06:11 UTC by miniusAreas

## About The Pull Request

Adds the Chiron Search and Rescue ship to the roster of CLIP ships, equipped with the Hermes ambulance subshuttle, and supplies for disaster relief and biological containment and control.

this is baby's first pullrequest in like, forever. I've stumbled through learning tortoisegit and unfortunately, the TG wiki page I was learning from is down at the moment, as TG's servers are currently dead. Please fuckin slap me if a maintainer (or anyone) sees anything off or if I fucked something. Thanks.

![image](https://github.com/user-attachments/assets/9abd1286-1cc9-4c99-8cec-b452c5c2d81c)

![image](https://github.com/user-attachments/assets/f6103444-5326-47b1-9b83-b6da6b1606f7)

# Roles
1x Captain
2x Corpsmen
2x Minutemen
1x Engineer
1x Reservist

## Why It's Good For The Game

adds another ship to test. Jokes aside, CLIP only has one ship (Atlas) and having more (from other branches of clip) is a good thing.

## Changelog

:cl:
add: Added Chiron, a BARD S&R ship!
add: Added Hermes, a CMM Ambulance shuttle that can MOVE.
/:cl:

2024-11-06 06:54 UTC, thearbiber commented
you put a holofield under the spoon outside the window
![Screenshot 2024-11-06 015417](https://github.com/user-attachments/assets/1f247710-207e-43bb-b65c-db60adac53c9)

2024-11-06 07:29 UTC, miniusAreas commented
what in the goddamn

> you put a holofield under the spoon outside the window ![Screenshot 2024-11-06 015417](https://private-user-images.githubusercontent.com/135081923/383439234-1f247710-207e-43bb-b65c-db60adac53c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzYzOTUsIm5iZiI6MTczMDg3NjA5NSwicGF0aCI6Ii8xMzUwODE5MjMvMzgzNDM5MjM0LTFmMjQ3NzEwLTIwN2UtNDNiYi1iNjVjLWRiNjBhZGFjNTNjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwNjU0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGJkYzQwNTAxZTM1ODc1NDAxMGE5MTc1Njk4MWZiNDg5MDhjNjhmZTg5NDdmZDFhZTI0MTZjYzA1MTdiNzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2u_9DciG2yl-hXw6PrOUUBhg32H4tBflZSAzABAG1vg)

2024-11-06 13:40 UTC, Apogee-dev commented
In retrospect the armory should probably not have windows

2024-11-06 15:39 UTC, meemofcourse requested changes
sorry if the massive pile of issue sorting is discouraging but uhm

![imagen](https://github.com/user-attachments/assets/17bbfb20-db9f-4029-8c99-90e1b678f6bb)
random subship dock present

![imagen](https://github.com/user-attachments/assets/96a7a7dd-90a4-4404-83fe-d70c8bc7c2f1)
please put these in a guncase. remove the shoulder holster

![imagen](https://github.com/user-attachments/assets/e47f2c12-3ddc-4aa2-a44b-e6ff8183e9f8)
these are a lot of wallmounts. i recommend you place the wideband onto a table

![imagen](https://github.com/user-attachments/assets/da1a1165-e1ef-408e-afa3-f486d02e8827)
duped cables in the hermes

![imagen](https://github.com/user-attachments/assets/b160a426-fe23-40f5-8bfa-6be592113190)
please adhere to the heavy firelock designs seen in the atlas

![imagen](https://github.com/user-attachments/assets/c6a9d9c4-ea7e-41f9-b177-3d2f8bc852a9)
the weapons in the armory should not start loaded

![imagen](https://github.com/user-attachments/assets/72d86f27-0d97-4d33-8c07-57ba5385fa80)
and why do we have windows in the Gun Storage Room anyway

![imagen](https://github.com/user-attachments/assets/2c670c27-6d99-4073-b133-add9c56554eb)
Defibulator Closet

![imagen](https://github.com/user-attachments/assets/42cf62bb-64f4-4917-9699-f2c93c94bd0f)
![imagen](https://github.com/user-attachments/assets/c5c6790d-a8c7-4dad-a57b-c7f015410b72)
![imagen](https://github.com/user-attachments/assets/fd3ad212-d54b-44bb-90cb-6e1e502e6f98)
corpsman uniform and gear should go into a specialized corpsman closet

![imagen](https://github.com/user-attachments/assets/c44cd3da-9ebc-4eed-82e0-159f859866bd)
the engineer shouldn't be meddling with medbay matters

![imagen](https://github.com/user-attachments/assets/dad0401e-5ed8-4538-8e80-c7dd581eecd9)
...and viceversa

![imagen](https://github.com/user-attachments/assets/b7311a85-3752-4d7a-9626-bfafa86169d2)
bad lighting

![imagen](https://github.com/user-attachments/assets/df733375-ec4e-4a57-9242-49b90e0c9ee4)
i dont know how i feel about the ATV

![imagen](https://github.com/user-attachments/assets/1588d7fe-1cde-4afb-a4af-9a305e765819)
there should probably be more than one type of suit present. the fire safety closet should be more of a dedicated firefighting closet than just an emergency one

___

![imagen](https://github.com/user-attachments/assets/74d4febc-a234-4ce0-88e8-efe3edd70649)
i'm gonna be honest with you, this subshuttle sucks ass. the haste is smaller but it fills in everything it needs - this one has a Single Stasis Bed among a lot of handrails. figure out a different layout (make it larger if you need to. remember this is meant to ferry a lot of probably injured people and at least a pair of corpsmen to tend to them) and change the decaling to match the rest of the ship please

* the ship feels like it leans too much into the medical aspect of S&R. i understand it is by intent a medical vessel but the reason why i purposefully announced to you the shift to disaster relief is for you to scale back the medical facilities and give way to a balance between engineering and medical collaboration - think something like firefighters with firefighter medics and engineers
* the ship feels understaffed. compared to something like the Valor, which is around the same size, it has better gear, but has 3 less crewmen (one Corpsman and the subshuttle crew)
* the ship needs a 2IC. the armory locked off to Minutemen works if there is someone regulating access to it and currently the only person capable of accessing it is the Captain, who is probably going to be busy handing ship to ship communication and getting the vessel places
* i feel like it would be best to split the medical roles with a Doctor and a Corpsman. one in the subshuttle, another stays on the ship

2024-11-06 15:39 UTC, meemofcourse commented on _maps/configs/minutemen_chiron.json
> +	"description": "The Chiron-class is a new-ish ship purpose-built for BARD. Built from hulls designed and made, but never used, during the Frontiersmen War, and equipped with a small but powerful amb
```suggestion
	"description": "The Chiron-class is a relatively new, purpose-built vessel for use by CMM-BARD. The Chiron's construction comes from hulls designed and made during the Frontiersmen War, repurposed and modernized as a disaster relief ship in response to Ryunosuke's Xenofauna Infestation. As a platform meant to adequately handle a multitude of disasters, it is equipped with numerous medical equipment, a nimble rescue subshuttle, and an armory for self-defense, but falls short of specialization at any of these aspects.",
```
i'm not sure about the "new-ish" part, considering that a frontiersmen war design would be some ~110 years old and a xenofauna war vessel would be around ~75 years old

2024-11-06 15:39 UTC, meemofcourse commented on _maps/configs/minutemen_chiron.json
> +	"namelists": ["GENERAL", "CLIP MINUTEMEN", "NATURAL_AGGRESSIVE"],
up to you but i don't think that natural aggressive really fits a S&R ship

2024-11-06 15:39 UTC, meemofcourse commented on _maps/configs/minutemen_chiron.json
> +	"limit": 1,
```suggestion
```
both of these are redundant because they're the default

2024-11-06 15:39 UTC, meemofcourse commented on _maps/configs/minutemen_chiron.json
> +	"starting_funds": 2000,
```suggestion
```

2024-11-08 04:58 UTC, miniusAreas commented
Closed after discussion with maptainers.

2024-11-08 04:58 UTC, closed without merging