Revenant-Class Placeholder (NAME AND DESC PENDING)
shiptest-ss13/Shiptest pull request #3741
Opened 2024-11-12 04:22 UTC by thearbiber

## About The Pull Request

early WIP hardliner scrapping ship.

![image](https://github.com/user-attachments/assets/015861fb-8831-4835-ab16-915152f4fb3a)
![image](https://github.com/user-attachments/assets/8d5431a9-9fdd-4934-9fc6-70045d082a87)

## Why It's Good For The Game

Dear lord they need something

## Changelog

:cl:
add: Added new things

/:cl:

2024-11-12 04:47 UTC, Apogee-dev commented
I'll just say what I commented on the dev thread for posterity, but I do feel like the design language here isn't _quite_ what I'd like to see for cybersun-built ships. other than that, i've got a strong preference for the numbers-and-letters ship class names i mentioned elsewhere on the discord (stuff like "400j class" or "G52 class") though the ghost names kinda work. i feel like the numbers stand out better from other factions.

2024-11-12 06:07 UTC, miniusAreas commented
whatever. go my scarab.

2024-11-16 00:17 UTC, Madtankdriver commented
H! Just a small suggestion. Looking at the Revenant-Class it doesn't really have much of a good reason to play on this shuttle since the Banshee-class class shuttle and the Phantom-Class would be better picks. So maybe adding engineering Protolathe or adding more engineering equipment might not be a bad idea. I could definitely see the Revenant-Class being tasked from Cybersun to construct a Blacksite on an ice planet, so in order to do so they would need to work with the Phantom class shuttle for armed support and for refining ore. Alongside the two they would be perfect to construct structures and work together. Take this with a grain of salt, this is what I thought of that might be a good idea to add onto this shuttle to be a tad more useful and good to work with an allied shuttle. Overall, the shuttles look great! Keep up the good work!

2024-11-16 00:24 UTC, thearbiber commented
> So maybe adding an engineering Protolathe or adding more engineering equipment might not be a bad idea.

I would sooner be dead than contribute a ship with RnD on it in 2024

2024-11-16 10:20 UTC, Sadhorizon commented on _maps/configs/syndicate_gorlex_revenant.json
> +	"map_path": "_maps/shuttles/syndicate/syndicate_gorlex_revenant.dmm",
Hey, rename it to `syndicate_hardliner_revenant.dmm`. The "gorlex" part is outdated, and is being slowly removed on the NGR side of things.

2024-11-19 05:06 UTC, thearbiber commented
updated images, changed ship shape very slightly.

2024-11-27 00:34 UTC, thearbiber commented
Should be ready for review I Think.

2024-11-28 19:57 UTC, Gristlebee requested changes
- You can set the reinforced tiles under the blast doors in the cargo bay to interior since it starts sealed. Space wind happens otherwise the first time you open it.
![image](https://github.com/user-attachments/assets/77fa4f82-4d72-4dad-9c3f-b6bdf2645e54)
- Giving the wrecker's gear lockers a unique name or changing the appearance to miners locker would look good instead of "closet".  Access restricting the closets would be good as well since the supply bay isn't access locked. 
![image](https://github.com/user-attachments/assets/c922d254-5623-4450-b5f6-b9b57a5696bd)
- The wreckers could also use welding protection of some kind for the angle grinder/cutter. Mining tools of some kind would also be useful.
- Use obj/melee/knife/kitchen instead of the base type. The name gets a bit wonky otherwise.
![image](https://github.com/user-attachments/assets/5fe2c550-5618-4a2c-a52d-b2f53ad992cd)
![image](https://github.com/user-attachments/assets/bc3cbe05-1b04-488b-9e4d-897b55fb4233)
- Some privacy shutters for the armory desk would be good due to it's proximity to the cargo bay.
![image](https://github.com/user-attachments/assets/3bdfb3a5-fa68-490a-900d-ff107ae0d04f)
- You'll want to set the access on the armory windoors to 3 (armory) so only the sergeant is able to access it. 
![image](https://github.com/user-attachments/assets/97d21cd2-e183-4e58-9ce0-3fde1ab1c07a)
![image](https://github.com/user-attachments/assets/ae406740-c350-46c6-9768-e4c27144940e)
- The ship probably doesnt need two sets of welding fuel and water tanks. Consider swapping one of them out for something else.
![image](https://github.com/user-attachments/assets/ba2bdbd7-0bc0-4f53-bf86-5a0d7fc717bb)
![image](https://github.com/user-attachments/assets/39a3fb2d-6917-45b9-933e-b99cab1d9a2f)
- The ship looks very sterile. You could map in some dust and dirt around the ship, some rust on the floors in the engine bay to make it look more lived in.
- The dorms feels a bit sparse. Some decals and linings to separate the lockers/dresser area off from the walkway could look nice.
![image](https://github.com/user-attachments/assets/094b3ed9-6a48-481b-b1bb-c01fe62e57ae)
- You'll want to set the access to 19 (heads) on the bridge unless you want the trooper walking in on the bridge.
![image](https://github.com/user-attachments/assets/bd13432c-4e5c-44fd-adff-0b95ec437730)
- I think some warning lines between the catwalks and the floors around the engines would make them pop and stand out more as a division.
![image](https://github.com/user-attachments/assets/6147002a-d8ef-415a-beed-69f3cb332517)
![image](https://github.com/user-attachments/assets/242334b6-67f8-41e6-b69d-96e4ed659273)
![image](https://github.com/user-attachments/assets/6f4b479f-5f6e-4d0a-9e29-45d0430a3b2b)

2024-11-28 22:09 UTC, thearbiber commented
Requested changes made.

2024-11-29 00:40 UTC, Gristlebee commented
Looks alright to me.

2024-12-06 18:31 UTC, Latentish requested changes
The ship so far is looking pretty good, however the  large issue I see with it is the lack of clutter and abundance of open, unused space.
Take this room for example.
![image](https://github.com/user-attachments/assets/2b113be1-a7e9-43a6-b8f0-adcb38ee6364)
It has good space allocation, markings, and general vibe, however the room is very very empty. Remember that players can decon simple structures that you add in for clutter, which is what your ship needs.

You tend to skirt your object placements around the edges of the room, rather than having many things that protrude into the central spaces, which causes you to end up with spaces like this
![image](https://github.com/user-attachments/assets/743390ad-aa0b-4032-af6b-16964d4904af)
This room is a good shape, size, has the bathroom there, it has all the elements it needs, however it has this large hole of space in the middle of the room. You could make the couch bigger, add a table, add vendors. But you need to use up more space.

Your Cryo room has a similar, but smaller issue.
![image](https://github.com/user-attachments/assets/50f1e248-872c-4b08-94cb-b915d62ecb1c)
You have this table here that has nothing on it, with an almost entirely empty 3x3.

I'm actually a bit sad to make a fuss about this part, because I think it looks really nice, however the port on a ship that allows a subshuttle to dock to it, needs to be able to be air sealed once the ship docks. This will not do that.
![image](https://github.com/user-attachments/assets/c0bdf77a-5e4d-43b8-9e14-dfe60072253f)

This room, while I really enjoy the layout, feels like a showroom showing how you could arrange furniture, rather than an actually used space. Add things to the tables, add some clutter to the room, and do something with the 4x3 space to the left of the kitchen.
![image](https://github.com/user-attachments/assets/dbf825f8-0e95-4384-a6d8-663ae26022d7)

This is probably the biggest offender on the ship in terms of being too empty. You have a lot of unused space.
![image](https://github.com/user-attachments/assets/12838fa7-85bb-4646-826b-ed77787ccbf2)

These engine rooms are a great start, but again, just need more stuff in them. The top nacelle is better than the bottom in that regard, but still needs more clutter.
![image](https://github.com/user-attachments/assets/66e942e8-85d9-4d7f-895c-2f3b1c442b7f)
![image](https://github.com/user-attachments/assets/596cdf89-016d-4a2e-ac7c-6fc3f7b10fd4)

Same with the bridge.
![image](https://github.com/user-attachments/assets/0245e0a5-3460-4e23-9047-70bb30395209)

Overall you have an extremely strong start. I really enjoy how you've layed out your rooms, I love the sillhouette, and I think once you get the ship a bit more filled in, this will be a great ship.

2024-12-06 21:52 UTC, thearbiber commented
Will continue work on this Soon, a bit busier IRL now. Thank you for the feedback though, it is appreciated.

2024-12-20 00:14 UTC, closed without merging