Phantom2
shiptest-ss13/Shiptest pull request #3744
Opened 2024-11-12 22:55 UTC by miniusAreas

## About The Pull Request

Adds the Phantom-Class Mining Courier for hardliners, made by ISF. Lets people play hardliners again. God bless.

![image](https://github.com/user-attachments/assets/b035e269-3425-4392-828f-5621a4b503f8)

_A modern ship only made in the past twenty-ish years, the Phantom's sleek hull, narrow profile, and wings would make one to believe it a racer, or small yacht. Inside, however, is a sturdy layout for small-scale Hardliner mining groups, commissioned by Cybersun and built by ISF._

## Why It's Good For The Game

lets people play their blorbos faction. Cause the Komodo got removed. With no replacement. Yeag.

## Changelog

:cl: miniusAreas
add: Added Phantom-Class Mining Courier to Hardliners. Enjoy muckin it in a shiny yacht.
/:cl:

2024-11-13 05:58 UTC, Apogee-dev commented
Remember to include an ISF decal somewhere in the ship (usually engi or cargo) and add a 4 digit ship number to one of the walls. Armory and cryo storage need hand rails, too.

Otherwise, it feels a bit sterile- it’s a sleek cybersun ship, but Hardliners are living in it. Add a bit of trash and clutter, and put some posters and signs up on the walls- warning signs in the airlock and near the engines and cargo bay door, for example, and personal posters in the living areas. Bridge could use a folder and pen by the paper big, and any stamps the captain might use (i think there’s a hardliner one… probably…)

2024-11-15 04:19 UTC, Apogee-dev commented
Could use some navigation lights on the wingtips (see Talos for example), and honestly those plastic folding chairs should probably be normal metal chairs for the most part- the plastic just feels way too cheap for a cybersun ship.

Other than that, please post an in-game screenshot of the map and an SDMM screenshot showing the map’s areas.

2024-11-16 09:42 UTC, Sadhorizon commented on _maps/configs/syndicate_gorlex_phantom.json
> +	"map_path": "_maps/shuttles/syndicate/syndicate_gorlex_phantom.dmm",
Hey, rename it to `syndicate_hardliner_phantom.dmm`. The "gorlex" part is outdated, and is being slowly removed on the NGR side of things.

2024-11-16 10:18 UTC, Sadhorizon commented
I like this.

- I think recolored white curtains would fit better than red/gold fancy ones.
![obraz](https://github.com/user-attachments/assets/f0f0c4a6-e778-42c8-b0cf-527affe35098)
- Since when do Hardliners use green? I'd suggest you use black suit vartedited to use `-med` sprite, since it's white-red-black.
![obraz](https://github.com/user-attachments/assets/da96cf45-14c9-4055-98b3-634f4ed0f94f)
- Put handrails somewhere here.
![obraz](https://github.com/user-attachments/assets/814cb9d9-2f76-4927-b42e-610a30a4ae64)
- The airlock is a sudden switch of floors. I'd just leave it black ngl. Also, add a handrail here.
![obraz](https://github.com/user-attachments/assets/4be1300f-3a97-47ea-92ad-a5fc7af0239d)
- Base trash spawner has nothing in the spawn list.
![obraz](https://github.com/user-attachments/assets/7ea4f85d-7db2-4951-af05-96f3cb9a0358)
- There is no starting materials for the lathe.
![obraz](https://github.com/user-attachments/assets/ad69a33c-9d26-4809-ab68-cf67f126e480)
- Fix the platform. Also, imo, plating doesn't really work here.
![obraz](https://github.com/user-attachments/assets/9feb0eb6-13c2-4e0b-aea0-2268a632ba25)
- I don't even know if jaunters work. Even if they do, it's _probably_ not a good idea.
![obraz](https://github.com/user-attachments/assets/7fc3d200-61cb-458e-834e-c09c166e07e0)
- The light switch is clipping into the APC here.
![obraz](https://github.com/user-attachments/assets/034fe038-96c4-488d-9189-3b0ac17afe26)
- Why is this in cryo. Also, why is there surgeon gear there? Should be in dorms - for example, in the spot of the AA.
![obraz](https://github.com/user-attachments/assets/2aa1555c-a63f-448e-bd02-7afbd3eabc35)
![obraz](https://github.com/user-attachments/assets/54062304-a85e-495e-bd61-d86d1eb6d59e)
- Cybersun uses the syndicate variant of cryopods.
![obraz](https://github.com/user-attachments/assets/a2c33d8a-43c8-4855-bc30-7410c441fdff)
- This rack has so much stuff on it, it should be an armorycage imo.
![obraz](https://github.com/user-attachments/assets/f2104dda-a261-4b55-8f58-fc10a7b58968)
- I have plenty issues with the safe. 1) For the love of god don't add maid outfits back. 2) Why is a cash safe in the armory? 3) Floor safes need to not be covered by a tile roundstart, or otherwise it's Weird. 4) Cybersun generally uses electronic wall safes over those big bastards.
- Airlock issues. So, how Cybersun does it is: Engi and cargo have freezer doors, Cryo and toilets have public doors (just turn off the var so they aren't actually public), Bridge uses command airlocks.
- Cybersun uses window firelocks. They also use heavy firelocks for the airlock (room) and the cargo bay shutters.
- This is A Lot of food. I'd remove a couple rations.
![obraz](https://github.com/user-attachments/assets/77b167ef-88e3-4c2c-ae51-7870975d3a30)
- This should be a secure closet.
![obraz](https://github.com/user-attachments/assets/753aefc3-b341-4642-a096-9d42db37e772)
- Cybersun uses secure holopads, as the cybersecurity company. Switch the var to "secure = 1" and also reflect it in the name.

2024-11-28 18:59 UTC, Gristlebee requested changes
- The suit storage unit area and cycle airlock could use lights. They're quite dark on their own.
![image](https://github.com/user-attachments/assets/877974b2-41cf-4042-99a8-f4ae3404368b)
- The south wall in the mess could use a light.
![image](https://github.com/user-attachments/assets/a892731e-2ec8-49eb-ba35-217dcb69b0f6)
- The unloading machine needs a conveyer under it to work properly. The input and output dirs on the stacking machine and smelter need to be oriented properly as well. The input and output dirs should be 4 and 8 on the stacking machine and 1 and 2 for the smelter.
![image](https://github.com/user-attachments/assets/7ed899e1-6855-4e78-8349-5b1c8046abe9)
- The combination of platforms and railings doesn't look great on live, and the platform overlays oddly over the stacking machine. I'd suggest getting rid of the railing and platform overtop the stacking machine. The platforms are also overlaying on top of the railing by the wrecker's lockers, which doesn't look right.
![image](https://github.com/user-attachments/assets/fb7f66e9-72d1-4a92-858a-864bc2969f1f)
- Platforms are overlaying on top of the railings over here as well.
![image](https://github.com/user-attachments/assets/f5fe1926-cdab-46be-b076-b5b94b4ff1d1)
- Stray freefloating safe in the engine wing.
![image](https://github.com/user-attachments/assets/05593bfc-e059-4477-b11b-b44c2554cc8f)
- This ship doesn't have any exterior windows. Some in the dorms or mess would be nice.
- The combination of EVA and dorms as a single room is strange. I'd recommend separating them into different rooms.
- The wreckers could use knifes in their lockers.
- This ship looks cramped to me with the use of one tile wide hallways. The circular floorplan in combination most of the ships room's are a thoroughfare across the ship or a trafficked area/hallway only exacerbates the issue.  I'd recommend experimenting with expanding the ship's sides by at least one tile to give you the space to widen the hallways.

2024-11-30 07:59 UTC, Gristlebee commented
Lets see how this performs in practice.

2024-12-06 18:17 UTC, Latentish commented
My primary issue here is the large amount of 1wide hallways in this ship. I understand that for a small crew ship, that I imagine is meant to feel cramped, however this very likely going to suffer in a similar way to the Noderider. You could help to alleviate this by making the south (and probably the north) hallway(s) into 2wide(s).
![image](https://github.com/user-attachments/assets/4991ab9c-a921-4b87-ba61-e80ee2889d23)

My other big issue here is that this airlock is in the middle of one of the 2 primary hallways leading from the front to the back of the ship. It being 3 entrance/exits is also rather awkward.
![image](https://github.com/user-attachments/assets/52144f8a-150f-4053-97ec-9048f5f8a877)

Overall, you're mapping skills have increased dramatically.

2025-01-10 06:58 UTC, Gristlebee requested changes
Feedback after testing on live
---

- The ship is missing a water tank.
- A valve or a gas pump to connect distro from the large air tank would be good for more fine control on the air feed rather than a direct pipe connection.
![image](https://github.com/user-attachments/assets/fe52c3f7-7af0-4217-80d6-002e5d15982e)
- Consider swapping out the jackhammers the wreckers get for the Gorlex salvage hammers. I do think it would be more flavourful.
- Players noted the ship did feel small for it's crew size. You may want to consider cutting one of the crew slots on the ship, or look into expanding the ship hallways as suggested.

2025-01-10 21:02 UTC, Gristlebee commented
Crates are able to drop onto the refinery conveyer belt and get stuck. I'd suggest either making the belt it's own separate area similar to the Scarab so crates don't drop inside, or adjust the layout of the refinery set up you can get the crate without needing to knock down a wall.
![image](https://github.com/user-attachments/assets/753160c2-1f99-4d93-8413-7ee0528f8b48)

2025-01-11 09:20 UTC, miniusAreas commented
I've adressed complaints and requests. Any above issues are fixed fully. Additional changes are
- alt hardliner coat for cap
- ID reader

2025-01-11 09:20 UTC, miniusAreas commented
![image](https://github.com/user-attachments/assets/ad22a120-5853-457f-90c3-b46e85f824ed)

2025-01-12 00:04 UTC, kaylexis commented
only one last issue i've noticed, the EVA storage room doesn't have a scrubber & vent

2025-01-17 20:48 UTC, Erikafox commented on _maps/configs/syndicate_hardliner_phantom.json
> +	"faction": "/datum/faction/hardliners",
```suggestion
	"faction": "/datum/faction/syndicate/hardliners",
```

Your faction datum won't allow access to general coalition gear otherwise.

2025-01-18 09:44 UTC, Gristlebee commented
Thank you for your contribution, but after deliberation from the maptainer team, we will not be accepting the PR at this time.

2025-01-18 09:44 UTC, closed without merging

2025-01-18 21:58 UTC, miniusAreas commented
> Thank you for your contribution, but after deliberation from the maptainer team, we will not be accepting the PR at this time.

I would like to have feedback, or at least know why. This is the second PR I've made with little to no feedback then closed, and that's extremely frustrating.

2025-01-18 22:15 UTC, Gristlebee commented
> I would like to have feedback, or at least know why. This is the second PR I've made with little to no feedback then closed, and that's extremely frustrating.

Sorry about that, it wasn't my intent to brush this aside with little fanfare, and I understand your frustration. The Banshee and the Phantom were both similar ships in purpose as small Hardliner salvage vessels and the team didn't want to merge both to avoid overlap in terms of niches. The final decision mainly came down to the layout and ship flow of the maps. The consensus among the maptainer team was the Phantom had a cramped layout with it's room placement and small hallways that was difficult to navigate.

2025-01-19 01:57 UTC, miniusAreas commented
> Sorry about that, it wasn't my intent to brush this aside with little fanfare, and I understand your frustration. The Banshee and the Phantom were both similar ships in purpose as small Hardliner salvage vessels and the team didn't want to merge both to avoid overlap in terms of niches. The final decision mainly came down to the layout and ship flow of the maps. The consensus among the maptainer team was the Phantom had a cramped layout with it's room placement and small hallways that was difficult to navigate.

The. I- The Phantom isn't a salvage vessel, it doesn't even have a grinder or any sort of salvage equipment beyond the hammers that I was told to put in. It's a mining vessel, whereas the Banshee is a mech-based salvage vessel. Player feedback was relatively positive to everything with it, and pretty much everything that was brought up to me was solved, including part of the cramp (related to the cargo bay doors). 

I'm still relatively confused as to *how* the Phantom could be confused as a salvage vessel when the name states it's a Mining Courier, lacks any salvage gear, contains a refinery- the whole point of doing this was to separate it from the Banshee to avoid it being a problem of having to similar ships for similar roles.

This is still extremely frustrating.