Adds the Banshee-class Salvage Clipper [Hardliner]
shiptest-ss13/Shiptest pull request #3761
Opened 2024-11-14 20:17 UTC by Burning02

## About The Pull Request

Adds the Banshee-class Salvage Clipper to the game for the Hardliner faction ingame as pictured below:
![2024-11-14 15 12 38](https://github.com/user-attachments/assets/aa96dcdb-a222-40cd-9c00-fda336491b48)

## Why It's Good For The Game

This adds a new vessel for a faction lacking in not only player spawnable vessels, but also small ships. The only currently available Hardliner vessel (Komodo) was too large for the average Komodo crew of 4, with either semi-important roles missing crew (Engineer, medic, or in some cases 2IC's), or the majority of the crew being one role (Deckhand, trooper).

## Changelog

:cl:
add: Adds the Banshee-class Salvage Clipper as a playable Hardliner vessel
/:cl:

2024-11-15 02:23 UTC, Apogee-dev commented
Remember to post an in-game screenshot and a screenshot of the map in SDMM with areas enabled in the PR body please

2024-11-15 02:24 UTC, Burning02 commented
Alright! I'll have those posted soon

2024-11-15 02:33 UTC, Burning02 commented
Pictures added as requested

2024-11-15 03:56 UTC, Apogee-dev commented
I think you went a little overkill on the colored exterior lights there. They’re supposed to be imitating navigational beacons on aircraft- You can honestly remove almost all of those and just have one or two on the wingtips, plus the ones on the cargo deck. If the wings are too dark, use floor lights or a more neutral color of beacon. there’s a white one, i think.

2024-11-15 03:59 UTC, Anticept commented
Funny thing apogee, white is also a restricted light.

Red left, right white, aft white, but internittent use like landing lights can be white too.

Strobes are white too.

2024-11-15 04:07 UTC, Apogee-dev commented
With that out of the way, some design feedback.
- The central hallway is remarkably barren, with no furniture at all outside of the trash can. I’d suggest putting a couple chairs or a corpo couch / bench against the wall somewhere in there. Sven if it’s just a couple it’ll break up the monotony a lot.
- Dorms is similarly very empty, especially near the door. Give them a couch against the back wall or an armchair by the table, maybe!
- Cryo has a similar problem with that big empty table, thanks to the locker scooping items up. If you have a wall locker on the same tile as a table, you don’t need a wall locker. Use a standing locker instead, or remove the table for a little more walking room. Maybe put a chair in the corner instead.
- Don’t use those dark iron chairs in canteen please, just use normal ones. The dark ones don’t stand out against the dark floor and don’t match the table.
- Please don’t put shutters over your external airlock. Enable ship access on the outer door if you’re concerned about uninvited guests.
- Speaking of the airlock, airlocks must have 2 passable tiles in sequence so somebody can drag an object through. That one has 2 tiles of internal space but if you walk into that second tile dragging something you’ll trap yourself. It also needs an emergency space suit and some oxygen; on a tiny ship like this, you can put those in a wall emergency closet.

2024-11-15 04:14 UTC, Apogee-dev commented
> Funny thing apogee, white is also a restricted light.
> 
> Red left, right white, aft white, but internittent use like landing lights can be white too.
> 
> Strobes are white too.

I think the reason I used green was probably because I was thinking of boats, which use those a big differently. Red port, green starboard, white on the stern and masthead lights (or all-around light). You’re right though, white would still be restricted.

2024-11-15 05:04 UTC, Anticept commented
> > Funny thing apogee, white is also a restricted light.
> > Red left, right white, aft white, but internittent use like landing lights can be white too.
> > Strobes are white too.
> 
> I think the reason I used green was probably because I was thinking of boats, which use those a bit differently. Red port, green starboard, white on the stern and masthead lights (or all-around light). You’re right though, white would still be restricted. Use yellow, then.

Edited, meant to say right is green.

2024-11-15 15:14 UTC, Burning02 commented
All feedback addressed in the map, I'll be updating the pictures and PR soonish.

2024-11-16 10:20 UTC, Sadhorizon commented on _maps/configs/syndicate_gorlex_banshee.json
> +	"map_path": "_maps/shuttles/syndicate/syndicate_gorlex_banshee.dmm",
Hey, rename it to `syndicate_hardliner_banshee.dmm`. The "gorlex" part is outdated, and is being slowly removed on the NGR side of things.

2024-11-16 16:01 UTC, Burning02 commented
Just a few replies to your review:

>Since when do Hardliners use green? I'd suggest you use black suit vartedited to use -med sprite, since it's white-red-black.

![Screenshot 2024-11-16 103814](https://github.com/user-attachments/assets/f1baf653-120f-48e4-9cc3-cc0a5ccf50e1)

>There is no starting autolathe mats.

Whoops, forgot to add thoses

>This really does not need three tanks - it's for emergencies, and there is only one suit anyways.

Did this when I had woke up so I probably fat fingered the left click, I'll fix that

>Cybersun uses heavy firelocks in airlocks.

No, they don't? Atleast not in the one other Cybersun map with an airlock

> Don't give them a CS stamp. I've talked with Apogee and we've decided that Hardliners should be stampless. I guess generic captain works though?

Unless Apogee forgot, I asked her in DM's if I could add a Cybersun stamp, and if so which one. They said the virtual solutions stamp.

>Anchor your generator.

I've included a wrench _and_ a toolbox to do such if no engineer is present whatsoever

>I have no idea if GEC and Hardliners should work with each other. Double check with someone who knows please.

Could've sworn the Hardliner outfit had a GEC alternative? I'll have to double check; And in regards of them working together I have at the very least before Komodo was kill had GEC mechanics pretty commonly although yeah I'll check with a lorehead

> Airlock issues. So, how Cybersun does it is: Engi and cargo have freezer doors, Cryo and toilets have public doors (just turn off the var so they aren't actually public).

Haven't had any complaints from Apogee with the specific airlocks I've used. Unless I get complaints from her, I'll keep them as is. Well, save for the cryo one I'll change that one to a public since it does feel out of place.

> Why is this a secure closet what??

Whoops, could've sworn I changed that to an emergency locker

Anyhow, I'll get to doing some of the changes.

2024-11-16 16:04 UTC, Burning02 commented
Nevermind, I'm mistaken on which Hardliner role has a GEC outfit alternative, it's the miner outfit for whatever odd reason

2024-11-16 19:19 UTC, Zevotech commented
@Sadhorizon The effort is appreciated, but please leave comprehensive reviews to maptainers. Providing conflicting information and styling your review as if the changes are required really isn't helpful. Feedback via discord or short comments is fine, but please refrain from doing this in the future.

2024-11-28 09:08 UTC, Gristlebee requested changes, later dismissed
- Platforms tend to overlay oddly with objects or structures on the same tile. The platforms overlap on the items on racks and the SSU, which looks odd.
![image](https://github.com/user-attachments/assets/563a5d41-ce64-4464-acb8-1bae1f3c375b)
- The ripley crate is missing the chassis, so you can't construct it.
![image](https://github.com/user-attachments/assets/d947b6e2-2e17-470b-b541-8507547b15cd)
- Gear wise, a mech mounted drill and an ore crate for the mech to carry could be useful.
- Not your fault, but it seems the note placer helper may be bugged
![image](https://github.com/user-attachments/assets/6f719ab3-aadf-4168-99b0-dfcb16b45abd)
- You have populate set on the fridge in the mess, which means it spawns with extra ingredients. Something to keep in mind if that wasn't intentional.
![image](https://github.com/user-attachments/assets/5aaa926e-a660-4bdc-aaf6-14d1133a3a12)
- Since you have the external hull plating here, you could move down the numbers here and pixel shift them upwards like posters so don't show on the interior side of the ship.
![image](https://github.com/user-attachments/assets/dc8f04eb-8e3b-485f-a9c4-fd5f6552c8a4)
- The area near the engines could use more lighting. It's quite dark.
![image](https://github.com/user-attachments/assets/a7fa1429-144b-4e55-84e6-3b4f3731a43d)
- The ship has no water tank.

2024-11-28 09:33 UTC, Burning02 commented
Review addressed in in the last push to the PR

2024-12-06 18:07 UTC, Latentish commented
This looks so tm'able I might add it to TMs.

2025-01-18 09:54 UTC, merged