New Ruin: Tesla Lab
shiptest-ss13/Shiptest pull request #3787
Opened 2024-11-16 20:42 UTC by Erikafox

## About The Pull Request
Adds a new ruin to the iceplanet ruin pool - Tesla Lab
<details><summary>Screencaps</summary>
<p>

![image](https://github.com/user-attachments/assets/190906ae-ff05-4b76-9b7c-9d58cfb7c98b)
![StrongDMM-2024-11-16 15 39 07](https://github.com/user-attachments/assets/36dffe44-0198-4439-bd71-320d5a951e69)
![StrongDMM-2024-11-16 15 39 08](https://github.com/user-attachments/assets/3d52d5e7-10a3-4c12-b1bb-65b76206f32f)

</p>
</details> 

## Why It's Good For The Game
This is an very hard ruin filled with nefarious tricks and a decent bit of loot. I want it to challenge people.
## Changelog

:cl:
add: CLIP has lost contact with a facility in the system. Go find it. Go see what happened. I dare you.
/:cl:

2024-11-16 22:23 UTC, Gristlebee requested changes
- since these are secure containment areas, I think it'd make sense if they had blastdoors for the windows. The tesla observation room also has no lighting.
![image](https://github.com/user-attachments/assets/d770e51d-937c-4c7f-9208-3d4435de1d60)
![image](https://github.com/user-attachments/assets/88d69dcb-0a4b-4bcc-b855-f2dbeef17bf8)
- these are all active turfs. Use planetary atmos subtypes please. The room also has no lighting.
![image](https://github.com/user-attachments/assets/034a3834-818c-453b-bb15-d112c41a47bc)
- no lighting in the jani closet or toilet.
![image](https://github.com/user-attachments/assets/3d2ffa87-7eec-4a7b-80a0-c9d4a35561c3)
- there's no lighting in this washroom as well.
![image](https://github.com/user-attachments/assets/22f9c322-146c-42b1-a63c-bbdd5d97ea93)
- the holofields in the subshuttle are not anchored. Use the roundstart subtype.
![image](https://github.com/user-attachments/assets/a7d7c058-5a2f-4219-8297-0c60433d5fb1)
- Exterior windows should have shutters I feel.
![image](https://github.com/user-attachments/assets/b32de871-5cd8-4737-bb94-f4b29a6758f5)
- same issue with the compound entrance holofields.
![image](https://github.com/user-attachments/assets/9f310c69-692c-4afd-9c40-80230579415e)
- the railing overlays on top of the medkits in the subshuttle medbay
![image](https://github.com/user-attachments/assets/42d8c634-fe53-491c-8f40-1f3e34030719)
- missing a wire here between subshuttle holofields and the SMES
![image](https://github.com/user-attachments/assets/b8065ecc-3259-434d-a039-840ce3fc98d6)
![image](https://github.com/user-attachments/assets/57dcc7e6-bfd3-481d-8c16-4640c02678e8)
- the compound holofields aren't properly wired either.
![image](https://github.com/user-attachments/assets/69e3dfbb-132a-48c6-8c23-38d1b6c1d868)
  - The compound entrance holofields and subshuttle portside holofields share the same IDs.
- the office has no buttons for the door and windows shutters.
  ![image](https://github.com/user-attachments/assets/c9e01db8-76c2-4229-bbfe-60e75a9e7724)
- the turrets on the subshuttle shoot the frontiersmen simplemobs as they dont have the frontiersmen faction set.
- the turrets wont target heads of staff.
![image](https://github.com/user-attachments/assets/2d3da919-8373-48a1-8779-6e4f210f7362)
- the tapes in here don't play back properly. They start, but never begin playing back the recording.
![image](https://github.com/user-attachments/assets/52b6d9c0-35d0-43cd-9e24-eda84b8b2e0c)
- this should be a proper cycle airlock if you're planning on making the tesla room airless.
![image](https://github.com/user-attachments/assets/965d663f-575e-47d4-a79d-08ead26d5bc4)
- the tesla anomaly engine is cool, but doesn't actually generate much in the way of power, and with such a large ruin it tends to burn through all it's stored power fast which is a concern. Maybe put some more SMESes with extra charge, though if you have another solution in mind you want to go with that's fine.
![image](https://github.com/user-attachments/assets/3b3ee867-4627-46a3-bcea-62937963aacb)
- the blood freezer is empty. I notice you set the populate to false, so maybe toss around some empty blood bags to imply they used up the blood so there's a bit more substance too it.
![image](https://github.com/user-attachments/assets/d377e59b-a432-425b-b24c-57d6a0a0fdd2)
- Another empty crate here in the cargo bay. Put something in, or have it start open to imply it's been looted like the other crates.
![image](https://github.com/user-attachments/assets/eb7b9a58-a54e-4d66-ab0b-95e2a984dc60)
- the desynchronizers are fun and it's nice to see them actually used. I'd say cut down the amount mapped to one or two though.
![image](https://github.com/user-attachments/assets/dbf2eb63-2468-499f-a406-95d45300ba68)

2024-11-16 23:36 UTC, Gristlebee requested changes
- You added shutters to the tesla room like I asked in the previous review, but not the static anomaly room. Is that intentional?
![image](https://github.com/user-attachments/assets/4afb4924-4a79-436b-82cf-23577f789fc1)
- You sealed off the room, which does solve the issue of active turfs, but does limit the amount of the ways you can enter the ruin and makes it a lot more linear. I do think it would be more interesting if you had it be open like before but with planetary turfs. There's also still no lights from what I can see.
![image](https://github.com/user-attachments/assets/0695f774-ee7d-425f-b32a-e502707e1555)
- Shutters and buttons in the office also have the wrong ID.
![image](https://github.com/user-attachments/assets/e1efe976-c44e-4e5e-977a-a463d97df3bb)
![image](https://github.com/user-attachments/assets/c39f7b92-be01-4d13-b0be-f950a2b3ca18)
- Stray light in the SMES room
![image](https://github.com/user-attachments/assets/a799aaf4-52c6-4d72-9112-4d0f59550e3e)
- Cycle airlock here as I asked for in the previous review unless you have a reason as for otherwise.
![image](https://github.com/user-attachments/assets/e9906e5d-0e2b-43e2-a1b5-fb8797a65ba5)
- You don't seem to have changed the faction on the turrets on the subshuttle from what I can tell so they're still gonna target the frontiersmen simple mobs around.
- Doing a check on the loot, the amount of frontiersmen that will drop their guns is concerning. I'd say set 4 of the shotgunners, 3 of the mosins, 1 of the SKM guys to neuter so they dont drop guns and the rest can drop their guns. I do get you want it to be a ruin with good loot for the challenge, but this is a lot of guns as is right now.

2024-11-21 04:39 UTC, thearbiber commented
Please keep in mind those claymores are capable of one shotting players and deleting their gear, while also being very small, hard to see, and not able to defuse/prevent like landmines.

2024-11-21 04:39 UTC, Erikafox commented
#3817

2024-11-21 04:41 UTC, thearbiber commented
waow

2024-11-21 04:45 UTC, Ratvarr commented
> Please keep in mind those claymores are capable of one shotting players and deleting their gear, while also being very small, hard to see, and not able to defuse/prevent like landmines.

defusal _is_ possible, I couldn't tell you how though. It's in the crate you buy them from on a page

2024-11-21 04:45 UTC, Erikafox commented
yeah apparently you can screwdriver them

2024-11-21 04:46 UTC, Burning02 commented
On top of that, they quite literally break your gun/s. You'll be unable to load it, fire it, or even remove/add attachments.

2024-11-21 04:46 UTC, Ratvarr commented
also: the Static Syncroniser is not a good item probably to have on this because it allows someone to literally delete themselves temporarily. also it has it's **own** bugs and issues potentionally

2024-11-21 04:48 UTC, Erikafox commented
It's a cool item that's appearing in like two spots on one ruin. (That gives you brain damage for using it)

2024-11-21 06:32 UTC, Gristlebee submitted a review, later dismissed
Feedback after testing on live:
---

- This hallway has too many anomalies. Keep the one in the center of the hall and cut the other two.
![image](https://github.com/user-attachments/assets/805320e1-2e69-4a56-9871-92c51545e624)
- I'd say either cut this static, move it further in the hall into the lab, or reduce it's effect range. It feels redundant to me already so close to the other anomaly in containment, and the range brain damage effect is enough to get through the firelocks, which you have to cut through to get to the anomaly, which means nearly guaranteed brain damage.
![image](https://github.com/user-attachments/assets/d126c61d-4927-4560-9d0c-79a9e1a40052)

- Increase the spacing on the turrets. Players running through the ruin found them a bigger threat than the actual mobs. They're well dug in, which is fine. But the clustering on them makes them difficult to approach. These two right are really close and a particular offender.
![image](https://github.com/user-attachments/assets/dc53338a-eaea-4d02-91a2-f8d45f0c8517)
- In the same vein, cut the sandbags here which were originally meant for more turret emplacements. The area is already being covered by the subshuttle turrets, which does the job.
![image](https://github.com/user-attachments/assets/540b3113-342f-413c-8629-badd0c7f96d2)
- I think it would be good to have a button on the exterior of the subshuttle doors from a level flow aspect, so there's a natural way in and players dont have to cut through.
![image](https://github.com/user-attachments/assets/699374d6-8eba-43a9-960f-9eedfef43199)
- The desynchronzers need a much shorter max duration. I notice you already set them a max of a minute at 600 max duration, but I feel that's still too long. Set the max duration to 15 seconds.
- I still think this ruin needs a culling on the amount of loot after seeing it run through on live, particularly the amount of guns. All the Frontiersmen don't need to drop their guns when there's already some strong weapons mapped in. One SKM, one shotgun and three mosins can be dropped from the frontiersmen and the rest should be set to neuter. The mauler and flamers dropped from the admiral and flametroopers can be left as is and don't need to be touched.
- Cut the claymores in the armory down to one if you're going to have the Hammer here.
![image](https://github.com/user-attachments/assets/424a5312-9829-43de-8989-c291d5b8edee)

2024-11-30 04:02 UTC, MarkSuckerberg commented
justice for doctor pills

2024-12-06 19:23 UTC, Latentish requested changes, later dismissed
![image](https://github.com/user-attachments/assets/3c3996c3-2817-49f2-beee-d8d1f76abdac)
You have an open parentheses somewhere.

2025-01-03 10:35 UTC, FalloutFalcon approved these changes

2025-01-04 00:11 UTC, merged