Underbarrel Gun Attachments
shiptest-ss13/Shiptest pull request #3825
Opened 2024-11-22 20:28 UTC by Gristlebee

## About The Pull Request

Adds underbarrel gun attachments. Current roster is the underbarrel shotgun, e-gun, flamethrower, riot grenade launcher and 40mm grenade launcher. The first four can be bought from the outpost cargo.

Underbarrel guns can be fired/reloaded/interacted with by swapping the fire select to underbarrel.

Cleans up the riot grenade launcher code a bit.

Underbarrel gun sprites are recolors of Rylie's underbarrel grenade launcher.

## Why It's Good For The Game

Adds some more customization and personalization options to a players loadout, and I think it's neat.

## Changelog

:cl: Gristlebee, Rylie
add: Underbarrel guns
fix: Grenade launcher code
/:cl:

2024-11-27 05:45 UTC, MarkSuckerberg submitted a review, later dismissed
now when are we adding killstreaks

2024-11-27 05:45 UTC, MarkSuckerberg commented on code/__DEFINES/guns.dm
> +#define COMSIG_ATTACHMENT_UNWEILD "attach-unwield"
```suggestion
#define COMSIG_ATTACHMENT_WIELD "attach-wield"
#define COMSIG_ATTACHMENT_UNWIELD "attach-unwield"
```

2024-11-27 05:45 UTC, MarkSuckerberg commented on code/datums/components/attachment.dm
> +	///Called on the parents unweild
```suggestion
	///Called on the parents wield
	var/datum/callback/on_wield
	///Called on the parents unwield
```

2024-11-27 05:45 UTC, MarkSuckerberg commented on code/datums/components/attachment.dm
> +	RegisterSignal(parent, COMSIG_ATTACHMENT_UNWEILD, PROC_REF(try_unwield))
```suggestion
	RegisterSignal(parent, COMSIG_ATTACHMENT_WIELD, PROC_REF(try_wield))
	RegisterSignal(parent, COMSIG_ATTACHMENT_UNWIELD, PROC_REF(try_unwield))
```

2024-11-27 05:45 UTC, MarkSuckerberg commented on code/datums/components/attachment_holder.dm
> +	if(!(is_type_in_list(attachment,valid_types)))
perhaps make `valid_types` a typecache?

2024-11-27 05:45 UTC, MarkSuckerberg commented on code/game/objects/items/attachments/gun_attachments/flamethrower.dm
> +	desc = "An internal fuel tank for a flamethrower. You shouldnt have been able to pull this out."
```suggestion
	desc = "An internal fuel tank for a flamethrower. You shouldn't have been able to pull this out."
```

2024-11-27 05:45 UTC, MarkSuckerberg commented on code/game/objects/items/attachments/gun_attachments/riot_launcher.dm
> +	desc = "An even terribler thing. Just despicable really. You shouldnt be seeing this."
```suggestion
	desc = "An even more terrible thing. Just despicable, really. You shouldn't be seeing this."
```

2024-12-04 06:32 UTC, Gristlebee commented on code/datums/components/attachment_holder.dm
> +	if(!(is_type_in_list(attachment,valid_types)))
made it a typecache, hopefully I did it right

2024-12-11 07:00 UTC, rye-rice approved these changes

2025-01-03 10:19 UTC, FalloutFalcon requested changes
small questions but otherwise pretty happy with the code and a good feature!

2025-01-03 10:19 UTC, FalloutFalcon commented on code/modules/projectiles/gun.dm
> +			AddComponent(/datum/component/automatic_fire, fire_delay)
Hrm. The way this works, i assume that if you take off and then remove an attachment it leaves the gun with a useless automatic_fire component.. you might want to add logic to clean it up if there is no fullauto modes on the gun?

2025-01-03 10:19 UTC, FalloutFalcon commented on code/modules/projectiles/guns/ballistic.dm
> +	var/always_chambers = FALSE
this seems like it should be a bolt type? I thought BOLT_TYPE_NO_BOLT accomplished the same behavior but I might be forgetting.

2025-01-03 10:19 UTC, FalloutFalcon commented on code/modules/projectiles/guns/ballistic.dm
> +				if ((chambered == null && bolt_type == BOLT_TYPE_NO_BOLT) || always_chambers)
might be wrong here but i assume you don't want it to chamber while there is something in there already.
```suggestion
				if (chambered == null && (bolt_type == BOLT_TYPE_NO_BOLT || always_chambers))
```

2025-01-03 10:19 UTC, FalloutFalcon commented on code/modules/projectiles/guns/manufacturer/scarborough/ballistics.dm
> +#define SCARBOROUGH_ATTACHMENTS list(/obj/item/attachment/silencer, /obj/item/attachment/laser_sight, /obj/item/attachment/rail_light, /obj/item/attachment/bayonet, /obj/item/attachment/energy_bayone
```suggestion
#define SCARBOROUGH_ATTACHMENTS list(/obj/item/attachment/silencer, /obj/item/attachment/laser_sight, /obj/item/attachment/rail_light, /obj/item/attachment/bayonet, /obj/item/attachment/energy_bayonet, /obj/item/attachment/gun)
```

2025-01-03 21:43 UTC, Gristlebee commented on code/modules/projectiles/gun.dm
> +			AddComponent(/datum/component/automatic_fire, fire_delay)
The logic checks if it has a full auto firemode in the first place, so barring any freak edge cases only guns that should have the automatic_fire component anyways should have it. I added this check because it was adding extra automatic_fire components to fully automatic weapons before and it bricked the gun.

It should be fine, but I can still add the logic if you want.

2025-01-03 21:49 UTC, Gristlebee commented on code/modules/projectiles/guns/ballistic.dm
> +	var/always_chambers = FALSE
BOLT_TYPE_NO_BOLT achieves a similar behavior with how it always chambers on load, but it also changes some gun functionality as well, which caused unintended behavior. So thats why I had this far to so I could have the correct bolt type I wanted and still make it always chamber.

2025-01-03 21:50 UTC, Gristlebee commented on code/modules/projectiles/guns/ballistic.dm
> +				if ((chambered == null && bolt_type == BOLT_TYPE_NO_BOLT) || always_chambers)
That's intended.

2025-01-03 23:07 UTC, FalloutFalcon commented on code/modules/projectiles/gun.dm
> +			AddComponent(/datum/component/automatic_fire, fire_delay)
hrm na its fine

2025-01-03 23:07 UTC, FalloutFalcon approved these changes

2025-01-06 13:12 UTC, merged