Vela Industrial Cruiser: 4th Time the charm?
shiptest-ss13/Shiptest pull request #3843
Opened 2024-11-27 01:37 UTC by Erikafox

## About The Pull Request
Adds the Vela Industrial Cruiser, a Minuteman capital ship (Last one I'm doing for a long time) built around mining, mechs, and roleplay.
<details><summary>Screenshots</summary>
<p>

![StrongDMM-2024-11-26 20 12 39](https://github.com/user-attachments/assets/5c6dd3bb-f0cb-4de2-8323-4725fb3703ca)
![StrongDMM-2024-11-26 20 12 41](https://github.com/user-attachments/assets/820441a8-26cf-4b5e-b8da-ea4d7e1dad91)
![dreamseeker_2vNSYmdM5A](https://github.com/user-attachments/assets/6a355765-62e6-4c1f-8498-d61468afed58)
![dreamseeker_v86d5uuOdN](https://github.com/user-attachments/assets/6f5ad67e-89da-4c65-831c-17d3766585fc)

</p>
</details> 

Crew of 15. Yes I am aware this is absurd. Yes I am aware it will get played very infrequently. Looking For Ship should help.
1x Captain
1x Foreman
1x First Officer
2x Mech Pilots
2x Mechanics
2x Minutemen
1x Doctor
5x Random Guys With Sticks

Light armament
sidearms for officers
2x cm23
1x cm15

Mech Stuff
Functional medbay
Well geared engineering
Sauna

## Why It's Good For The Game
frankly this is a vanity project. 

## Changelog

:cl:
add: The Vela-Class industrial cruiser is BACK and WORSE THAN EVER
/:cl:

2024-11-27 01:40 UTC, thearbiber commented
What if you added crack for the minutemen

2024-11-27 01:41 UTC, MassiveMen commented
No image attached, take my downvote

2024-11-27 01:43 UTC, MassiveMen commented
What if you. Wanted to go to heaven. But god said. Remap the Vela a fourth time.

2024-11-27 01:46 UTC, Erikafox commented
the vela fits a similar niche to stupid overengineered nazi vanity projects. it is stupid. it is overengineered. it is way too big. it doesn't work good. sometimes it just combusts. people keep trying to make it work.

2024-11-27 01:48 UTC, meemofcourse commented
IT'LL WORK THIS TIME

2024-11-27 07:38 UTC, generalthrax commented
Hows the power drain on this ship

2024-11-27 07:38 UTC, Erikafox commented
Worthy of the engineering section

2024-11-29 14:15 UTC, dessysalta commented
Just wanted to say this ship is gorgeous.

2024-12-05 22:44 UTC, meemofcourse requested changes
![imagen](https://github.com/user-attachments/assets/af631bff-81ee-4c95-b4a0-ab607fca082c)
![imagen](https://github.com/user-attachments/assets/defc3be2-39a9-4064-a617-e9a7b41a156a)

* i have to ask. why is there a crate full of soda cans
* there are two ration crates with no rations in them and three water bottles each

![imagen](https://github.com/user-attachments/assets/00e6eb20-733e-447e-a003-fb3205e02a80)

i do not like these dorms. this is a military-ish ship so it should probably have something more akin to barracks

![imagen](https://github.com/user-attachments/assets/fc37ea7f-fae4-48fe-8a44-6ec0de059761)

i know this is a ridiculous change. but i'm gonna have to ask you to remove one beagle mug from the bridge

![imagen](https://github.com/user-attachments/assets/c60e0107-5d42-40fe-b39e-8f798b1c5409)

i do not like the perfect spacing between these coffee mugs

![imagen](https://github.com/user-attachments/assets/e92dc18d-accd-4036-97db-8eabbc61da87)

this does not feel like a correct use of platforms

![imagen](https://github.com/user-attachments/assets/d25cedc6-f60c-49aa-935a-59d0bef10834)

minor nitpick and you can object but the minuteman outfit popularly uses bulletproof vests, not standard armor vests

![imagen](https://github.com/user-attachments/assets/6852e0f3-5c9f-4998-b597-4c9124cecc1a)

officers get jackboots

![imagen](https://github.com/user-attachments/assets/3cd96f19-bd70-491d-8952-bd2642f383a2)

you should avoid mapping stamps that are for a faction itself since that kind of implies the ability to approve stuff on the behalf of the entire faction

![imagen](https://github.com/user-attachments/assets/607b46ce-8ffa-4e78-93c0-1859584acae2)

i would probably ask rye if you can use the cm-1

![imagen](https://github.com/user-attachments/assets/73ede34f-a345-4521-bafc-4df6cafaf398)

change the description on this Guy.

![imagen](https://github.com/user-attachments/assets/8a1122f3-0ca5-48b3-9ae2-65294dee0cd5)

you cannot use wooden logs as fuel for the sauna

![imagen](https://github.com/user-attachments/assets/bef93053-9566-4be7-9e84-b5b7b8de4e27)

minor nitpick but most of the ship could use some more signaling for where stuff is

i dunno what else i wanna take a nap

2024-12-05 22:50 UTC, Erikafox commented
> * i have to ask. why is there a crate full of soda cans
> * there are two ration crates with no rations in them and three water bottles each

No vendors on the ship (clip rule), ration crates spawn rations on init

>i do not like these dorms. this is a military-ish ship so it should probably have something more akin to barracks

design intent is for a less military design. Less space cops and more "This is military adjacent"

>minor nitpick but most of the ship could use some more signaling for where stuff is

I'll put some signs up.

2024-12-06 18:00 UTC, Latentish commented
![image](https://github.com/user-attachments/assets/93a9a146-d71e-49e0-9d24-bd01d4532e2d)
You have two disconnected pipes. I'm unsure if the "Wet floor" error is a hiccup with the components unrelated to your pr, or if there's an issue somewhere on the ship with a wet floor tile.

2024-12-06 18:55 UTC, Erikafox commented
fixed, not caused by me

2025-01-04 22:56 UTC, Gristlebee submitted a review, later dismissed
The Vela is under independent instead of minutemen in the shuttle manipulator.
![image](https://github.com/user-attachments/assets/c80c73e1-3190-4829-a756-e30e9fcdcff6)
Hansk the wolf tries to murder you if you don't have the minuteman faction, rather than being passive.
![image](https://github.com/user-attachments/assets/347b52ba-d5d5-491b-af95-930901ece32c)
The toilets are pretty dark. It could use brighter/more lights.
![image](https://github.com/user-attachments/assets/20da3f8d-d0e0-4e32-9917-ef6b8a83ae5e)
The ends of the hallways to the mech bay are pretty dark too.
![image](https://github.com/user-attachments/assets/b0b1be04-999b-48cf-a1af-6bc96b22fd8f)
The minutemen suit storage units already come with hardsuits. Either get rid of the ones you mapped on top, or use inherit suit storage units. 
![image](https://github.com/user-attachments/assets/e33e29a8-3b8f-4420-a542-8e0055cac367)
![image](https://github.com/user-attachments/assets/a6613070-4d7e-4c21-870c-6903e273a6c9)
Light embedded behind the window to the cell.
<img width="278" alt="image" src="https://github.com/user-attachments/assets/8f778878-0298-4ef4-87f6-b08243ac9686" />
The smokes and soda crate should start closed unless you have a reason for them to be open. Same for the mat crates by the furnaces.
![image](https://github.com/user-attachments/assets/dc4d7536-96f3-4940-a2d1-a297f34a8966)
![image](https://github.com/user-attachments/assets/82f295d3-d31d-4aa8-9287-61ce2f1f888b)
Both holofields are not wired.
![image](https://github.com/user-attachments/assets/ca0a205e-7eb1-43fa-a64b-2683400cc251)
![image](https://github.com/user-attachments/assets/a1eeb26a-1fc7-4d75-82a1-2471e8767b8b)
Crew quarters is missing an air alarm. I'd suggest having one inside the sauna for ease of filtering out the steam when you're done.
![image](https://github.com/user-attachments/assets/f91aab71-3700-41f7-ba7d-4f2375fbe6ab)
Janitorial and Med is missing an air alarm too.
![image](https://github.com/user-attachments/assets/674fda62-f065-4444-ad4d-95336e6dee85)
![image](https://github.com/user-attachments/assets/4972fadc-2387-4e05-b0aa-70b0704a77c0)
Grav gen isnt wired.
![image](https://github.com/user-attachments/assets/4be84a9b-4de2-48e9-9deb-5bd10b5bccb1)
The port engineering airlock has no lights.
![image](https://github.com/user-attachments/assets/a527c751-a2ca-4442-98b2-24fcb431e46f)

The ship doesnt have much in the way of spare internals. I'd recommend putting a tank dispenser/internals crate somewhere.

5 assistant roles (crewman) is a lot. Cut it down to two.

2025-01-04 23:07 UTC, Erikafox commented
should be addressed

2025-01-12 17:41 UTC, meemofcourse approved these changes

2025-02-02 05:41 UTC, Rainrun445 commented
Could you add a crew monitor somewhere here? It would help with the large crew size command has to babysit.
![390213424-5c6dd3bb-f0cb-4de2-8323-4725fb3703ca](https://github.com/user-attachments/assets/6596a896-60dd-4805-8421-cda15f7523e3)

2025-02-19 20:02 UTC, merged