riggers
shiptest-ss13/Shiptest pull request #385
Opened 2021-10-26 07:02 UTC by Apogee-dev

## About The Pull Request

![riggerB](https://user-images.githubusercontent.com/60533805/138824401-e846b186-81bd-4900-8716-3b8c08c6f396.png)
![riggerC](https://user-images.githubusercontent.com/60533805/138824404-daa943bb-138a-42b3-adbf-ee378282d687.png)

Adds the Rigoureaux and Rigoureaux(D)-class Auxiliary Cutters.

Civilian Riggs-class sloops purchased and modified by SolGov as auxiliary vessels. They retain the versatility and most features of the basic Riggs, but come with a better-stocked armory and brig cells as well as a comfortable canteen and a dedicated SolGov Rep office.

Credit to retlaw34 for most of the work on the variants proper, I was responsible for the base Rigger map and finishing touches.

## Why It's Good For The Game

ship good

## Changelog
:cl:
add: Added Rigoureaux-class Auxiliary Cutter
add: Added Rigoureaux(D)-class Auxiliary Cutter
/:cl:

2021-10-27 14:22 UTC, AtlasRules commented
epic demod ship canonicity

2021-10-27 18:23 UTC, Bokkiewokkie requested changes

2021-10-27 18:23 UTC, Bokkiewokkie commented on _maps/shuttles/shiptest/rigger_b.dmm
> +	location = "brigcells
```suggestion
	location = "brigcells"
```
minor skill issue

2021-11-15 16:28 UTC, ZephyrTFA commented
Just gonna call this one good to go, I've not heard any complaints as of yet.

2021-11-15 16:29 UTC, merged