Updates the Paracelsus's map, and removes Long Term Patients + add Sonnensöldner
shiptest-ss13/Shiptest pull request #3866
Opened 2024-12-02 02:05 UTC by Ratvarr

## About The Pull Request
The Paracelsus currently has some awkwardness in how it's setup, and Long Term Patients don't make any sense whatsoever for a medical vessel in the frontier, nor do they even have places to BE on the ship; alongside this, bringing the ship up to speed with other major medical vessels and gives the ship a dedicated Sonnensöldner slot, and room.
Alongside this, tweaks the 'main' holofield entranceway, and adds a second entranceway on the opposite side of the ship for patients.
Gives the firearms locker a box of careless 5.56
Also fixes a locker being named "East"
![image](https://github.com/user-attachments/assets/5a87a625-b22d-4804-9c1b-4b8e2d75dd58)
![image](https://github.com/user-attachments/assets/f54cfbaf-ba8c-400d-851b-c57b2c7d1064)
![image](https://github.com/user-attachments/assets/92d06c7f-8fe5-4ecb-8c5f-672e526f1828)

## Why It's Good For The Game
Removes a role that doesn't really match with Shiptest's current 2.5-4 hour long rounds focused around Not BarRP or TraumaRP
Brings the ship more in-line with other factional medships which have a dedicated security role
Moves the Autolathe into a more reasonable location
Adds a fast-track method into the ship for medical aid instead of routing through the entire vessel to get to the treatment center.
## Changelog

:cl:
add: The Paracelsus has been remapped to accommodate a Sonnensöldner and a second entry gate, alongside other minor fixes
add: SolCon now staffs the Paracelsus with a Sonnensöldner
del: SolCon no longer sends out long-term patients to the Frontier.
/:cl:

2024-12-06 18:51 UTC, Latentish commented
God's work. I'll throw this on TMs and either tell you something blew up or merge it by the end of the day.

2024-12-06 20:54 UTC, Zevotech requested changes
![image](https://github.com/user-attachments/assets/fd95e6cf-99fc-489a-ac64-1e7450025e12)

Morgue area needs to either be a closed room again, or be made into something that isn't a strange mixture of a morgue and a front desk. Consider removing the morgue trays and surgical table entirely and converting it fully into a front desk or patient waiting area.
The floor under the table still has the decals and firelocks from where there previously was a door.

The seating area in the entry room, and really the entire room itself, should be rearranged to better serve the area as a patient-recieving entryway. Roller beds, bodybags, and possibly some cleaning supplies for when the floors inevitably become tracked with blood.

2024-12-06 21:33 UTC, Ratvarr commented
i'll get these fixed up and looked at; i wont have these ready by the second round, probably not even the third just because I'm headed out and also probably playing shiptest

2024-12-07 07:32 UTC, Ratvarr commented
![image](https://github.com/user-attachments/assets/31e57d3c-480e-49b4-9abd-a774962323e5)

2024-12-21 04:37 UTC, Geoengi commented
Could you change the doors so that they respond to the command door remote that spawns in the captain's locker?

2024-12-21 04:38 UTC, Ratvarr commented
I have no idea how those remotes even begin to work. I can... See about it..? Also, I doubt this PR will be merged until post OM5, bytheby

2024-12-21 06:09 UTC, Anticept commented
door remotes are tied to access. adding "command" access to a door will enable the remoter to work

2025-01-14 05:42 UTC, Ratvarr commented
this is being shot behind the shed because Somebody Can't Use Github Properly And Has Destroyed This Branch And Another Branch Tee Hee.

2025-01-14 05:42 UTC, closed without merging