Overmap Expansion #5
shiptest-ss13/Shiptest pull request #3868
Opened 2024-12-02 07:35 UTC by rye-rice

## About The Pull Request

I have tested this and it does function. Yes, I actually test my code. 

At long last...

![carp_sleeping 1](https://github.com/user-attachments/assets/5716ca97-d8b3-42ab-9654-37670cc1c830)

## Introduction

![om5](https://github.com/user-attachments/assets/12b65178-115c-4c55-bd6d-f160456b0a44)
### Happy  ~~Holidays~~ SPRING Shiptest!
This project initially started as yet another "add more planets, more stuff to do" PR, but as I have seen, even overmap expansion # 4 didn't really accomplish the goal of making people feel more connected to the overmap, or really making the overmap more interesting... The only interesting parts were the planets as was always the case.

So in order to do this, I have done several (Many!) things...

To keep it simple and easy to understand I have split:

<details><summary>For Players:</summary>

![om52](https://github.com/user-attachments/assets/8f2f3ea7-7c12-4a5a-b95e-ab7abd305311)
Overmap sprites have been almost completely redrawn in a nice and easy to click style

![image](https://github.com/user-attachments/assets/fe423d0b-abd7-4cd1-8a43-5a1df5df65fb)

As you might have noticed by the numbers, limited lifespan hazards. The issue with the old overmap is that it felt very static and not very "alive". This aims to fix it and add some depth, and also to keep people away from the sun.

You also might notice the asteroid field "planet" is nowhere to be seen. Well, they're actually everywhere! You just need to dock to empty space while on top of an asteroid field.

![image](https://github.com/user-attachments/assets/0b9d5981-ece1-4f6b-bb76-014d3c58b072)

What's Malachite?

![image](https://github.com/user-attachments/assets/248e7a49-b6cd-47c6-9f90-44ff00c30331)

New ores were added, along with new materials. The ore rates on some planets were jacked the fuck up to make different planets worth visiting if you need X material.

![image](https://github.com/user-attachments/assets/ce957b16-5936-4666-973e-42705e65f7e5)
![image](https://github.com/user-attachments/assets/38d9e1c1-e53c-46e2-942d-81da96b985c7)

Examining planets will allow you to see which ores are on what, alongside the "Materials and You" book that spawns on every ship now!

![greeble](https://github.com/user-attachments/assets/c5425932-d2f4-4d7e-96a8-1831ac94f4e4)

With the new greeble system, (certain) planets should have MUCH more variety

![image](https://github.com/user-attachments/assets/c1ef230c-7a17-4b40-94f0-ee29423d9fe0)

Ever ignore the overmap because it literally does not matter? Well no more! Interference is the first step in "merging" the overmap and game worlds. It's not a very complicated nor intresting system, but maybe in the future we could integrate the overmap into gameplay more

Wideband has a new sound.

![image](https://github.com/user-attachments/assets/4b3c9742-7ac6-4684-9cfb-b06d22729c9b)
Some new hazards, debris, radioactive, solar flare, and emp storms. None of these objects spawn naturally, but instead are created by the sun.
Nebulas now mess with your lights

![image](https://github.com/user-attachments/assets/5fe1039a-e781-4653-a36c-9b77d64093e1)

![image](https://github.com/user-attachments/assets/01afd187-4671-4033-9486-67f7b0b5646f)

Always felt annoyed that you couldnt choose your exact docking location, or didn't have much control over interacting with overmap objects? Well now you can! The old docking button is now "quick dock" or the red anchor, helpful!

![image](https://github.com/user-attachments/assets/078516d3-8e24-474c-af78-411b71c20838)

Some old fauna balance has been updated. In genenral, most fauna should feel less tanky for no reason, and should die in very few hits with firearms as intended. Bye bye station balance!

Plasteel is now carbon steel, being an alloy of carbon and metal instead. It just made sense.

![image](https://github.com/user-attachments/assets/37710dd2-a914-48f7-935c-8137052db157)

Most planets have their own unique ore veins and missions.

![om5lava](https://github.com/user-attachments/assets/a7f0a94e-7361-4dc6-a633-5b878218e5c6)
![om5ice](https://github.com/user-attachments/assets/531aaa2c-efd0-4c15-900b-070bab02019e)
![om5_sandplanet](https://github.com/user-attachments/assets/725ed632-b57b-4c51-a26b-9c028a551c38)

Because we have a dedicated team of spriters here, most if not all planets have gotten a makeover...

</details>

<details><summary>For Admins:</summary>

![image](https://github.com/user-attachments/assets/65910b00-dd27-482a-ad38-9083ca568350)
For my fellow eventmins, you have 2 more buildmode tools, these actually manipulate the overmap unlike BUILD_ADV before which only messed with the token
Modif Overmap works like BUILD_ADV but only for the overmap, while (//) --> Overmap moves overmap objects, like the move tool

![image](https://github.com/user-attachments/assets/ca824100-248e-4b9f-bbeb-0557a4b55e69)

There's now a few new VV options of commonly used variables, such as `parent` and an option to fix overmap objects if they are truly and well fucked.

![om5_multiovermap](https://github.com/user-attachments/assets/e380bfe1-5ec4-43a2-bb99-48fab1a2ddaf)

As a side effect of making overmap code more modular, you can now spawn in mutiple overmaps with the `Spawn-Overmap` verb. This isn't exactly intuitive, so I would experiment for a bit

![awful](https://github.com/user-attachments/assets/2ac67248-30a8-48e1-9ee6-e5cbc66e0818)

To make your overmaps really be set apart, you can now set the overmap colors of overmaps to whatever clown vomit you want! There's some preset palettes for experimenting with. if you dare.

![image](https://github.com/user-attachments/assets/fd9001d9-b110-4ca2-9b86-c02e513a3a0f)
`Map-Template---Upload` Now has a better UI, and allows you to spawn in your map as a static object, great for eventmins! In addition, `Map-template---Place` asks you if you want to align your maps to the bottom left corner where your ghost is!

![image](https://github.com/user-attachments/assets/312f8b2f-c99e-4eb6-b941-5b36dbf0683d)

Static overmap objects are a bit like gateways, as in they are completely pre-mapped planets, with little or no dynamic generation going on. This may be useful to eventmins, although it was made for the maptainers.

![image](https://github.com/user-attachments/assets/54da139a-cad7-44fe-b6c1-9263c6127045)

You got a few new planets to play with. Some shouldn't appear naturally, so go wild.

</details>

<details><summary>For Coders:</summary>

![om5_multiovermap](https://github.com/user-attachments/assets/e380bfe1-5ec4-43a2-bb99-48fab1a2ddaf)
In order to get some things to work, this splits the overmap off from SSovermap (`/datum/overmap_star_system/`). This techinically allows for mutiple overmaps, but the main purpose was to make the code more modular. I found this much easier to work with than having to go look at SSovermap constantly.

![image](https://github.com/user-attachments/assets/6198de23-76a6-4226-ad9c-a1a0baaeeda2)

Punchcards (`/obj/item/overmap_punchcard_spawner`)  are an object that lets you spawn any overmap object you want, including but not limited to dynamic planets (used in missions) or a premapped planet (Static overmap datums). Maptainers requested this long ago, and only barely got around to it

![image](https://github.com/user-attachments/assets/56b647dc-f843-4a0d-a992-78e6dc7e04e5)
Planets now have more variety with greebles, essentially, these are premapped "miniruins"  spawned to make certain planets feel more alive. These avoid loading over ships or in walls. To make one, make a `/obj/effect/greeble_spawner` subtype with an ` /datum/map_template/greeble subtype, as seen here:
 
```js
/obj/effect/greeble_spawner
	name = "planet greeble spawner"
	template = /datum/map_template/greeble
```

![image](https://github.com/user-attachments/assets/b5cf0012-8081-472b-a325-f1940fe56b14)
There are now mutiple sprites for overmap ships! By default it's the second one in that screenshot. You can edit it in th [...]

2024-12-06 22:29 UTC, Erikafox commented
outposts should only spawn outside of the hazard spawn range for stars.

2024-12-06 22:38 UTC, generalthrax commented
Small thing but I had mixed feelings on the materials. I know materials outside of metal, glass, plasma, and uranium were practically useless, but this might be inflating them a little bit. Carbon Steel replacing Plasteel as a much smaller, tinier thing, as I personally think it kind of detracts from the value of plasteel and kind of incentivizes everyone to take to fully mining instead of alternate routes like shipbreaking for fuel.

2024-12-06 23:02 UTC, tantspants commented
For some reason this update broke pointing-to-inhand-items.  The thought bubble is just gone, and the icon of the item itself is also invisible unless it is in a wall tile for some reason.
![Screenshot 2024-12-06 175858](https://github.com/user-attachments/assets/9f7cf3dd-bfa5-4be5-9155-03f857abd9e0)

2024-12-06 23:04 UTC, tantspants commented
also, this update is amazing, but the new mud sound effects are kind of irritating. Something about the squishing sound makes me really uncomfortable.

2024-12-07 00:18 UTC, thearbiber commented
Will say, every planet having miles of tiles that slow down your movement doesn't feel great.

2024-12-07 00:18 UTC, Erikafox commented
tile slowdown is probably getting killed somewhat in planetary tiles (probably around sunday)

2024-12-07 00:20 UTC, Erikafox commented
cragoney health and max health do not match

2024-12-07 21:01 UTC, Erikafox commented
the outpost should be immune to comms interference.

2024-12-07 21:24 UTC, Ratvarr commented
Desert planet: Very good, but the air burns the lungs of srothy+eluouze, forcing them to wear internals. Would be cool to have it not burn their lungs
I really love the ambience of them.
The antlions need to have their death sprite applied after they die instead of when they are pulled south after death.

2024-12-14 02:25 UTC, FalloutFalcon requested changes
![image](https://github.com/user-attachments/assets/02e4cf74-f28e-4c87-80c6-f7012046cbf8)
first review. not even kinda done..
this is very unatomic please dont make one of these again.

2024-12-14 02:25 UTC, FalloutFalcon commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +	shell_damage(max(P.force, MAX_BULLET_SHELL_DAMAGE))
```suggestion
	shell_damage(min(P.force, MAX_BULLET_SHELL_DAMAGE))
```

2024-12-14 02:25 UTC, FalloutFalcon commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
> +				return
you shouldnt even be running this proc if it has a client.

2024-12-14 02:25 UTC, FalloutFalcon commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
> +		return
Why?

2024-12-14 02:25 UTC, FalloutFalcon commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
> +		turf_to_flame.IgniteTurf(power, fire_color)
Could be in a better spot (probally mob helpers) or not global

2024-12-14 02:25 UTC, FalloutFalcon commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/ice_demon.dm
> -	health = 80
Reasoning?

2024-12-14 02:25 UTC, FalloutFalcon commented on code/modules/overmap/_overmap_datum.dm
> +	VV_DROPDOWN_OPTION(VV_HK_UNFSCK_OBJECT, "Unfsck this overmap object | PANIC BUTTON")
unfsck? unfuck? this should probally just be "fix"

2024-12-14 02:25 UTC, FalloutFalcon commented on code/modules/surgery/organs/lungs.dm
> +			H.reagents.add_reagent(/datum/reagent/carbon_monoxide, 2)
Reasoning?

2024-12-14 02:25 UTC, FalloutFalcon commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/antlion.dm
I would recommend using an effect where they are still visible while burrowed.

2024-12-14 02:25 UTC, FalloutFalcon commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/antlion.dm
> +	AIStatus = AI_ON
```suggestion
	toggle_ai(AI_ON)
```

2024-12-14 02:25 UTC, FalloutFalcon commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/antlion.dm
> +	AIStatus = AI_OFF
```suggestion
	toggle_ai(AI_OFF)
```

2024-12-14 02:25 UTC, FalloutFalcon commented on code/datums/diseases/advance/presets.dm
> +	name = BIOME_COLD
bad regex..
```suggestion
	name = "Cold"
```

2024-12-14 02:54 UTC, Erikafox commented
I think legally speaking we need to not use the ftl sfx for storms and stuff.

2024-12-20 21:17 UTC, Erikafox commented on code/modules/overmap/objects/jump_point.dm
> +/datum/overmap/jump_point/proc/link_points(other_point)
this really needs better feedback for admin usage. It shouldn't be a pain in the ass to create jump points and link them.

2024-12-20 21:19 UTC, Erikafox commented on code/modules/overmap/objects/jump_point.dm
> +/datum/overmap/jump_point
interacting with one as a ghost should move you to the linked point

2024-12-21 02:39 UTC, Erikafox commented on code/game/machinery/cryopod.dm
> -/obj/machinery/cryopod/apply_effects_to_mob(mob/living/carbon/sleepyhead)
This should be in the cl or removed.

2024-12-22 19:28 UTC, Erikafox commented
stars should be POIs for ghosts to make transitioning between overmaps smoother

2024-12-28 21:15 UTC, Erikafox commented
![image](https://github.com/user-attachments/assets/0e4efdcc-dee9-4745-a6dc-58437ae429ec)
the sidings here are big enough to make it impossible to click on some tiles. that's way too big.

2024-12-28 21:24 UTC, Erikafox commented
![image](https://github.com/user-attachments/assets/4db0c254-a97a-4351-b0d8-cc01e037171e)
still having issues with greebles loading after planetload. the screencap *was* of a greeblespawner just floating but then it loaded.

2024-12-28 21:50 UTC, Erikafox commented
![image](https://github.com/user-attachments/assets/9da35940-04b8-45bf-ad5f-c27731e98921)

objects of interest should not be spawning in lava.

2024-12-28 22:16 UTC, Erikafox commented
![dreamseeker_xbBwFVUk53](https://github.com/user-attachments/assets/f57e3094-3919-49e4-9baa-0f30743ffd09)

tile overlays: this fucking sucks

2024-12-29 02:39 UTC, Erikafox commented
![image](https://github.com/user-attachments/assets/434c0e2f-e93b-4006-8560-eb907bd0bba5)
the forests aren't fun when they're like this

2024-12-29 02:42 UTC, Erikafox commented
every single tile in this area of gen has a tree dare i venture this is the opposite of fun

2024-12-29 05:38 UTC, Erikafox commented
> ![image](https://private-user-images.githubusercontent.com/94164348/399116895-0e4efdcc-dee9-4745-a6dc-58437ae429ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MjEzMzEsIm5iZiI6MTczNTQyMTAzMSwicGF0aCI6Ii85NDE2NDM0OC8zOTkxMTY4OTUtMGU0ZWZkY2MtZGVlOS00NzQ1LWE2ZGMtNTg0MzdhZTQyOWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDIxMjM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNjY3NzM0NjliYzFiYTYyNjBkY2Q0NDQ2YjA2OTAxYWNlZjVkMjNkNzJhNTA2N2RlYTM1ZjY1OGM0YjJjMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1xKJQAadqOTsNEVUEApDrY7Rym1mUaiKae6pqzrleKQ) the sidings here are big enough to make it impossible to click on some tiles. that's way too big.

![image](https://github.com/user-attachments/assets/12d68dc9-3b3d-417d-a939-ce46b85031ea)
Better example

2025-01-03 21:25 UTC, Erikafox commented
![image](https://github.com/user-attachments/assets/952ad79c-937e-4d5e-9c94-1d19da72d05d)

2025-01-03 21:42 UTC, Erikafox commented
![image](https://github.com/user-attachments/assets/9f639f1c-1b1e-477a-8e31-4d0d11894b16)
old sidings should be removed.

Personally, I would prefer if the tiles didn't overlay onto 'artifical' tiles unless mapped. Maybe use a flag for that. Then put in some of the new edges as a replacement for the old sidings.

2025-01-03 23:36 UTC, FalloutFalcon commented
![image](https://github.com/user-attachments/assets/cf665c71-f78f-474c-b491-06c0ed368a27) 
![image](https://github.com/user-attachments/assets/8a91eee5-2ee2-46f9-9273-c63e21c6d423)

this color does not seem to match with the current flora and makes them all kinda pop-out weirdly

2025-03-12 17:39 UTC, Erikafox commented on _maps/configs/independent_dwayne.json
> +	"tranist_x_offset": -5,
transit?

2025-03-12 17:39 UTC, Erikafox commented on code/__DEFINES/colors.dm
> +#define COLOR_FOGGY_LIGHT "#849abf"
```suggestion
#define COLOR_BATTLEFIELD_PLANET_LIGHT "#849abf"
```

2025-03-12 17:39 UTC, Erikafox commented on code/game/turfs/open/floor/plating/desert.dm
> +	light_color = "#ffd2bd"
make desert lighting a define like other planetary lighting colors

2025-03-12 22:50 UTC, FalloutFalcon commented
/turf/open/floor/grass/ship/jungle seems fucked
![image](https://github.com/user-attachments/assets/c2d822f0-c973-4d45-a177-4b93025164cf)

2025-03-12 23:06 UTC, FalloutFalcon commented on _maps/configs/independent_dwayne.json
> +	"tranist_x_offset": -5,
it seems like its another style of dock? why is not being handled the same way we do our other docks

2025-03-12 23:16 UTC, FalloutFalcon commented
I dont see the reason to have quartz as a precuser material for glass when functionally glass is just quartz and you can just treat the material as such. If you want to rename the glass material to quartz that's fine i just don't see the reason to have it.

2025-03-12 23:46 UTC, FalloutFalcon requested changes

2025-03-12 23:46 UTC, FalloutFalcon commented on code/controllers/subsystem/mapping.dm
> +	var/list/greeble_templates = list() //TB EDIT MARKER
what part of this is meant to be edited?

2025-03-12 23:46 UTC, FalloutFalcon commented on code/modules/overmap/transponder.dm
> +/*
Need to outline how or why this is diffrent from the 8 other ways to talk to ships. Im fine with a deticated machine this just needs to be properly outlined.

2025-03-12 23:46 UTC, FalloutFalcon commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	name = "carbon steel"
why are we reflavoring plasteel to carbon steel.

2025-03-12 23:46 UTC, FalloutFalcon commented on code/game/machinery/shieldgen.dm
> +		playsound(src, 'sound/machines/synth_no.ogg', 100, TRUE, frequency = 6120)
Has anyone found this to be too quite?

2025-03-12 23:46 UTC, FalloutFalcon commented on code/datums/diseases/cold9.dm
> +			affected_mob.adjust_bodytemperature(-3)
why

2025-03-12 23:46 UTC, FalloutFalcon commented on code/datums/diseases/fluspanish.dm
> +			affected_mob.adjust_bodytemperature(5)
why

2025-03-12 23:46 UTC, FalloutFalcon commented on code/datums/diseases/fluspanish.dm
> +			affected_mob.adjust_bodytemperature(10)
why

2025-03-12 23:46 UTC, FalloutFalcon commented on code/__DEFINES/dcs/signals/signals.dm
> +#define COMSIG_OVERMAP_MOVE_SELF "overmap_move_self"
you dont use a new singal for this. You register to COMSIG_OVERMAP_MOVED

2025-03-13 00:12 UTC, FalloutFalcon commented
I also dont see to reason to rename most of the ores, extra so for the ooc/backend stuff.

2025-03-13 00:16 UTC, FalloutFalcon commented
Not required but i still think the pr desperately needs it.

2025-03-13 01:29 UTC, FalloutFalcon commented
shoudlnt be saying saying solar flare twice 
![image](https://github.com/user-attachments/assets/5a44e17d-df9f-4eaa-b302-6fdfe877e72d)

2025-03-13 02:29 UTC, FalloutFalcon commented
interference makes alot of radio messages appear in chat and runetext twice.

2025-03-13 03:22 UTC, FalloutFalcon commented
Heard reports that you nerfed the ore amount from 1 sheet to half?

2025-03-13 18:19 UTC, Ratvarr commented
> interference makes alot of radio messages appear in chat and runetext twice.

this might have been because of me because on the Cataclysm I setup every intercom to a private frequency and never shut the microphones off so it would have been audible to ghosts.
we went to a few places for long periods of time with extreme interference so it might have simply been overtly noticeable

2025-03-15 21:11 UTC, rivercadaver commented
Interference is imo really overtuned and unfun to play with. Radio being essentially unusable even when you're a single tile away is annoying, and trying to wideband to just be greeted with *#(#*@ #@(($@( )!()@)! is infuriating. If you don't have a PDA group, you're essentially unable to communicate with anyone else on most planets (holopads get jammed too), and it's totally hell for any sort of long-range coordination. Plus, no more fun wideband arguments.

2025-03-15 21:27 UTC, rivercadaver commented
> Interference is imo really overtuned and unfun to play with. Radio being essentially unusable even when you're a single tile away is annoying, and trying to wideband to just be greeted with _#(#_@ #@(($@( )!()@)! is infuriating. If you don't have a PDA group, you're essentially unable to communicate with anyone else on most planets (holopads get jammed too), and it's totally hell for any sort of long-range coordination. Plus, no more fun wideband arguments.

smiles. god forbid you want to holocall someone while you're in space either, because electromagnetic interference will kick you off after two seconds. Gameplay.

2025-03-19 05:42 UTC, rye-rice commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
> +				return
Not an issue.

2025-03-19 05:42 UTC, rye-rice commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
> +		return
Not an issue.

2025-03-19 05:42 UTC, rye-rice commented on code/modules/overmap/_overmap_datum.dm
> +	VV_DROPDOWN_OPTION(VV_HK_UNFSCK_OBJECT, "Unfsck this overmap object | PANIC BUTTON")
Not an issue.

2025-03-19 05:42 UTC, rye-rice commented on code/modules/overmap/objects/jump_point.dm
> +/datum/overmap/jump_point/proc/link_points(other_point)
Agreed. If I remember to

2025-03-19 05:42 UTC, rye-rice commented on code/modules/overmap/objects/jump_point.dm
> +/datum/overmap/jump_point
Agreed

2025-03-19 05:43 UTC, rye-rice commented on code/modules/overmap/transponder.dm
> +/*
Not an issue.

2025-03-19 05:43 UTC, rye-rice commented on code/game/machinery/shieldgen.dm
> +		playsound(src, 'sound/machines/synth_no.ogg', 100, TRUE, frequency = 6120)
Not an issue.

2025-03-19 05:43 UTC, rye-rice commented on code/datums/diseases/fluspanish.dm
> +			affected_mob.adjust_bodytemperature(5)
Not an issue.

2025-03-19 05:43 UTC, rye-rice commented on code/__DEFINES/dcs/signals/signals.dm
> +#define COMSIG_OVERMAP_MOVE_SELF "overmap_move_self"
Not an issue.

2025-03-19 05:54 UTC, FalloutFalcon commented on code/__DEFINES/dcs/signals/signals.dm
> +#define COMSIG_OVERMAP_MOVE_SELF "overmap_move_self"
Its not going to break anything but its also doing the same thing as COMSIG_OVEMRAP_MOVED, you should use that please.

2025-03-19 06:45 UTC, rye-rice commented on code/__DEFINES/dcs/signals/signals.dm
> +#define COMSIG_OVERMAP_MOVE_SELF "overmap_move_self"
I tried. It didnt work.

2025-03-19 17:43 UTC, FalloutFalcon commented
more bad grass 
![image](https://github.com/user-attachments/assets/6b38930b-7946-41ac-aa75-1d2470727b75)

2025-03-19 18:54 UTC, FalloutFalcon commented
![image](https://github.com/user-attachments/assets/e7a7b288-b9e3-4c99-8568-ba727d012c5f)

2025-03-21 08:30 UTC, FalloutFalcon commented on code/__DEFINES/dcs/signals/signals_overmap.dm
> +// /datum/overmap signals
```suggestion
```

2025-03-21 08:52 UTC, FalloutFalcon requested changes

2025-03-21 08:52 UTC, FalloutFalcon commented on code/modules/mining/ore_veins.dm
> -/obj/structure/vein/ice/classfour
accidental removal

2025-03-21 08:52 UTC, FalloutFalcon commented on code/modules/missions/dynamic/signaled.dm
> +		return
should prevent the ruin mission for these from breaking
```suggestion
	if(orevein_wanted && !istype(our_vein, orevein_wanted))
		say("Error: Incorrect class of planetiod for operation.")
		return
```

2025-03-21 08:52 UTC, FalloutFalcon commented on code/modules/overmap/_overmap_datum.dm
> +		position = current_overmap.get_unused_overmap_square(force = TRUE)
Had this pop up while running in the background during review. It does this forever lol.
"Exception has occurred: Cannot execute null.get unused overmap square()."

2025-03-21 08:52 UTC, FalloutFalcon commented on code/controllers/subsystem/overmap.dm
> + * Not sure what this does. Called everytime SSOvermap fires and overmap has mission_system_enabled enabled.
This is tangentily related to dynmaic missions, its doing the same despawn thing you added for overmap events. Its meant to cycle out planets very slowly.

2025-03-21 08:52 UTC, FalloutFalcon commented on code/modules/overmap/objects/dynamic_datum.dm
> +	current_overmap.replace_dynamic_datum()
let it die..... (Handle it with a subsystem like i already was doing so you can adjust the cap on the fly and have it acctually populate)

2025-03-21 09:05 UTC, FalloutFalcon commented on code/controllers/subsystem/overmap.dm
> +		new /datum/overmap/dynamic(system_spawned_in = src)
i removed these. see https://github.com/shiptest-ss13/Shiptest/pull/4214

2025-03-21 09:07 UTC, FalloutFalcon commented on code/controllers/subsystem/overmap.dm
> +		spawn_ruin_level()
Need to move this onto the systems

2025-03-21 09:08 UTC, FalloutFalcon commented on code/controllers/subsystem/overmap.dm
> +	var/mission_system_enabled = FALSE
Does not prevent missions from spawning.

2025-03-21 18:13 UTC, FalloutFalcon commented
Dynamic missions either need to display there sector in tgui or you need to refactor the mission behavoir to pull the sectors missions instead and prevent random sectors from eating all the mission limits.

2025-03-21 19:43 UTC, FalloutFalcon commented on code/__DEFINES/dcs/signals/signals.dm
> +#define COMSIG_OVERMAP_MOVE_SELF "overmap_move_self"
I fixed it myself in https://github.com/rye-rice/Shiptest/pull/12

2025-03-21 20:42 UTC, FalloutFalcon commented
still fucked 
![image](https://github.com/user-attachments/assets/795980d8-31d9-483f-bc1a-5308232c2341)

2025-03-23 00:21 UTC, FalloutFalcon commented
Still need to fix pointing to things sprite

2025-03-23 02:00 UTC, thgvr commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +	armor = list("melee" = 65, "bullet" = 75, "laser" = 45, "energy" = 20, "bomb" = 50, "bio" = 30, "rad" = 30, "fire" = 30, "acid" = 30)
Way too much. I'd just make them goliath reskins honestly or make them work like basilisks. They're literally immune to most types of guns.

2025-03-23 02:01 UTC, thgvr commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +	armor = list("melee" = 60, "bullet" = 95, "laser" = 55, "energy" = 30, "bomb" = 60, "bio" = 30, "rad" = 50, "fire" = 30, "acid" = 50)
same as previous comment, this is absurd

2025-03-23 02:05 UTC, thgvr commented
I'm gonna be real. Here's what'll need to happen to merge this:
* Address the rest of Fallcon's reviews
* Fix the pointing bubble icon 
* Fix the shipgrass and adjacent turfs that need pixel x/y shifted
* Fix smoothing groups for plating,floortiles,lava with the new tiles.
* Whatever checks are still failing

I'll give everything a once-over and then I'd like to just get this out of the way. If something's broken, we'll fix it, same for any of the balance.

2025-03-27 00:28 UTC, rye-rice commented on code/__DEFINES/colors.dm
> +#define COLOR_FOGGY_LIGHT "#849abf"
I do want to generalize it in case a mapper wants to use it for their punchcard

2025-03-27 04:37 UTC, rye-rice commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +	armor = list("melee" = 65, "bullet" = 75, "laser" = 45, "energy" = 20, "bomb" = 50, "bio" = 30, "rad" = 30, "fire" = 30, "acid" = 30)
reduced by like 45%

2025-03-27 04:37 UTC, rye-rice commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +	armor = list("melee" = 60, "bullet" = 95, "laser" = 55, "energy" = 30, "bomb" = 60, "bio" = 30, "rad" = 50, "fire" = 30, "acid" = 50)
ditto

2025-03-27 04:51 UTC, rye-rice commented on code/controllers/subsystem/overmap.dm
> + * Not sure what this does. Called everytime SSOvermap fires and overmap has mission_system_enabled enabled.
Fixed the comment

2025-03-27 04:52 UTC, rye-rice commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
> +		turf_to_flame.IgniteTurf(power, fire_color)
Thrown in unsorted.dm

2025-03-27 04:56 UTC, rye-rice commented on code/__DEFINES/dcs/signals/signals_overmap.dm
> +// /datum/overmap signals
done

2025-03-27 04:58 UTC, rye-rice commented on code/__DEFINES/colors.dm
> +#define COLOR_FOGGY_LIGHT "#849abf"
Or admin uses it for an event

2025-03-29 18:49 UTC, SomeguyManperson commented on code/modules/overmap/objects/event_datum.dm
> +	max_damage = 1000
These usually won't do anything afaik since telsa zaps stop once their power is less than 1000

2025-03-29 18:49 UTC, SomeguyManperson commented on code/modules/power/tesla/energy_ball.dm
> +	var/static/things_to_shock = typecacheof(list(/obj/machinery, /turf/closed/wall, /obj/structure, /obj/vehicle/ridden))
This makes it remarkably safer to approach tesla anomalies, and to go through electrical storms that don't explode, since they can't hurt people
Also I don't think there's any behavior for shocking walls, in testing arcs don't seem to target them even if there's nothing else nearby

2025-04-02 23:59 UTC, FalloutFalcon commented
why do you have [IDB IGNORE] [MDB IGNORE] on

2025-04-03 01:28 UTC, generalthrax commented
im not sure if this changed any since april fools but Something seems to be fucking up outpost docking ports

2025-04-04 22:31 UTC, FalloutFalcon commented
"del: Removes cryosickness" ....

2025-04-05 21:11 UTC, thgvr commented
> > del: Removes cryosickness
> 
> if thats gonna be in the pr can i alteast get a reason.

as the person who added it I don't think it actually adds a lot to the experience in the end, after having it for a while now

2025-04-10 06:44 UTC, FalloutFalcon commented on code/__DEFINES/layers.dm
> +#define SNOW_TURF_LAYER 2.4551 //snow should be 2.029, set to 2.4551 for testing
```suggestion
#define SNOW_TURF_LAYER 2.029 //snow
```

2025-04-10 06:44 UTC, FalloutFalcon commented on code/__DEFINES/layers.dm
> +#define SNOW_TURF_LAYER 2.4551 //snow should be 2.029, set to 2.4551 for testing
idk if your still testing it but to make sure its not forgotten

2025-04-10 07:47 UTC, FalloutFalcon approved these changes
God.. I'm never reviewing something this big again. I will just close it.
![image](https://github.com/user-attachments/assets/e731dba7-18e6-44ec-93f2-da8116dd60ad)

Regardless. Nothing here is "required" (Excpet changelog requests) alot of it is recommended, but at this point, it should be done in a seperate pr. Im tired of this PR and I am just gonna do some of it myself once its merged. Anything that is an open question, please just ping me about at some point if your not going to answer it in this pr..
Also you reverted or added a ton of spans (not defined)

2025-04-10 07:47 UTC, FalloutFalcon commented on code/__HELPERS/priority_announce.dm
> -		message = "A distress beacon has been activated from [location.name] at local sector co-ordinates [location.x]/[location.y]. No further information available."
Did you move creating distress beacons from other locations to else where?

2025-04-10 07:47 UTC, FalloutFalcon commented on code/datums/looping_sounds/weather.dm
> +	mid_length = 10.03 SECONDS // The lengths for the files vary, but the longest is ten seconds, so this will make it sound like intermittent wind.
notes to self. This can be done programmatically now.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/__DEFINES/dcs/signals/signals_overmap.dm
> +#define COMSIG_OVERMAP_MOVE_SYSTEMS "overmap_moved_systems"
Still think this is redudent but will just make a separate pr after this is merged to remove it! If it really does break like you said it does we can test merge my pr and find out.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/datums/mapgen/greeble.dm
> +/obj/effect/spawner/random/greeble/random_ruin_greeble
will need to be repathed to reflect its moon based contents, fine for this pr.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/datums/mapgen/planetary/SandGenerator.dm
> +			BIOME_LOW_HUMIDITY =/datum/biome/sand/grass/dead,
```suggestion
			BIOME_LOW_HUMIDITY = /datum/biome/sand/grass/dead,
```

2025-04-10 07:47 UTC, FalloutFalcon commented on code/datums/mapgen/planetary/SandGenerator.dm
> +			BIOME_LOWEST_HUMIDITY =/datum/biome/sand/sulfur_plains,
```suggestion
			BIOME_LOWEST_HUMIDITY = /datum/biome/sand/sulfur_plains,
```

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/machinery/computer/communications.dm
> +	deadchat_broadcast(" made a priority announcement from <span class='name'>[get_area_name(usr, TRUE)]</span>: [input].", "<span class='name'>[user.real_name]</span>", user, message_type=DEADCHAT_ANNO
```suggestion
	deadchat_broadcast(" made a priority announcement from [span_name("[get_area_name(usr, TRUE)]")]: [input].", span_name("[user.real_name]"), user, message_type=DEADCHAT_ANNOUNCEMENT)
```

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/machinery/_machinery.dm
> +		explosion(src, 0, 1, 2, flame_range = 2, adminlog = FALSE, smoke = FALSE)
Add to changelog.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/machinery/cryopod.dm
> +	to_chat(sleepyhead, "<span class='boldnotice'>You begin to wake from cryosleep...</span>")
reversion of span define removal
```suggestion
	to_chat(sleepyhead, span_boldnotice("You begin to wake from cryosleep..."))
```

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/objects/items/stacks/sheets/mineral.dm
> +
All of this should probally be above the weird(i made it) fancy hidden material. not required for this pr.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	singular_name = "carbon steel"
Still very much not a fan of this, some sort of revert pr is probally in order after om5 unless im convinced otherwise..

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/objects/obj_defense.dm
> +			take_damage(rand(220, 330), BRUTE, "bomb", 0)
It should alteast do more then that, thats not even enough to break most mechs. Does not have to be infinity but should be close to quaruple digets, also document in cl these major nerfs to ex_act

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/turfs/closed/_closed.dm
> +			alter_integrity(rand(-100, -200))
More undocumented nerfs to ex_act. Please give me a reason for this at some point.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/turfs/open/floor/plating/icemoon.dm
> +	if(smoothing_flags)
This really should not be happening twice, need a var for it.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/turfs/open/floor/plating/whitesands.dm
> +	add_overlay("sandalt_[rand(6,9)]")
seeing this copy pasted in about 19 diffrent spots in the folder, needs to be moved to a var alt_state and range var or something.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/turfs/open/acid.dm
> +			object_to_melt.acid_act(10, 1)
second nerf ive seen to acid_act, document in CL

2025-04-10 07:47 UTC, FalloutFalcon commented on code/game/turfs/open/chasm.dm
> +	. += "<span class='warning'>You WILL fucking die if you step on this!!!</span>"
could also really use a better message but whatever. Should place more importance on the inability to come back.
```suggestion
	. += span_warning("You WILL fucking die if you step on this!!!")
```

2025-04-10 07:47 UTC, FalloutFalcon commented on code/modules/admin/verbs/map_template_loadverb.dm
> +			message_admins("<span class='adminnotice'>[key_name_admin(src)] has placed a map template ([template.name]) at [ADMIN_COORDJMP(T)]</span>")
```suggestion
			message_admins(span_adminnotice("[key_name_admin(src)] has placed a map template ([template.name]) at [ADMIN_COORDJMP(T)]"))
```

2025-04-10 07:47 UTC, FalloutFalcon commented on code/modules/admin/verbs/map_template_loadverb.dm
> +		to_chat(src, "<span class='warning'>Map template '[map]' failed to parse properly.</span>", confidential = TRUE)
```suggestion
		to_chat(src, span_warning("Map template '[map]' failed to parse properly."), confidential = TRUE)
```

2025-04-10 07:47 UTC, FalloutFalcon commented on code/modules/atmospherics/auxgm/gas_types.dm
> +	fusion_power = 0
What is this here for?

2025-04-10 07:47 UTC, FalloutFalcon commented on code/modules/missions/dynamic/signaled.dm
> +	mission_class = 3
should be class 4. Its specificly meant to be specific to ruins and harder then the normal onces.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/modules/mob/mob_helpers.dm
> +	if(!chance)
Should really be a seperate chance then the one for acctualy randomizing the characters.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/controllers/subsystem/overmap.dm
> +/datum/overmap_star_system/proc/handle_dynamic_missions()
Still has nothing to do with dynamic missions.

2025-04-10 07:47 UTC, FalloutFalcon commented on code/controllers/subsystem/overmap.dm
> +/datum/overmap_star_system
Move to a seperate file.

2025-04-14 01:34 UTC, FalloutFalcon commented
I am going to be merging this pr tonight if no objections. Its massively obstructive to development and needs to merged so we can start test merging other prs again. There is 1 outgoing bug with docking ports and unaddressed reviews but all of them will need to be done in another pr. If you don't get it in the next few hours rye i will just update the CL myself.

2025-04-14 03:16 UTC, FalloutFalcon commented
that was all just the span marcos from my review

2025-04-14 03:57 UTC, FalloutFalcon commented
just gonna force it through and fix the hard del in a bit.

2025-04-14 04:09 UTC, merged