Faction Cargo: Armor
shiptest-ss13/Shiptest pull request #3887
Opened 2024-12-06 05:40 UTC by Erikafox

## About The Pull Request
Adds a bunch of the stupid armor variations and not stupid hardsuits to cargo for factions to buy.

Removes a bunch of armor cruft like wizard hardsuits. or chronosuits. yeah. chronosuits. those are really in the vogue now.

Adjusts some values on armor / spacesuits to make them a little more unique.

## Why It's Good For The Game
buy faction gear good yes yes?

## Changelog

:cl:
add: You can now purchase most faction's special armor at the outpost.
del: a bunch of wizard bullshit, and also chrono troopers from red alert 2
code: spacesuit_armor has been split into 2 files
/:cl:

2024-12-06 05:45 UTC, DIB-DOG commented on code/modules/cargo/packs/spacesuits.dm
> +	desc = "Contains one Tortoise Microlite Armored Suit, the pride and joy of many Solarian explorers."
Hi, PGFoid here. The "fucking gezena" Rakalla Crate shares the same description with the "solgov" Solarian Vacsuit Crate. Assuming that's not intentional.

2024-12-06 05:45 UTC, Erikafox commented on code/modules/cargo/packs/spacesuits.dm
> +	desc = "Contains one Tortoise Microlite Armored Suit, the pride and joy of many Solarian explorers."
whoops

2024-12-06 05:47 UTC, Erikafox commented on code/modules/cargo/packs/spacesuits.dm
> +	desc = "Contains one Tortoise Microlite Armored Suit, the pride and joy of many Solarian explorers."
fixed

2024-12-06 18:18 UTC, Sadhorizon commented on code/modules/cargo/packs/armor.dm
> +	name = "Hardliner Crate"
Filled with your very own Hardliners
(should probably say _Hardliner **Armor** Crate_)

2024-12-06 18:21 UTC, Sadhorizon commented on code/modules/cargo/packs/spacesuits.dm
> +/datum/supply_pack/spacesuits/spacesuit/solgov
this is still broken, should say /gezena or whatever

2024-12-06 18:23 UTC, Sadhorizon commented on code/modules/cargo/packs/spacesuits.dm
> +/datum/supply_pack/spacesuits/spacesuit/solgov
copypasting issues also on NGR and Roumain

2024-12-06 19:44 UTC, Erikafox commented
fixed those and a few others.

2024-12-06 20:20 UTC, Apogee-dev commented
The cargo changes are good but the stat changes should be in a separate PR so they don’t get everything else in this PR hung up on them.

2024-12-06 20:53 UTC, Erikafox commented
i'd agree but i did some flavor changes for this stuff too, so it's bundled together somewhat neatly.

2024-12-07 00:00 UTC, Apogee-dev commented
Alright well, most of the armor changes are pretty minimal but I’ve got major objections to the sec hardsuit change. It _really_ should not be better than or equivalent to a normal armor vest, especially since it comes with limb protection.

2024-12-12 05:15 UTC, MarkSuckerberg requested changes

2024-12-12 05:15 UTC, MarkSuckerberg commented on code/modules/cargo/packs/spacesuits.dm
> +/datum/supply_pack/spacesuits/spacesuit/binteq
```suggestion
/datum/supply_pack/spacesuits/spacesuit/inteq
```
you can have jardliners but you can't have binteq

2024-12-12 05:15 UTC, MarkSuckerberg commented on code/modules/clothing/spacesuits/hardsuit.dm
> +
```suggestion
```
c'moooon not too much or it spoils the funny

2024-12-12 05:21 UTC, MarkSuckerberg approved these changes
any price rebalances can be done later tbh

2025-01-17 21:18 UTC, merged