Arke-Class Surveying Ship | CLIP-LAND
shiptest-ss13/Shiptest pull request #3910
Opened 2024-12-16 02:23 UTC by Ical92

## About The Pull Request
Adds a new specialist ship to CLIP's roster, a small CLIP-LAND ship for surveying planets and relaying information to friendly ships. Has a telecommunications setup and basic equipment, as well as a small armory for two CMM Reservists. 

![image](https://github.com/user-attachments/assets/2b238a54-4676-4c41-ab54-f1c1c38a2235)

<details><summary>SDMM Screenshots</summary>
<p>

![image](https://github.com/user-attachments/assets/ec7b6741-3251-4735-8bef-bf65f192e272)

![image](https://github.com/user-attachments/assets/93b98b72-f950-4b5a-aa6b-ce14718bc2c2)

</p>
</details> 

<details><summary>More In-Game Screenshots</summary>
<p>

![image](https://github.com/user-attachments/assets/40f07bc2-077e-49c7-b602-98ddfda782c4)
![image](https://github.com/user-attachments/assets/14fc04bf-86b3-497e-b17e-4eb557450edb)
![image](https://github.com/user-attachments/assets/2f6c81cd-cfad-4c45-8eff-6d99761122b5)
![image](https://github.com/user-attachments/assets/2be483e7-a005-497e-82ab-e0e8dad864cf)

</p>
</details> 

## Why It's Good For The Game
Adds a new small-crew ship and a new ship for CLIP that isn't part of CMM. Gives telecommunications access to CLIP ships without the need for a larger command ship.

## Changelog

:cl:
add: Arke-Class Surveying Ship
/:cl:

2024-12-20 02:04 UTC, meemofcourse requested changes
![imagen](https://github.com/user-attachments/assets/4882c039-f350-447e-bb70-8043cf9c7412)

change the wooden table, i dont think it fits

![imagen](https://github.com/user-attachments/assets/c4a0ad88-c422-45a5-af8f-6b634d4da7d8)

i would prefer if the toolboxes were on a table, or a shelf

2025-01-04 18:32 UTC, meemofcourse approved these changes
yea

2025-01-05 03:30 UTC, Jedi-Toothpaste commented
Hi, bit of feedback on the ship
firstly, some qol I wouldn't mind seeing.
Could the button for the shutters be moved closer to the pilot's seat?
![image](https://github.com/user-attachments/assets/833e950d-e872-44fb-8eec-a11552a321ec)
Here is a potential place for it

To my knowledge the windoors to the guns are accessible by the Deckhands, would it be possible to keep this to elevated access as it's a Government vessel, not everyone would be weapon's trained!

I don't think the ship needs a doctor slot, given it doesn't have a dedicated doctor's space, I think the slot might be better either gone, or another engineer of some kind? 
Or even contracted IRMG security like you see on old ships like the Beluga (i'd go over this with a maptainer however)

The comms room starts vented, instead of cold, if you want to keep it vented, can you map in a vent set to siphon which injects back outside, like in this diagram for example?
![image](https://github.com/user-attachments/assets/b78ad9e1-2323-4553-9bc2-c25c2b4e7678)

Would you be able to move the light-switch in the engine room so it can be flicked from the stairs?
![image](https://github.com/user-attachments/assets/ace46688-9a50-4791-bfa3-9ef5046f2910)

Also, a lightswitch in the cryo-room would be nice, but not required.
![image](https://github.com/user-attachments/assets/885e3cb6-0d55-4cb7-b832-1b5a9206cccb)



Secondly, to bugs, there aren't that many, to my knowledge.
First off, this lightswitch in the comms room seems misaligned
![image](https://github.com/user-attachments/assets/a72b717b-f43e-426f-bd2f-31ffb24e8700)

Only the captain spawns with a radio headset, and since there is no way of obtaining more radio keys they just have to use a custom frequency instead of the Minutemen one you created.

2025-01-05 03:45 UTC, Ical92 commented
@Jedi-Toothpaste 
> Could the button for the shutters be moved closer to the pilot's seat?
nodnods, definitely, 

> To my knowledge the windoors to the guns are accessible by the Deckhands
It *shouldn't* be, so I'll double check the access on those, thanks for the catch

> I don't think the ship needs a doctor slot, given it doesn't have a dedicated doctor's space
Definitely not a full "doctor" but I'd say some sort of designated medical person is helpful, may rephrase the job title somehow though to clarify that they won't be getting a proper medbay. 

> The comms room starts vented, instead of cold
Not *quite* vented, just low pressure

Onto the smaller things
* I'll probably leave the light switch on that same tile, since that's quite a distance to shift it
* Can definitely add a switch to the cryo room
* Tcomms switch is definitely in an awkward spot, I'll try and center it a bit more to see if it helps
* Talking with maptainers to check about headsets, but should be able to get starting headsets in, and already added a couple spare headsets in the crew locker.

2025-01-06 02:10 UTC, Sadhorizon commented on code/modules/clothing/outfits/factions/minutemen.dm
> +/datum/outfit/job/clip/medtech
This is defined twice, once as `/medtech`, once as `/minutemen/paramedic`. Same outfit twice seems weird, I'd remove the old unused one (the /paramedic one)
Also, afaik, this outfit is cruft from the Asclepius. You should check up with someone on how to update it I think, because it uses essentially indie gear.

2025-01-06 02:15 UTC, Ical92 commented on code/modules/clothing/outfits/factions/minutemen.dm
> +/datum/outfit/job/clip/medtech
`/medtech` was meant to be the non-military version of `/minutemen/paramedic` (hence why it doesn't have an armored vest. Though I agree this definitely could use some more explicit CLIP identification than just *being very blue*.

2025-01-15 18:53 UTC, Sadhorizon commented on code/modules/clothing/outfits/factions/minutemen.dm
> +	satchel = /obj/item/storage/backpack/security/clip
This seems odd? There exists an actual CLIP satchel, if you want to use it.

2025-01-15 19:13 UTC, Burning02 commented
Under this specific airlock in the... airlock, theres a missing tile, leading to space
![image](https://github.com/user-attachments/assets/e5046fb2-8f3f-4b1a-86f7-6df152e545fc)

2025-01-15 19:35 UTC, meemofcourse requested changes
conducted a very short test

![imagen](https://github.com/user-attachments/assets/9a09a196-b675-4097-99b4-2ff925fe0a0d)

i'm not sure if like this double decaling

![imagen](https://github.com/user-attachments/assets/dcd51955-d5ff-42b0-b13c-74c054770886)

that's not good

2025-01-16 02:57 UTC, Ical92 commented on code/modules/clothing/outfits/factions/minutemen.dm
> +	satchel = /obj/item/storage/backpack/security/clip
Mistyped, put the backpack and satchel in properly

2025-01-20 19:17 UTC, meemofcourse approved these changes
ships tested

2025-01-20 19:27 UTC, merged