The Independent Suit Update
shiptest-ss13/Shiptest pull request #455
Opened 2021-11-22 05:39 UTC by Apogee-dev

## About The Pull Request
![mixed_spread](https://user-images.githubusercontent.com/60533805/142805459-9864e322-c9e7-48ea-90a5-cbb39cef1b79.png)
Adds several independent space suits, makes some minor adjustments to independent-themed clothing, and adds the new clothes to the Rigger.

Space suit details:
- Independent security hardsuit. A more outdated version of Nanotrasen's security suits, this suit has higher bullet protection and weaker laser protection, but the same total armor value.
- Independent mining hardsuit. A civilian-market, somewhat outdated alternative to Nanotrasen's mining hardsuits.
- Independent engineering space suit. A "soft" suit with enhanced thermal and radiation shielding. The helmet, with its integrated hard hat, also has protection against blunt impacts and a built-in headlight. Like the sec suit, has slightly more bullet armor than laser armor.
- Pilot space suit. A very old space suit design that makes boarding and ejecting from mechs and space pods twice as fast. There are eight different skins for the helmet, with a random one chosen upon spawn! While it has built-in storage and is useful for vehicle operators, it is still completely unarmored.

Other changes:
- Hazard jumpsuits for engineers and miners now roll down when toggled instead of just rolling up the sleeves.
- Spacepods have a small eject delay identical to mechs.
- the Rigger has been updated with the new space suits.
- Rigger's wrecked Ripley has been replaced with a scattering of parts for constructing a new Ripley.

## Why It's Good For The Game

## Changelog
:cl:
add: Added four new Independent-themed space suits
tweak: Updated Rigger with new space suits
tweak: Rigger command and armory lockers are now locked by default
tweak: Replaced wrecked Ripley on the Rigger with an unassembled Ripley
tweak: Space pods now have a small eject delay for consistency with mechs
fix: Fixed duplicated objects on the Rigger
/:cl:

2021-11-22 06:05 UTC, retlaw34 commented
hellll yeaa

2021-11-22 06:05 UTC, retlaw34 commented
god i love those pilot suits

2021-11-22 09:15 UTC, CapnMachaddish commented
Absolutely fragnificent. Glad to see these come to fruition.

2021-11-22 17:39 UTC, triplezeta commented
:+1:

2021-12-01 05:11 UTC, MarkSuckerberg requested changes
Last touches

2021-12-01 05:11 UTC, MarkSuckerberg commented on code/modules/clothing/spacesuits/hardsuit.dm
> +/obj/item/clothing/head/helmet/space/light/
```suggestion
/obj/item/clothing/head/helmet/space/light
```

2021-12-01 05:11 UTC, MarkSuckerberg commented on code/modules/clothing/spacesuits/hardsuit.dm
> +
```suggestion
```
Not needed, already added on the parent's component initialize

2021-12-01 05:28 UTC, merged