Firelock improvements
shiptest-ss13/Shiptest pull request #478
Opened 2021-11-27 22:01 UTC by MaltVinegar

## About The Pull Request

Makes window firelocks constructable
Fixes a bug that prevented firelocks from being able to be completed which maybe happened in some circumstances

## Why It's Good For The Game

Bugs bad and bad sprites worse

## Changelog
:cl:
fix: "improves" some firelock code
image: changes the window firelock sprites to something a bit prettier
/:cl:

2021-12-04 05:19 UTC, ZephyrTFA requested changes

2021-12-04 05:19 UTC, ZephyrTFA commented on code/game/machinery/doors/firedoor.dm
> +									 "<span class='notice'>You begin adding glass to [src]...</span>")
```suggestion
				user.visible_message("<span class='notice'>[user] begins adding glass to [src]...</span>",
													"<span class='notice'>You begin adding glass to [src]...</span>")
```

2021-12-04 05:19 UTC, ZephyrTFA commented on code/game/machinery/doors/firedoor.dm
> +										 "<span class='notice'>You add glass to [src].</span>")
```suggestion
					user.visible_message("<span class='notice'>[user] adds glass to [src].</span>",
														"<span class='notice'>You add glass to [src].</span>")
```

2021-12-04 05:19 UTC, ZephyrTFA commented on code/game/machinery/doors/firedoor.dm
> +				var/obj/machinery/door/firedoor/F = new firelock_type(get_turf(src))
Use a better var name here

2021-12-04 05:19 UTC, ZephyrTFA commented on code/game/machinery/doors/firedoor.dm
>  				var/obj/item/stack/sheet/plasteel/P = C
I understand this isnt your code but since you are already touching this file can you cleanup all of the old style var names

2021-12-04 05:19 UTC, ZephyrTFA commented on code/game/machinery/doors/firedoor.dm
> +/obj/structure/firelock_frame/border/update_icon()
update_icon should not be overriden in this manner. Look at the base definition of it to see why.

2021-12-22 05:40 UTC, triplezeta commented
guh

2022-01-01 22:07 UTC, MarkSuckerberg commented
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 14 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

2022-01-01 22:07 UTC, closed without merging