Xenomorph Tweaks
shiptest-ss13/Shiptest pull request #521
Opened 2021-12-14 23:44 UTC by MemedHams

## About The Pull Request
A number of assorted tweaks to xenomorph functionality that make them better-suited for shiptest

- [ ] Removes xenomorph hardstuns, replacing with stamina damage
- [ ] Slightly increases xenomorph queen's speed
- [ ] Allows aliens to understand, but not speak common
- [ ] Allows aliens to pick up and use items. Gives them futzy fingers that prevent firing guns
- [ ] Allow aliens to interact with objects and machinery

## Why It's Good For The Game
-makes xenos both slightly fairer to fight and more of a threat without admin intervention

## Changelog
:cl:
balance: xenomorphs can now pick up items properly. They cannot, however, use firearms.
balance: Replaced all xenomorph hardstuns with stamina damage
balance: xenos can now understand common.
balance: boosts xenomorph queen's speed from Mobility Scooter to John Deere tractor
/:cl:

2021-12-14 23:52 UTC, ValoTheValo commented
Xenos shouldn't be able to speak common to be honest.

2021-12-14 23:53 UTC, MarkSuckerberg commented
> Xenos shouldn't be able to speak common to be honest.

They can't, it just says "understand" common.

2021-12-14 23:53 UTC, MemedHams commented
they can't, at least not by default- they can only understand it.

> Xenos shouldn't be able to speak common to be honest.

2021-12-14 23:54 UTC, ValoTheValo commented
And being able to do stuff like weld doors or fly a fucking space ship doesnt make sense. They are smart but not that smart and also they dont have thumbs

2021-12-14 23:57 UTC, MemedHams commented
> And being able to do stuff like weld doors or fly a fucking space ship doesnt make sense. They are smart but not that smart and also they dont have thumbs

fun fact: aliens actually have mirrored opposable thumbs on each hand.
![image](https://user-images.githubusercontent.com/45698967/146098054-00786d4c-852b-4bf3-ab1d-5d33993643d6.png)

2021-12-15 01:33 UTC, TallDeekus commented
Honestly based PR, although I wonder if there is a way to make it so that, while they can use consoles and stuff, the typing on the console is randomized, understanding spoken common does not equal being able to read it, it would be neat, as it wouldn't limit players controlling computers, but it would limit information retained from them.

2021-12-15 04:34 UTC, Dimasw99 commented
Give them DNA too while you are at it so that they can be cloned

2021-12-15 15:34 UTC, UltraNumeron commented
Does this mean benos could now hypothetically use a holopara injector

2021-12-15 17:38 UTC, ValoTheValo commented
> Does this mean benos could now hypothetically use a holopara injector

It means benos can robust people with toolboxes and eswords and yes holopara

2021-12-15 17:39 UTC, UltraNumeron commented
that is hilarious and i love it

2021-12-15 17:41 UTC, ValoTheValo commented
My favorite scene in alien is when the xenomorph hit lampert over the head with a toolbox 12 timed and said "skill issue cope and seethe" then hacked the atmospherics and vented the entire nostromo by setting it to panic siphon

2021-12-16 03:27 UTC, ilikesaying commented
My favourite scene in Aliens was when the Queen used her stand "「Danger Zone」" to trap the Colonial Marines inside the room while the drones throw paper airplanes and soap.

2021-12-22 14:35 UTC, MemedHams commented
I need some help with task 6/6, if anyone familiar with buttons in TGUI tabs ends up reading this

2021-12-27 19:00 UTC, BigManMassive commented
Good lord i can imagine a xeno with a fireaxe or a double esword.

2022-01-05 03:25 UTC, MarkSuckerberg requested changes

2022-01-05 03:25 UTC, MarkSuckerberg commented on code/modules/mob/living/carbon/human/human_defense.dm
>  				to_chat(M, "<span class='danger'>You disarm [src]!</span>")
```suggestion
			if(I && dropItemToGround(I))
				if(prob(50))
					playsound(loc, 'sound/weapons/slash.ogg', 25, TRUE, -1)
					visible_message("<span class='danger'>[M] disarms [src]!</span>", \
								"<span class='userdanger'>[M] disarms you!</span>", "<span class='hear'>You hear aggressive shuffling!</span>", null, M)
					to_chat(M, "<span class='danger'>You disarm [src]!</span>")
```

2022-01-10 04:08 UTC, MarkSuckerberg commented
This is funny, and the code most definitely works, but there are severe balance concerns that would require a great deal of effort to reconcile, I believe.

2022-01-21 21:00 UTC, MarkSuckerberg commented
General maintainer consensus that this is way too powerful. I'm sure there's different avenues that could be explored in the same vein as this, such as a xeno race or something similar, but as it stands this just won't end well.

2022-01-21 21:00 UTC, closed without merging