Hyena Tweaks
shiptest-ss13/Shiptest pull request #627
Opened 2022-01-07 03:11 UTC by Apogee-dev

## About The Pull Request

Minor tweaks to the Hyena; replaces the roundstart crushers with Syndicate cleavers and adds a design disk for 10mm ammo boxes (boxes, not magazines, so retain your roundstart mags).

## Why It's Good For The Game

## Changelog
:cl:
tweak: Added Magnetic Cleavers and 10mm Design Disk to hyena
/:cl:

2022-01-07 03:17 UTC, PrefabQuasar commented
I think hyena originally had syndie crushers and they were asked to be removed because of how powerful they were, although I'm unsure if they actually are unbalanced, may be worth discussing it in the discord.

2022-01-07 03:21 UTC, Apogee-dev commented
> I think hyena originally had syndie crushers and they were asked to be removed because of how powerful they were, although I'm unsure if they actually are unbalanced, may be worth discussing it in the discord.

Memed Hams informed me that the magnetic cleavers were significantly reined in since their initial addition to the game. I wouldn't have bothered replacing the crushers if they hadn't mentioned that to me. They should be fine.

2022-01-07 04:03 UTC, MemedHams commented
I tweaked the cleavers slightly, instead of being stupid powerful eswords with the additional damage power of a crusher, they now have identical damage to the kinetic crusher- but more of that damage is in the original hit, instead of the detonation, making them more useful against humans. They also have a bit of ap.

2022-01-10 05:34 UTC, MarkSuckerberg requested changes

2022-01-10 05:34 UTC, MarkSuckerberg commented on whitesands/code/modules/projectiles/boxes_magazines/pistol.dm
> +	category = list("Imported")
```suggestion
``` 
Already defined elsewhere, that's what your runtime is for https://github.com/shiptest-ss13/Shiptest/blob/d7e28054357e6b4765b754ecccc73cebccfdda24/code/modules/research/designs/autolathe_designs.dm#L855-L861

2022-01-10 05:36 UTC, MarkSuckerberg commented on whitesands/code/modules/projectiles/boxes_magazines/pistol.dm
> +	blueprints[1] = C
```suggestion
	blueprints[1] = new /datum/design/c10mm()
``` whoops, missed this, my bad

2022-01-14 01:24 UTC, merged