Bay highvis jacket & evening gloves port
shiptest-ss13/Shiptest pull request #632
Opened 2022-01-07 07:37 UTC by Apogee-dev

## About The Pull Request

Adds the highvis jacket from Bay, as the "industrial jacket," as well as the evening gloves, both available via the loadout screen. Also adds the hazard jacket to the loadout menu.

## Why It's Good For The Game

fashion options are good

## Changelog
:cl:
add: Ported high-visibility jacket and evening gloves from Bay
add: Added three new items to loadout screen
/:cl:

2022-01-07 08:50 UTC, atteria commented
An image of the sprites, so others don't have to.
![image](https://user-images.githubusercontent.com/86520558/148517844-e0be8761-e4c3-45f2-bd18-1c78c877de9a.png)

2022-01-07 14:37 UTC, swifterjack commented
images pls

2022-01-07 18:54 UTC, MarkSuckerberg approved these changes

2022-01-07 19:38 UTC, Kapu1178 requested changes
I dont like how there's an item named "High visibility jacket" that isnt the highvis jacket typepath. (`/obj/item/clothing/suit/toggle/hazard`)

We also have "hazardvest" which in the description calls it a high-visibility vest.

2022-01-08 04:22 UTC, Kapu1178 approved these changes

2022-01-08 04:23 UTC, merged