Refactor and Fix Stationloving into Shiploving
shiptest-ss13/Shiptest pull request #657
Opened 2022-01-14 02:06 UTC by ZephyrTFA

Unit tests make me sad.

2022-01-15 20:00 UTC, MarkSuckerberg requested changes

2022-01-15 20:00 UTC, MarkSuckerberg commented on code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
> +	AddComponent(/datum/component/shiploving, !fake)
```suggestion
	AddComponent(/datum/component/shiploving, inform_admins = !fake)
```

2022-01-15 20:00 UTC, MarkSuckerberg commented on code/modules/antagonists/blob/structures/core.dm
> +	AddComponent(/datum/component/shiploving, FALSE, TRUE)
```suggestion
	AddComponent(/datum/component/shiploving, inform_admins = FALSE, allow_death = TRUE)
```

2022-01-15 20:00 UTC, MarkSuckerberg commented on code/datums/components/shiploving.dm
> +		parent_ship = pick(SSovermap.simulated_ships)
```suggestion
	if(!parent_ship)
		  for(var/obj/structure/overmap/ship/simulated/ship as anything in SSovermap.simulated_ships)
			  if(get_area(parent) in ship.shuttle.shuttle_areas)
				  parent_ship = ship
				  break
	if(!parent_ship)
		message_admins("[parent] created with [type] outside a ship, assigning a ship at random!")
		parent_ship = pick(SSovermap.simulated_ships)
```

2022-01-15 20:21 UTC, ZephyrTFA commented on code/datums/components/shiploving.dm
> +	for(var/obj/structure/overmap/ship/simulated/ship as anything in SSovermap.simulated_ships)
```suggestion
	src.allow_death = allow_death
	src.parent_ship = parent_ship
	for(var/obj/structure/overmap/ship/simulated/ship as anything in SSovermap.simulated_ships)
```

2022-01-15 20:21 UTC, ZephyrTFA commented on code/datums/components/shiploving.dm
>  			allow_death = newc.allow_death
```suggestion
			allow_death = newc.allow_death
			parent_ship = newc.parent_ship
```

2022-01-15 20:24 UTC, ZephyrTFA commented on code/datums/components/shiploving.dm
> +/datum/component/shiploving/InheritComponent(datum/component/shiploving/newc, i_am_original, inform_admins, allow_death)
```suggestion
/datum/component/shiploving/InheritComponent(datum/component/shiploving/newc, i_am_original, parent_ship, inform_admins, allow_death)
```

2022-01-17 01:14 UTC, ZephyrTFA commented
@MarkSuckerberg I can't merge this because I dont want to setup the github cli to override automerge

2022-01-17 01:17 UTC, MarkSuckerberg approved these changes

2022-01-17 01:17 UTC, merged