QoL additions for engineering
shiptest-ss13/Shiptest pull request #678
Opened 2022-01-18 16:13 UTC by Dimasw99

## About The Pull Request

The following things can be ordered now:
Plasma canister for 4000
TEG set boards for 5000
2 Freezer boards for 2000
T2 parts 3 each for 20000
T3 parts 3 each for 60000

Server RnD board and Pipe dispenser board is now sorted in the Machinery tab in the autolathe

Pipe dispenser are now constructable

## Why It's Good For The Game

As an engineer I find myself often very bottle necked in the ability to do things like constructing an SM or wanting to do fusion/atmos magic. I would always have to hope that there is a ship to ship interaction happening (Which very few captains seek out even when suggested) and have the other ship cooperate or have the necessary equipment. This luck dependency makes it just a mere luck investment or a huge time sink. 

An orderable plasma canister was added because not every atmosphere has plasma and bugging the captain about moving to another planet can be pretty annoying for the whole crew. With it being base component for a lot of atmos magic it should hopefully encourage players to do some gas reactions. So far I have never seen anyone do it.

This too helps mix things up. I am always sad to see that my engineering option right now is just "Hey set up the AM" which is just a 3x3 box that magically produces 200kW with no active tweaking or management. 

Likewise I have seen very little use of T2 or T3 parts. Either everything is just T1 or T4. Hopefully this makes T2 and T3 somewhat more common used. To make things even more interesting, Golems can drop T4 parts rarely. Making components management somewhat of a more thought intensive matter with the limited amount you get. Priotise your gear!

Making the pipe dispenser constructable with simple tech will allow people to repair/expand their atmos and I consider it to be a bare necessity since the alternative is the RPD which requires some pretty advanced RnD making this a very simple early stage solution. 

## Changelog
:cl:
add: TEG boards, freezer boards, plasma, T2 and T3 parts can be ordered on the express console.
add: Pipe dispenser boards can now be printed at an autolathe. Can now also be constructed/deconstructed.
balance: Golems can drop part boxes including T4
fix: RnD server board added to machinery category in the autolathe
/:cl:

2022-01-18 16:22 UTC, Ms-Mee commented
The part tier thing is kinda already changed by Interrim since only 2 techfab types have access to T3 and only one to T4 so I'm not so sure about that

2022-01-18 16:35 UTC, Dimasw99 commented
> The part tier thing is kinda already changed by Interrim since only 2 techfab types have access to T3 and only one to T4 so I'm not so sure about that

I am unsure how long interrim is going to be in merge conflict hell or when the next test merge will be. I have added such high pricing cost on purpose to incentivize seeking out ship to ship interaction instead of grinding for it. Just sometimes this ship to ship interaction never happens so it can be treated as a type of safety net. Being stuck to low tier components can suck

2022-01-18 16:44 UTC, Ms-Mee commented
> > The part tier thing is kinda already changed by Interrim since only 2 techfab types have access to T3 and only one to T4 so I'm not so sure about that
> 
> I am unsure how long interrim is going to be in merge conflict hell or when the next test merge will be. I have added such high pricing cost on purpose to incentivize seeking out ship to ship interaction instead of grinding for it. Just sometimes this ship to ship interaction never happens so it can be treated as a type of safety net. Being stuck to low tier components can suck

Main issue is getting a lot of money is quite trivial if you want to and even this relies on having access to cargo in the first place

2022-01-18 16:49 UTC, Dimasw99 commented
> > > The part tier thing is kinda already changed by Interrim since only 2 techfab types have access to T3 and only one to T4 so I'm not so sure about that
> > 
> > 
> > I am unsure how long interrim is going to be in merge conflict hell or when the next test merge will be. I have added such high pricing cost on purpose to incentivize seeking out ship to ship interaction instead of grinding for it. Just sometimes this ship to ship interaction never happens so it can be treated as a type of safety net. Being stuck to low tier components can suck
> 
> Main issue is getting a lot of money is quite trivial if you want to and even this relies on having access to cargo in the first place

From my experience I have seen people reach around 100k when determined and 200k on very rare occasions

2022-01-18 16:52 UTC, Ms-Mee commented
> > > > The part tier thing is kinda already changed by Interrim since only 2 techfab types have access to T3 and only one to T4 so I'm not so sure about that
> > > 
> > > 
> > > I am unsure how long interrim is going to be in merge conflict hell or when the next test merge will be. I have added such high pricing cost on purpose to incentivize seeking out ship to ship interaction instead of grinding for it. Just sometimes this ship to ship interaction never happens so it can be treated as a type of safety net. Being stuck to low tier components can suck
> > 
> > Main issue is getting a lot of money is quite trivial if you want to and even this relies on having access to cargo in the first place
> 
> From my experience I have seen people reach around 100k when determined and 200k on very rare occasions 

You can very easily get a rate of about 27000 per minute with gas farms on planets, or at least could last time I tried, how much you get depends more on how much you want to get

2022-01-18 16:58 UTC, Dimasw99 commented
> You can very easily get a rate of about 27000 per minute with gas farms on planets, or at least could last time I tried, how much you get depends more on how much you want to get

God damn. That is what I call being super lucky with the BZ mole count on an atmosphere which doesn't apply always. Getting 10 moles is huge when compared to the other times when it is just 2 or even zero

2022-01-18 17:04 UTC, Ms-Mee commented
> > You can very easily get a rate of about 27000 per minute with gas farms on planets, or at least could last time I tried, how much you get depends more on how much you want to get
> 
> God damn. That is what I call being super lucky with the BZ mole count on an atmosphere which doesn't apply always. Getting 10 moles is huge when compared to the other times when it is just 2 or even zero

Considering I've done it 5 separate times without any complications or differences in effectiveness I don't think being lucky is a factor here

2022-01-20 02:13 UTC, triplezeta requested changes
Changes look good, review contains single spelling correction. Merge in master to make checks pass.

2022-01-20 02:13 UTC, triplezeta commented on code/modules/cargo/packs.dm
> +	desc = "Contains a canister of Plasma. Handy when no synthetization or plasma-rich atmospheres are aviable"
aviable

```suggestion
	desc = "Contains a canister of Plasma. Handy when no synthetization or plasma-rich atmospheres are available."
```

2022-01-22 05:22 UTC, merged