Ports tribal expansion
shiptest-ss13/Shiptest pull request #68
Opened 2021-07-06 04:42 UTC by retlaw34

## About The Pull Request

This is nowhere near finished, this is just so people can yell at me to finish it

## Why It's Good For The Game

Its only good for ashwalkers, which seem to be rare in the shiptest-verse

## Changelog
:cl:
add: Why even write these changelogs? They aren't even shown in game. 
add: Added a Goliath shield and it takes less damage from fauna.
add: Added a new Watcher bola, slightly better than the standard bola.
add: Added a new one handed bone sword.
add: Added a new belt quiver to carry arrows.
add: Two new craftable bow types "pipe bow" and "bone bow".
add: 4 new arrow types wood, ash, bone and bronze.
add: New export prices for bows, arrows.
add: New bounty for a bow.
add: New variation of bone armor (heavy bone armor)
add: Cotton seeds in askwalker nest for bowcrafting.
add: QOL cultivator for ashwalkers added to nest.
tweak: blowgun no longer needs a firing pin and can be used by anyone
soundadd: New sounds for drawing the arrow and firing.
add: New weapon and ammo type for bows.
fix: Added a crafting recipe for the primal explorers belt.
add: A new material Silk which can be made from cloth on the loom. (needed in bowcrafting)
imageadd: Added Sprites for the new items and materials.
imageadd: New sprites for existing bone equipment.
refactor: Cloth is now a subtype of cotton and coded in descending order of creation.
crafting recipes are updated to reflect this.
Cotton>cloth>silk
refactor: Crafting refactor
/:cl:

2021-07-06 20:35 UTC, triplezeta commented
Please link the original PR in your description.

2021-07-23 04:40 UTC, retlaw34 commented
after sitting on this for so long it should be good to go

2021-07-29 23:24 UTC, MarkSuckerberg requested changes
Looks good other than this, should be testmerged first, though

2021-07-29 23:24 UTC, MarkSuckerberg commented on code/modules/projectiles/guns/misc/bow.dm
> +		to_chat(user, "<span class='notice'>You [drawn ? "release the tension on" : "draw the string on"] [src].</span>")
```suggestion
		to_chat(user, "<span class='notice'>You [drawn ? "release" : "draw"] [src]'s string.</span>")
```

2021-07-31 04:36 UTC, triplezeta commented
how

2021-07-31 05:18 UTC, retlaw34 commented
i will scream

2021-08-08 06:06 UTC, merged

2021-08-08 07:13 UTC, Pontenerd commented
It's finally over

2021-08-08 11:06 UTC, retlaw34 commented
at long last