Makes both ak rifles unbuyable
shiptest-ss13/Shiptest pull request #680
Opened 2022-01-19 01:26 UTC by retlaw34

## About The Pull Request

Comments out the code that lets the ak47 and NT-AK buyable from cargo

## Why It's Good For The Game
There are a shit-ton of guns you can buy from cargo, and while you may avoid buying the AK to save money, when you are fighiting another ship, it's just more worth to buy a ak or nt ak, because even though nt-ak technicaly does around 10 less damage, the extreme firing rate just outpaces the amount of damage it does. Talk to the discord and even people that use the AK want it removed.

## Changelog
:cl:
balance: AK-47s are sold out.
balance: Additionally, NT-AKs are discontinued following record sales, but not hitting sales projections.
/:cl:

2022-01-19 01:48 UTC, Kapu1178 requested changes
Remove don't comment. Also, are you telling me supply_packs arent "sanitized" and you can just buy any of the type?

2022-01-19 02:00 UTC, Kapu1178 approved these changes
Code checks out

2022-01-19 23:57 UTC, WindowsErrors commented
أي نوع من العرب سأكون بدون مسدس مدفون تحت بيتي

2022-01-20 02:13 UTC, Zevotech commented
жалкие американцы больше не могут владеть славным русским автоматом Калашникова

2022-01-21 20:50 UTC, merged