Produce slicing fix and wrench seed extraction sound change
shiptest-ss13/Shiptest pull request #702
Opened 2022-01-21 22:38 UTC by Ms-Mee

## About The Pull Request

This PR changes the sound effect for extracting seeds with a wrench and makes extracting seeds no longer the default option on sliceable produce.

## Why It's Good For The Game

Bug bad.

## Changelog
:cl:
tweak: Changed the ghetto seed extraction sound effect for wrenches.
fix: Plants can be sliced again.
/:cl:

2022-01-25 16:39 UTC, Ms-Mee commented
I hate the scrapper I hate the scrapper I hate the scrapper

2022-01-27 22:42 UTC, MarkSuckerberg requested changes

2022-01-27 22:42 UTC, MarkSuckerberg commented on code/modules/hydroponics/grown.dm
> +			user.visible_message("<span class='notice'>[user] starts wackng \the [src].</span>", "<span class='notice'>You start wacking \the [src]...</span>", "<span class='hear'>You hear the sound of a plan
```suggestion
			user.visible_message("<span class='notice'>[user] starts whacking \the [src].</span>", "<span class='notice'>You start whacking \the [src]...</span>", "<span class='hear'>You hear the sound of a plant being whacked violently.</span>")
```

2022-02-11 20:37 UTC, MarkSuckerberg approved these changes

2022-02-11 20:38 UTC, merged