Ports Multilingual quirk from Beestation, makes it not random.
shiptest-ss13/Shiptest pull request #708
Opened 2022-01-22 18:55 UTC by Ms-Mee

## About The Pull Request

This PR ports https://github.com/BeeStation/BeeStation-Hornet/pull/2228, additionally making the language not random and instead selectable.
Additional credits go to super12pl for the initial port and attempt at adding such a feature, and AsciiSquid who tested and fixed the language selection button, which I could not.

## Why It's Good For The Game

Being able to select a secondary language is a nice and simple way of improving character customization, and this makes the language system overall a bit more present.

## Changelog
:cl: DatBoiTim, yorii, super12pl, Ms-Mee, AsciiSquid
add: Added a new quirk which allows you to select a second language your character understands and speaks.
/:cl:

2022-01-22 20:11 UTC, Kapu1178 requested changes

2022-01-22 20:11 UTC, Kapu1178 commented on code/modules/client/preferences.dm
> +	var/language = "Kalixcian Common"
Doesn't need to exist.

2022-01-22 20:11 UTC, Kapu1178 commented on code/modules/client/preferences.dm
> +					languages_possible -= typecacheof(/datum/language/codespeak)
```suggestion
					languages_possible -= GLOB.restricted_languages
```

make a global list for restricted roundstart languages

2022-01-22 20:11 UTC, Kapu1178 commented on code/modules/client/preferences.dm
> +						language_names |= initial(lang_possible.name)
```suggestion
					var/list/language_options = list()
					for(var/datum/language/lang_option in languages_possible)
						languages |= initial(lang_option.name)
						languages[initial(lang_option.name)] = lang_option
```

2022-01-22 20:11 UTC, Kapu1178 commented on code/modules/client/preferences.dm
> +					var/languageType = input(user, "What other language do you know?", "Character Preference", language) as null|anything in language_names
```suggestion
					var/languageType = input(user, "What other language do you know?", "Character Preference", language) as null|anything in language_options
```

2022-01-22 20:11 UTC, Kapu1178 commented on code/modules/client/preferences.dm
> +					var/languageType = input(user, "What other language do you know?", "Character Preference", language) as null|anything in language_names
```suggestion
					var/selected_language = input(user, "What other language do you know?", "Character Preference", language) as null|anything in language_names
```

2022-01-22 20:11 UTC, Kapu1178 commented on code/modules/client/preferences.dm
> +						language = languageType
```suggestion
					if(selected_language)
```

2022-01-22 20:11 UTC, Kapu1178 commented on code/modules/client/preferences.dm
> +								break
```suggestion
						language_datum = language_options[selected_language]
```

2022-01-22 20:11 UTC, Kapu1178 commented on code/modules/client/preferences.dm
>  				if ("max_chat_length")
```suggestion
					qdel(language_holder)
					qdel(T)

				if ("max_chat_length")
```

2022-01-23 03:33 UTC, Kapu1178 requested changes

2022-01-23 03:33 UTC, Kapu1178 commented on code/controllers/subsystem/language.dm
> +	GLOB.restricted_languages = list(/datum/language/codespeak)
```suggestion
	GLOB.restricted_languages += /datum/language/codespeak
```

2022-01-30 01:49 UTC, Ms-Mee commented
For some reason changing the language is making it so you can't speak any other language
Loading the savefile works perfectly fine
So probably something in the selection part is causing that
What? I have no clue...

2022-02-17 14:50 UTC, closed without merging