Adds a telecom floor tile
shiptest-ss13/Shiptest pull request #744
Opened 2022-01-30 05:50 UTC by retlaw34

## About The Pull Request
Adds a new floor tile dedicated to high-tech areas.
![image](https://user-images.githubusercontent.com/58402542/151688311-dd6bc2a4-36a8-4464-9031-798b1a916d30.png)
It's animated as well
Currently this touches no maps, so thats for a future mapper to handle

these were ported from TGMC and most likely from CM

## Why It's Good For The Game

https://streamable.com/p8rvyi

## Changelog
:cl:
add: Adds a telecomms floor
/:cl:

2022-01-30 06:52 UTC, MarkSuckerberg approved these changes

2022-01-30 08:09 UTC, swifterjack commented
these are good, cant wait to use em

2022-01-31 02:00 UTC, ZephyrTFA requested changes
Whitesands folder is deprecated.

2022-02-13 23:54 UTC, retlaw34 commented
Demodularized misc.dmi

2022-02-13 23:56 UTC, ZephyrTFA approved these changes

2022-02-14 00:00 UTC, merged