Changes all instances of assembly/flash to assembly/flash/handheld on maps
shiptest-ss13/Shiptest pull request #760
Opened 2022-02-03 19:54 UTC by Zevotech

## About The Pull Request
fixes a dumb issue with maps that prevented construction of borgs

## Why It's Good For The Game
small 5 minute fix to a kinda annoying issue

## Changelog
:cl:
fix: changed instances of asssembly/flash to assembly/flash/handheld
/:cl:

2022-02-03 19:59 UTC, Zevotech commented
that worked? okay, yeah, of course it did.

2022-02-03 22:11 UTC, Kapu1178 commented
undocumented addition to the Osprey

2022-02-03 23:11 UTC, Zevotech commented
oh godammit i was supposed to document that? i hate to be a fucking moron but how do i do that?

2022-02-03 23:16 UTC, Kapu1178 commented
> oh godammit i was supposed to document that? i hate to be a fucking moron but how do i do that?

put it in the changelog

2022-02-03 23:38 UTC, Zevotech commented
done, 'scuse me while i go check if the HOP locker item pool has a assembly/flash in it

2022-02-04 01:08 UTC, ZephyrTFA commented on _maps/shuttles/shiptest/ntsv_osprey.dmm
> +/obj/item/storage/box/PDAs,
```suggestion
/obj/item/storage/box/PDAs)
```
Try not to webedit map files because you'll end up breaking the map file like this

2022-02-11 21:02 UTC, MarkSuckerberg commented on _maps/shuttles/shiptest/ntsv_osprey.dmm
> +/obj/item/clothing/under/rank/command/lieutenant/blue,
Invalid path, I can't look up what it actually is to make a suggestion

2022-02-19 18:18 UTC, ZephyrTFA requested changes

2022-02-19 18:18 UTC, ZephyrTFA commented on _maps/shuttles/shiptest/ntsv_osprey.dmm
> +/obj/item/storage/box/PDAs)
This does a lot more than just fixing a flash path.

2022-03-14 01:19 UTC, closed without merging