Last ditch effort to get wounds working
shiptest-ss13/Shiptest pull request #780
Opened 2022-02-06 07:29 UTC by retlaw34

## About The Pull Request

Wounds completely broke
Reopen of #305

## Why It's Good For The Game
Bone repair surgery is awful
## Changelog
:cl:
add: ports tg wounds
/:cl:

2022-02-06 10:40 UTC, retlaw34 commented
ok it works now

2022-02-06 15:45 UTC, Kapu1178 requested changes

2022-02-06 15:45 UTC, Kapu1178 commented on code/datums/status_effects/debuffs.dm
> +		var/datum/wound/W = thing
```suggestion
	for(var/datum/wound/W as anything in throat.wounds)
```

2022-02-06 15:45 UTC, Kapu1178 commented on code/game/objects/items/devices/scanners.dm
> +			var/datum/wound/W = k
```suggestion
		for(var/datum/wound/W as anything in wounded_part.wounds)
```

2022-02-06 15:45 UTC, Kapu1178 commented on code/game/objects/items/devices/scanners.dm
> +				var/datum/wound/W = k
```suggestion
			for(var/datum/wound/W as anything in wounded_part.wounds)
```

2022-02-06 15:45 UTC, Kapu1178 commented on code/game/objects/items/devices/scanners.dm
> +			var/obj/item/bodypart/wounded_part = i
```suggestion
		for(var/obj/item/bodypart/wounded_part as anything in wounded_parts)
```

2022-02-06 15:45 UTC, Kapu1178 commented on code/datums/status_effects/wound_effects.dm
> +			var/datum/wound/W = thing
```suggestion
		for(var/datum/wound/W as anything in right.wounds)

```

2022-02-06 15:45 UTC, Kapu1178 commented on code/datums/status_effects/wound_effects.dm
> +			var/datum/wound/W = thing
```suggestion
		for(var/datum/wound/W as anything in left.wounds)
```

2022-02-06 15:45 UTC, Kapu1178 commented on code/datums/elements/embed.dm
> +		limb = C.get_bodypart()
```suggestion
	limb ||= C.get_bodypart()
```

2022-02-06 15:45 UTC, Kapu1178 commented on code/__HELPERS/pronouns.dm
> +		temp_gender = gender
```suggestion
	temp_gender ||= gender
```

2022-02-14 21:09 UTC, Kapu1178 requested changes
AS ANYTHING

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +	if(bodytype != BODYPART_ORGANIC)
```suggestion
	if(!IS_ORGANIC_LIMB(src))
```

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +	for(var/obj/item/organ/drop_organ in get_organs())
```suggestion
	for(var/obj/item/organ/drop_organ as anything in get_organs())
```

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +		var/obj/item/organ/organ_check = i
```suggestion
	for(var/obj/item/organ/organ_check as anything in owner.internal_organs) //internal organs inside the dismembered limb are dropped.
```

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +		var/datum/wound/iter_wound = i
```suggestion
	for(var/datum/wound/iter_wound as anything in wounds)
```

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +			var/obj/item/clothing/clothes_check = i
```suggestion
		for(var/obj/item/clothing/clothes_check as anything in clothing)
```

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +					replaced_wound = existing_wound
This is expensive and badly coded, you're looping through lists a shit load of times.

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +		var/datum/wound/existing_wound = i
```suggestion
	for(var/datum/wound/existing_wound as anything in wounds)
```

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +			var/obj/item/clothing/C = c
```suggestion
		for(var/obj/item/clothing/C as anything in clothing)
```

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +		var/datum/wound/W = thing
```suggestion
	for(var/datum/wound/W as anything in wounds)
```

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +		var/datum/wound/iter_wound = i
```suggestion
	for(var/datum/wound/iter_wound as anything in wounds)
```

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +	for(var/obj/item/embeddies in embedded_objects)
```suggestion
	for(var/obj/item/embeddies as anything in embedded_objects)
```

2022-02-14 21:09 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +		var/datum/wound/W = thing
```suggestion
	for(var/datum/wound/W as anything in wounds)
```

2022-03-16 07:41 UTC, retlaw34 commented
Remind me to finish this again when all the carbon PRs are done

2022-05-13 14:57 UTC, retlaw34 commented
i wonder how many merge conflicts this has

2022-05-13 15:03 UTC, retlaw34 commented
Jesus fucking Christ

2022-05-13 22:15 UTC, retlaw34 commented
this now has even more conflicts than ever before

2022-05-13 22:15 UTC, retlaw34 commented
github doesnt even show them all

2022-05-27 00:39 UTC, retlaw34 commented
confliucts fixed

2022-06-02 22:42 UTC, retlaw34 commented
when does this never have conflicts bot

2022-06-22 01:34 UTC, retlaw34 commented
wait this went stale?

2022-06-26 12:14 UTC, retlaw34 commented
![image](https://user-images.githubusercontent.com/58402542/175813609-ea0d8ecc-d401-4805-9e88-85e62c418370.png)
ughhhhhhhhhhhhhhhhh

2022-06-26 12:17 UTC, Zevotech commented
keep fighting.

2022-06-26 12:32 UTC, retlaw34 commented
conflicts fixed, again

2022-11-22 03:16 UTC, ZephyrTFA commented
As far as I can tell this is not being worked on.
Feel free to make another PR if this is not true

2022-11-22 03:16 UTC, closed without merging