Adds short people, body size options port
shiptest-ss13/Shiptest pull request #795
Opened 2022-02-09 19:03 UTC by E-MonaRhg

## About The Pull Request
Port of https://github.com/BeeStation/BeeStation-Hornet/pull/6046
As the original PR described it:
Short/Normal/Tall
All species (except IPCs) can now choose between "Normal" and "Short" height. Short height scales their sprite by 0.93 and Tall 1.03, which I hand-picked to be the best looking scaling.

Ever wanted to play as an even shorter (or taller) Kepori? Now you can!
![image](https://user-images.githubusercontent.com/71735193/153271588-b6fd5c66-d944-47c9-973f-52eaf19f2ec3.png)

... works on other species too I guess...
![image](https://user-images.githubusercontent.com/71735193/153271633-91b21822-e8fe-4409-a1f4-028e357694e1.png)

## Why It's Good For The Game
Now you can project your real-life insecurities by making a characters that is _slightly_ taller (or shorter) than all the other ones... or well, it looks nice I suppose...

## Changelog
:cl:
add: You can now pick body size for characters: short, normal or tall.
/:cl:

2022-02-09 20:09 UTC, Kapu1178 approved these changes

2022-02-10 17:47 UTC, Martinpachu commented
why not ipcs :( i want a tiny robot too

2022-02-10 18:19 UTC, ZephyrTFA commented
Because this touches body code it'll probably need to be test merged

2022-02-11 22:53 UTC, francinum commented on code/datums/dna.dm
> +	var/change_multiplier = desired_size / current_body_size
`current_body_size` can be null.
```
proc name: update body size (/datum/dna/proc/update_body_size)
usr: Piperdoots/(Piperdoots)
usr.loc: (start area (8, 174, 1))
src: /datum/dna (/datum/dna)
call stack:
/datum/dna (/datum/dna): update body size()
/datum/preferences (/datum/preferences): copy to(Melari (/mob/living/carbon/human/dummy), 1, 1, 1, 0, 1)
/datum/preferences (/datum/preferences): update preview icon(1, 1)
/datum/preferences (/datum/preferences): ShowChoices(Piperdoots (/mob/dead/new_player))
Piperdoots (/mob/dead/new_player): Topic("src=\[mob_69];show_preferences...", /list (/list))
Piperdoots (/client): Topic("src=\[mob_69];show_preferences...", /list (/list), Piperdoots (/mob/dead/new_player))
Piperdoots (/client): Topic("src=\[mob_69];show_preferences...", /list (/list), Piperdoots (/mob/dead/new_player))
Piperdoots (/client): Topic("src=\[mob_69];show_preferences...", /list (/list), Piperdoots (/mob/dead/new_player))
```

2022-02-11 22:58 UTC, francinum commented on code/datums/dna.dm
> +	var/change_multiplier = desired_size / current_body_size
Ping me on discord when this issue is resolved.

2022-02-11 23:07 UTC, francinum commented on code/datums/dna.dm
> +	var/change_multiplier = desired_size / current_body_size
This appears to be a result of a race condition with preference code, where `prefs.features` is not properly initialized and thus is missing the body_size selection.

2022-02-15 01:36 UTC, MarkSuckerberg requested changes, later dismissed
Doing this to block merging, see Fran's requests above

2022-02-17 06:43 UTC, WindowsErrors commented
5' 6" crew holds the entire Caribbean Sector hostage with a single pirate ship

2022-02-19 18:18 UTC, Ms-Mee commented
Is there any specific reason for the features list to not normally include body_size?

2022-02-19 19:19 UTC, Kapu1178 requested changes

2022-02-19 19:19 UTC, Kapu1178 commented on code/modules/client/preferences.dm
> +						)
```suggestion
							"flavor_text" = ""
							"body_size = "Normal"
						)
```

2022-02-19 19:21 UTC, Kapu1178 requested changes
fuckin github

2022-02-19 19:21 UTC, Kapu1178 commented on code/modules/client/preferences.dm
> +						)
```suggestion
							"flavor_text" = "",
							"body_size" = "Normal"
						)
```

2022-03-09 19:59 UTC, Kapu1178 approved these changes

2022-03-17 21:17 UTC, someguyjust commented
Is there a reason why this hasn't been merged yet?

2022-03-17 21:25 UTC, Kapu1178 commented
> Is there a reason why this hasn't been merged yet?

Review requested for @MarkSuckerberg

2022-03-17 21:45 UTC, MarkSuckerberg approved these changes

2022-03-17 21:45 UTC, merged