Resprites Medical Tools And Scanners
shiptest-ss13/Shiptest pull request #836
Opened 2022-02-16 01:20 UTC by Zevotech

## About The Pull Request
Resprites the basic and advanced surgery tools, as well as adding proper inhands for advanced tools.
Also resprites the health analyzer, advanced health analyzer and reagent scanner.
ALSO makes the health analyzer and advanced health analyzer change sprites and inhands upon changing scan modes.
![exam3](https://user-images.githubusercontent.com/95449138/154178181-2ac7ff70-6365-47e4-abd5-27fb3cb348bc.png)
![exam](https://user-images.githubusercontent.com/95449138/154178185-bc67c3c1-2089-428f-9c1c-fe8873dfb950.png)
![exam1](https://user-images.githubusercontent.com/95449138/154178187-96f609e5-8121-4f0c-b578-a4e6c8d71bfb.png)
**Sprites done by Any%. God Bless.**

## Why It's Good For The Game
Gives basic surgery tools and the health analyzer a nicer look, while making the advanced tools look cool as shit. Simple as.

## Changelog
:cl:
add: More and better surgical tool sprites and inhands.
code: Health analyzers actually change sprites based on scanmode.
/:cl:
please just let me be done.

2022-02-16 01:29 UTC, zestybastard commented
thanks for all the custom code 👍

2022-02-16 01:30 UTC, triplezeta requested changes
Looks great, but really needs a style pass.

2022-02-16 01:30 UTC, Ms-Mee commented
Someone who should be in the changelog isn't there, how sus

2022-02-16 01:33 UTC, Zevotech commented
> Looks great, but really needs a style pass.

![image](https://user-images.githubusercontent.com/95449138/154179306-dae2c1d3-95a7-4d80-b736-4a708a765fd0.png)

2022-02-16 01:35 UTC, zestybastard commented
> Looks great, but really needs a style pass.

TetraZeta The Missile. The Missile TetraZetra. You Have To Watch Out

2022-02-16 01:37 UTC, Ms-Mee commented
> Someone who should be in the changelog isn't there, how sus

(They are too distracted by zeter and cannot see me if I stand perfectly still, because I have chameleon)

2022-02-16 03:49 UTC, MemedHams commented
> Looks great, but really needs a style pass.
 
 I honestly feel like it's the rest of our sprites that need a style pass to match these ones
 Imagine a bright future of pastel 80's techwave for all of our stuff ingame

2022-03-01 22:15 UTC, MarkSuckerberg requested changes

2022-03-01 22:15 UTC, MarkSuckerberg commented on code/game/objects/items/devices/scanners.dm
> +    custom_price = 300
Should be tabs instead of spaces

2022-03-01 22:15 UTC, MarkSuckerberg commented on code/game/objects/items/devices/scanners.dm
> +    reagentinhand = "advreagentanalyzer"
Tabs

2022-03-01 22:15 UTC, MarkSuckerberg commented on code/modules/surgery/tools.dm
> +        icon_state = "advdrill"
Tabs

2022-03-19 05:47 UTC, Zevotech commented
fixed the tabs, i actually kept using them out of muscle memory and kept getting inconsistent indentation errors so i just converted them to spaces

2022-03-19 05:48 UTC, Zevotech commented
(by that i mean theyre all tabs now, i just changed them to spaces while working on the pr cause i didnt want to fuck with the indentation and cause some kind of error down the line)

2022-03-19 06:14 UTC, Zevotech commented
This Unpleasant Squiggle Shows Up At Your Door
![image](https://user-images.githubusercontent.com/95449138/159109754-ff30e9bc-e080-457e-a3ab-837d10c43301.png)

2022-03-19 07:15 UTC, Zevotech commented
Im Going To Cry

2022-03-19 07:22 UTC, someguyjust commented
> Im Going To Cry

oof, that seems rough. gl

2022-03-19 20:26 UTC, Zevotech commented
now just to beg for mergies before the stale label murders my hopes and dreams

2022-03-19 21:56 UTC, zestybastard commented
> now just to beg for mergies before the stale label murders my hopes and dreams

dont hold your breath, the sprites need more outline so i have to go add that soon

2022-05-10 19:23 UTC, Zevotech commented
hey can we testmerge this on tomorrow's uptime?

2022-05-10 19:24 UTC, retlaw34 commented
were the sprites outlinfified?

2022-05-10 19:28 UTC, Zevotech commented
> were the sprites outlinfified?

![image](https://user-images.githubusercontent.com/95449138/167707065-a154ea34-0f7f-4307-814a-2560abd7314a.png)

2022-05-13 22:11 UTC, Fikou commented on code/game/objects/items/devices/scanners.dm
> +		righthand_file = 'icons/mob/inhands/equipment/medical_righthand.dmi'
use ternary operators i.e.
variable = scan_mode ? "thing1" : "thing2"

2022-05-13 22:13 UTC, Fikou requested changes

2022-05-13 22:13 UTC, Fikou commented on code/game/objects/items/devices/scanners.dm
> +		righthand_file = 'icons/mob/inhands/equipment/medical_righthand.dmi'
why are you setting these

2022-05-13 22:13 UTC, Fikou commented on code/game/objects/items/devices/scanners.dm
> +	var/reagentinhand = "reagentanalyzer-1"
these variables need better names

2022-06-08 21:37 UTC, Vexylius commented
@Zevotech hi

2022-06-09 23:37 UTC, Zevotech commented
> @Zevotech hi

I'll save changes for when any% gives me the new sprites for these. you know the ones with the outlines.

oh. 
![image](https://user-images.githubusercontent.com/95449138/172962234-f691000b-0db9-4773-9490-0a4f015f7c76.png)

2022-07-01 01:28 UTC, closed without merging

2022-07-01 04:44 UTC, someguyjust commented
bruh

2022-07-01 06:14 UTC, Zevotech commented
we live in a spriteciety

2023-04-28 23:10 UTC, Zevotech commented
![image0-2](https://user-images.githubusercontent.com/95449138/235268098-295b9771-a442-4f33-acb1-829c4e1c2940.jpg)