Adds wolfgirls
shiptest-ss13/Shiptest pull request #899
Opened 2022-03-07 08:52 UTC by retlaw34

## About The Pull Request

A long, long time ago, a kingdom was crumbling. It's royal family hath left them, and its citizens living in poverty.
Then a light came, a mysterious man took the throne, and attempted his best efforts to keep the kingdom alive.
Unfortunately, the kingdom was acursed to crumble, and no deal of effort could save it.
Despite this, though his efforts, the kingdom hath survived several months more had it not been for him.
The man did not ask for any rewards, except for one:
"add wolfgirls lmao"
And thus, he set forth a prophesy. Though the kingdom hath long faded, the prophesy still stands tall.
This brings us to today.

## Why It's Good For The Game

Jokes aside, it adds a pretty neat customization option, and just adds another option to felinids, speaking of which, @TheNeoGamer42 abhumans when

![Screenshot_2715](https://user-images.githubusercontent.com/58402542/156998087-ca040b70-119d-40d4-a8e1-1fdc57c1f9b5.png)
![Screenshot_2716](https://user-images.githubusercontent.com/58402542/156998094-3497e0a0-2bcc-4da5-9d05-15837f67b946.png)

ported from https://github.com/Bungalow-13/Bungalow-13/pull/365
which was ported from https://github.com/MrMelbert/MapleStationCode/pull/112

@lunaboards-dev

## Changelog
:cl: Gofawful5
add: fox tails for felinids
refactor: demodularized sprite accesories, kind of
/:cl:

2022-03-07 09:11 UTC, TheNeoGamer42 commented
Dear god. Also abhumans aren't coming the funny people said that they just wanna shove the felinid stuff into humans lmao.

2022-03-07 09:12 UTC, TheNeoGamer42 commented
wait a fucking second this is a foxgirl tail not a wolfgirl tail i've been scammed, we've all been scammed

2022-03-07 21:01 UTC, Kapu1178 requested changes
Not a fan of the concept as a whole. Will bring it up with other maints.

I also shouldn't have to explain why the organ code added is bad. `cat/wolf`? Seriously?

2022-03-07 21:20 UTC, francinum commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +	color_src = HAIR
Duplicate set.

2022-03-07 21:24 UTC, francinum requested changes
This code is an absolute mess and desperately needs deduplication.

2022-03-07 21:24 UTC, francinum commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +	color_src = HAIR
Duplicate set.

2022-03-07 21:24 UTC, francinum commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +	color_src = HAIR
Duplicate set.

2022-03-07 21:24 UTC, francinum commented on code/modules/surgery/organs/tails.dm
> +		var/default_part = H.dna.species.mutant_bodyparts["tail_human"]
Why?

2022-03-07 21:24 UTC, francinum commented on code/modules/surgery/organs/tails.dm
> +		H.update_body()
This entire proc is identical to the parent.

2022-03-07 21:26 UTC, francinum commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +	color_src = HAIR
Eh, this enhances readability, it's fine.

2022-03-07 21:26 UTC, francinum commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +	color_src = HAIR
Eh, this enhances readability, it's fine.

2022-03-19 22:40 UTC, 1glitchycent commented
INCREDIBLY BASED.

2022-03-19 22:47 UTC, 1glitchycent commented
> Not a fan of the concept as a whole. Will bring it up with other maints.
> 
> I also shouldn't have to explain why the organ code added is bad. `cat/wolf`? Seriously?

Cope.

2022-03-20 02:32 UTC, francinum commented on code/modules/mob/living/carbon/human/species_types/felinid.dm
> +			mutant_organs += /obj/item/organ/tail/cat/wolf
Explain why this is necessary?

2022-03-20 02:33 UTC, francinum commented on code/modules/mob/living/carbon/human/species_types/felinid.dm
> +			mutant_organs += /obj/item/organ/tail/cat/wolf
...Oh, I see what's up here.

Please restructure this to not result in an incorrect list entry.

2022-03-20 02:35 UTC, francinum requested changes
Prepare a savefile burn to rename felinids (and update their ID) to something more generic. 'Modified Human' per instance.

2022-04-29 03:49 UTC, MarkSuckerberg commented on code/modules/mob/living/carbon/human/species_types/felinid.dm
> +			mutant_organs += /obj/item/organ/tail/cat/wolf
```suggestion
			mutant_organs = list(/obj/item/organ/tail/cat/wolf)
```
I think this is what is needed, but I could be wrong.

2022-04-29 03:50 UTC, MarkSuckerberg commented
My verdict on this honestly is just to leave felinids as they are, and then hopefully someone goes the extra mile and actually folds them completely into humans. I just don't see the sense of doing two savefile burns, so, yeah.

2022-05-08 03:41 UTC, WindowsErrors commented
_... the felinids will use any means ... commit in the new series of attacks against the so-called neighborhood sniper ..._

**PUP PUP PUP PUP PUP PUP**

Perched up high on a rooftop
Like a bird, I'm havin' evil thoughts
A black helm covers my face
And death flows through my mind at it's own pace
Sometimes I feel like a superhero
Urgin' to free my kind
I'm so accurate
I shoot ya heart with a dime
Now I'm back to the moral of my tale
I see a victim, and then my thoughts fail
My mind's still fumblin' with the present slavery, I'm here to save you but who's to save me
I hold my strap so long that my palms all wet
I put finger on the button and then the sight I check
I make the kill, here's the deal
After the trigger's pulled then the death is sealed
So it's the shots that sing out like a piper
Everyone's scared of the neighborhood sniper

So my boy is a furry
I put my gun up to his head
And simply scared the bitch, BOO
Being the E ya know I'm thinkin' devious thoughts
Take off ya clothes, nigga, and here comes a plot
His catbitch was scared, she made a move I pulled the trigger now the room is red
Now there's nothing left but a furry
Here's a four leaf clover punk make a wish
One **PUP** two **PUP** three strikes your out
This furry's dead now I'm lookin' for a window to get out
I made my escape the cops chase
Duckin' to an alley so they don't recognize my face
The boy had to pay the piper
So they all stay in fear of the neighborhood sniper

I'm doin' dirt by myself as I continue my mission
Killin' all furries as an addiction
As the E, lovin' the game, leavin' a shame
And in my heart I feel no muthafuckin' pain
Because my heart is cold as I was told
And with the A.K.47 I stand bold
Rippin' up shit with the fury of my gun shot
Pop pop pow as I watch the fur drop
Lovin' the site as the blood spill
Take a photograph, to keep in my hall in thrills 
I’m stayin' calm and never hyper
As I succeed in my mission
At bein' a neighborhood sniper

2022-05-08 04:31 UTC, TheNeoGamer42 commented
and so windowserror makes their rare appearance, shitposting upon the coder texts once more

2022-05-08 07:15 UTC, retlaw34 commented
![Screenshot_284](https://user-images.githubusercontent.com/58402542/167285954-a2eb96de-c331-4dc5-a4aa-71acee9b8892.png)

2022-05-08 07:15 UTC, closed without merging