Syndicate drip part 1
shiptest-ss13/Shiptest pull request #90
Opened 2021-07-21 15:21 UTC by 1glitchycent

## About The Pull Request
Adds a Gorlex Marauders officer uniform, intended to be used for captains on most Syndicate vessels

## Why It's Good For The Game
The Syndicate is lacking in job uniforms, this will help remedy that

## Changelog
:cl:
add: Added a jumpsuit, coat and hat for syndicate captains.
/:cl:

2021-07-21 15:23 UTC, 1glitchycent commented
pictures 
![image](https://user-images.githubusercontent.com/57820766/126515135-6b4bea3d-3de2-4c5d-8148-c00b617aed97.png)
![image](https://user-images.githubusercontent.com/57820766/126515169-92dbd5c9-f260-45fb-b5b9-babe9bd0a812.png)
![image](https://user-images.githubusercontent.com/57820766/126515202-18ff62c7-2163-47fa-86c3-0da87cf301cb.png)

2021-07-24 04:59 UTC, MarkSuckerberg requested changes

2021-07-24 04:59 UTC, MarkSuckerberg commented on whitesands/code/modules/clothing/suits/coats.dm
> +/obj/item/clothing/suit/toggle/solgov
Needs new path

2021-07-24 04:59 UTC, MarkSuckerberg commented on whitesands/code/modules/clothing/head/misc
> +	strip_delay = 60
File needs to end with .dm and be included in the DME

2021-07-25 14:39 UTC, triplezeta commented
this should be ready for re-review

nice sprites btw

2021-07-25 14:39 UTC, triplezeta commented
do you think you could get some screenshots of them in-game?

2021-07-29 23:27 UTC, merged