adds boss ruins to lavaland
shiptest-ss13/Shiptest pull request #91
Opened 2021-07-22 11:05 UTC by thatchunkymonkey

## About The Pull Request
adds boss ruins such as drake, bubble gum and colossus with questionable quality mapping, i have not tested this at all and I have no idea what I am doing so beware
## Why It's Good For The Game
it adds bosses in the form of ruins
## Changelog
add: add ruins
code: add ruin datums

2021-07-23 04:49 UTC, retlaw34 requested changes

2021-07-23 04:49 UTC, retlaw34 commented on code/datums/ruins/lavaland.dm
> +
```suggestion
	
/datum/map_template/ruin/lavaland/boss/bubblegum
	name = "Bubblegum Ritual"
	id = "bubblegum-ritual"
	description = "A giant hulking flesh monster cartoonishly named bubblegum has recently awoken here."
	suffix = "bubblegum_ruin.dmm"

/datum/map_template/ruin/lavaland/boss/drake
	name = "Dragon Cave"
	id = "dragon-cave"
	description = "A dragon has taken lodging in this here cave, storing its riches and valuables."
	suffix = "drake_ruin.dmm"
	
```

2021-07-23 06:53 UTC, triplezeta approved these changes
Excellent PR. Not that this review means anything. But still.

2021-07-24 04:02 UTC, tmtmtl30 commented
made some fixes, should be good now

2021-07-24 04:56 UTC, merged