Ports https://github.com/Whitesands13/Whitesands/pull/766
shiptest-ss13/Shiptest pull request #918
Opened 2022-03-16 04:30 UTC by retlaw34

## About The Pull Request
Ports https://github.com/Whitesands13/Whitesands/pull/766

Here we have a perfectly fine and completed PR, ready to merge, yet it was never merged. Why? I have zero clue
Bascially ports TG botany, without the plant DNA manipulator removal. It also does not add the special tools meant to replace it

## Why It's Good For The Game

Good to keep the codebase updated with tg a bit, makes ghetto chem a lot more doable without stealing chem dispensers

The autogrow feature takes a shit ton of power, making more powerful power gen actually worth it

## Changelog
ArcaneMusic with tweaks from The0bserver
add: Adds and modifies fertilizers, as well as a new stat, Instability.
add: Upgrades plant guns to have two new functions. Revolution and Mutation Lock.
del: Removes the rather disused functionality of irrigation hoses.
tweak: Plant Analyzer have been upgraded. Using one in hand will now switch between a stat view of your plant, and a chemical view of your plant.
tweak: Trays now accept and store reagents, as well as coming with an autogrow mode. However, these upgrades came at the cost of old self sufficiency, meaning you must attend to your plants a bit more often.
tweak: Earthsblood, while not being able to gild trays anymore, has been found to still be quite powerful as a fertilizer.
/:cl:

2022-05-11 20:37 UTC, Fikou commented on code/modules/hydroponics/hydroitemdefines.dm
> +	return ..()
newline

2022-05-11 20:38 UTC, Fikou commented on code/modules/hydroponics/hydroponics_chemreact.dm
> +		var/datum/reagent/chem = c
as anything, descript variable names

2022-05-11 20:42 UTC, Fikou requested changes

2022-05-11 20:42 UTC, Fikou commented on code/modules/hydroponics/plant_genes.dm
> +/datum/plant_gene/core/instability/apply_stat(obj/item/seeds/S)
descript variable name

2022-05-11 20:42 UTC, Fikou commented on code/modules/hydroponics/seeds.dm
> +			. += "<span class='notice'>- [G.get_name()] -</span>"
as anything, descript variable name

2022-05-11 20:42 UTC, Fikou commented on code/modules/reagents/chemistry/reagents.dm
> +	return
what are you doing here

2022-05-11 20:42 UTC, Fikou commented on code/modules/hydroponics/seeds.dm
> +	var/datum/plant_gene/core/C = get_gene(/datum/plant_gene/core/instability)
yep

2022-05-11 20:42 UTC, Fikou commented on code/modules/hydroponics/seeds.dm
> +	var/datum/plant_gene/core/C = get_gene(/datum/plant_gene/core/instability)
yep

2022-05-11 20:42 UTC, Fikou commented on code/modules/hydroponics/seeds.dm
> +	if(instability == -1)
this should be a define

2022-05-12 16:31 UTC, Fikou commented on code/modules/hydroponics/hydroponics.dm
> +	var/cycledelay = CYCLE_DELAY_DEFAULT	//WS edit - Crystals
kill the ws edit comments

2022-05-12 16:33 UTC, Fikou commented on code/modules/hydroponics/hydroponics.dm
> +	var/mob/lastuser //Last user to add reagents to a tray. Mostly for logging.
not a fan, can you weakref this or use some other method?

2022-05-12 16:35 UTC, Fikou commented on code/modules/hydroponics/hydroponics.dm
> +	. = ..()
return ..() at end of procs

2022-05-12 16:36 UTC, Fikou commented on code/modules/hydroponics/hydroponics.dm
> +				myseed.instability = (myseed.instability/2)
```suggestion
		if(length(myseed.mutatelist))
			myseed.instability = (myseed.instability/2)
```

2022-05-12 16:37 UTC, Fikou commented on code/modules/hydroponics/hydroponics.dm
> +		myseed.forceMove(src)
dont run this on process, move the myseed on the exited proc

2022-05-12 16:37 UTC, Fikou commented on code/modules/hydroponics/hydroponics.dm
> +	cycledelay = CYCLE_DELAY_DEFAULT //WS edit - crystals
cut this

2022-05-12 16:38 UTC, Fikou commented on code/modules/hydroponics/hydroponics.dm
> +				for(var/datum/plant_gene/reagent/G in myseed.genes)
as anything, descript variable

2022-05-25 17:33 UTC, retlaw34 commented
See https://github.com/shiptest-ss13/Shiptest/pull/1116

2022-05-25 17:33 UTC, closed without merging