Resprites intercoms
shiptest-ss13/Shiptest pull request #928
Opened 2022-03-22 06:00 UTC by Quantum-M

## About The Pull Request

Re-srpites the intercoms (both regular and wideband)
## Why It's Good For The Game
Hopefully more nicer and distinct sprites.

Main Intercoms:
![image](https://user-images.githubusercontent.com/32376559/159417466-d80ffb73-a498-4c63-92f5-4306c9a2f8c9.png)
Wall frame/unbuilt versions:
![image](https://user-images.githubusercontent.com/32376559/159417521-a880a932-bac7-45ad-b57e-747867939fb1.png)

## Changelog
:cl: Quantum-M
tweak: Resprites intercoms
/:cl:

2022-03-30 00:34 UTC, triplezeta approved these changes

2022-03-30 00:36 UTC, triplezeta requested changes
actually no, i rescind that, there's some things i didnt pick up earlier

2022-05-01 22:04 UTC, Vexylius requested changes
"Wideband intercoms still need to be changed so that they look normal on walls again". After that it can be merged. Pulling it out of testmerge machine.

2022-05-03 13:32 UTC, Fikou requested changes
add the table version as a subtype or automatically change the icon depending on what surface it was made on

2022-05-05 05:19 UTC, Vexylius commented
I would merge it. This can be added as a later feature

2022-05-13 22:31 UTC, Fikou commented on whitesands/code/game/objects/items/devices/radio/intercom.dm
>  	result_path = /obj/item/radio/intercom/wideband/unscrewed
```suggestion
	result_path = /obj/item/radio/intercom/wideband/unscrewed

/obj/item/wallframe/intercom/wideband/table
	icon_state = "intercom-wideband-table"
```

2022-06-08 22:11 UTC, Vexylius approved these changes
😎👍

2022-06-13 02:27 UTC, triplezeta approved these changes
these look good enough ingame

2022-06-17 16:49 UTC, Fikou approved these changes

2022-06-17 16:49 UTC, merged