Adds cement and concrete, used to make concrete walls and floors.
shiptest-ss13/Shiptest pull request #950
Opened 2022-03-30 01:01 UTC by tmtmtl30

## About The Pull Request

Adds liquid cement and concrete, along with the stronger hexement and hexacrete. They can be used to make walls and floors.

Concrete walls and floors take time to harden, and must be destroyed instead of deconstructed. Concrete walls can only be removed by dealing enough damage to break them (mining tools deal more damage, sharp or hot items deal less), and concrete floors must be smashed using pickaxes or other mining tools. If you walk over a concrete floor while it's hardening, it'll leave a trail of footprints.

This PR includes minor changes to wall and reagent container code and a few other tweaks to ensure everything functions correctly. It isn't 100% finished, and there are a few things I need to test to ensure they work correctly.

Sprites are courtesy of @triplezeta :
![image](https://user-images.githubusercontent.com/53132901/160729613-0dc66e2c-946b-4ef2-87e7-db8e848f62b3.png)
Along the top, concrete walls and floors, the walls in various stages of dryness. Along the bottom, hexacrete walls and floors.

## Why It's Good For The Game

![cement](https://user-images.githubusercontent.com/53132901/160727955-b89c59a4-b034-47a5-982e-fcdd3f1e3e30.gif)

## Changelog
:cl: tmtmtl30, tetrazeta
add: Pouring -- you can now pour out a portion of a beaker's contents by clicking on an object with a beaker while on help intent.
add: Liquid cement, made from heated carbon, hydrogen, oxygen, and water; it can be concentrated into hexement by adding phenol. Don't eat it.
add: Concrete, made by adding sand to liquid cement. Similarly, hexacrete can be made by adding sand to a beaker of hexement.
add: Concrete floors, made by pouring concrete or hexacrete onto catwalks over plating. Use a chisel to change how they look, but be careful not to step on them while they're wet.
add: Concrete walls, made by pouring concrete onto metal grilles. They take 30 seconds to fully harden, and will break if subjected to enough punishment.
add: Hexacrete walls, stronger concrete walls that take longer to harden, made by pouring hexacrete onto metal girders. Good for building explosion-resistant bunkers.
/:cl:

2022-03-30 01:03 UTC, triplezeta commented
sliiight clarification, Azlan did the "smooth" concrete floor (far left). I did the rest of the sprites.

2022-03-30 01:05 UTC, Zevotech commented
i do have some concerns about the beaker pouring thing, like how it interacts with tables and machines that you put beakers into.

otherwise yeah sure ill glaze a donut with cement

2022-03-30 01:08 UTC, tmtmtl30 commented
beakers are still placed on tables or into machines normally. that said, there are probably some weird edge cases i don't know about where pouring acts strange.

2022-03-30 01:11 UTC, Zevotech commented
> beakers are still placed on tables or into machines normally. that said, there are probably some weird edge cases i don't know about where pouring acts strange.

Remember to consider things like mediborgs, service borgs and other non ordinary mobs that can access beakers.
also, harm intent will just splash a beaker onto something and while i understand that splashing cement onto a wall may not make some sense it wouldnt be too hard to just change the verb used.

2022-03-30 01:12 UTC, triplezeta commented
the reason why splashing was intentionally not used was because splashing your *entire* beaker when you need to pour out an entire row of walls is... not optimal

2022-03-30 01:13 UTC, Zevotech commented
hngh fuck good point. fucked up how that works. anyways yes the beaker storage module may not allow mediborgs to pour at all considering its only technically a beaker. either that or they can only pour with it.

2022-03-31 16:42 UTC, someguyjust commented
Say, can you make it so that we can cement someone

2022-04-02 03:34 UTC, Apogee-dev commented
i'd still love to have a special interaction for hitting someone with a spray or foam containing any of the cement or concrete reagents. GLOO gun ass antics

2022-04-20 20:11 UTC, PrefabQuasar commented
theres no method for rotating any of the asymetrical concrete floor tiles

2022-04-20 20:18 UTC, PrefabQuasar commented
also radial menus for reskinning floor tiles feels extremely clunky, and makes building concrete, which is meant to be a faster way of building, significantly slower than using traditional tiles
also uses 4x as much metal, since you need 1 sheet of metal to make the rods for a single catwalk, and 1/4 a sheet of metal to make a tile

2022-04-27 16:39 UTC, Fikou commented on code/game/objects/structures/girders.dm
> +		new remains(loc, 2)
shouldnt this be only when not disassembled, and broken by force?

2022-05-13 22:44 UTC, Fikou commented on code/game/objects/items/tools/chisel.dm
> +			var/turf/open/floor/concrete/C = target
descript variable names please

2022-05-13 22:45 UTC, Fikou commented on code/game/turfs/closed/wall/misc_walls.dm
> +	return null
any reason to not just use return?

2022-05-13 22:45 UTC, Fikou commented on code/game/turfs/closed/walls.dm
> +	for(var/D in dent_decals)
descript variable name please

2022-05-13 22:46 UTC, Fikou commented on code/game/turfs/open/floor/conc_floor.dm
> +		var/turf/open/floor/concrete/conc = T
you can use typing with as anything, and descript variable name

2022-05-13 22:48 UTC, Vexylius commented
When filling a bucket from a sink, when it's full you start pouring water over the sink. Would say that's a bug

2022-05-13 22:49 UTC, Fikou requested changes

2022-05-13 22:49 UTC, Fikou commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	if(ishuman(M))
and here

2022-05-13 22:49 UTC, Fikou commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	var/turf/closed/wall/concrete/W = T.PlaceOnTop(wall_type)
and here

2022-05-13 22:49 UTC, Fikou commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	var/turf/open/floor/concrete/F = T.PlaceOnTop(floor_type)
and here

2022-05-13 22:49 UTC, Fikou commented on code/modules/reagents/reagent_containers.dm
> +	. = ..()
use return ..() at the end of procs for readability, same with the lower one

2022-05-13 22:49 UTC, Fikou commented on code/modules/reagents/reagent_containers.dm
> +	for(var/reagent in reagents.reagent_list)
type it, use as anything

2022-05-27 12:08 UTC, Vexylius commented
Please fix conflicts, everyone **NEEDS** cement

2022-05-29 06:04 UTC, SweetBlueSylveon commented
I desperately request you finish this PR. I desire cement for my morning cereal.

2022-06-03 02:09 UTC, triplezeta commented
pleading pleading pleading pleading 🥺 🥺 🥺 🥺 🥺 🥺 🥺 🥺 🥺 🥺 🥺 🥺 🥺 🥺

2022-06-04 04:05 UTC, tmtmtl30 commented on code/game/turfs/closed/wall/misc_walls.dm
> +	return null
not particularly. will change

2022-06-04 04:32 UTC, tmtmtl30 commented on code/game/objects/structures/girders.dm
> +		new remains(loc, 2)
this was to make rwalls drop slightly more metal when they get annihilated by explosions, i believe? you can see the default code for /obj/structure/girder/deconstruct() above -- note the similarity. girders don't use deconstruct() to handle deconstruction-via-tools, i think it's generally only called when their integrity falls to 0. not entirely sure what to do here

2022-06-04 04:45 UTC, tmtmtl30 commented
resolved merge conflicts, handled reviews

2022-06-14 19:12 UTC, SweetBlueSylveon commented
Have any bugs been discovered from the testmerge? If not, I'd really love to see this merged for real so I can start using it in mapping.

2022-06-15 10:57 UTC, ZephyrTFA commented
This has been test merged for about... *looks at watch* a month now. Is this good to merge?

2022-06-16 03:57 UTC, tmtmtl30 commented
> Is this good to merge?
probably? pouring is inherently kind of (very) janky but fixing that would likely involve a rework of the "reagent_containers" attack chain procs

2022-06-17 21:54 UTC, triplezeta approved these changes
as the person who made these sprites i approve:tm:

2022-06-29 05:46 UTC, Fikou requested changes
other than that please use descript variable names in the files you created (concrete walls, concrete floors,  concrete reagent)

2022-06-29 05:46 UTC, Fikou commented on code/game/mecha/equipment/tools/mining_tools.dm
> +		dismantle_wall(TRUE)
can you make this a named argument? just TRUE doesnt tell much

2022-06-29 05:46 UTC, Fikou commented on code/game/mecha/equipment/tools/mining_tools.dm
> +			dismantle_wall(TRUE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/modules/research/xenobiology/crossbreeding/burning.dm
> +		W.dismantle_wall(TRUE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/modules/projectiles/guns/misc/blastcannon.dm
> +					W.dismantle_wall(TRUE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/modules/projectiles/guns/misc/beam_rifle.dm
> +				W.dismantle_wall(TRUE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/modules/mob/living/simple_animal/hostile/space_dragon.dm
> +			thewall.dismantle_wall(TRUE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/game/turfs/closed/wall/mineral_walls.dm
> +			dismantle_wall(FALSE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/game/turfs/closed/wall/reinf_walls.dm
> +		dismantle_wall(TRUE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/game/objects/items/pitchfork.dm
> +		W.dismantle_wall(FALSE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/game/turfs/closed/wall/conc_walls.dm
> +		dismantle_wall(health <= -50 ? TRUE : FALSE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/game/turfs/closed/walls.dm
> +				dismantle_wall(FALSE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/game/turfs/closed/walls.dm
> +				dismantle_wall(TRUE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/game/turfs/closed/walls.dm
> +		dismantle_wall(TRUE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/game/turfs/closed/walls.dm
> +		dismantle_wall(TRUE)
and here

2022-06-29 05:46 UTC, Fikou commented on code/game/turfs/closed/walls.dm
> +	dismantle_wall(TRUE)
and here

2022-06-30 11:38 UTC, Fikou approved these changes
whatever

2022-06-30 11:38 UTC, merged